### ISSUE TITLE
ERROR 405: Cannot download charts index from server when monitoring docker container metrics in kubernetes

### ISSUE THREAD

**Issue by kmhagan** [firehol/netdata#2498] opened 2017-07-22 18:27 UTC
Hello,

I am receiving "ERROR 405: Cannot download charts index from server: [ip address]:19999/api/v1/charts" when I enable docker container metrics. Netdata is running inside kubernetes using the docker image "titpetric/netdata:latest". I am receiving this error when I mount "/var/run/docker.sock" and appears to be related to cgroup metrics.

Running the /api/v1/charts response through jsonlint:
```
Error: Parse error on line 2007:
...date_every": 15,			"di�				"			cpu0 ":
----------------------^
Expecting 'STRING', got 'undefined'
```

Example data from api/v1/charts where the issue occurs:
```
			"chart_type": "stacked",
			"duration": 13860,
			"first_entry": 1500739530,
			"last_entry": 1500739800,
			"update_every": 15,
			"di�				"
			cpu0 ": { "
			name ": "
			cpu0 " },
			"cpu1": {
				"name": "cpu1"
			},
			"cpu2": {
				"name": "cpu2"
			},
```

Another example:
```
"context": "cgroup.throttle_serviced_ops",
		"title": "Throttle Serviced I/O Operations (all disks) for cgroup k8s_config.6ee51733_config-143357590-z5s18_name_here_0b0b0776-6cbb-11e7-8b9f-0af8405df138_a3fe2ac0 (cgroup_k8s_config.6ee51733_config_143357590_z5s18_name_here_0b0b0776_6cbb_11e7_8b9f_0af8405df138_a3fe2ac0.throttle_serviced_ops)",
		"priority": 41200,
		"enabled": true,
		"units": "operations/s",
		"data_url": "/api/v1/data?chart=cgroup_k8s_config.6ee51733_config_143357590_z5s18_name_here_0b0b0776_6cbb_11e7_8b9f_0af8405df138_a3fe2ac0.throttle_serviced_ops",
		"chart_type": "line",
		"duration": 13860,
		"first_entry": 1500739530,
		"last_entry": 1500739800,
		"update_e�				"
		read ": { "
		name ": "
		read " },
		"write": {
			"name": "write"
		}
	},
	"green": null,
	"red": null
},
```

**Comment by ktsaou** [comment] 2017-07-22 19:54
This seems related to #2276 in which we concluded that it has something to do with very long names.
Let me try to reproduce this with an extremely long cgroup name.

**Comment by ktsaou** [comment] 2017-07-22 20:32
Well, I can't reproduce it. I tried setting docker names with 500 characters and netdata handles them without issues.

Could you please post the output of `grep cgroup-name.sh /var/log/netdata/error.log` (from the container)? I will attempt to use exactly the same names your system has to reproduce this.

This is totally crazy. The corruption happens at `vsprintf()` (a libc call), at a fixed string. It is like `vsprintf()` gets confused for some reason.

**Comment by ktsaou** [comment] 2017-07-22 20:34
It would also be helpful if you could post the entire output of `/api/v1/charts`.

**Comment by ktsaou** [comment] 2017-07-22 21:34
Found it! And fixed it!

There was a faulty assumption that each chart in the JSON format will be at most 1024 bytes. Of course, this was not intended. It was a bug. Now it is dynamic. It does not care how long it will be.

Thank you for reporting it!

**Comment by ktsaou** [comment] 2017-07-22 22:27
merged it.
Could you please update your netdata and confirm it now works?

**Closed** 2017-07-22 22:27 UTC
Labels: bug, fixed

**Comment by kmhagan** [comment] 2017-07-22 22:38
Performing `grep cgroup-name.sh /var/log/netdata/error.log` inside the container doesn't return anything and runs forever. I'm assuming the logging aspect performs a little differently when in a container?

In the following link are the results from a splunk search for cgroup on the pod and the entire output of `/api/v1/charts`: https://1drv.ms/f/s!AlZIyRf4-AyClBH4XwJR6tgZzIdL

**Comment by kmhagan** [comment] 2017-07-22 22:50
That fixed the issue! Thank you!
