### ISSUE TITLE
[feature request] Disabling alarms and/or set uniq thresholds for single instances

### ISSUE THREAD

**Issue by Tronic69** [firehol/netdata#904] opened 2016-09-06 23:10 UTC
I just started using and testing netdata and it was absolutely amazing what is all working out-of-the-box!
AWESOME !!!

I like the health checking with alarming working from scratch, but I would like to configure it a little bit more. At the moment it is only possible to activate or deactivate an alarm on disk usage (disk_full_percent) completely, but not only for one disk. I even can deactivate monitoring for one disk, but this is not what I want. I also can only change the thresholds on disk usage only for all disk, but not for only one. 

I tried to set and uniq threshold for one disk like this:
```
template: disk_space.dm-9
      on: disk.space
    calc: $used * 100 / ($avail + $used)
   every: 1m
    warn: $this > 93
    crit: $this > 98
   units: %
    info: current disk space usage
      to: sysadmin
```
This ended up in having 2 alarms for dm-9!

It would be nice to disable alarm for space_usage only for one or two discs or set threshold for crit and warn to an uniq value.

At the moment there are the following configuration options:

- auto = enable monitoring if the collected values are not zero
- yes = enable monitoring
- no = disable monitoring

It would be nice to have another option for turning on monitoring without alarming (e.g. quiet).

Thanks in advance,
Tom

**Comment by ktsaou** [comment] 2016-09-07 00:55
Nice you like it. Thanks!

Please check the wiki: `template` = apply this to all similar charts. `alarm` = apply this to the given chart only.

As netdata is today, you can either have a `template` applied to all similar charts, or independent per chart alarms. You cannot have a `template` applied to all similar charts except one or two. Sorry...

So, if you don't like the templates included in netdata, comment them out and give per disk alarms (i.e. `alarm` entries where the `on` line refers to the exact disk chart).

Check the wiki.

**Comment by Tronic69** [comment] 2016-09-07 06:35
Sorry, I looked into the wiki, but maybe it was too late and I overseen or didn´t even understood it ;-)

As I understand now I can only have ONE template for ALL charts with the same thresholds or I have to configure multiple alarms for each chart of the same context, if I need a different configuration or do not want an alarm for just one chart. That´s heavy, if you have a lot of disks or logical volumes.

I like the templates and they work well for most cases, you did a great job on it! But it would be much better, if an configured alarm would overwrite a template to set an exclusion to a template. 
For example: 
You have 10 filesystems and just one is used for archiving stuff wich is filled manually, not growing fast and nearly full every time (e.g. for database data files, setup files or videos). By default I will have alarms, when a filesystem/disk is 90% full, but in this case 96 or 97% is early enough (especially when it has a size of >500 GB ^^). In this case i have to configure TEN alarms instead of ONE template and ONE Alarm to overwrite the template.

**Comment by ktsaou** [comment] 2016-09-07 07:10
I see in the code, that if you add an `alarm` BEFORE a `template`, the template will not be applied to the chart. Both have to have the same name.

Never tested it. Can you give it a try?

**Comment by ktsaou** [comment] 2016-09-07 07:11
Also an error is printed: `Health alarm '%s' already exists in host '%s'`

**Comment by ktsaou** [comment] 2016-09-07 07:15
And alarms before templates or vice versa is not taken into account. alarms are always applied to charts before templates.

Can you try defining an overlapping alarm both before and after the template? (just to make sure there is no side effect).

**Comment by Tronic69** [comment] 2016-09-07 12:54
I tried following:

1) Added overlapping alarm for to charts => still getting alarms based on threesholds of template.

2) Commented out template complete => alarms are gone and I see thresholds of configured alarms, but I would get only alarms for this 2 charts and none of the other in that context.

3) Activated template again (removed comments) => all alarms are back with thresholds of template.

It doesn´t matter if I put the alarms in other or same config file or if I put alarms BEFORE or AFTER template in same config file. :(

**Comment by ktsaou** [comment] 2016-09-07 14:13
ok. let me trace this. I'll try to include the fix to PR #905 which will be merged later today.

**Comment by ktsaou** [comment] 2016-09-07 18:24
ok I found the problem and fixed it.
It is in PR #905.
This allows alarms to be used instead of templates (it does not matter where you put it - it does not even need to be in the same file).
Of course, both alarms and templates need to have exactly the same name.

**Comment by Tronic69** [comment] 2016-09-07 19:59
I will try to update and test it tomorrow, for today I'm finished with computers ;-)

**Closed** 2016-09-07 21:12 UTC
Labels: bug, fixed

**Comment by Tronic69** [comment] 2016-09-08 22:06
It's now working as I expected it, alarms overwrite templates. 

Thanks for your fast response and fixing! Awesome!

**Comment by ovizii** [comment] 2016-09-20 11:58
I understood about half of this discussion although I've read the wiki on health monitoring. 
Can someone maybe explain how to create an alarm vs a template? 
It looks like netdata ships with templates only, right? Can I see an example for an alarm please?

**Comment by ktsaou** [comment] 2016-09-20 12:28
Alarms start with the keyword `alarm`, while templates start with keyword `template`.

Alarms are attached to specific charts (the `on` line of alarms is the chart name).
Templates are attached to a set of charts, having a specific context (the `on` line of templates is context).

Everything else is exactly the same.

There are both alarms and templates shipped with netdata.

```sh
# cd /etc/netdata/health.d

# grep 'alarm:' *.conf
entropy.conf:   alarm: 1hour_lowest_entropy
ram.conf:   alarm: ram_in_use
softnet.conf:   alarm: 1hour_netdev_backlog_exceeded
softnet.conf:   alarm: 1hour_netdev_budget_ran_outs
swap.conf:   alarm: 30min_ram_swapped_out
swap.conf:   alarm: used_swap_space
tcp_resets.conf:   alarm: ipv4_tcphandshake_last_collected_secs
tcp_resets.conf:   alarm: 1m_ipv4_tcp_resets
tcp_resets.conf:   alarm: 10s_ipv4_tcp_resets

# grep 'template:' *.conf
apache.conf:template: apache_last_collected_secs
cpu.conf:template: 10min_cpu_usage
cpu.conf:template: 10min_cpu_iowait
cpu.conf:template: 20min_steal_cpu
disks.conf:template: disk_space_last_collected_secs
disks.conf:template: disk_last_collected_secs
disks.conf:template: disk_space_usage
disks.conf:template: disk_inode_usage
disks.conf:template: disk_fill_rate
disks.conf:template: out_of_disk_space_time
disks.conf:template: 10min_disk_utilization
disks.conf:template: 10min_disk_backlog
memcached.conf:template: memcached_last_collected_secs
memcached.conf:template: memcached_cache_memory_usage
memcached.conf:template: cache_fill_rate
memcached.conf:template: out_of_cache_space_time
mysql.conf:template: mysql_last_collected_secs
named.conf:template: named_last_collected_secs
net.conf:template: interface_last_collected_secs
net.conf:template: 1hour_packet_drops
net.conf:template: 1hour_fifo_errors
nginx.conf:template: nginx_last_collected_secs
qos.conf:#template: 10min_qos_packet_drops
redis.conf:template: redis_last_collected_secs
retroshare.conf:template: retroshare_last_collected_secs
retroshare.conf:template: retroshare_dht_working
squid.conf:template: squid_last_collected_secs

```

**Comment by ktsaou** [comment] 2016-09-20 12:34
The discussion above, is about overriding a template for a specific chart. So let's assume that you want a disk to have different thresholds that the default. To override the template for this disk:

1. copy the template definition to a new file, e.g. `my-alarms.conf`.
2. paste it and change the keyword `template:` to `alarm:`
3. change the `on:` line to match the chart you want this alarm to be attached (it has to be a compatible chart)
4. adapt the thresholds to your needs
5. `killall -USR2 netdata` to load the new alarms.

After these steps, all the charts this template matches will have default thresholds, except the one you defined alarm for.

**Comment by ovizii** [comment] 2016-09-20 12:41
awesome, thanks for the detailed explanations, still confused about a few things in the last example:

- the file name is irrelevant?
- as an example lets take disks.conf => step 3 is basically the part where I replace say disk.space with disk_util.sda and thus I now have an alarm with specific settigns for SDA which differs from the general tempalte file for all disks?

**Comment by ktsaou** [comment] 2016-09-20 12:56
1. yes, the filename is irrelevant. You can even create subdirectories in `/etc/netdata/health.d` and put `*.conf` in them. netdata does not care. It will just read all the `*.conf` files under `/etc/netdata/health.d`.

2. When you convert a template to an alarm, it is important to attach it to the same chart that would have been matched by the template. Otherwise, you will be creating a new alarm and not overriding a template for a chart.

  So, if you take the `disk.space` template and attach it to a `disk.util` chart, you are not overriding (and most probably won't work because the `disk.util` chart does not have the dimensions required by the alarm). So, the chart has to be compatible.

  The right way to pick the chart name, is open the alarm modal on the dashboard and find the exact chart id you need to alter:

  ![image](https://cloud.githubusercontent.com/assets/2662304/18670934/c6236e8c-7f4a-11e6-8530-a092dde285b2.png)

**Comment by robbat2** [comment] 2016-12-14 20:36
For the next person wanting a very clear example, see below. The `alarm`/`on` lines are changed from the template, and `warn: 0`, `crit: 0` are added at the end. This doesn't actually disable the alarm evaluation, but always forces it to a "good" state.
```
   alarm: disk_space_usage
      on: disk_space.dm-25
    calc: $used * 100 / ($avail + $used)
   units: %
   every: 1m
    warn: $this > (($status >= $WARNING ) ? (70) : (80))
    crit: $this > (($status == $CRITICAL) ? (85) : (95))
   delay: up 1m down 15m multiplier 1.5 max 1h
    info: current disk space usage
      to: sysadmin
    warn: 0
    crit: 0
```

**Comment by edualm** [comment] 2017-04-09 17:26
Sorry to hijack this issue, but I am not being able to do this.

I created a new template under /etc/netdata/health.d, called custom_plex.conf

>   alarm: disk_space_usage
      on: disk.space._mnt_plex
    calc: $used * 100 / ($avail + $used)
   units: %
   every: 1m
    warn: $this > (($status >= $WARNING ) ? (80) : (90))
    crit: $this > (($status == $CRITICAL) ? (90) : (98))
   delay: up 1m down 15m multiplier 1.5 max 1h
    info: current disk space usage
      to: sysadmin
    warn: 0
    crit: 0

It is being loaded, because I had mis-typed alarm as alert and it was throwing errors in the log:

`2017-04-09 18:10:41: netdata: ERROR: Health configuration at line 12 of file '/etc/netdata/health.d/custom_plex.conf' has unknown key 'crit'. Expected either 'alarm' or 'template'.`

And after fixing it, it's not showing any errors anymore.

Though... alerts are being sent:

`2017-04-09 18:17:52: alarm-notify.sh: INFO: sent email notification for: claptrap disk_space._mnt_plex.disk_space_usage is WARNING to 'root'`

Any ideas of what I may be doing wrong?

**Comment by ktsaou** [comment] 2017-04-09 20:33
What the dashboard says about this alarm?

![image](https://cloud.githubusercontent.com/assets/2662304/24840758/2c18b150-1d7c-11e7-8426-c6a258228703.png)

Check the lower right corner. It says the line and file of the alarm. Is it your alarm?

In general, if you want to disable a templatized alarm, you can do the following.

All templates accept a `families` line, like this:

```
template: disk_space_usage
      on: disk.space
families: *
    calc: $used * 100 / ($avail + $used)
   units: %
   every: 1m
    warn: $this > (($status >= $WARNING ) ? (80) : (90))
    crit: $this > (($status == $CRITICAL) ? (90) : (98))
   delay: up 1m down 15m multiplier 1.5 max 1h
    info: current disk space usage
      to: sysadmin
```

By default the `families` are set to `*` (everything).
You can put there the family of the chart. This is usually the submenu of the dashboard. In you case the submenu would be `/mnt/plex`.

So you can use this:

```
template: disk_space_usage
      on: disk.space
families: !/mnt/plex *
    calc: $used * 100 / ($avail + $used)
   units: %
   every: 1m
    warn: $this > (($status >= $WARNING ) ? (80) : (90))
    crit: $this > (($status == $CRITICAL) ? (90) : (98))
   delay: up 1m down 15m multiplier 1.5 max 1h
    info: current disk space usage
      to: sysadmin
```

The `!` prefix gives a negative match. So, the above will match all charts, except the one with family `/mnt/plex`.

**Comment by edualm** [comment] 2017-04-10 09:33
@ktsaou Thank you, that did the trick.

Any idea why the method I was using did not work? As per your screenshot, it was always loading the (default) template at disks.conf and not the alarm I had created (and posted above).

**Comment by ktsaou** [comment] 2017-04-10 20:54
nice.

> Any idea why the method I was using did not work?

Well... I just tried it:

1. I copied `/etc/netdata/health.d/disks.conf` to `/etc/netdata/health.d/disks2.conf`
2. I edited `disks2.conf` and left only this:

```
   alarm: disk_space_usage
      on: disk_space._
    calc: $used * 100 / ($avail + $used)
   units: %
   every: 1m
    warn: 0
    crit: 0
   delay: up 1m down 15m multiplier 1.5 max 1h
    info: HELLO current disk space usage
      to: sysadmin
```

Note the `on` line and the `HELLO` word at the description.

Without restarting netdata, I run `killall -USR2 netdata` to make it reload health info (I also tried restarting netdata - same results). In `error.log` I got this:

```
2017-04-10 23:45:43: netdata: INFO : Received signal 12 to reload health configuration...
2017-04-10 23:45:43: netdata: INFO : Health alarm 'disk_space._.disk_space_usage' already exists in host 'ktsaou-laptop'.
2017-04-10 23:45:43: netdata: INFO : Health tried to create alarm from template 'disk_space_usage' on chart 'disk_space._' of host 'ktsaou-laptop', but it failed
```

So, the template failed to be applied to this chart.

Then the dashboard showed this:

![screenshot from 2017-04-10 23-48-58](https://cloud.githubusercontent.com/assets/2662304/24882209/ef63152a-1e48-11e7-8fb9-6a31d7977c73.png)

Could you please repeat the process and verify the above work for you too?

**Comment by edualm** [comment] 2017-04-11 19:57
@ktsaou Indeed, that worked. Thanks for your assistance!

I am not being able to reproduce this for the inbound_packets_dropped alarm though.

> ➜  health.d cat xdisabled.conf 
>
>   alarm: inbound_packets_dropped
      on: net.drops
  lookup: sum -10m unaligned absolute of inbound
   units: packets
   every: 1m
    warn: 0
   delay: down 1h multiplier 1.5 max 2h
    info: interface inbound dropped packets in the last 10 minutes
      to: sysadmin

I get no messages on the error.log, apart from the expected ones from the fix you described (I disabled two disks):

>2017-04-11 20:55:18: netdata: INFO : Received signal 12 to reload health configuration...
2017-04-11 20:55:18: netdata: ERROR: Health alarm 'disk_space._mnt_harder-plex.disk_space_usage' already exists in host 'claptrap'. (errno 4, Interrupted system call)
2017-04-11 20:55:18: netdata: ERROR: Health tried to create alarm from template 'disk_space_usage', but it failed
2017-04-11 20:55:18: netdata: ERROR: Health alarm 'disk_space._mnt_plex.disk_space_usage' already exists in host 'claptrap'.
2017-04-11 20:55:18: netdata: ERROR: Health tried to create alarm from template 'disk_space_usage', but it failed

Sorry for all the hassle I am causing. :)

Thanks.

**Comment by ktsaou** [comment] 2017-04-11 20:52
You are not causing a hassle, but you have missed a little, but important note.

The `on` line accepts:

- on templates, the `context` of the chart
- on alarms, the `id` or `name` of the chart, as shown on the dashboard.

The `context` of a chart is its template (upon which it was created). So all disk space usage charts have different IDs and names, but they have the same `context`. Actually the `context` of the chart, combined with the `family` of the chart, make its `id` or `name`. This is why the `template` alarms have a `families` line (to filter the families they will be applied to).

To find the context of a chart, the simplest way is to fetch http://your.netdata.ip:19999/netdata.conf, search for the chart id (as shown on the dashboard), and then you will have something like this:

```
[net_drops.eth0]
	# history = 172956
	# enabled = yes
	# cache directory = /mnt/netdata/net_drops.eth0
	# chart type = line
	# type = net_drops
	# family = eth0
	# units = drops/s
	# context = net.drops
	# priority = 7003
	# gap when lost iterations above = 1
	# name = net_drops.eth0
	# title = Interface Drops (net_drops.eth0)
	# dim inbound name = inbound
	# dim inbound algorithm = incremental
	# dim inbound multiplier = 1
	# dim inbound divisor = 1
	# dim outbound name = outbound
	# dim outbound algorithm = incremental
	# dim outbound multiplier = -1
	# dim outbound divisor = 1
```

So, the chart is called `net_drops.eth0`, its context is `net.drops` and its family is `eth0`. All network interfaces have a chart with this context with different family, which results to different id and name.

So, ids or names for `alarm`, contexts for `template`.

I know it is complicated. But it was the simplest way I could think of to make this happen.

**Comment by edualm** [comment] 2017-04-12 13:01
@ktsaou Success! Proof: https://g.edr.io/ef3e81aa-c019-4294-9a3d-2129bac54bb8 :)

Everything's running just how I want it now, thank you! 

Hopefully this issue can be of help to others too!

**Comment by ktsaou** [comment] 2017-04-12 19:02
nice!

**Comment by ytjohn** [comment] 2018-03-26 13:36
Sorry for hitting this older issue. I thought about opening a new one, but I think keeping it related will help. I've been trying to override the template of "inbound packets dropped ratio" for eth0 with an alarm that has a higher threshhold, but am missing something.

![image](https://user-images.githubusercontent.com/163156/37908886-6fff22d6-30d7-11e8-93f1-306a87ceb321.png)

The template is [standard](https://github.com/firehol/netdata/blob/master/conf.d/health.d/net.conf#L37-L50).

From /netdata.conf: 

```
[net_packets.eth0]
	# history = 3996
	# enabled = yes
	# cache directory = /var/cache/netdata/net_packets.eth0
	# chart type = line
	# type = net_packets
	# family = eth0
	# units = packets/s
	# context = net.packets
	# priority = 7001
	# name = net_packets.eth0
	# title = Packets
	# dim received name = received
	# dim received algorithm = incremental
	# dim received multiplier = 1
	# dim received divisor = 1
	# dim sent name = sent
	# dim sent algorithm = incremental
	# dim sent multiplier = -1
	# dim sent divisor = 1
	# dim multicast name = multicast
	# dim multicast algorithm = incremental
	# dim multicast multiplier = 1
	# dim multicast divisor = 1
```

Now, I create a netoverride.conf file with my alarm, main goal is to override warn and crit levels.

```
 alarm: inbound_packets_dropped_ratio
    on: net_packets.eth0
    os: linux
lookup: sum -10m unaligned absolute of received
  calc: (($inbound_packets_dropped != nan AND $this > 0) ? ($inbound_packets_dropped * 100 / $this) : (0))
 units: %
 every: 1m
  warn: $this >= 4
  crit: $this >= 8
 delay: down 1h multiplier 1.5 max 2h
  info: the ratio of inbound dropped packets vs the total number of received packets of the network interface, during the last 10 minutes
    to: sysadmin
```

This fails to process and the alarm remains as is in the screenshot above.


```
2018-03-26 13:27:35: netdata INFO  : MAIN : SIGNAL: Received SIGUSR2. Reloading HEALTH configuration...
root@rackhd01:/etc/netdata/health.d# 2018-03-26 13:27:35: netdata INFO  : MAIN : Health alarm 'net_packets.eth0.inbound_packets_dropped_ratio' already exists in host 'rackhd01'.
2018-03-26 13:27:35: netdata INFO  : MAIN : Health tried to create alarm from template 'inbound_packets_dropped_ratio' on chart 'net_packets.eth0' of host 'rackhd01', but it failed
2018-03-26 13:27:42: vs-alarm-notify.sh: INFO: not sending notification for CLEAR of 'rackhd01.sss.egvg0.vs.management.net_packets.eth0.inbound_packets_dropped_ratio' (last status was UNINITIALIZED)
```

If I change the name to "inbound_packets_dropped_ratio_eth0" or such, I avoid the duplicate name issue, but that still leaves the original alert in place.
