### ISSUE TITLE
allow easypiechart to render the value relative to max and min

### ISSUE THREAD

**Issue by BrainDoctor** [firehol/netdata#2455] opened 2017-07-12 20:12 UTC
I am writing a custom dashboard with easy pie chart: 
```html
<div data-netdata="stiebeleltron_system.hotwater.hotwatertemp"
                     data-title="Hot Water Temperature"
                     data-decimal-digits="1"
                     data-chart-library="easypiechart"
                     data-width="50%"
                     data-height="50%"
                     data-points="300"
                     data-after="-1200"
                     data-dimensions="actual"
                     data-units="°C"
                     data-easypiechart-max-value="50"
                     data-easypiechart-min-value="40"
                ></div>
```
So here I provide a min and max value of 40 and 50 °C. If the value is 46 °C, I expect the chart bar to be a little more than in the middle. Instead, it is shown almost completely filled:
![easypie_bug](https://user-images.githubusercontent.com/12159026/28137206-be8ee558-674c-11e7-8959-8159b11d8ea0.png)

So I dug deeper in dashboard.js and found out that the calculation is "wrong":
dashboard.js, around line 5555 - 5580:
```javascript
NETDATA.easypiechartPercentFromValueMinMax = function(value, min, max) {
        if(typeof value !== 'number') value = 0;
        if(typeof min !== 'number') min = 0;
        if(typeof max !== 'number') max = 0;

        if(min > value) min = value;
        if(max < value) max = value;

        // make sure it is zero based
        if(min > 0) min = 0;
        if(max < 0) max = 0;

        var pcent = 0;
        if(value >= 0) {
            if(max !== 0)
                pcent = Math.round(value * 100 / max);
            if(pcent === 0) pcent = 0.1;
        }
        else {
            if(min !== 0)
                pcent = Math.round(-value * 100 / min);
            if(pcent === 0) pcent = -0.1;
        }

        return pcent;
    };
```
To my understanding, the percentage should take into account the minimum value. So It should calculate the percentage not only based on the maximum, but the difference **between** max **and** min. In the code above, min is completely ignored if max is set.

Is that intentional? I will fix it in my setup but could create a PR

**Comment by BrainDoctor** [comment] 2017-07-12 20:44
Actually this is causing the trouble:
```javascript
// make sure it is zero based
if(min > 0) min = 0;
if(max < 0) max = 0;
```
This resets any min values given from the arguments. I propose to add a parameter which calculates the pcent relative of min/max. Let me try something.

**Comment by ktsaou** [comment] 2017-07-13 20:03
This is by design.

These checks are supposed to bring zero into the visible area.

The idea is that if `min = -10` and `max = -5`, then the chart should show the range `-10` to `0`.
Similarly for max.

If we don't put this way, and both min and max are floating around, the graph is misleading.
But I guess that if you really need it that way by setting min and max yourself, we could support it.

**Comment by BrainDoctor** [comment] 2017-07-14 10:49
I know and it perfectly makes sense.
However if I have a metric that is constantly between 1200 and 1100, then the chart is kinda misleading too, since the updates would not show any significant visual differences between 1100 and 1200. For the sake of the argument, lets pretend the metric cannot fall under 1100. What the graph should be showing then is the relative percentage within 1100 and 1200. So at 1150 the graph should show 50%. Does that make sense?

My approach is this one:
```javascript
 NETDATA.easypiechartPercentFromValueMinMax = function(value, min, max, relativeMinMax) {
        if(typeof value !== 'number') value = 0;
        if(typeof min !== 'number') min = 0;
        if(typeof max !== 'number') max = 0;

        if(min > value) min = value;
        if(max < value) max = value;

        if (!relativeMinMax) {
            // make sure it is zero based
            if (min > 0) min = 0;
            if (max < 0) max = 0;
        }

        var pcent = 0;
        var range = max - min;
        if(value >= 0) {
            if(max !== 0) pcent = Math.round(value * 100 / max);
            if(relativeMinMax && range !== 0) pcent = Math.round((value - min) * 100 / range);
            if(pcent === 0) return 0.1;
        }
        else {
            if(min !== 0) pcent = Math.round(-value * 100 / min);
            if(relativeMinMax && range !== 0) pcent = Math.round((value - min) * 100 / range);
            if(pcent === 0) return -0.1;
        }

        return pcent;
    };
```
That boolean flag (default: false) can be set by using it in the html:
```html
data-netdata="something"
data-easypiechart-max-value="30"
data-easypiechart-min-value="15"
data-easypiechart-relative-min-max="true"
```
The min/max values are optional/can be dynamic

Works with negative values too: If `min = -1100` and `max = 1100`, then the range is `1100 + -1100 = 2200`. So a `value = 0` would result in a chart with 50 %.

I did the complete implementation in [my fork](https://github.com/BrainDoctor/netdata/blob/easypiechart/web/dashboard.js). Also look at the create method at ~5694.

**Comment by ktsaou** [comment] 2017-07-15 10:23
ok, in PR #2462 is another solution.
The code does not force zero-based min and max, if they have been set with `data` attributes. So, no need for the additional flag. So, to force non-zero min, just set it. The same for max.

**Comment by ktsaou** [comment] 2017-07-15 12:54
merged it.

**Closed** 2017-07-15 12:54 UTC
Labels: enhancement, fixed

**Comment by BrainDoctor** [comment] 2017-07-15 23:31
well that was fast! Thanks, I'll try it out :)

**Comment by BrainDoctor** [comment] 2017-07-22 15:55
uhm are you sure you tested this? because your merge changed... nothing.
This is the chart with your changes:
![2017-07-22_174643](https://user-images.githubusercontent.com/12159026/28492574-3720ef64-6f06-11e7-9aea-7fa06111fa8e.png)

so it's still around 94% where it should be 71% (if max=50, min=40). Should I open a new issue or re-open this one?

**Comment by ktsaou** [comment] 2017-07-23 21:11
You are right! I tested gauge chart and took your word for the change required in easypiechart.
I fixed it now. Making a PR.

**Comment by BrainDoctor** [comment] 2017-07-23 22:56
well, it was only part of the problem ;) another formula that respects the range was still necessary. but thanks, it works now
![2017-07-24_005350](https://user-images.githubusercontent.com/12159026/28503614-96bdb6f0-700a-11e7-9b2c-3e6b3b3bc834.png)

**Comment by BrainDoctor** [comment] 2017-07-24 14:50
now it doesn't render negative values anymore (it's in the positive)
![2017-07-24_164728](https://user-images.githubusercontent.com/12159026/28529106-f1609ad4-708f-11e7-9c04-308a064e65d9.png)
```html
            <div data-netdata="fronius_Solar.power"
                 data-decimal-digits="0"
                 data-title="- Grid +"
                 data-chart-library="easypiechart"
                 data-override-options="signed"
                 data-width="31%"
                 data-height="49%"
                 data-after="-1200"
                 data-points="1200"
                 data-colors="#4043ff"
                 data-dimensions="p_grid"
                 data-legend="no"
            ></div>
```

**Comment by ktsaou** [comment] 2017-07-24 15:09
Now it always has a min-max range.

The percentage is calculated like the following: https://github.com/firehol/netdata/blob/29cfbfc8d4f8f07ec1b76468d14fae036cfb301e/web/dashboard.js#L5555-L5572

```
if(min > value) min = value;
if(max < value) max = value;
pcent = Math.round((value - min) * 100 / (max - min));
```

So, it does not care what the `min` and `max` are (positive or negative). The animation is always clockwise.

If you switch to gauge, it prints the min and max on the chart. Could you please switch it temporarily?
I see that gauge has another protection: it does not allow min > max:  https://github.com/firehol/netdata/blob/29cfbfc8d4f8f07ec1b76468d14fae036cfb301e/web/dashboard.js#L5824-L5828

**Comment by BrainDoctor** [comment] 2017-07-24 15:16
I guess the range has been adjusted in the meantime.
![2017-07-24_171623](https://user-images.githubusercontent.com/12159026/28530344-d5720b10-7093-11e7-8c1c-d26f46258c92.png)

**Comment by ktsaou** [comment] 2017-07-24 15:20
hm... so is there anything to fix?

**Comment by ktsaou** [comment] 2017-07-24 15:23
sorry, just read the rest.


> What I meant was to render the range only when min and max are given, otherwise keeping the zero based calculations (with negative values)

I think this is what I did. You didn't give min and max to the gauge?

**Comment by BrainDoctor** [comment] 2017-07-24 15:23
yes, in the grid chart I didn't specify the min and max values. I would like them to keep dynamic, since I can't know the max and mins. But the grid chart also produces negative values, which should then be counter-clockwise (also using dynamic min/max).

The hot water chart is a different story. Here I know the min/max values, so the range is more important than zero-based percentage

**Comment by ktsaou** [comment] 2017-07-24 15:24
oh! I see! Yes, now it never goes counter clockwise. Let me fix that...

**Comment by ktsaou** [comment] 2017-07-24 16:01
I see that before the recent changes, the chart was using clockwise animation if the value to be rendered was positive and counter clockwise animation if the value was negative.

There was something wrong though: if the range was spanning from a negative value to a positive value, it was zeroing the opposite (it was zeroing `min` if value was positive, and `max` if the value was negative).

I think the right should be:

1. If the value is negative and max is zero, use counter clockwise
2. If the value is positive and min is zero, use clockwise
3. If min is negative and max is positive, then use max = max(-min, max) and min = -max, so that zero is at the top center, and animate on the direction of the value

What do you think?

**Comment by BrainDoctor** [comment] 2017-07-24 16:28
Let me write how I understand the chart. Your cases don't specify the user settings enough for me ;)

1. Use **zero-based** counter clockwise if: the value is negative AND max was NOT set by html AND min was not set by html.
2. Use **zero-based** clockwise if: the value is negative AND max was not set by html AND min was not set by html.

This allows negative and positive values with a dynamic max or min. If only max was set by html, it still allows a user to set a known maxima with a zero-based chart. But it also allows negative values with a dynamic minimum, should the values go negative.

3. Use **range-based** counter clockwise if: the value is negative AND max was set by html AND min was set by html AND max is < 0. This allows the "hot water" chart but with negative values, min and max
4. Use **range-based** clockwise if: the value is positive AND max was set by html AND min was set by html AND min is > 0. The "hot water" chart szenario
5. Use **range-based** clockwise if: (the value is negative OR positive) AND max was set by html AND min was set by html. This allows spanning ranges e.g. min= -20, max = 20, so that a value=0 means 50%. This is mathematically the same as with 4).

I guess the code becomes quite complicated then. Maybe you could make the check whether BOTH min/max were set at startup, then use javascript's function pointers to calculate using different methods.

**Comment by BrainDoctor** [comment] 2017-07-24 16:32
Another alternative would be setting the min or max with "inf" or something like that in the HTML. It would explicitly enable dynamic min/max and render negative values counter-clockwise (no spanning range).

**Comment by ktsaou** [comment] 2017-07-24 16:43
I think this covers all the cases:

```js
        if(min > max) {
            var t = min;
            min = max;
            max = t;
        }

        if(min > value) min = value;
        if(max < value) max = value;

        if(state.tmp.easyPieChartMin === null && min > 0) min = 0;
        if(state.tmp.easyPieChartMax === null && max < 0) max = 0;

        var pcent;

        if(min < 0 && max > 0) {
            // it is both positive and negative
            // zero at the top center of the chart
            max = (-min > max)? -min : max;
            pcent = Math.round(value * 100 / max);
        }
        else if(value >= 0 && min >= 0 && max >= 0) {
            // clockwise
            pcent = Math.round((value - min) * 100 / (max - min));
            if(pcent === 0) pcent = 0.1;
        }
        else {
            // counter clockwise
            pcent = Math.round((value - max) * 100 / (max - min));
            if(pcent === 0) pcent = -0.1;
        }

        return pcent;
```

With one exception: your rule No 5 will get clockwise or counter clockwise depending on the value.

So, it works like this:

1. If min > max, flip them
2. if value is outside min or max, adjust min or max to include value
3. If min is not set by user, and is above zero, set it to zero
4. If max is not set by user, and is below zero, set it to zero
5. if min is negative and max is positive, split the chart in half and animate clockwise or counter clockwise
6. else if all values are positive, animate clockwise
7. else animate counter clockwise

**Comment by ktsaou** [comment] 2017-07-24 16:50
I have created PR #2511 with it.

**Comment by ktsaou** [comment] 2017-07-24 17:08
Something worth saying is that when the range is negative to positive, the chart will animate clockwise if the value is positive and counter clockwise if the value is negative, but **in either direction it will use the whole chart** (i.e. it if is min = -100 and max = 100, value -100 and value 100 will look the same: full circle in color).

I can make it use half the circle, but I am not sure what is the best.

**Comment by BrainDoctor** [comment] 2017-07-24 17:21
Great! I'll test it soon.

yes, I would expect the full circle. For me that is fine. I think most of the "fixed min/max" use cases will allow some space for the expected values and round them to sensible number. So it shouldn't be often the case that the circle is full. At least in my cases ;)

**Comment by BrainDoctor** [comment] 2017-07-24 17:30
So it works for the hot water chart:
![2017-07-24_192732](https://user-images.githubusercontent.com/12159026/28535855-2628931e-70a6-11e7-99d2-d1a2d99f967f.png)
and the grid shows a positive number. based on the 1200 seconds history the maximum and percentage seem valid:
![2017-07-24_192756](https://user-images.githubusercontent.com/12159026/28535873-34626efa-70a6-11e7-9e1a-bec36b87c720.png)

**Comment by ktsaou** [comment] 2017-07-24 18:35
it works that too:

![screenshot from 2017-07-24 21-34-43](https://user-images.githubusercontent.com/2662304/28538729-f4b99276-70b7-11e7-804b-288a46d24b50.png)

**Comment by ktsaou** [comment] 2017-07-24 18:37
merged it
