### ISSUE TITLE
Slack not receiving alarms (testing alarm-notify.sh works OK)

### ISSUE THREAD

**Issue by jorgemfm** [firehol/netdata#2894] opened 2017-10-18 15:45 UTC
I'm getting alerts from the web interface but not on slack.

When I run `/usr/libexec/netdata/plugins.d/alarm-notify.sh test` its works OK.

Edit: Already received a notification but not all.

**out of disk space time** is working
**disk space usage** not working, I haven't changed the default rules

**/etc/netdata/health.d/disks.conf**

```
template: disk_space_usage
      on: disk.space
      os: linux
   hosts: *
families: *
    calc: $used * 100 / ($avail + $used)
   units: %
   every: 1m
    warn: $this > (($status >= $WARNING ) ? (80) : (90))
    crit: $this > (($status == $CRITICAL) ? (90) : (98))
   delay: up 1m down 15m multiplier 1.5 max 1h
    info: current disk space usage
      to: sysadmin
```

```
template: out_of_disk_space_time
      on: disk.space
      os: linux
   hosts: *
families: *
    calc: ($disk_fill_rate > 0) ? ($avail / $disk_fill_rate) : (inf)
   units: hours
   every: 10s
    warn: $this > 0 and $this < (($status >= $WARNING)  ? (48) : (8))
    crit: $this > 0 and $this < (($status == $CRITICAL) ? (24) : (2))
   delay: down 15m multiplier 1.2 max 1h
    info: estimated time the disk will run out of space, if the system continues to add data with the rate of the last hour
      to: sysadmin
```

**Comment by ktsaou** [comment] 2017-10-19 21:03
Hi, could you please run this and post the output?

```sh
grep alarm-notify.sh /var/log/netdata/error.log | grep slack
```

Here is mine:

```
2017-10-19 00:35:30: alarm-notify.sh: INFO: sent slack notification for: pi3 ipv4.udperrors.ipv4_udperrors_last_collected_secs is CRITICAL to 'alarms'
2017-10-19 00:35:31: alarm-notify.sh: INFO: sent slack notification for: pi3 ipv4.tcphandshake.ipv4_tcphandshake_last_collected_secs is CRITICAL to 'alarms'
2017-10-19 00:36:45: alarm-notify.sh: INFO: sent slack notification for: bedtv net_drops.eth0.inbound_packets_dropped is WARNING to 'alarms'
2017-10-19 00:39:11: alarm-notify.sh: ERROR: failed to send slack notification for: box disk_space._data.disk_space_usage is WARNING to 'alarms', with HTTP error code 000.
2017-10-19 00:39:12: alarm-notify.sh: INFO: sent slack notification for: jasontv net_drops.eth0.inbound_packets_dropped is WARNING to 'alarms'
2017-10-19 01:25:44: alarm-notify.sh: INFO: sent slack notification for: box net_drops.eth0.inbound_packets_dropped is WARNING to 'alarms'
2017-10-19 02:27:44: alarm-notify.sh: INFO: sent slack notification for: box net_drops.eth0.inbound_packets_dropped is CLEAR to 'alarms'
2017-10-19 03:06:52: alarm-notify.sh: INFO: sent slack notification for: bigtv2 net_packets.eth0.inbound_packets_dropped_ratio is WARNING to 'alarms'
2017-10-19 03:14:54: alarm-notify.sh: INFO: sent slack notification for: box disk_space._backup.out_of_disk_space_time is CRITICAL to 'alarms'
2017-10-19 03:24:54: alarm-notify.sh: INFO: sent slack notification for: box disk_backlog.sde.10min_disk_backlog is WARNING to 'alarms'
2017-10-19 03:30:55: alarm-notify.sh: INFO: sent slack notification for: box disk_space._backup.out_of_disk_space_time is CLEAR to 'alarms'
2017-10-19 03:44:54: alarm-notify.sh: INFO: sent slack notification for: box disk_backlog.sde.10min_disk_backlog is CLEAR to 'alarms'
2017-10-19 03:47:53: alarm-notify.sh: INFO: sent slack notification for: box disk_backlog.sdd.10min_disk_backlog is WARNING to 'alarms'
2017-10-19 04:09:55: alarm-notify.sh: INFO: sent slack notification for: bigtv2 net_packets.eth0.inbound_packets_dropped_ratio is WARNING to 'alarms'
2017-10-19 05:34:55: alarm-notify.sh: INFO: sent slack notification for: bigtv2 net_packets.eth0.inbound_packets_dropped_ratio is CLEAR to 'alarms'
2017-10-19 06:33:05: alarm-notify.sh: INFO: sent slack notification for: jasontv ipv4.udperrors.ipv4_udperrors_last_collected_secs is WARNING to 'alarms'
2017-10-19 06:33:06: alarm-notify.sh: INFO: sent slack notification for: jasontv ipv4.tcphandshake.ipv4_tcphandshake_last_collected_secs is WARNING to 'alarms'
2017-10-19 06:33:45: alarm-notify.sh: INFO: sent slack notification for: bedtv ipv4.udperrors.ipv4_udperrors_last_collected_secs is WARNING to 'alarms'
2017-10-19 06:33:45: alarm-notify.sh: INFO: sent slack notification for: bedtv ipv4.tcphandshake.ipv4_tcphandshake_last_collected_secs is WARNING to 'alarms'
2017-10-19 06:39:05: alarm-notify.sh: INFO: sent slack notification for: jasontv ipv4.udperrors.ipv4_udperrors_last_collected_secs is CLEAR to 'alarms'
2017-10-19 06:39:06: alarm-notify.sh: INFO: sent slack notification for: jasontv ipv4.tcphandshake.ipv4_tcphandshake_last_collected_secs is CLEAR to 'alarms'
2017-10-19 06:39:54: alarm-notify.sh: INFO: sent slack notification for: bedtv ipv4.udperrors.ipv4_udperrors_last_collected_secs is CLEAR to 'alarms'
2017-10-19 06:39:55: alarm-notify.sh: INFO: sent slack notification for: bedtv ipv4.tcphandshake.ipv4_tcphandshake_last_collected_secs is CLEAR to 'alarms'
2017-10-19 06:51:25: alarm-notify.sh: INFO: sent slack notification for: bigtv2 net_packets.eth0.inbound_packets_dropped_ratio is WARNING to 'alarms'
2017-10-19 21:14:25: alarm-notify.sh: INFO: sent slack notification for: bigtv2 net_packets.eth0.inbound_packets_dropped_ratio is CLEAR to 'alarms'
```

As you can see, I have an `ERROR` too. But this is related to slack (they probably had difficulties). Unfortunately, netdata does not retry.

**Comment by jorgemfm** [comment] 2017-10-20 09:04
```
2017-10-18 16:55:49: alarm-notify.sh: INFO: sent slack notification for: server disk_space._.out_of_disk_space_time is WARNING to 'it'
2017-10-18 20:04:04: alarm-notify.sh: INFO: sent slack notification for: server disk_space._.out_of_disk_space_time is CRITICAL to 'it'
2017-10-18 20:57:14: alarm-notify.sh: INFO: sent slack notification for: server disk_space._.out_of_disk_space_time is CLEAR to 'it'
```
The **out_of_disk_space_time** are the one i'm receiving on slack, but O get other warnings on the web interface as you can see on the image:

https://imgur.com/a/pdMN9

**Comment by ktsaou** [comment] 2017-10-20 09:44
The netdev budget alarm is silent:

![screenshot from 2017-10-20 12-41-17](https://user-images.githubusercontent.com/2662304/31814996-ff0385c2-b593-11e7-8fda-332b7e1d0c7a.png)

The disk space usage alarm, I think netdata believes it has already sent it, so it does not sent it again. You will receive it again, when it changes status. As long as it stays in warning status, netdata will try not to bother you again.

**Comment by ktsaou** [comment] 2017-10-20 09:47
About the disk space alarm, to verify what netdata things, goto to this:

![screenshot from 2017-10-20 12-46-24](https://user-images.githubusercontent.com/2662304/31815236-c277c004-b594-11e7-9196-52b76a95d7fb.png)

And enable the "Run Script At" column:

![screenshot from 2017-10-20 12-46-46](https://user-images.githubusercontent.com/2662304/31815260-d73ae99e-b594-11e7-8075-3e5cccddd386.png)

**Comment by jorgemfm** [comment] 2017-10-20 10:24
Thank you,

I don't know what to make of it, but I restarted the netdada service again (I already tried a few times yesterday) and now I received the **disk space usage** warning that I wasn't getting notified. 

> The disk space usage alarm, I think netdata believes it has already sent it, so it does not sent it again. You will receive it again, when it changes status. As long as it stays in warning status, netdata will try not to bother you again.

The thing is, that everytime I restarted the netdata service I would get 3 warnings by the web interface, (https://imgur.com/a/pdMN9), but only one was sent to slack (check image at the end), if the "netdata believes it has already sent it" is what's happening, shouldn't the web interface notification also not happen?

Image with the slack notification yesterday and today (already with the **disk space usage**)

https://imgur.com/a/9nHzB


I will check the alarms like you said and run some more tests as soon as possible.

Thank you for your help.

**Comment by ktsaou** [comment] 2017-10-20 13:04
> The thing is, that everytime I restarted the netdata service I would get 3 warnings by the web interface, (https://imgur.com/a/pdMN9), but only one was sent to slack (check image at the end), if the "netdata believes it has already sent it" is what's happening, shouldn't the web interface notification also not happen?

The web UI is a little bit more chatty (by design). All alarms notifications have incremental IDs. Each viewer / browser remembers the ID last shown. When you restart netdata, new alarm notification IDs are generated, so all viewers see the web notifications again.

The notifications sent, has a more complex algorithm. It tries to figure if the alarm notification to be sent matches the state of the last notification dispatched. When they match, the notification is not sent.

**Comment by ktsaou** [comment] 2017-12-03 18:49
cleaning up. I am closing this, but if you need help just post.

**Closed by ktsaou** 2017-12-03 18:49 UTC
Labels: question

**Comment by kubuntux** [comment] 2018-07-11 17:39
Hi, I need help. This is really weird.

Slack notifications are working in test alerts, but not with real alerts.

This is the test:

`sudo su -s /bin/bash netdata
bash-4.1$ export NETDATA_ALARM_NOTIFY_DEBUG=1
bash-4.1$ /opt/netdata/usr/libexec/netdata/plugins.d/alarm-notify.sh test

# SENDING TEST WARNING ALARM TO ROLE: sysadmin
--- BEGIN curl command ---
/usr/bin/curl -X POST --data-urlencode $'payload=        {\n            "channel": "#server-alerts",\n            "username": "netdata on XXXXXX",\n            "icon_url": "https://registry.my-netdata.io/images/seo-performance-128.png",\n            "text": "XXXXXX needs attention, `test.chart` (_test.family_), *test alarm = new value*",\n            "attachments": [\n                {\n                    "fallback": "test alarm = new value - test.chart (test.family) - this is a test alarm to verify notifications work",\n                    "color": "warning",\n                    "title": "test alarm = new value",\n                    "title_link": "https://registry.my-netdata.io/goto-host-from-alarm.html?host=XXXXXX&chart=test.chart&family=test.family&alarm=test_alarm&alarm_unique_id=1&alarm_id=1&alarm_event_id=1",\n                    "text": "this is a test alarm to verify notifications work",\n                    "fields": [\n                        {\n                            "title": "test.chart",\n                            "short": true\n                        },\n                        {\n                            "title": "test.family",\n                            "short": true\n                        }\n                    ],\n                    "thumb_url": "https://registry.my-netdata.io/images/alert-128-orange.png",\n                    "footer": "by <https://registry.my-netdata.io/goto-host-from-alarm.html?host=XXXXXX&chart=test.chart&family=test.family&alarm=test_alarm&alarm_unique_id=1&alarm_id=1&alarm_event_id=1|XXXXX>",\n                    "ts": 1531330006\n                }\n            ]\n        }' https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXX 
--- END curl command ---
--- BEGIN received response ---
ok
--- END received response ---
RECEIVED HTTP RESPONSE CODE: 200
2018-07-12 01:26:47: alarm-notify.sh: INFO: sent slack notification for: XXXXXX test.chart.test_alarm is WARNING to 'server-alerts'
--- BEGIN sendmail command ---
/usr/sbin/sendmail -t 
--- END sendmail command ---
2018-07-12 01:26:47: alarm-notify.sh: INFO: sent email notification for: XXXXXX test.chart.test_alarm is WARNING to 'root'
# OK

# SENDING TEST CRITICAL ALARM TO ROLE: sysadmin
--- BEGIN curl command ---
/usr/bin/curl -X POST --data-urlencode $'payload=        {\n            "channel": "#server-alerts",\n            "username": "netdata on XXXXXX",\n            "icon_url": "https://registry.my-netdata.io/images/seo-performance-128.png",\n            "text": "XXXXXX is critical, `test.chart` (_test.family_), *test alarm = new value*",\n            "attachments": [\n                {\n                    "fallback": "test alarm = new value - test.chart (test.family) - this is a test alarm to verify notifications work",\n                    "color": "danger",\n                    "title": "test alarm = new value",\n                    "title_link": "https://registry.my-netdata.io/goto-host-from-alarm.html?host=XXXXXX&chart=test.chart&family=test.family&alarm=test_alarm&alarm_unique_id=1&alarm_id=1&alarm_event_id=2",\n                    "text": "this is a test alarm to verify notifications work",\n                    "fields": [\n                        {\n                            "title": "test.chart",\n                            "short": true\n                        },\n                        {\n                            "title": "test.family",\n                            "short": true\n                        }\n                    ],\n                    "thumb_url": "https://registry.my-netdata.io/images/alert-128-red.png",\n                    "footer": "by <https://registry.my-netdata.io/goto-host-from-alarm.html?host=XXXXXX&chart=test.chart&family=test.family&alarm=test_alarm&alarm_unique_id=1&alarm_id=1&alarm_event_id=2|XXXXX>",\n                    "ts": 1531330007\n                }\n            ]\n        }' https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXX 
--- END curl command ---
--- BEGIN received response ---
ok
--- END received response ---
RECEIVED HTTP RESPONSE CODE: 200
2018-07-12 01:26:48: alarm-notify.sh: INFO: sent slack notification for: XXXXXX test.chart.test_alarm is CRITICAL to 'server-alerts'
--- BEGIN sendmail command ---
/usr/sbin/sendmail -t 
--- END sendmail command ---
2018-07-12 01:26:48: alarm-notify.sh: INFO: sent email notification for: XXXXXX test.chart.test_alarm is CRITICAL to 'root'
# OK

# SENDING TEST CLEAR ALARM TO ROLE: sysadmin
--- BEGIN curl command ---
/usr/bin/curl -X POST --data-urlencode $'payload=        {\n            "channel": "#server-alerts",\n            "username": "netdata on XXXXXX",\n            "icon_url": "https://registry.my-netdata.io/images/seo-performance-128.png",\n            "text": "XXXXXX recovered, `test.chart` (_test.family_), *test alarm (alarm was raised for 3 seconds)*",\n            "attachments": [\n                {\n                    "fallback": "test alarm (alarm was raised for 3 seconds) - test.chart (test.family) - this is a test alarm to verify notifications work",\n                    "color": "good",\n                    "title": "test alarm (alarm was raised for 3 seconds)",\n                    "title_link": "https://registry.my-netdata.io/goto-host-from-alarm.html?host=XXXXXX&chart=test.chart&family=test.family&alarm=test_alarm&alarm_unique_id=1&alarm_id=1&alarm_event_id=3",\n                    "text": "this is a test alarm to verify notifications work",\n                    "fields": [\n                        {\n                            "title": "test.chart",\n                            "short": true\n                        },\n                        {\n                            "title": "test.family",\n                            "short": true\n                        }\n                    ],\n                    "thumb_url": "https://registry.my-netdata.io/images/check-mark-2-128-green.png",\n                    "footer": "by <https://registry.my-netdata.io/goto-host-from-alarm.html?host=XXXXXX&chart=test.chart&family=test.family&alarm=test_alarm&alarm_unique_id=1&alarm_id=1&alarm_event_id=3|XXXXX>",\n                    "ts": 1531330008\n                }\n            ]\n        }' https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXX 
--- END curl command ---
--- BEGIN received response ---
ok
--- END received response ---
RECEIVED HTTP RESPONSE CODE: 200
2018-07-12 01:26:49: alarm-notify.sh: INFO: sent slack notification for: XXXXXX test.chart.test_alarm is CLEAR to 'server-alerts'
--- BEGIN sendmail command ---
/usr/sbin/sendmail -t 
--- END sendmail command ---
2018-07-12 01:26:49: alarm-notify.sh: INFO: sent email notification for: XXXXXX test.chart.test_alarm is CLEAR to 'root'
# OK`

But on real alerts, I am getting this log:

`grep alarm-notify.sh /opt/netdata/var/log/netdata/error.log | grep slack
2018-07-12 01:11:14: alarm-notify.sh: ERROR: failed to send slack notification for: XXXXXX disk_space._.out_of_disk_space_time is WARNING to 'server-alerts', with HTTP error code 000.`

Thanks!

**Comment by ktsaou** [comment] 2018-07-11 23:19
error code 000 for curl means network issues (the curl command was disconnected before sending the request).

**Comment by kubuntux** [comment] 2018-07-12 02:43
@ktsaou Thank you for your reply.

But this is happening for all live alarms, to all of the servers I tested this with (6 servers).

But with the test, I tested it with the netdata user, and it looks good.

Right now, maybe I'm thinking netdata can't see the correct path to the cURL because it is installed as standalone in /opt/netdata.

I'll try to define full path to the cURL binary in the config file, then let you know if it worked.

**Comment by ktsaou** [comment] 2018-07-12 08:28
hm... This might be a problem of SSL certificates.
The static netdata ships with its own curl, but it needs the ssl root certificates to be installed on the system. May be it can't find them.

If you set `curl=/opt/netdata/bin/curl` to try it again by hand, does it work?

**Comment by kubuntux** [comment] 2018-07-12 12:29
Hello @ktsaou, ok I'll try this in another server. Then I'll let you know the results.

Still waiting for some real alerts to happen.

**Comment by kubuntux** [comment] 2018-07-12 12:47
@ktsaou 

Ok I tried both, but this what worked for me: `curl="/usr/bin/curl"`

I tested to raise live alarm by changing system.cpu warning levels.

**Comment by Ferroin** [comment] 2018-07-12 12:57
YOu can check if it's a certificate issue by disabling certificate verification by uncommenting or adding this line in `/etc/netdata/health_alarm_notify.conf`:

    curl_options='--insecure'

If you get notifications fine with that, then it's something related to certificate verification.

Note that that should only be used as a long term fix if you can find no other solution, disabling certificate verification makes it really easy for an attacker to intercept notifications, read them, and prevent them from ever being delivered (potentially with no indication in the log files that this is happening).
