### ISSUE TITLE
Tomcat metrics stopped reporting after upgrading to v1.8.0

### ISSUE THREAD

**Issue by kmhagan** [firehol/netdata#2837] opened 2017-10-03 19:05 UTC
Hello,

Most tomcat metrics stopped reporting after I upgraded from netdata-v1.7.0-14 to netdata-v1.8.0-76

Here is a picture showing the metrics after the upgrade:
![image](https://user-images.githubusercontent.com/8941761/31143353-f041be7e-a831-11e7-9fdd-348f92b63b09.png)

Tomcat metrics from /api/v1/allmetrics for netdata-v1.7.0-14 
```
# chart: netdata.plugin_pythond_tomcat_local (name: netdata.plugin_pythond_tomcat_local)
NETDATA_NETDATA_PLUGIN_PYTHOND_TOMCAT_LOCAL_RUN_TIME="8"      # milliseconds / run
NETDATA_NETDATA_PLUGIN_PYTHOND_TOMCAT_LOCAL_VISIBLETOTAL="8"      # milliseconds / run

# chart: tomcat_local.jvm (name: tomcat_local.jvm)
NETDATA_TOMCAT_LOCAL_JVM_FREE="215"      # MB
NETDATA_TOMCAT_LOCAL_JVM_VISIBLETOTAL="215"      # MB

# chart: tomcat_local.threads (name: tomcat_local.threads)
NETDATA_TOMCAT_LOCAL_THREADS_CURRENT="66"      # current threads
NETDATA_TOMCAT_LOCAL_THREADS_BUSY="2"      # current threads
NETDATA_TOMCAT_LOCAL_THREADS_VISIBLETOTAL="68"      # current threads

# chart: tomcat_local.volume (name: tomcat_local.volume)
NETDATA_TOMCAT_LOCAL_VOLUME_VOLUME="49"      # KB/s
NETDATA_TOMCAT_LOCAL_VOLUME_VISIBLETOTAL="49"      # KB/s

# chart: tomcat_local.accesses (name: tomcat_local.accesses)
NETDATA_TOMCAT_LOCAL_ACCESSES_ACCESSES="4"      # requests/s
NETDATA_TOMCAT_LOCAL_ACCESSES_VISIBLETOTAL="4"      # requests/s
```

And tomcat metrics from /api/v1/allmetrics for netdata-v1.8.0-76
```
# chart: netdata.plugin_pythond_tomcat_local (name: netdata.plugin_pythond_tomcat_local)
NETDATA_NETDATA_PLUGIN_PYTHOND_TOMCAT_LOCAL_RUN_TIME="7"      # milliseconds / run
NETDATA_NETDATA_PLUGIN_PYTHOND_TOMCAT_LOCAL_VISIBLETOTAL="7"      # milliseconds / run

# chart: tomcat_local.jvm_tenured (name: tomcat_local.jvm_tenured)

# chart: tomcat_local.jvm_survivor (name: tomcat_local.jvm_survivor)

# chart: tomcat_local.jvm_eden (name: tomcat_local.jvm_eden)

# chart: tomcat_local.jvm (name: tomcat_local.jvm)
NETDATA_TOMCAT_LOCAL_JVM_FREE="214"      # MB
NETDATA_TOMCAT_LOCAL_JVM_CODE_CACHE="62"      # MB
NETDATA_TOMCAT_LOCAL_JVM_METASPACE="67"      # MB
NETDATA_TOMCAT_LOCAL_JVM_VISIBLETOTAL="343"      # MB

# chart: tomcat_local.threads (name: tomcat_local.threads)
NETDATA_TOMCAT_LOCAL_THREADS_CURRENT="0"      # current threads
NETDATA_TOMCAT_LOCAL_THREADS_BUSY="0"      # current threads
NETDATA_TOMCAT_LOCAL_THREADS_VISIBLETOTAL="0"      # current threads

# chart: tomcat_local.processing_time (name: tomcat_local.processing_time)
NETDATA_TOMCAT_LOCAL_PROCESSING_TIME_PROCESSING_TIME="0"      # seconds
NETDATA_TOMCAT_LOCAL_PROCESSING_TIME_VISIBLETOTAL="0"      # seconds

# chart: tomcat_local.bandwidth (name: tomcat_local.bandwidth)
NETDATA_TOMCAT_LOCAL_BANDWIDTH_SENT="0"      # KB/s
NETDATA_TOMCAT_LOCAL_BANDWIDTH_RECEIVED="0"      # KB/s
NETDATA_TOMCAT_LOCAL_BANDWIDTH_VISIBLETOTAL="0"      # KB/s

# chart: tomcat_local.accesses (name: tomcat_local.accesses)
NETDATA_TOMCAT_LOCAL_ACCESSES_ACCESSES="0"      # requests/s
NETDATA_TOMCAT_LOCAL_ACCESSES_ERRORS="0"      # requests/s
NETDATA_TOMCAT_LOCAL_ACCESSES_VISIBLETOTAL="0"      # requests/s
```

I'm installing netdata through the binary packages. If I reinstall the older version over the new version tomcat metrics appear once again.

**Comment by ktsaou** [comment] 2017-10-03 20:31
oops! 

@kmhagan thank you for reporting this!

`tomcat.chart.py` has been changed by PR #2525 and #2481

@l2isbad @Wing924 please check this.

**Comment by Wing924** [comment] 2017-10-03 23:35
@kmhagan
I checked my netdata, it works well for tomcat.
Can you show me the details of your config, sample status XML and plugin output?

**Comment by kmhagan** [comment] 2017-10-04 00:17
config details:
```
localhost:
  name : 'local'
  url  : 'http://localhost:8280/manager/status?XML=true'
  user : 'username'
  pass : 'password'

localipv4:
  name : 'local'
  url  : 'http://127.0.0.1:8280/manager/status?XML=true'
  user : 'username'
  pass : 'password'

localipv6:
  name : 'local'
  url  : 'http://[::1]:8280/manager/status?XML=true'
  user : 'username'
  pass : 'password'
```

sample XML status:
```
<?xml version="1.0" encoding="utf-8"?><?xml-stylesheet type="text/xsl" href="/manager/xform.xsl" ?>
<status><jvm><memory free='1156637752' total='1282932736' max='3817865216'/><memorypool name='PS Eden Space' type='Heap memory' usageInit='245891072' usageCommitted='531628032' usageMax='1398276096' usageUsed='26204776'/><memorypool name='PS Old Gen' type='Heap memory' usageInit='655884288' usageCommitted='743964672' usageMax='2863661056' usageUsed='92966496'/><memorypool name='PS Survivor Space' type='Heap memory' usageInit='40894464' usageCommitted='7340032' usageMax='7340032' usageUsed='7123712'/><memorypool name='Code Cache' type='Non-heap memory' usageInit='2555904' usageCommitted='57999360' usageMax='251658240' usageUsed='57414976'/><memorypool name='Compressed Class Space' type='Non-heap memory' usageInit='0' usageCommitted='8167424' usageMax='1073741824' usageUsed='7841024'/><memorypool name='Metaspace' type='Non-heap memory' usageInit='0' usageCommitted='71081984' usageMax='-1' usageUsed='69459432'/></jvm><connector name='"ajp-nio-8209"'><threadInfo  maxThreads="200" currentThreadCount="0" currentThreadsBusy="0" /><requestInfo  maxTime="0" processingTime="0" requestCount="0" errorCount="0" bytesReceived="0" bytesSent="0" /><workers></workers></connector><connector name='"http-nio-8280"'><threadInfo  maxThreads="200" currentThreadCount="10" currentThreadsBusy="1" /><requestInfo  maxTime="3552" processingTime="2463843" requestCount="29794" errorCount="6699" bytesReceived="7170673" bytesSent="250886525" /><workers><worker  stage="S" requestProcessingTime="1" requestBytesSent="0" requestBytesReceived="0" remoteAddr="127.0.0.1" virtualHost="localhost" method="GET" currentUri="/manager/status" currentQueryString="XML=true" protocol="HTTP/1.1" /><worker  stage="R" requestProcessingTime="0" requestBytesSent="0" requestBytesReceived="0" remoteAddr="&#63;" virtualHost="&#63;" method="&#63;" currentUri="&#63;" currentQueryString="&#63;" protocol="&#63;" /><worker  stage="R" requestProcessingTime="0" requestBytesSent="0" requestBytesReceived="0" remoteAddr="&#63;" virtualHost="&#63;" method="&#63;" currentUri="&#63;" currentQueryString="&#63;" protocol="&#63;" /><worker  stage="R" requestProcessingTime="0" requestBytesSent="0" requestBytesReceived="0" remoteAddr="&#63;" virtualHost="&#63;" method="&#63;" currentUri="&#63;" currentQueryString="&#63;" protocol="&#63;" /><worker  stage="R" requestProcessingTime="0" requestBytesSent="0" requestBytesReceived="0" remoteAddr="&#63;" virtualHost="&#63;" method="&#63;" currentUri="&#63;" currentQueryString="&#63;" protocol="&#63;" /><worker  stage="R" requestProcessingTime="0" requestBytesSent="0" requestBytesReceived="0" remoteAddr="&#63;" virtualHost="&#63;" method="&#63;" currentUri="&#63;" currentQueryString="&#63;" protocol="&#63;" /><worker  stage="R" requestProcessingTime="0" requestBytesSent="0" requestBytesReceived="0" remoteAddr="&#63;" virtualHost="&#63;" method="&#63;" currentUri="&#63;" currentQueryString="&#63;" protocol="&#63;" /><worker  stage="R" requestProcessingTime="0" requestBytesSent="0" requestBytesReceived="0" remoteAddr="&#63;" virtualHost="&#63;" method="&#63;" currentUri="&#63;" currentQueryString="&#63;" protocol="&#63;" /></workers></connector></status>
```

What do I need to do to get plugin output?

**Comment by Wing924** [comment] 2017-10-04 00:27
@kmhagan 
Can you try this?
```
sudo -u netdata /usr/libexec/netdata/plugins.d 1 tomcat
```

**Comment by kmhagan** [comment] 2017-10-04 00:35
Running:
`sudo -u netdata /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1 tomcat`

Gives me:
```
sudo -u netdata /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1 tomcat
2017-10-04 00:30:55:  INFO: Using python v2
2017-10-04 00:30:55:  INFO: YAML output is ordered
2017-10-04 00:30:55: python.d INFO: reading configuration file: /opt/netdata/usr/libexec/netdata/plugins.d/../../../../etc/netdata/python.d.conf
2017-10-04 00:30:55: python.d INFO: MODULES_DIR='/opt/netdata/usr/libexec/netdata/python.d/', CONFIG_DIR='/opt/netdata/usr/libexec/netdata/plugins.d/../../../../etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['tomcat']
2017-10-04 00:30:55: python.d INFO: CHECKED OK: tomcat_localhost
2017-10-04 00:30:55: python.d INFO: RENAMED: tomcat_local , from tomcat_localhost
2017-10-04 00:30:55: python.d INFO: CHECKED OK: tomcat_localipv4
2017-10-04 00:30:55: python.d INFO: DROPPED: localipv4 , job 'local' is already served by another job.
2017-10-04 00:30:55: python.d ERROR: DISABLED: tomcat/localipv4
2017-10-04 00:30:55: python.d INFO: CHECKED OK: tomcat_localipv6
2017-10-04 00:30:55: python.d INFO: DROPPED: localipv6 , job 'local' is already served by another job.
2017-10-04 00:30:55: python.d ERROR: DISABLED: tomcat/localipv6
CHART tomcat_local.accesses '' Requests requests/s statistics tomcat.accesses area 60000 1
DIMENSION requestCount accesses incremental 1 1
CHART tomcat_local.volume '' Volume KB/s volume tomcat.volume area 60001 1
DIMENSION bytesSent volume incremental 1 1024
CHART tomcat_local.threads '' Threads 'current threads' statistics tomcat.threads line 60002 1
DIMENSION currentThreadCount current absolute 1 1
DIMENSION currentThreadsBusy busy absolute 1 1
CHART tomcat_local.jvm '' 'JVM Free Memory' MB statistics tomcat.jvm area 60003 1
DIMENSION free free absolute 1 1048576

CHART netdata.plugin_pythond_tomcat_local '' 'Execution time for tomcat_local plugin' 'milliseconds / run' python.d netdata.plugin_python area 145000 1
DIMENSION run_time 'run time' absolute 1 1

BEGIN tomcat_local.accesses 0
SET requestCount = 36734
END 
BEGIN tomcat_local.volume 0
SET bytesSent = 313335906
END 
BEGIN tomcat_local.threads 0
SET currentThreadCount = 10
SET currentThreadsBusy = 1
END 
BEGIN tomcat_local.jvm 0
SET free = 660806168
END 

BEGIN netdata.plugin_pythond_tomcat_local 0
SET run_time = 2
END

BEGIN tomcat_local.accesses 1000904
SET requestCount = 36738
END 
BEGIN tomcat_local.volume 1000904
SET bytesSent = 313347418
END 
BEGIN tomcat_local.threads 1000904
SET currentThreadCount = 10
SET currentThreadsBusy = 1
END 
BEGIN tomcat_local.jvm 1000904
SET free = 660801976
END 

BEGIN netdata.plugin_pythond_tomcat_local 1000904
SET run_time = 2
END

... more of the same ...
```

**Comment by kmhagan** [comment] 2017-10-04 00:36
That is on older version, let me install newer version and run again..

**Comment by kmhagan** [comment] 2017-10-04 00:38
Using v1.8.0 version:
```
2017-10-04 00:37:11:  INFO: Using python v2
2017-10-04 00:37:11:  INFO: YAML output is ordered
2017-10-04 00:37:11: python.d INFO: reading configuration file: /opt/netdata/usr/libexec/netdata/plugins.d/../../../../etc/netdata/python.d.conf
2017-10-04 00:37:11: python.d INFO: MODULES_DIR='/opt/netdata/usr/libexec/netdata/python.d/', CONFIG_DIR='/opt/netdata/usr/libexec/netdata/plugins.d/../../../../etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['tomcat']
/opt/netdata/usr/libexec/netdata/python.d/tomcat.chart.py:140: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
  if connector:
2017-10-04 00:37:11: python.d INFO: CHECKED OK: tomcat_localhost
2017-10-04 00:37:11: python.d INFO: RENAMED: tomcat_local , from tomcat_localhost
2017-10-04 00:37:11: python.d INFO: CHECKED OK: tomcat_localipv4
2017-10-04 00:37:11: python.d INFO: DROPPED: localipv4 , job 'local' is already served by another job.
2017-10-04 00:37:11: python.d ERROR: DISABLED: tomcat/localipv4
2017-10-04 00:37:11: python.d INFO: CHECKED OK: tomcat_localipv6
2017-10-04 00:37:11: python.d INFO: DROPPED: localipv6 , job 'local' is already served by another job.
2017-10-04 00:37:11: python.d ERROR: DISABLED: tomcat/localipv6
CHART tomcat_local.accesses '' Requests requests/s statistics tomcat.accesses area 60000 1
DIMENSION requestCount accesses incremental 1 1
DIMENSION errorCount errors incremental 1 1
CHART tomcat_local.bandwidth '' Bandwidth KB/s statistics tomcat.bandwidth area 60001 1
DIMENSION bytesSent sent incremental 1 1024
DIMENSION bytesReceived received incremental 1 1024
CHART tomcat_local.processing_time '' 'processing time' seconds statistics tomcat.processing_time area 60002 1
DIMENSION processingTime 'processing time' incremental 1 1000
CHART tomcat_local.threads '' Threads 'current threads' statistics tomcat.threads area 60003 1
DIMENSION currentThreadCount current absolute 1 1
DIMENSION currentThreadsBusy busy absolute 1 1
CHART tomcat_local.jvm '' 'JVM Memory Pool Usage' MB memory tomcat.jvm stacked 60004 1
DIMENSION free free absolute 1 1048576
DIMENSION code_cache_used 'code cache' absolute 1 1048576
DIMENSION metaspace_used metaspace absolute 1 1048576
CHART tomcat_local.jvm_eden '' 'Eden Memory Usage' MB memory tomcat.jvm_eden area 60005 1
CHART tomcat_local.jvm_survivor '' 'Survivor Memory Usage' MB memory tomcat.jvm_survivor area 60006 1
CHART tomcat_local.jvm_tenured '' 'Tenured Memory Usage' MB memory tomcat.jvm_tenured area 60007 1

CHART netdata.plugin_pythond_tomcat_local '' 'Execution time for tomcat_local plugin' 'milliseconds / run' python.d netdata.plugin_python area 145000 1
DIMENSION run_time 'run time' absolute 1 1

BEGIN tomcat_local.accesses 0
SET requestCount = 0
SET errorCount = 0
END 
BEGIN tomcat_local.bandwidth 0
SET bytesSent = 0
SET bytesReceived = 0
END 
BEGIN tomcat_local.processing_time 0
SET processingTime = 0
END 
BEGIN tomcat_local.threads 0
SET currentThreadCount = 0
SET currentThreadsBusy = 0
END 
BEGIN tomcat_local.jvm 0
SET free = 783002792
SET code_cache_used = 57489408
SET metaspace_used = 69613176
END 

BEGIN netdata.plugin_pythond_tomcat_local 0
SET run_time = 1
END

BEGIN tomcat_local.accesses 1000477
SET requestCount = 0
SET errorCount = 0
END 
BEGIN tomcat_local.bandwidth 1000477
SET bytesSent = 0
SET bytesReceived = 0
END 
BEGIN tomcat_local.processing_time 1000477
SET processingTime = 0
END 
BEGIN tomcat_local.threads 1000477
SET currentThreadCount = 0
SET currentThreadsBusy = 0
END 
BEGIN tomcat_local.jvm 1000477
SET free = 781122584
SET code_cache_used = 57489408
SET metaspace_used = 69613176
END 

BEGIN netdata.plugin_pythond_tomcat_local 1000477
SET run_time = 2
END

... more of the same ...
```

**Comment by kmhagan** [comment] 2017-10-04 01:22
@Wing924 Thanks for mentioning the connector name, didn't have that in original config comments.

I now have:
```
localhost:
  name : 'local'
  url  : 'http://localhost:8280/manager/status?XML=true'
  user : 'username'
  pass : 'password'
  connector_name: '"http-nio-8280"'

localipv4:
  name : 'local'
  url  : 'http://127.0.0.1:8280/manager/status?XML=true'
  user : 'username'
  pass : 'password'
  connector_name: '"http-nio-8280"'

localipv6:
  name : 'local'
  url  : 'http://[::1]:8280/manager/status?XML=true'
  user : 'username'
  pass : 'password'
  connector_name: '"http-nio-8280"'
```

And get the following:
```
# chart: netdata.plugin_pythond_tomcat_local (name: netdata.plugin_pythond_tomcat_local)
NETDATA_NETDATA_PLUGIN_PYTHOND_TOMCAT_LOCAL_RUN_TIME="3"      # milliseconds / run
NETDATA_NETDATA_PLUGIN_PYTHOND_TOMCAT_LOCAL_VISIBLETOTAL="3"      # milliseconds / run

# chart: tomcat_local.jvm_tenured (name: tomcat_local.jvm_tenured)

# chart: tomcat_local.jvm_survivor (name: tomcat_local.jvm_survivor)

# chart: tomcat_local.jvm_eden (name: tomcat_local.jvm_eden)

# chart: tomcat_local.jvm (name: tomcat_local.jvm)
NETDATA_TOMCAT_LOCAL_JVM_FREE="808"      # MB
NETDATA_TOMCAT_LOCAL_JVM_CODE_CACHE="55"      # MB
NETDATA_TOMCAT_LOCAL_JVM_METASPACE="66"      # MB
NETDATA_TOMCAT_LOCAL_JVM_VISIBLETOTAL="929"      # MB

# chart: tomcat_local.threads (name: tomcat_local.threads)
NETDATA_TOMCAT_LOCAL_THREADS_CURRENT="10"      # current threads
NETDATA_TOMCAT_LOCAL_THREADS_BUSY="1"      # current threads
NETDATA_TOMCAT_LOCAL_THREADS_VISIBLETOTAL="11"      # current threads

# chart: tomcat_local.processing_time (name: tomcat_local.processing_time)
NETDATA_TOMCAT_LOCAL_PROCESSING_TIME_PROCESSING_TIME="0"      # seconds
NETDATA_TOMCAT_LOCAL_PROCESSING_TIME_VISIBLETOTAL="0"      # seconds

# chart: tomcat_local.bandwidth (name: tomcat_local.bandwidth)
NETDATA_TOMCAT_LOCAL_BANDWIDTH_SENT="16"      # KB/s
NETDATA_TOMCAT_LOCAL_BANDWIDTH_RECEIVED="1"      # KB/s
NETDATA_TOMCAT_LOCAL_BANDWIDTH_VISIBLETOTAL="17"      # KB/s

# chart: tomcat_local.accesses (name: tomcat_local.accesses)
NETDATA_TOMCAT_LOCAL_ACCESSES_ACCESSES="4"      # requests/s
NETDATA_TOMCAT_LOCAL_ACCESSES_ERRORS="0"      # requests/s
NETDATA_TOMCAT_LOCAL_ACCESSES_VISIBLETOTAL="4"      # requests/s
```

That fixed my issue with the threads, should i be getting results for jvm_tenured, jvm_survivor, jvm_eden?

**Comment by Wing924** [comment] 2017-10-04 01:35
@kmhagan 
Your memory pool status in XML:
```XML
<memorypool name="PS Eden Space" type="Heap memory" usageInit="245891072" usageCommitted="531628032" usageMax="1398276096" usageUsed="26204776" />
<memorypool name="PS Old Gen" type="Heap memory" usageInit="655884288" usageCommitted="743964672" usageMax="2863661056" usageUsed="92966496" />
<memorypool name="PS Survivor Space" type="Heap memory" usageInit="40894464" usageCommitted="7340032" usageMax="7340032" usageUsed="7123712" />
<memorypool name="Code Cache" type="Non-heap memory" usageInit="2555904" usageCommitted="57999360" usageMax="251658240" usageUsed="57414976" />
```

My tomcat status:
```XML
<memorypool name="Eden Space" type="Heap memory" usageInit="35782656" usageCommitted="35782656" usageMax="35782656" usageUsed="9924488" />
<memorypool name="Survivor Space" type="Heap memory" usageInit="4456448" usageCommitted="4456448" usageMax="4456448" usageUsed="29344" />
<memorypool name="Tenured Gen" type="Heap memory" usageInit="89522176" usageCommitted="89522176" usageMax="89522176" usageUsed="67137840" />
<memorypool name="Code Cache" type="Non-heap memory" usageInit="2555904" usageCommitted="24379392" usageMax="251658240" usageUsed="24104704" />
```

The problem is your tomcat use `PS Eden Space` while my tomcat use `Eden Space`.
Can you tell me what version of tomcat do you use and do you know what does PS mean?

ref. https://github.com/firehol/netdata/blob/master/python.d/tomcat.chart.py#L115

**Comment by kmhagan** [comment] 2017-10-04 01:50
@Wing924 Looking on the box it has `Apache Tomcat Version 8.0.32`, I'm not sure what the difference is from `PS Eden Space` and `Eden Space` is. I see references to PS on google but not an explanation of the differences.

**Comment by ktsaou** [comment] 2017-10-04 06:13
merged it.
Thank you @Wing924 !

**Comment by kmhagan** [comment] 2017-10-04 15:59
@Wing924 thanks for making the changes! However they won't catch `PS Old Gen`

`PS Old Gen` and `Tenured Gen` are from what I can tell the same thing: https://stackoverflow.com/questions/26461226/difference-between-old-generation-and-tenured-generation

**Comment by Wing924** [comment] 2017-10-05 02:27
@kmhagan 
I deep searched about JVM memory pool and found:
- PS Old Gen: parallel GC
- Tenured Gen: Serial GC

I'll send PR later.

ref. https://searchcode.com/file/125200329/src/share/vm/services/memoryService.cpp

@ktsaou Can you reopen this issue?

**Comment by ktsaou** [comment] 2017-10-05 06:35
merged it.

**Closed** 2017-10-05 06:35 UTC
Labels: bug, fixed

**Comment by GitStoph** [comment] 2017-12-07 17:32
I know this is an old closed bug, but I was experiencing a similar-ish issue with the plugin. 
My conf:
```
localhost:
  name : 'localhttps'
  url  : 'https://localhost:8443/manager/status?XML=true'
  user : 'netdata'
  pass : 'mycoolpass'
  connector_name: '"http-bio-8443"'

localipv4:
  name : 'local'
  url  : 'http://127.0.0.1:8443/manager/status?XML=true'
  user : 'netdata'
  pass : 'mycoolpass'
  connector_name: '"http-bio-8443"'

localipv6:
  name : 'local'
  url  : 'https://[::1]:8443/manager/status?XML=true'
  user : 'netdata'
  pass : 'mycoolpass'
  connector_name: '"http-bio-8443"'

Casper:
  name : 'MyJSS'
  url  : 'https://our.cool.domain:8443/manager/status?XML=true'
  user : 'netdata'
  pass : 'mycoolpass'
  connector_name: '"http-bio-8443"'
```
when I run ` sudo -u netdata /usr/libexec/netdata/plugins.d/python.d.plugin 1 tomcat` I get the following results:
```
2017-12-07 11:23:03: python.d INFO: plugin: main: Using python 2
2017-12-07 11:23:03: python.d ERROR: tomcat: localhost: Url: https://localhost:8443/manager/status?XML=true. Error: hostname 'localhost' doesn't match either of '*.my.cool.domain', 'my.cool.domain'
2017-12-07 11:23:03: python.d ERROR: tomcat: localhost: _get_data() returned no data or type is not <dict>
2017-12-07 11:23:03: python.d ERROR: tomcat: localhost: check() => [FAILED]
2017-12-07 11:23:03: python.d ERROR: tomcat: localipv4: _get_data() returned no data or type is not <dict>
2017-12-07 11:23:03: python.d ERROR: tomcat: localipv4: check() => [FAILED]
2017-12-07 11:23:03: python.d ERROR: tomcat: localipv6: Url: https://[::1]:8443/manager/status?XML=true. Error: hostname '::1' doesn't match either of '*.my.cool.domain', 'my.cool.domain'
2017-12-07 11:23:03: python.d ERROR: tomcat: localipv6: _get_data() returned no data or type is not <dict>
2017-12-07 11:23:03: python.d ERROR: tomcat: localipv6: check() => [FAILED]
/usr/libexec/netdata/python.d/tomcat.chart.py:141: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
  if connector:
2017-12-07 11:23:03: python.d INFO: tomcat: Casper: check() => [OK]
CHART netdata.runtime_tomcat_MyJSS '' 'Execution time for tomcat_MyJSS' 'ms' 'python.d' netdata.pythond_runtime line 145000 1
DIMENSION run_time 'run time' absolute 1 1

CHART tomcat_MyJSS.jvm_survivor '' 'Survivor Memory Usage' 'MB' 'memory' 'tomcat.jvm_survivor' area 60006 1 '' 'python.d.plugin' 'tomcat'
DIMENSION 'survivor_used' 'used' absolute 1 1048576 ''
DIMENSION 'survivor_commited' 'commited' absolute 1 1048576 ''
DIMENSION 'survivor_max' 'max' absolute 1 1048576 ''
```
So it runs with the full domain. Since it is an external facing server, I'd prefer to have access to the manager locked down to localhost via:
```
<Context privileged="true" antiResourceLocking="false"
         docBase="${catalina.home}/webapps/manager">
  <Valve className="org.apache.catalina.valves.RemoteAddrValve"
         allow="127\.0\.0\.1" />
</Context>
```
Thing is, when I run elinks on https://localhost:8443/manager/status?XML=true, it works. It only fails in the plugin citing the SSL cert as an issue. Is there a good way I could resolve this without leaving my manager info open to the world? 
Thanks so much!

**Comment by ktsaou** [comment] 2017-12-07 21:17
hm... so I understand the netdata plugin checks the SSL certificate and refuses to fetch the URL if it does not match the certificate.

@l2isbad I searched around and people suggest to use something like this:

```python
s.get("https://localhost", headers={"Host": "example.org"})
```

or

```python
s.get('https://localhost', verify=False)
```

for urllib3 they suggest option `cert_reqs=ssl.CERT_NONE`: https://stackoverflow.com/questions/18061640/ignore-certificate-validation-with-urllib3

Can you check it?

**Comment by GitStoph** [comment] 2017-12-08 17:49
Edited `/usr/libexec/netdata/python.d/tomcat.chart.py` line 79 to say `self.url = self.configuration.get('url', "https://127.0.0.1:8080/manager/status?XML=true", verify=False)`
Result:
```
2017-12-08 11:31:51: python.d INFO: plugin: main: Using python 2
2017-12-08 11:31:51: python.d ERROR: plugin: main: job initialization: 'tomcat localhost' => ['FAILED'] (get() takes no keyword arguments)
2017-12-08 11:31:51: python.d ERROR: plugin: main: job initialization: 'tomcat localipv4' => ['FAILED'] (get() takes no keyword arguments)
2017-12-08 11:31:51: python.d ERROR: plugin: main: job initialization: 'tomcat localipv6' => ['FAILED'] (get() takes no keyword arguments)
2017-12-08 11:31:51: python.d ERROR: plugin: main: job initialization: 'tomcat Casper' => ['FAILED'] (get() takes no keyword arguments)
2017-12-08 11:31:51: python.d ERROR: plugin: main: job initialization: 'tomcat Casper2' => ['FAILED'] (get() takes no keyword arguments)
2017-12-08 11:31:51: python.d INFO: plugin: main: No modules to run. Exit...
```
`self.url = self.configuration.get('url', "https://127.0.0.1:8080/manager/status?XML=true",  headers={"myhost": "myhost.cool.fqdn"})` came back with the result of:
```
2017-12-08 11:36:50: python.d INFO: plugin: main: Using python 2
2017-12-08 11:36:50: python.d ERROR: plugin: main: job initialization: 'tomcat localhost' => ['FAILED'] (get() takes no keyword arguments)
2017-12-08 11:36:50: python.d ERROR: plugin: main: job initialization: 'tomcat localipv4' => ['FAILED'] (get() takes no keyword arguments)
2017-12-08 11:36:50: python.d ERROR: plugin: main: job initialization: 'tomcat localipv6' => ['FAILED'] (get() takes no keyword arguments)
2017-12-08 11:36:50: python.d ERROR: plugin: main: job initialization: 'tomcat Casper' => ['FAILED'] (get() takes no keyword arguments)
2017-12-08 11:36:50: python.d ERROR: plugin: main: job initialization: 'tomcat Casper2' => ['FAILED'] (get() takes no keyword arguments)
2017-12-08 11:36:50: python.d INFO: plugin: main: No modules to run. Exit...
```
`self.url = self.configuration.get('url', "https://127.0.0.1:8080/manager/status?XML=true", cert_reqs=ssl.CERT_NONE)` came back with the result of:
```
2017-12-08 11:41:19: python.d INFO: plugin: main: Using python 2
2017-12-08 11:41:19: python.d ERROR: plugin: main: job initialization: 'tomcat localhost' => ['FAILED'] (global name 'ssl' is not defined)
2017-12-08 11:41:19: python.d ERROR: plugin: main: job initialization: 'tomcat localipv4' => ['FAILED'] (global name 'ssl' is not defined)
2017-12-08 11:41:19: python.d ERROR: plugin: main: job initialization: 'tomcat localipv6' => ['FAILED'] (global name 'ssl' is not defined)
2017-12-08 11:41:19: python.d ERROR: plugin: main: job initialization: 'tomcat Casper' => ['FAILED'] (global name 'ssl' is not defined)
2017-12-08 11:41:19: python.d ERROR: plugin: main: job initialization: 'tomcat Casper2' => ['FAILED'] (global name 'ssl' is not defined)
2017-12-08 11:41:19: python.d INFO: plugin: main: No modules to run. Exit...
```
I suspect my lack of python knowledge is causing some syntax errors. 

In the interim, I found another solution by editing my `/var/lib/tomcat7/conf/Catalina/localhost/manager.xml` to:
```
<Context privileged="true" antiResourceLocking="false"
         docBase="/var/lib/tomcat7/webapps/manager">
  <Valve className="org.apache.catalina.valves.RemoteAddrValve"
         allow="127\.0\.0\.1|my\.ip\.address\.ofhost" denyStatus="404" />
</Context>
```
That way if an unauthorized IP attempts to check the status page, they'll get a 404 and hopefully think that nothing exists there. It'd be cool if netdata could automagically handle these situations, but I know that time is limited and the value of my use case may not be high enough to be a priority. Let me know if there's something else I should try? Thanks!

**Comment by l2isbad** [comment] 2017-12-08 18:26
@GitStoph 
try to modify
https://github.com/firehol/netdata/blob/master/python.d/python_modules/bases/FrameworkServices/UrlService.py#L64

to
```python
return manager(assert_hostname=False, **params)
```

or

```python
return manager(assert_hostname=False, cert_reqs='CERT_NONE', **params)
```

**Comment by ktsaou** [comment] 2017-12-08 20:55
hm... @l2isbad does it make sense to be like that by default?

**Comment by l2isbad** [comment] 2017-12-09 03:28
i think yes, why not

**Comment by l2isbad** [comment] 2017-12-09 07:29
@GitStoph has this solved the problem?

**Comment by GitStoph** [comment] 2017-12-11 20:13
@l2isbad , sorry, just got a chance to try this today. It did not work. The debugger reports:
```
2017-12-11 14:10:35: python.d INFO: plugin: main: Using python 2
/usr/libexec/netdata/python.d/tomcat.chart.py:141: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
  if connector:
2017-12-11 14:10:36: python.d INFO: tomcat: localhost: check() => [OK]
2017-12-11 14:10:36: python.d ERROR: tomcat: localipv4: Url: http://127.0.0.1:8443/manager/status?XML=true. Error: __init__() got an unexpected keyword argument 'assert_hostname'
2017-12-11 14:10:36: python.d ERROR: tomcat: localipv4: _get_data() returned no data or type is not <dict>
2017-12-11 14:10:36: python.d ERROR: tomcat: localipv4: check() => [FAILED]
2017-12-11 14:10:36: python.d ERROR: tomcat: localipv6: _get_data() returned no data or type is not <dict>
2017-12-11 14:10:36: python.d ERROR: tomcat: localipv6: check() => [FAILED]
```
The requested change was made at line 64 with ` sudo nano /usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/UrlService.py` as mentioned above.

**Comment by l2isbad** [comment] 2017-12-11 23:00
> Interestingly enough, it would NOT work for the 1st or third lines without the https for 127

yes,
```python
assert_hostname=False
```
should be added only for `https://` urls, not `http://`

>  Would make sense to change the setting in UrlService.py for people who may bump into it in the future?

yes
