### ISSUE TITLE
Total CPU utilization over 100%

### ISSUE THREAD

**Issue by ciccatrix** [firehol/netdata#644] opened 2016-07-04 15:16 UTC
My system only has 1 core, and collectl/top don't show any such spikes, do you know what could be the problem? These happen quite often.
![spike](https://cloud.githubusercontent.com/assets/5808552/16564989/6f8d4a98-41d8-11e6-8cba-4dd565328be5.png)
![spike2](https://cloud.githubusercontent.com/assets/5808552/16567447/f3dcd746-41ec-11e6-9f59-14b33d2fed70.PNG)
Am I misunderstanding, how could it be over 100%?

**Comment by ktsaou** [comment] 2016-07-04 18:40
Hi. Thanks for reporting this.

This is very strange. You are the first reporting something like that.

Can you give me some information about your system? Is there anything special about it? Is it a physical machine, a VM or an embedded device? Do you know its architecture?

One way for this to happen is to have your own plugins updating the same charts. Have you developed custom plugins?

Does this also happen at the CPU section? The Applications section? The Users section? All these sections have CPU charts.

Please try to answer these questions. I am trying to figure out how that is possible...

**Comment by ciccatrix** [comment] 2016-07-04 20:41
It's an embedded device on ARM (armv5tejl) and using a custom 3.11.10 kernel (very similar to [da850-evm](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/arch/arm/mach-davinci/board-da850-evm.c?h=v3.11)). I haven't used any custom plugins, it's displaying system.cpu, system.load, system.ram, ipv4.tcpsock, ipv4.tcppackets, ipv4.tcperrors, ipv4.tcphandshake, ipv4.udppackets, ipv4.udperrors, ipv4.packets, ipv4.errors, ipv4.fragsout, ipv4.fragsin. 

Happens at the CPU section, will update if I see it on the others you listed.
![cpu section](https://cloud.githubusercontent.com/assets/5808552/16569579/2f3a1236-4206-11e6-8b91-28103fc2a31b.PNG)

**Comment by ktsaou** [comment] 2016-07-04 21:52
This is even more strange. I use netdata on a lot of raspberry PIs (ARM too) without any issues at all.

Questions:

- Was this compiled with gcc?
- Did you enable any optimizations?
- Have you linked it with math lib (`-lm`)?

**Comment by ciccatrix** [comment] 2016-07-04 23:58
Yes, it was compiled with gcc using the -O2 optimization option and was linked with the math library.

This is the full link line:
arm-poky-linux-gnueabi-gcc  -march=armv5te  -marm -mthumb-interwork  -mtune=arm926ej-s --sysroot=/home/sallyhui/git/products_helios/meridian-compact-parent/MC-PH1/target/helios/build/tmp/sysroots/heliosv9      -O2 -pipe -g -feliminate-unused-debug-types -pthread  -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -o netdata appconfig.o avl.o common.o daemon.o dictionary.o global_statistics.o log.o main.o plugin_checks.o plugin_idlejitter.o plugin_nfacct.o plugin_proc.o plugin_tc.o plugins_d.o popen.o proc_diskstats.o proc_interrupts.o proc_softirqs.o proc_loadavg.o proc_meminfo.o proc_net_dev.o proc_net_ip_vs_stats.o proc_net_netstat.o proc_net_rpc_nfsd.o proc_net_snmp.o proc_net_snmp6.o proc_net_stat_conntrack.o proc_net_stat_synproxy.o proc_stat.o proc_self_mountinfo.o proc_sys_kernel_random_entropy_avail.o proc_vmstat.o sys_kernel_mm_ksm.o sys_fs_cgroup.o procfile.o registry.o rrd.o rrd2json.o storage_number.o unit_test.o url.o web_buffer.o web_buffer_svg.o web_client.o web_server.o -lm  -lz   -luuid

**Comment by ktsaou** [comment] 2016-07-05 07:09
Can you disable the optimizations?

The issue is this:

The system.cpu chart is calculating the total for all dimensions. The dimensions are measured in clock ticks. Then the percentage of each dimension is calculated based on this total, so the total for all dimensions should never be above 100%. For some reason, this calculation gives wrong results on this architecture.

If you disable this calculation and it still gives wrong values, I will provide you with a special netdata with some debugging enabled, so that we will be able to track the faulty calculation.

**Comment by ciccatrix** [comment] 2016-07-05 17:05
Okay, I just tried disabling optimizations and it still shows up.

Updated link line:
arm-poky-linux-gnueabi-gcc  -march=armv5te  -marm -mthumb-interwork  -mtune=arm926ej-s --sysroot=/home/sallyhui/git/products_helios/meridian-compact-parent/MC-PH1/target/helios/build/tmp/sysroots/heliosv9      -O0 -pipe -g -feliminate-unused-debug-types -pthread  -Wl,-O0 -Wl,--hash-style=gnu -Wl,--as-needed -o netdata appconfig.o avl.o common.o daemon.o dictionary.o global_statistics.o log.o main.o plugin_checks.o plugin_idlejitter.o plugin_nfacct.o plugin_proc.o plugin_tc.o plugins_d.o popen.o proc_diskstats.o proc_interrupts.o proc_softirqs.o proc_loadavg.o proc_meminfo.o proc_net_dev.o proc_net_ip_vs_stats.o proc_net_netstat.o proc_net_rpc_nfsd.o proc_net_snmp.o proc_net_snmp6.o proc_net_stat_conntrack.o proc_net_stat_synproxy.o proc_stat.o proc_self_mountinfo.o proc_sys_kernel_random_entropy_avail.o proc_vmstat.o sys_kernel_mm_ksm.o sys_fs_cgroup.o procfile.o registry.o rrd.o rrd2json.o storage_number.o unit_test.o url.o web_buffer.o web_buffer_svg.o web_client.o web_server.o -lm  -lz   -luuid    

![disabled](https://cloud.githubusercontent.com/assets/5808552/16592939/1336ccc2-42b1-11e6-8da2-54d964cf4e9d.PNG)

**Comment by ktsaou** [comment] 2016-07-05 20:57
ok. I added a few unit tests and found a case where netdata did the calculation wrong. I fixed it, but I think this will not solve your problem.

Let me explain:

netdata collects values. The bug I fixed was appearing only when a value that is to be collected once per second, sometimes it was collected twice per second or more. When it was collected more than once in the same second, the charts where presenting a spike. This is why we never saw this problem anywhere else. Values never get collected more than once per second. I fixed the calculation. Now even when the values are collected multiple times per second, the calculation is right.

However, what bothers me is that values on your system are sometimes collected multiple times per second. The only way this can happen is if your system has a faulty timer.

I think the `system.cpu` and `cpu.cpuX` charts should now be ok.  However, if I am right and you have a faulty timer, the Applications, Users, User Groups and probably a lot more charts (even not CPU related) will be faulty. The reason is that netdata cannot measure time precisely on this system.

Once workaround could be to increase `update_every`. If you set `update_every = 5`, the effects of this timer accuracy loss may fade. But you have to try it.

**Comment by ciccatrix** [comment] 2016-07-05 21:57
Thanks. I just tried your fix. Yes, the system.cpu and cpu.cpuX charts don't go over 100% now but the users cpu one still does (not sure about the values of all the other charts). I'll look into timing and try less frequent update intervals.

**Comment by ktsaou** [comment] 2016-07-05 22:12
Unfortunately, when the users CPU goes above 100% all the charts (except the percentage ones - after my fix) go crazy too. This is a timer issue.

**Comment by ktsaou** [comment] 2016-07-05 23:17
Assuming your timer is not faulty, I tried to investigate alternatives.

I found the following:

1. `usleep()` may not sleep more that 999999 microseconds on a few systems. This can be a cause for what you are experiencing. I fixed it. Now netdata should handle this properly.

2. `usleep()` has been deprecated by POSIX. I implemented an alternative using `nanosleep()`. To compile netdata with `nanosleep()`, pass `-DNETDATA_WITH_NANOSLEEP=1` to gcc.

Please test both `usleep()` with the fix and `nanosleep()`. If your hardware timer is good, they may fix the problem.

**Comment by ktsaou** [comment] 2016-07-05 23:18
The patches that implement the above are merged. So, please test them.

**Comment by ciccatrix** [comment] 2016-07-06 14:55
I just tried your new merge, with -DNETDATA_WITH_NANOSLEEP=1 added to the CFLAGS, and the users cpu chart still spikes >100%.

`arm-poky-linux-gnueabi-gcc  -march=armv5te  -marm -mthumb-interwork  -mtune=arm926ej-s --sysroot=/home/sallyhui/git/products_helios/meridian-compact-parent/MC-PH1/target/helios/build/tmp/sysroots/heliosv9      -O2 -pipe -g -feliminate-unused-debug-types -DNETDATA_WITH_NANOSLEEP=1 -pthread  -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -o netdata appconfig.o avl.o common.o daemon.o dictionary.o global_statistics.o log.o main.o plugin_checks.o plugin_idlejitter.o plugin_nfacct.o plugin_proc.o plugin_tc.o plugins_d.o popen.o proc_diskstats.o proc_interrupts.o proc_softirqs.o proc_loadavg.o proc_meminfo.o proc_net_dev.o proc_net_ip_vs_stats.o proc_net_netstat.o proc_net_rpc_nfsd.o proc_net_snmp.o proc_net_snmp6.o proc_net_stat_conntrack.o proc_net_stat_synproxy.o proc_stat.o proc_self_mountinfo.o proc_sys_kernel_random_entropy_avail.o proc_vmstat.o sys_kernel_mm_ksm.o sys_fs_cgroup.o procfile.o registry.o rrd.o rrd2json.o storage_number.o unit_test.o url.o web_buffer.o web_buffer_svg.o web_client.o web_server.o -lm  -lz   -luuid    
`

![image](https://cloud.githubusercontent.com/assets/5808552/16622402/13e864e8-4368-11e6-9efe-8c54de1071e9.png)

**Comment by ktsaou** [comment] 2016-07-06 17:08
Hm... it happens on user root...

Let's check something different.

Edit /etc/netdata/netdata.conf find this section:

```
[plugin:apps]
	# update every = 1
	# command options = 
```

and change it to this:

```
[plugin:apps]
	update every = 1
	command options = no-childs
```

Check https://github.com/firehol/netdata/pull/635 for more info. This option disables the effects of this PR. If with this disabled, you never see the see go above 100%, your timer is ok. There is a special case apps.plugin does not handle properly when accumulating childs into parents.

**Comment by ciccatrix** [comment] 2016-07-06 19:08
Okay, I just tried your suggestion, changed the [conf file](http://puu.sh/pSyXV/357323e9aa.txt), still observing it on the application and users cpu charts:
![image](https://cloud.githubusercontent.com/assets/5808552/16631059/0f2c42e4-438b-11e6-9506-20e962d7d5cb.png)
![image](https://cloud.githubusercontent.com/assets/5808552/16631081/2bedcefc-438b-11e6-8012-ca2dfa4c7dc9.png)

**Comment by ktsaou** [comment] 2016-07-06 19:13
can you verify it runs with `no-client` ? Run `ps fax | grep apps.plugin`. Is it there?

**Comment by ciccatrix** [comment] 2016-07-06 19:15
The output is

20229 pts/0    S+     0:00  |       \_ grep apps.plugin
19179 ?        RN     0:22  \_ /usr/libexec/netdata/plugins.d/apps.plugin 1 no-childs

**Comment by ktsaou** [comment] 2016-07-06 19:16
yes it run (it was `no-childs` sure).

**Comment by ciccatrix** [comment] 2016-07-06 19:21
Could I check anything else for you now? If the timer is the problem, could you tell me which charts would still show reliable data?

**Comment by ktsaou** [comment] 2016-07-06 20:13
I am trying to replicate the problem of apps.plugin.
I think the problem is limited to its charts only (i.e. section Applications, Users, User Groups). I have indications that the latest patches broke something there.

The fact that the first bug was triggered on your machine still makes me think there is a timer issue there. However I am not sure. It may be that your system is just too slow for per second collection and this triggered it as a side effect.

For the moment I think I managed to replicate the issue of apps.plugin on a very old rpi 1. Give me some time to figure it out. I am working on it.

**Comment by ciccatrix** [comment] 2016-07-06 20:17
Thanks.. sorry, no rush, just let me know if any more info would be useful from my side.

**Comment by ktsaou** [comment] 2016-07-06 23:18
I think I found the bug in apps.plugin. It is actually a logic problem. apps.plugin is processing the /proc files for a lot of processes and then aggregates the data into a few metrics which are send to netdata. The problem on slow systems is that the time from the read of the first file to the last file can be significant as a percentage of the total time. This causes the CPU utilization to go above 100.

I am developing a fix that will allow apps.plugin to be very precise. Actually I am going to keep timings per file, find the rate per process and then sum their rates to send the total to netdata.

I have a working prototype that seems good. Never goes above 100. But it needs some more work, since I refactored a lot of it.

**Comment by ktsaou** [comment] 2016-07-08 00:56
it closed automatically, I reopen it.
Could you please test it?

**Comment by ciccatrix** [comment] 2016-07-08 01:21
I just tried commit 8e5c1, not sure if it made it worse..
![image](https://cloud.githubusercontent.com/assets/5808552/16674684/cd4ab668-4488-11e6-90a7-ca54c6e51028.png)

**Comment by ktsaou** [comment] 2016-07-08 01:26
Can you try the merged version?

**Comment by ktsaou** [comment] 2016-07-08 01:31
I was assuming hz is 100. If your machine has hz = 1000 this chart is logical.

**Comment by ciccatrix** [comment] 2016-07-08 01:49
It is running at 100Hz (kernel tick). Just tried the merged commit, c2f188, and it seems like the applications and users cpu have not spiked >100%! Thanks so much, I will update you in the morning if it's all good.

**Comment by ktsaou** [comment] 2016-07-08 08:40
> It is running at 100Hz (kernel tick).

Yes, my bad. I had not used hz at all.

> Thanks so much, I will update you in the morning if it's all good.

ok

**Comment by ciccatrix** [comment] 2016-07-08 14:11
Seems good.

**Comment by ktsaou** [comment] 2016-07-08 15:15
ok. I am closing this. If you find any other discrepancy, let me know.

**Closed by ktsaou** 2016-07-08 15:15 UTC
Labels: bug, fixed

**Comment by ktsaou** [comment] 2016-07-08 23:47
could you please make another test with the recent version?

The current version of apps.plugin has a normalization function that prevents it from reporting values above to the total cpu utilization of the system.

I have also added 2 charts to monitor this normalization:

![image](https://cloud.githubusercontent.com/assets/2662304/16704404/5951a59e-457f-11e6-80a4-3254d1d3eb81.png)

For more information check: https://github.com/firehol/netdata/pull/669

**Comment by ciccatrix** [comment] 2016-07-08 23:52
Sure thing, but I will have to check it after the weekend.

**Comment by ciccatrix** [comment] 2016-07-11 15:20
Not sure if there was something specific you wanted me to check with the new charts, so here are how the graphs look like now. Not sure how to enable the netdata.apps_children_fix graph, it doesn't show up in the /netdata.conf but [netdata.apps_fix] does.

![image](https://cloud.githubusercontent.com/assets/5808552/16735977/214b4f66-4759-11e6-815d-3cc5059307e1.png)
![image](https://cloud.githubusercontent.com/assets/5808552/16735998/349ca68c-4759-11e6-87b3-beb13f7af0e0.png)
![image](https://cloud.githubusercontent.com/assets/5808552/16736016/42711bd0-4759-11e6-8f6d-2b0e292d0695.png)
![image](https://cloud.githubusercontent.com/assets/5808552/16736044/5404abfa-4759-11e6-9315-06c7238521f0.png)
![image](https://cloud.githubusercontent.com/assets/5808552/16736055/6065ffde-4759-11e6-81ac-7ca605a720cf.png)

**Comment by ktsaou** [comment] 2016-07-11 15:35
They seem good.

I think we have left `no-children` option to apps.plugin on your setup. You can remove it. Then you will have another `apps_children_fix` chart about the exited children.

At the last chart you posted (apps_fix) you can see the percentage of the collected values used, to match the total CPU utilisation of the system. So, netdata collects info from all processes, and then it gets the total CPU utilisation of the system and uses this info to scale the process information. So the `system.cpu` and `apps.cpu` always match (although apps.plugin will never magnify the information collected from processes - if it is less that `system.cpu`, it will present it without any changes). 

The second chart (`apps_children_fix`) will also show the percentage of the exited children information used. Of course, for `apps_fix` to be less than 100, `apps_children_fix` will be zero. And I see that on your system, `apps_fix` is frequently less than 100.

As I said, this is a timing issue. It is not related to a faulty timer, but it is visible mainly on slower systems. Check the same charts on a faster system:

![image](https://cloud.githubusercontent.com/assets/2662304/16736524/f50e4c54-4795-11e6-9084-1f19e86be71b.png)

`apps_children_fix` is constantly giving values that result in a too big total CPU utilisation.

**Comment by ciccatrix** [comment] 2016-07-11 21:08
Okay, seems good. Should I still have the nanosleep option passed to gcc?

**Comment by ktsaou** [comment] 2016-07-11 21:21
Nice. I switched the default to `nanosleep()`. Everyone runs netdata with it now.

**Comment by collinspam** [comment] 2016-07-13 04:58
UNSUBSCRIBE ME NOW
