### ISSUE TITLE
Empty files in /etc/netdata

### ISSUE THREAD

**Issue by agross** [firehol/netdata#815] opened 2016-08-21 19:44 UTC
Hi,

After the most recent update (`git pull && ./netdata-installer.sh` as usual), I noticed new files showing up in `/etc/netdata`.

There seems to appear a new file after netdata starts. I've had files called `/etc/netdata/230` `/etc/netdata/720` and `/etc/netdata/1800` on different systems. The names always were different. All of the files were empty.

I have yet to determine why they are created. Just restarting the systemd unit doesn't seem to trigger it. I noticed these files because I use etckeeper.

**Comment by ktsaou** [comment] 2016-08-21 20:18
I noticed that too.

What has changed, is that we have been advised for security reasons to change the default directory for netdata to something that is not `/tmp`. PR #775 changed that to `/etc/netdata`. So, the whole process tree runs now in `/etc/netdata.

I deleted the files, updated netdata and re-installed. So far they have not been created. I am not sure which command creates them. For sure this is not intentional.

My mind goes to `/usr/sbin/sendmail`, the command that sends alarms. Have you received alarms at the times the files were created?

**Comment by agross** [comment] 2016-08-21 20:27
@ktsaou 

Yep, I received alarms, but not from the machine that also had an untracked file. (At least there's no mail for root.) I'll monitor the correlation between untracked files and alerts as I currently deleted all untracked files.

Did you consider using [`PrivateTmp=`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#PrivateTmp=) in the systemd unit?

**Comment by ktsaou** [comment] 2016-08-21 20:41
Yes, there have been a long discussion about several systemd options in several issues. The distro maintainers suggested to leave most of the options to their defaults.

I will keep an eye too to find the root cause of these files.

**Comment by ktsaou** [comment] 2016-08-24 11:40
I think I found it. The files are generated by `alarm-email.sh`. I had a few BASH arithmetic comparisons with `>` instead of `-gt`. Too many programming languages in netdata I guess...

Will be merged with PR #835

**Closed** 2016-08-24 11:41 UTC
Labels: bug, fixed

**Comment by agross** [comment] 2016-08-24 11:44
Nice spot! Compiling now, I'll report here if they reappear.
