### ISSUE TITLE
menu without with apache

### ISSUE THREAD

**Issue by yeniugo** [firehol/netdata#3723] opened 2018-05-13 15:52 UTC
os: centos 7.4
apache: 2.4.6
i can not see the apache menu,and what command do I need to enter?i see a command and i have a debug,this is a debug mod

**Comment by l2isbad** [comment] 2018-06-01 12:51
duplicate of https://github.com/firehol/netdata/issues/3725

**Closed** 2018-06-10 21:43 UTC
Labels: duplicate
