### ISSUE TITLE
Line Graph representation 

### ISSUE THREAD

**Issue by arulvelu21** [firehol/netdata#1941] opened 2017-03-14 09:29 UTC
Hi I have created a custom dashboard , which posses only two information such as CPU and RAM . I need to use Line graph to represent both the data in same graph. Where x axis represents time and Y axis represents percentage used. Does netdata supports this multiple data in single chart ?

**Comment by l2isbad** [comment] 2017-03-14 11:48
https://github.com/firehol/netdata/issues/1140

**Comment by ktsaou** [comment] 2017-03-14 21:13
Hi, unfortunately currently no.
I am closing this as duplicate of #1140. Let's continue the discussion there.

**Closed by ktsaou** 2017-03-14 21:13 UTC
