### ISSUE TITLE
NGINX Plus plugin?

### ISSUE THREAD

**Issue by kmhagan** [firehol/netdata#3049] opened 2017-11-22 02:25 UTC
NGINX plugin does not work with NGINX Plus, would be nice to get at least some of the basic information into Netdata that the NGINX plugin provides.

Example of nginx plus dashboard: https://demo.nginx.com/status.html
Example of json data provided: http://demo.nginx.com/status

If this was to be added to Netdata, would it be better as a separate plugin or added to the existing NGINX plugin?

**Comment by l2isbad** [comment] 2017-11-22 03:30
Hi @kmhagan 

Separate.

**Comment by l2isbad** [comment] 2017-12-02 17:49
@ktsaou i need your help
netdata's dashboard 2 level hierarchy is killing me 😄 

Please help me to make charts from
http://demo.nginx.com/status

**Comment by ktsaou** [comment] 2017-12-02 21:28
wow! this has huge amounts of info.

Let's see:

### family `processes`

A chart with this:

```js
  "processes": {
    "respawned": 0
  },
```

### family `connections`

2 charts with these (the first 2 values are connections, the other 2 I guess are workers):

```js
  "connections": {
    "accepted": 59029597,
    "dropped": 2752,
    "active": 10,
    "idle": 983
  },
```

### family `ssl`

a chart with these:

```js
  "ssl": {
    "handshakes": 3881562,
    "handshakes_failed": 732539,
    "session_reuses": 686867
  },
```

### family `requests`

2 charts for these (`total` will be incremental connections/s, and `current` will be absolute connections):

```js
  "requests": {
    "total": 261495697,
    "current": 105
  },
```

### family `web zone XXX`

For each zone a different family with name `zone hg.nginx.org` and as many charts as needed. It would be nice to add a few gauges above each zone.

- chart `nginx.zone_XXX_processing` with `processing`
- chart `nginx.zone_XXX_requests` with `requests` and `discarded`
- chart `nginx.zone_XXX_responses` with `responses`
- chart `nginx.zone_XXX_net` with `sent` (negative) and `received` (positive)

```js
  "server_zones": {
    "hg.nginx.org": {
      "processing": 3,
      "requests": 92009,
      "responses": {
        "1xx": 0,
        "2xx": 90701,
        "3xx": 654,
        "4xx": 218,
        "5xx": 220,
        "total": 91793
      },
      "discarded": 213,
      "received": 22635311,
      "sent": 2718261691
    },
```

### family `web upstream XXX`

One family for each upstream.

Each upstream has many peers, so I suggest to be a little be innovative about charts:

- chart `nginx.upstream_XXX_status` with the `state` (1/0 of up/not up) of each peer as dimension.
- chart `nginx.upstream_XXX_active` with the `active` of each peer as dimension.
- chart `nginx.upstream_XXX_requests` with the `requests` of each peer as dimension.
- chart `nginx.upstream_XXX_fails` with the `fails`  of each peer as dimension.
- chart `nginx.upstream_XXX_unavail` with the `unavail`  of each peer as dimension.
- combined chart `nginx.upstream_XXX_all_net`, area, with the sum of `sent` (negative) and `received` (positive) of all peers.
- a chart like the previous for each peer too: `nginx.upstream_XXX_Y_net` where `Y` is the peer id.
- combined chart `nginx.upstream_XXX_all_responses` with the sum of all peers for `responses` (`1xx`, `2xx`, etc).
- a chart like the previous for each peer too: `nginx.upstream_XXX_Y_responses` where `Y` is the peer id.
- a chart `nginx.upstream_XXX_Y_timings` for each peer, with the timings (`header_time`, `response_time`), where `Y` is the id of each peer.

### family `stream zone XXX`

### family `stream backend XXX`

Again stream backends have many peers, so something like `web upstream` needs to be done here.

### family `cache XXX`

### family `slab XXX`

Many slabs are related to upstreams/backends, so I think we could move them at the upstream section. So, only the slabs that are not associated to an upstream/backends should get their own family.


What do you think?

**Comment by l2isbad** [comment] 2017-12-05 12:59
@ktsaou have a look

processes + connections + ssl + requests + web zone XXX + web upstream XXX

> chart nginx.upstream_XXX_status with the state (1/0 of up/not up) of each peer as dimension

i did 1/-1. Zero values are hidden by default.

> chart nginx.upstream_XXX_fails with the fails of each peer as dimension.
> chart nginx.upstream_XXX_unavail with the unavail of each peer as dimension.

not added. Do you sure we need them?

[snapshot.tar.gz](https://github.com/firehol/netdata/files/1531164/snapshot.tar.gz)

**Comment by l2isbad** [comment] 2017-12-05 13:03
@kmhagan 
what info is the most useful on [nginx plus status page](https://demo.nginx.com/status.html#) ?

it would be great if you looked at nginx_plus charts from my snapshot too.

**Comment by kmhagan** [comment] 2017-12-05 17:58
Hi @l2isbad,

Server Zones, Upstreams, and Caches are the most important for us. It would be nice to get all the metrics though =).

How do I load  a snapshot? I don't see the snapshot icons shown in https://github.com/firehol/netdata/pull/3000 

I'm running netdata version ca54f713103421a4e0f5ed8bd969cbdd38fc8563 which at the time of this writing is the latest.

**Comment by ktsaou** [comment] 2017-12-05 20:02
Wow! snapshots rock!

@kmhagan unzip the snapshot, then click this button on your netdata:

![image](https://user-images.githubusercontent.com/2662304/33627960-d3496634-da07-11e7-91b7-fa0b2427e4c5.png)

then, drag and drop the unzipped snapshot file on the dialog that opens on the dashboard.

@l2isbad comments:

1. workers should be a stacked chart
2. backend status +1/-1 is somewhat problematic. The problem is that we will not be able to show a gauge with the active backends. 1/0 would allow a sum on the dimensions to get the number of active backends.
3. traffic charts (zones and backends) should be area charts and in killobits/s (a rate with 1000 divisor, not 1024).
4. The units of the requests charts is `connections[/s]`. I think they should be `requests[/s]`.

The families should be sorted like this:

1. requests
2. connections
3. ssl
4. processes
5. web zones
6. web upstreams
7. stream zones
8. stream backends

This is very nice work! Well done!

**Comment by kmhagan** [comment] 2017-12-05 20:15
Hi @ktsaou,

I don't see that option in my netdata, do I need to do anything special to enable it?

![image](https://user-images.githubusercontent.com/8941761/33628448-9f2fd8e4-d9b5-11e7-8bd2-60855e8e6c4f.png)

 Note: I just recently upgraded the version of netdata on my virtualbox, not sure if that has anything to do with the option not showing up. Running Firefox v56.0

**Comment by ktsaou** [comment] 2017-12-05 20:17
hm... this is an old netdata.
You need the current git version.
Anyway, you can use any of the demo sites to load the snapshot. Just go to https://my-netdata.io and pick any demo server.

**Comment by ktsaou** [comment] 2017-12-05 20:23
@kmhagan the commit id you posted is the current netdata (7 hours old), but the dashboard image you posted is old. Could you please press control-F5 on your browser to force it reload everything?

**Comment by kmhagan** [comment] 2017-12-05 20:39
I should have known, that did the trick @ktsaou!

**Comment by kmhagan** [comment] 2017-12-05 20:43
Thanks for all the work @l2isbad! 

As mentioned previously I think the following are the metrics we are currently most interested in:
https://demo.nginx.com/status.html#server_zones
https://demo.nginx.com/status.html#upstreams
https://demo.nginx.com/status.html#caches

**Comment by ktsaou** [comment] 2017-12-05 21:02
hm... the UI of nginx provides also a few more info for web upstreams, like:

- % of memory utilization, based on pages
- there is a limit on the connections on a server, this could be used to calculate the % of connections used

**Comment by l2isbad** [comment] 2017-12-05 23:11
found pages in `slabs`

> there is a limit on the connections on a server, this could be used to calculate the % of connections used

i don't see any limit in [json](http://demo.nginx.com/status). No limit in response = no limit?

**Comment by l2isbad** [comment] 2017-12-06 13:52
@ktsaou 
still no `stream` stuff but i believe i did all the suggestions from https://github.com/firehol/netdata/issues/3049#issuecomment-349423951
[snapshot.tar.gz](https://github.com/firehol/netdata/files/1535359/snapshot.tar.gz)

**Comment by ktsaou** [comment] 2017-12-07 20:54
@l2isbad nice work!

I suggest to split the memory chart to separate charts when it can be matched:

1. ssl -> separate ssl_memory chart (area) at the `ssl` family
2. each backend that is matched 100% to the web upstream name -> separate memory chart (area) at each backend family (same is true for web upstream, stream backends and caches)

I also see `backend_connections_usage` chart. This is zero so I don't know what type it is. I suggest to make it `line` chart.

**Comment by l2isbad** [comment] 2017-12-07 23:52
> I also see backend_connections_usage chart. This is zero so I don't know what type it is. I suggest to make it line chart.

It is `active` connections / `max_conns`. If `max_conns` is unlimited % is always zero.
Already line chart.

**Closed** 2018-01-22 23:27 UTC
Labels: enhancement, new plugin request
