### ISSUE TITLE
Prometheus backend with netdata buggy?

### ISSUE THREAD

**Issue by elfgoh** [firehol/netdata#2458] opened 2017-07-13 10:01 UTC
Entering `netdata_system_cpu` into the expression console, and clicking the `execute` button in prometheus, does not reveal any graph. 

I am under the impression that the metrics are not stored in prometheus. 

Appreciate guidance as I am unfamiliar with prometheus.

<img width="1274" alt="screen shot 2017-07-13 at 5 53 17 pm" src="https://user-images.githubusercontent.com/491688/28161213-3c246882-67f5-11e7-925a-34b965333f01.png">

**Comment by ktsaou** [comment] 2017-07-13 19:55
hm... may be, we just changed the format.
@brian-brazil is there a way to verify prometheus is processing the metrics netdata publishes?

**Comment by brian-brazil** [comment] 2017-07-13 20:34
You can check if the scrape is successful on the target status page, and look at the logs for timestamp errors.

**Comment by ktsaou** [comment] 2017-07-14 21:05
@elfgoh did you check? I am going to release netdata this weekend, so it should be good to know it works.

**Comment by elfgoh** [comment] 2017-07-15 07:37
Sorry I am unable to check as I am traveling. Back on Monday. I suggest to just release first?
--------------------------------------------
On Sat, 7/15/17, Costa Tsaousis <notifications@github.com> wrote:

 Subject: Re: [firehol/netdata] Prometheus backend with netdata buggy? (#2458)
 To: "firehol/netdata" <netdata@noreply.github.com>
 Cc: "elfgoh" <elfgoh@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Saturday, July 15, 2017, 4:05 AM
 
 @elfgoh did you check?
 I am going to release netdata this weekend, so it should be
 good to know it works.
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by ktsaou** [comment] 2017-07-15 09:51
ok, no problem. I just checked it works.

**Comment by elfgoh** [comment] 2017-07-18 03:02
It appears that the follow error appears in the systemd logs for prometheus (truncated at the front):

```
4+08:00" level=info msg="Starting prometheus (version=1.7.1, branch=master, revision=3afb3fffa3a29c3de865e1172fb740442e9d0133)" source="main.go:88"
4+08:00" level=info msg="Build context (go=go1.8.3, user=root@0aa1b7fc430d, date=20170612-12:12:06)" source="main.go:89"
4+08:00" level=info msg="Host details (Linux 4.4.54-ti-r93 #1 SMP Fri Mar 17 13:08:22 UTC 2017 armv7l spdibox4816BBBK3CD7 (none))" source="main.go:90"
4+08:00" level=info msg="Loading configuration file /opt/prometheus/prometheus.yml" source="main.go:252"
8+08:00" level=info msg="Loading series map and head chunks..." source="storage.go:428"
2+08:00" level=info msg="3305 series loaded." source="storage.go:439"
2+08:00" level=info msg="Starting target manager..." source="targetmanager.go:63"
2+08:00" level=info msg="Listening on :9090" source="web.go:259"
0+08:00" level=warning msg="Error on ingesting samples with different value but same timestamp" numDropped=3 source="scrape.go:537"
```

**Comment by elfgoh** [comment] 2017-07-18 03:10
It seems that netdata metrics may not be logging to Prometheus. I have managed to graphed `go_goroutines` and `scrape_duration_seconds` without issues. But for netdata metrics, it returns `No datapoints found.`

<img width="1750" alt="screen shot 2017-07-18 at 11 07 56 am" src="https://user-images.githubusercontent.com/491688/28299034-69eef414-6ba9-11e7-8845-cb53e6e80a6c.png">

**Comment by ktsaou** [comment] 2017-07-18 06:38
Could you please post a screenshot of the prometheus status page?

**Comment by elfgoh** [comment] 2017-07-18 07:16
Are you referring to this page?
<img width="1276" alt="screen shot 2017-07-18 at 3 15 31 pm" src="https://user-images.githubusercontent.com/491688/28304838-012703c2-6bcc-11e7-902e-3d11ea0694e6.png">

**Comment by elfgoh** [comment] 2017-07-18 07:48
Fwiw, netdata and promethus are both running on `192.168.7.2`

**Comment by elfgoh** [comment] 2017-07-18 10:18
I did not duplicate the issue when I did a fresh install of netdata on a fresh debian image and then install prometheus as per the [listed instructions](https://github.com/firehol/netdata/wiki/Using-Netdata-with-Prometheus). I guess this issue can be considered closed unless there is a need to further investigate the cause of failure.

**Comment by ktsaou** [comment] 2017-07-18 10:23
ok. If you can't reproduce it anymore, I guess we can close it.

**Closed by ktsaou** 2017-07-18 10:23 UTC
Labels: question
