### ISSUE TITLE
'/usr/libexec/netdata/plugins.d' # : Permission denied

### ISSUE THREAD

**Issue by DardBrinza** [firehol/netdata#1292] opened 2016-11-28 15:54 UTC
After installing netdata, it is not included. The status of the error.

```
root@host:~# service netdata status -l
● netdata.service - Real time performance monitoring
   Loaded: loaded (/etc/systemd/system/netdata.service; enabled)
   Active: failed (Result: exit-code) since Sun 2016-11-27 22:32:05 MSK; 20h ago
  Process: 21839 ExecStart=/usr/sbin/netdata -D (code=exited, status=1/FAILURE)
 Main PID: 21839 (code=exited, status=1/FAILURE)

Nov 27 22:32:05 host175 netdata[21839]: 2016-11-27 22:32:05: netdata: FATAL: Cannot cd to directory '/usr/libexec/netdata/plugins.d' # : Permission denied
Nov 27 22:32:05 host175 systemd[1]: netdata.service: main process exited, code=exited, status=1/FAILURE
Nov 27 22:32:05 host175 systemd[1]: Unit netdata.service entered failed state.
Nov 27 22:32:05 host175 netdata[21839]: 2016-11-27 22:32:05: netdata: INFO: Saving database...
Nov 27 22:32:05 host175 netdata[21839]: 2016-11-27 22:32:05: netdata: INFO: NetData exiting. Bye bye...

```

**Comment by gmorain** [comment] 2016-11-28 16:53
I have the same issue.

I tried to uninstall / reinstall several times, sudo / non sudo mode, in default directory or other directory, but always the same result.

install script is unable to download configuration file, but says 'OK. NetData is installed and it is running.', even if `service netdata status` says otherwise.

I'm no expert, but can help if directed how to collect relevant logfiles

(Debian Jessie updated minutes before the attempt to install netdata)

**Comment by marko8904** [comment] 2016-11-28 18:47
Seeing the same issue. Seems the recent changes modifying global readability affects /usr/libexec and /etc/netdata folders if they are created by netdata installer. They are being created with 770 permissions. You can fix the problem manually by
chmod a+rX /usr/libexec
and
chmod a+rX /etc/netdata

The first one will enable all plugins again. The second one will let netdata read its own config files.

**Comment by alibo** [comment] 2016-11-28 19:02
Also, I think you should change owner of `/usr/libexec/netdata` from `root:root` to `netdata:netdata` by
```
sudo chown -R netdata:netdata /usr/libexec/netdata/
```

**Comment by simon021** [comment] 2016-11-28 19:08
After executing all suggestions including Alibo's, I am left with this when trying to start netdata

 netdata
2016-11-28 13:06:51: netdata: ERROR: Cannot open file '/etc/netdata/netdata.conf' (errno 13, Permission denied)
2016-11-28 13:06:51: netdata: FATAL: Cannot cd to directory '/var/cache/netdata' # : Permission denied

2016-11-28 13:06:51: netdata: INFO: Saving database...
2016-11-28 13:06:51: netdata: INFO: NetData exiting. Bye bye...

Seems like the permissions are still not correct

**Comment by marko8904** [comment] 2016-11-28 19:31
@simon021 see my comment above @alibo's. You need to apply permissions change on /etc/netdata as well (`sudo chmod a+rX /etc/netdata`)

**Comment by simon021** [comment] 2016-11-28 19:33
I followed your suggestions first, and then alibo's

same error.  Do I need the -R to hit everything below /etc/netdata?

**Comment by DardBrinza** [comment] 2016-11-28 19:58
Thank you guys, it works.

**Comment by ktsaou** [comment] 2016-11-28 20:02
my fault guys.
I changed the default `umask` of the installer to `007` and all the directories indirectly created were not world-readable. I changed it back to `002`.

I am testing now the other permissions, because there should not be a problem with them...

**Comment by gmorain** [comment] 2016-11-28 20:15
Hi ktsaou, I've just done the follwoing : 
```
$ sudo ./netdata-uninstaller.sh --force
$ git pull
$ nano netdata-installer.sh # to ensure that umask is 002
$ sudo ./netdata-installer.sh
$ sudo service netdata status
``
and netdata service is now `active`. 
I still have to check that everything works as intended since it's my first install of this tool, and I am currently accessing the machine remotely, but at least the installation part seems now ok !

**Comment by ktsaou** [comment] 2016-11-28 20:19
ok. did a fresh install and yeap, this was it.

I also fixed the directories indirectly and incorrectly created by the wrong umask.
It should be ok now.

merged the fix.

**Comment by ktsaou** [comment] 2016-11-28 20:19
Just pull the repo again and run the installer.
It should fix the wrong permissions.
Please report back success or failure.

**Closed** 2016-11-28 20:19 UTC

**Comment by simon021** [comment] 2016-11-28 20:24
confirming the fix worked.
Thank you all very much.

**Comment by ktsaou** [comment] 2016-11-28 20:27
nice! (and sorry guys...)

**Comment by gmorain** [comment] 2016-11-28 20:48
Hi, 

just forced a reinstall after a git pull, and it works (Debian Jessie)

Thanks for the fix !
