### ISSUE TITLE
Add alert in future?

### ISSUE THREAD

**Issue by bclicn** [firehol/netdata#572] opened 2016-06-17 08:56 UTC
Hi, I was trying to convince my colleagues to use net data in their new project since it's easy to install & has a cool web interface.
But our clients want not only the real-time data but also alerts.
For example they want a text-message to be popped up on their cellphones when something went wrong 
So I think it would be nice if netdata daemon can provide a alert API, ex: Alert monitor-node when CPU usage is greater than 95% in 10 metrics collects. 
I know netdata is a real-time monitoring tool, and for long term monitoring I should probably use ganglia instead. But I really love your GUI  please try to make it as our all-in-one solution for cluster monitoring in future :)  Thanks

**Comment by paulfantom** [comment] 2016-06-17 09:00
Not only them want this feature, there is an ongoing [poll about new features to include in netdata](
https://github.com/firehol/netdata/issues/436).

**Comment by ktsaou** [comment] 2016-06-17 09:01
This is the next feature to be implemented, according to the poll.

**Comment by ktsaou** [comment] 2016-06-26 11:27
Cleaning up. I close this as duplicate of #318

**Closed by ktsaou** 2016-06-26 11:27 UTC
Labels: duplicate, enhancement
