### ISSUE TITLE
Netdata Not Picking Up Fail2ban After Re-install

### ISSUE THREAD

**Issue by Monstar316** [firehol/netdata#2202] opened 2017-05-18 15:52 UTC
I had an issue with Fail2ban and had to do a re-install of it. Since then, netadata is no longer showing anything for fail2ban.

Nothing has changed on my system other than fail2ban was removed then re-added again. The fail2ban.log is where is should be and so is the fail2ban.conf file.

Any help to getting this back on netdata would be greatly appreciated. :-)

**Comment by ktsaou** [comment] 2017-05-18 20:17
I am using fail2ban... probably @l2isbad can help...

**Comment by l2isbad** [comment] 2017-05-18 22:57
> Any help to getting this back on netdata would be greatly appreciated. :-)

Restart netdata?

If still not working
[verify netdata plugins](https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata#configuring-plugins)

**Comment by l2isbad** [comment] 2017-05-19 01:16
Works for me, but regex should be updated (https://github.com/firehol/netdata/pull/2200)
```
apt-cache show fail2ban
Package: fail2ban
Version: 0.9.6-2
```

**Comment by ktsaou** [comment] 2017-05-19 07:39
merged the fix

**Comment by l2isbad** [comment] 2017-05-19 08:06
Actually this is not the fix for the "`Netdata Not Picking Up Fail2ban After Re-install`" problem. Only requirement for the fail2ban plugin is readable `failban.log`.
@Monstar316 
Can you reproduce the problem?
What i did:
1. install fail2ban
2. restart netdata
3. remove fail2ban (fail2ban.log still in the /var/log/)
4. install fail2ban

i see no problem, all works

**Comment by Monstar316** [comment] 2017-05-19 11:29
We're back in business!

@l2isbad Even after doing what you metioned, fail2ban would not run and kept throwing up errors all over the place. I managed to get to the bottom of the issue and once I re-installed fail2ban, it's running fine and netdata has picked it up again :-)

Thanks for getting back to me, guys.

**Comment by ktsaou** [comment] 2017-08-04 20:49
Cleaning up. If you need further help, just post here.

**Closed by ktsaou** 2017-08-04 20:49 UTC
Labels: bug, fixed
