### ISSUE TITLE
web_log plugin does not match hostnames in web log

### ISSUE THREAD

**Issue by G4Zz0L1** [firehol/netdata#2670] opened 2017-09-03 02:58 UTC
I'm on Arch, with last version of netdata and httpd and I just can't make it work, either with the default or the LogFormat suggested in the web_log.conf.

I've tried also the custom_log_format, but it seems I'm not able to create the exact regex right, because the web_log debug returns
`python.d ERROR: web_log Unknown log format. You need to use "custom_log_format" feature`

A sample line in the access_log is (now I've returned to the default httpd LogFormat with log_config and logio):
`localhost - - [03/Sep/2017:04:55:47 +0200] "GET /server-status?auto HTTP/1.1" 200 842`

With the LogFormat suggested in the web_log.conf it turns into:
`localhost - - [03/Sep/2017:04:57:36 +0200] "GET /server-status?auto HTTP/1.1" 200 1012 130 7131 "-" "Python-urllib/3.6"`

If anyone can help me, I'll be grateful!

**Comment by ktsaou** [comment] 2017-09-03 08:30
Hi,

Could you please check the git version of netdata? It is very easy to install it. Just uninstall the package and install it with this:

```
bash <(curl -Ss https://my-netdata.io/kickstart.sh)
```

**Comment by l2isbad** [comment] 2017-09-03 08:36
The problem is 

**localhost** - - [03/Sep/2017:04:55:47 +0200] "GET /server-status?auto HTTP/1.1" 200 842

https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py#L564

Plugin expect `ipv4` or `ipv6 `address

**Comment by ktsaou** [comment] 2017-09-03 08:50
I think we should fix it. No?

**Comment by l2isbad** [comment] 2017-09-03 08:59
> I think we should fix it. No?

yes!

**Comment by G4Zz0L1** [comment] 2017-09-03 11:10
Hmm, what should i do? Install the git version or try to find a regex?

The git version will overwrite the package one?

**Comment by ktsaou** [comment] 2017-09-03 11:50
@G4Zz0L1 let's wait for a PR from @l2isbad first.

The best way to install a different distribution of netdata, is to first uninstall the one you have installed.

**Comment by l2isbad** [comment] 2017-09-03 19:07
What should i do? Replace `localhos`t with `127.0.0.1` ?

**Comment by G4Zz0L1** [comment] 2017-09-03 19:22
Or include localhost in the regex for the source IP?

**Comment by G4Zz0L1** [comment] 2017-09-03 23:33
While I'm here, I don't want to open anoter issue, and I don't find the answer googling around: how can I make netdata read the log, if the log are made by root? I've already tried to add netdata to root group, and launching netdata as root, but it still complain:
`python.d ERROR: fail2ban_fail2ban /var/log/fail2ban.log is not readable or empty`
even if:
`-rw-------  1 root     root             927  4 set 01.01 fail2ban.log`

**Comment by ktsaou** [comment] 2017-09-04 04:29
> What should i do? Replace localhost with 127.0.0.1 ?

I think we should not replace anything. Why you can't use the hostname?

@G4Zz0L1 open another issue please for fail2ban.

**Comment by l2isbad** [comment] 2017-09-04 04:59
> Or include localhost in the regex for the source IP?

It can be not only `localhost`

> I think we should not replace anything. Why you can't use the hostname?

Ok. It's easy to identify ipv4/ipv6 address, but i'm not sure if hostname regex not matches anything else . Is it safe to assume that `%h` always stands at the beginning of the line?

**Comment by ktsaou** [comment] 2017-09-04 05:07
https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_host_names

> Hostnames are composed of series of labels concatenated with dots, as are all domain names. For example, "en.wikipedia.org" is a hostname. Each label must be from 1 to 63 characters long,[2] and the entire hostname (including the delimiting dots but not a trailing dot) has a maximum of 253 ASCII characters.[3]
> The Internet standards (Requests for Comments) for protocols mandate that component hostname labels may contain only the ASCII letters 'a' through 'z' (in a case-insensitive manner), the digits '0' through '9', and the minus sign ('-'). The original specification of hostnames in RFC 952, mandated that labels could not start with a digit or with a minus sign, and must not end with a minus sign. However, a subsequent specification (RFC 1123) permitted hostname labels to start with digits. No other symbols, punctuation characters, or white space are permitted.
> While a hostname may not contain other characters, such as the underscore character (_), other DNS names may contain the underscore.[4] Systems such as DomainKeys and service records use the underscore as a means to assure that their special character is not confused with hostnames. For example, _http._sctp.www.example.com specifies a service pointer for an SCTP capable webserver host (www) in the domain example.com. Note that some applications (e.g. Microsoft Internet Explorer) won't work correctly if any part of the hostname contains an underscore character.[5]

So, I guess `([a-z][A-Z][0-9]\.:-)+` should match any IP (v4 or v6) or hostname.

**Comment by l2isbad** [comment] 2017-09-04 05:19
As well as `'-'`. I mean it matches the first occurrence and if it's not `%h` (remote hostname) it will be a bug.
```
root@loled2[/var/log/apache2]tail other_vhosts_access.log.1 -n 1
netdata.mywebsite.com:80 127.0.0.1 - - [18/May/2017:00:02:04 +0900] "GET /api/v1/data?chart=system.io&format=array&points=540&group=average&options=absolute|jsonwrap|nonzero&after=-540&dimensions=out&_=1495033257100 HTTP/1.1" 200 1749 "http://netdata.mywebsite.com:8081/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.114 Safari/537.36 Vivaldi/1.9.818.50"
```

netdata.mywebsite.com:80 is not address

**Comment by G4Zz0L1** [comment] 2017-09-04 05:27
I guess we can't simply check for the life in the httpd file and check the order of the operand?

**Comment by l2isbad** [comment] 2017-09-04 05:28
According http://httpd.apache.org/docs/current/mod/mod_log_config.html `%h` will log the IP address if `HostnameLookups` is set to Off, which is the default.

**Comment by G4Zz0L1** [comment] 2017-09-04 05:29
I can try with that, and if it's the case just leave all like it is now. Give me on sec...

**Comment by G4Zz0L1** [comment] 2017-09-04 05:32
It's alread Off in my system

`HostnameLookups Off`

**Comment by l2isbad** [comment] 2017-09-04 05:32
" If it logs the hostname for only a few hosts, you probably have access control directives mentioning them by name. See the [Require host documentation](http://httpd.apache.org/docs/current/mod/mod_authz_host.html#reqhost)."

**Comment by G4Zz0L1** [comment] 2017-09-04 05:33
I've missed that, let me check

**Comment by G4Zz0L1** [comment] 2017-09-04 05:35
Nope, it isn't that

`grepr "Require host"   
./conf/extra/httpd-info.conf:16:#     #Require host 
./conf/extra/httpd-info.conf:37:#    #Require host `

**Comment by l2isbad** [comment] 2017-09-04 05:48
Well, it's official documentation for Apache 2.4 (current version)
```
lgz@lgz-homepc[~]pacman --sync --info apache
Repository      : extra
Name            : apache
Version         : 2.4.27-1
```
I install it on my arch pc. Default is 
```
[/var/log/httpd]cat access_log 
127.0.0.1 - - [04/Sep/2017:14:42:57 +0900] "GET / HTTP/1.1" 200 481
127.0.0.1 - - [04/Sep/2017:14:42:57 +0900] "GET /icons/blank.gif HTTP/1.1" 200 148
127.0.0.1 - - [04/Sep/2017:14:42:57 +0900] "GET /favicon.ico HTTP/1.1" 404 1092
127.0.0.1 - - [04/Sep/2017:14:43:15 +0900] "GET / HTTP/1.1" 200 481
```

Then 

l```
gz@lgz-homepc[/etc/httpd/conf]grep localhost httpd.conf -B 26 -A 1
<Directory "/srv/http">
    #
    # Possible values for the Options directive are "None", "All",
    # or any combination of:
    #   Indexes Includes FollowSymLinks SymLinksifOwnerMatch ExecCGI MultiViews
    #
    # Note that "MultiViews" must be named *explicitly* --- "Options All"
    # doesn't give it to you.
    #
    # The Options directive is both complicated and important.  Please see
    # http://httpd.apache.org/docs/2.4/mod/core.html#options
    # for more information.
    #
    Options Indexes FollowSymLinks

    #
    # AllowOverride controls what directives may be placed in .htaccess files.
    # It can be "All", "None", or any combination of the keywords:
    #   AllowOverride FileInfo AuthConfig Limit
    #
    AllowOverride None

    #
    # Controls who can get stuff from this server.
    #
    #Require all granted
    Require host localhost      <--------------------------------------!!!
</Directory>
```

```
lgz@lgz-homepc[/var/log/httpd]cat access_log 
127.0.0.1 - - [04/Sep/2017:14:42:57 +0900] "GET / HTTP/1.1" 200 481
127.0.0.1 - - [04/Sep/2017:14:42:57 +0900] "GET /icons/blank.gif HTTP/1.1" 200 148
127.0.0.1 - - [04/Sep/2017:14:42:57 +0900] "GET /favicon.ico HTTP/1.1" 404 1092
127.0.0.1 - - [04/Sep/2017:14:43:15 +0900] "GET / HTTP/1.1" 200 481
localhost - - [04/Sep/2017:14:46:48 +0900] "GET / HTTP/1.1" 200 481
localhost - - [04/Sep/2017:14:46:48 +0900] "GET / HTTP/1.1" 200 481

```

**Comment by l2isbad** [comment] 2017-09-04 05:57
Anyway add 'localhost' to the address regex seem a good idea.

**Comment by G4Zz0L1** [comment] 2017-09-04 16:35
I don't have that line in my apache.conf, but I'll check better when I get home.

**Comment by G4Zz0L1** [comment] 2017-09-04 18:10
Nope, it isn't in the entire httpd folder. I don't know why my log comes like that, though...

**Comment by l2isbad** [comment] 2017-09-04 18:48
You can change it manually to make it work (i cant do a PR right now)

https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py#L564
https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py#L571
https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py#L580

change regex to

```python
r'(?P<address>(?:[\da-f.:]+|localhost))'
```

**Comment by G4Zz0L1** [comment] 2017-09-04 18:50
I already tried with a-zA-Z0-9.:-_ but it didn't work. I'll try yours and report ASAP.

**Comment by G4Zz0L1** [comment] 2017-09-04 18:59
It works in the file web_log.chart.py, but I can't make the same regex on the web_log.conf with the custom_log_format. I've tried any combination of regex that I've in mind, but nothing.

So far so good, though.

**Comment by l2isbad** [comment] 2017-09-04 19:02
Even if regex is correct it will fail because of https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py#L696
(custom regex check function)

**Comment by l2isbad** [comment] 2017-09-04 19:09
> I've tried any combination of regex that I've in mind, but nothing.

You always can check in python interpreter. Just copy one of log lines.

```
lgz@lgz-homepc[~]python
Python 3.6.2 (default, Jul 20 2017, 03:52:27) 
[GCC 7.1.1 20170630] on linux
Type "help", "copyright", "credits" or "license" for more information.
```
```python
>>> import re
>>> string = 'localhost - - [03/Sep/2017:04:55:47 +0200] "GET /server-status?auto HTTP/1.1" 200 842'
>>> regex = '(?P<address>(?:[\da-f.:]+|localhost)) -.*?"(?P<method>[A-Z]+) (?P<url>.*?)" (?P<code>[1-9]\d{2}) (?P<bytes_sent>\d+)'
>>> re.search(regex, s)
<_sre.SRE_Match object; span=(0, 85), match='localhost - - [03/Sep/2017:04:55:47 +0200] "GET />
>>> re.search(regex, string).grpoupdict()
>>> re.search(regex, string).groupdict()
{'address': 'localhost', 'method': 'GET', 'url': '/server-status?auto HTTP/1.1', 'code': '200', 'bytes_sent': '842'}
>>>

**Comment by G4Zz0L1** [comment] 2017-09-04 19:11
Oh, that's the problem. I don't know python very well, but I've to learn it.

Well, I think I can leave it like that, until the PR.

**Comment by ktsaou** [comment] 2017-09-06 20:28
I reopen it, since the PR says "partial fix" is supplied.

**Comment by G4Zz0L1** [comment] 2017-09-06 20:42
It isn't better to build a A-Za-z0-9.:-_ regex? But I can be wrong...

**Comment by l2isbad** [comment] 2017-09-07 03:10
No it's not. At least not in default regexes. But this can be allowed in custom regex.

**Comment by ktsaou** [comment] 2017-09-07 06:48
@l2isbad so is this done? Is anything pending?

**Comment by l2isbad** [comment] 2017-09-10 08:24
Yes. Hostnames will be allowed as addresses in custom regex after https://github.com/firehol/netdata/pull/2693
I think its ok for current implementation (which is not optimal and should be refactored - maybe standalone plugin splitted into different files)

**Comment by ktsaou** [comment] 2017-09-18 17:26
So, shall we close this or you want it open?

**Comment by l2isbad** [comment] 2017-09-18 22:43
close

**Closed** 2017-09-18 22:59 UTC
Labels: bug, fixed
