### ISSUE TITLE
Feature req: change charts color depending on the conditions

### ISSUE THREAD

**Issue by l2isbad** [firehol/netdata#1089] opened 2016-10-09 07:57 UTC
Are there any chance to implement feature that could change charts color?

I want to create a dashboard showing the ups battery charge and it will be awesome if chart colors (in my case easypiechart) could vary depending on the conditions (ex 100 green, <95 > 70 orange and so on).
Or change color on warning/critical alarm is up.

If you are using custom dashboards Its one of the "must have" features in my opinion

**Comment by ktsaou** [comment] 2016-10-09 08:45
this is duplicate of #958 
I have given the solution there.

**Closed** 2016-10-09 08:45 UTC
Labels: duplicate
