### ISSUE TITLE
New release without glibc-ism

### ISSUE THREAD

**Issue by the-maldridge** [firehol/netdata#117] opened 2016-04-01 00:39 UTC
In release 1.0 there is usage of __useconds_t, this breaks the build when building againts musl.  In later iterations of the code this has been corrected.  I am looking to package netdata for Void Linux but cannot package non-release versions.

**Comment by ktsaou** [comment] 2016-04-02 04:01
I think this is duplicate of #66 
The issue you are referring to, has been fixed.

**Comment by the-maldridge** [comment] 2016-04-02 05:19
The issue is mostly fixed.   It is fixed in your source tree, but there is no currently a release containing that code.  At your convenience I am requesting a release (with version number) which contains that fix, that way I can bring this excellent dashboard to Void.

**Comment by ktsaou** [comment] 2016-04-02 09:45
Yes you are right! Sorry!
I am trying to solve a few issues to release it again.
Hopefully I am going to release it tomorrow.

**Comment by ktsaou** [comment] 2016-04-16 16:25
Well, I will add the `fixed` tag again, because I end up entering this issue again and again.
There are many fixes and enhancements to be released. I'll do it asap.

**Comment by ktsaou** [comment] 2016-05-03 12:03
cleaning up. If something remains open it again.

**Closed by ktsaou** 2016-05-03 12:03 UTC
Labels: bug, fixed
