### ISSUE TITLE
Add ACL support - limit access to specific clients (IPs, subnets)

### ISSUE THREAD

**Issue by atsaloli** [firehol/netdata#2732] opened 2017-09-13 22:54 UTC
@ktsaou commented on Jan 29, 2016 in https://github.com/firehol/netdata/issues/49#issuecomment-176745092

> netdata needs some work in order to ... Possibly limit its access to specific clients (IPs, subnets).

@ktsaou added the ability to bind to a specific address which adds security; it would be nice to be able to control who can access netdata -- an ACL would add protection.

I'm aware that one can provide an ACL by putting a Web server in front of the netdata instance or by using iptables; and I saw Costa's comment that this would be a low priority feature.

As a sysadmin, it would be nice if I could configure an ACL in netdata, as that would allow for a simpler configuration (compared to having to bolt on nginx) and increased security.

Thanks for a great tool!

**Comment by mikeweilgart** [comment] 2017-09-14 22:12
Agreed.  I want to emphasize that such a feature would *not* have to be extremely versatile to be useful.  If sysadmins want complicated ACL rulesets, then of course they can use iptables or whatever else.  But for the simple enterprise use case where only a single IP or a single subnet should be allowed to access the netdata console on each host, a simple ACL config option (default to 0.0.0.0/32 to match current behavior) would be a godsend.

**Comment by ktsaou** [comment] 2017-09-15 19:32
Hi,

This is duplicate of #2636 

Well, checking IPv4 and IPv6 IPs, subnets and ranges is quite some work (I tried to find a simple C library for parsing them, without luck).

What I can easily do, is check strings (string patterns like `10.*` or `192.168.*.1`). So, #2636 is about string comparisons.

I am closing in favor of #2636, so let's continue the discussion there.

**Closed by ktsaou** 2017-09-15 19:32 UTC
Labels: duplicate

**Comment by ktsaou** [comment] 2017-09-17 11:40
implemented this with #2750

**Comment by atsaloli** [comment] 2017-09-19 01:49
Wow!!  Thanks!!
