### ISSUE TITLE
EdgeRouter Pro 1.9 Failed Install

### ISSUE THREAD

**Issue by Kuroyukihimeeee** [firehol/netdata#1572] opened 2017-01-15 21:03 UTC
Trying to install Netdata onto an Ubiquiti Edgerouter Pro running 1.9 update generates the following error when using either the basic install or full install.

The following packages have unmet dependencies:
 libmnl-dev : Depends: libmnl0 (= 1.0.3-3) but 1.0.3-5 is to be installed
 uuid-dev : Depends: libc6-dev but it is not going to be installed or
                     libc-dev
 zlib1g-dev : Depends: libc6-dev but it is not going to be installed or
                       libc-dev
E: Unable to correct problems, you have held broken packages.

Already followed steps on https://help.ubnt.com/hc/en-us/articles/205202560-EdgeMAX-Add-other-Debian-packages-to-EdgeOS to ensure it can grab other packages.

Tried installing without these packages but they are required for netdata to run so it will not install.

Any pointers?

**Comment by ktsaou** [comment] 2017-01-15 22:53
You can ignore `libmnl`, netdata can work without it.

The other 2 are needed. The problem is that `libc6-dev is not going to be installed`. I can't know why. It seems a problem of the package manager...

**Comment by ktsaou** [comment] 2017-01-19 16:46
Did you solve it?

**Comment by Kuroyukihimeeee** [comment] 2017-01-20 21:24
No didnt managed to resolve.

Tried factory resetting, updating, etc. Tried without as many packages as i could but couldnt get past libc6-dev issue

**Comment by ktsaou** [comment] 2017-01-20 22:27
I am very sorry. I don't know how to help you though...

**Comment by Kuroyukihimeeee** [comment] 2017-01-20 22:42
No worries, next time it gets a firmware update it might work. Will update at that point if it works or gives a different error at all.

**Comment by ktsaou** [comment] 2017-02-04 21:03
@Kuroyukihimeeee I am closing this.
If we can help somehow, just post.

**Closed by ktsaou** 2017-02-04 21:03 UTC
Labels: question
