### ISSUE TITLE
Hipchat notifications

### ISSUE THREAD

**Issue by curantes** [firehol/netdata#1526] opened 2017-01-08 18:57 UTC
I have a suggestion to also add support of Hipchat alert notification similar to what we have for slack today.

**Comment by ktsaou** [comment] 2017-01-08 19:30
nice!

Can you help?

If you manage to send a notification to hipchat using the `curl` command from a terminal, we could adapt [`alarm-notifiy.sh`](https://github.com/firehol/netdata/blob/master/plugins.d/alarm-notify.sh) to support it.

**Comment by curantes** [comment] 2017-01-08 22:26
I am not a developer but I can try to assist in any way possible. There is a REST API to hipchat and the documentation can be found at: https://www.hipchat.com/docs/apiv2 and the interesting part would be to https://www.hipchat.com/docs/apiv2/method/send_room_notification (Send notification to a room) I think it would be possible to add this to alarm-notify.sh script.

**Comment by ktsaou** [comment] 2017-01-08 22:38
Well, I can do the integration on `alarms-notify.sh`. I only need a working `curl` command. That is a single `curl` shell command that can **successfully** post "hello world" to a room on hipchat.

This will require from you to research a bit hipchat authentication (I will need this info, since this is how `alarms-notify.sh` has to be configured - and documented), setup a test environment where this can be tested, and experiment a bit with the command line options of `curl` to make it happen.

If you can provide this `curl` command, I can make use of it at netdata.

I am sorry, but if you can't do it, we will have to wait for someone with access to hipchat, that can do this research and tests...

**Comment by curantes** [comment] 2017-01-08 22:45
I can do some research on the subject and provide  you with a working curl command. I also will be able to do some testing since I have access to hipchat at work. I will post here when I have a working curl command ready

**Comment by ktsaou** [comment] 2017-01-08 23:31
perfect! looking forward to it!

**Comment by curantes** [comment] 2017-01-12 22:43
Below is an example of a curl that should work. A nice feature is that we can have different background colors for the messages so if it is possible it would be nice if warnings could use yellow, and critical messages red. Also there is a notify flag that might be good to have enabled to users in the room will get notified.

Let me know if you need any other info.

```
AUTH_TOKEN="<hipchat_auth_token>"
ROOM_ID="<hipchat_room_id>"
FROM="netdata" # A label to be shown in addition to the sender's name Valid length range: 0 - 64. 
MESSAGE_FORMAT="text" # Valid values: html, text. Defaults to 'html'.
MESSAGE="Hello World" 
COLOR="yellow" # Background color for message. Valid values: yellow, green, red, purple, gray, random. Defaults to 'yellow'.
NOTIFY="true" # Whether this message should trigger a user notification (change the tab color, play a sound, notify mobile phones, etc). Each recipient's notification preferences are taken into account. Defaults to false.

curl -H "Content-type: application/json" \
-H "Authorization: Bearer $AUTH_TOKEN" \
-X POST \
-d "{\"color\": \"$COLOR\", \"from\": \"$FROM\", \"message_format\": \"$MESSAGE_FORMAT\", \"message\": \"$MESSAGE\", \"notify\": \"$NOTIFY\"}" \
https://api.hipchat.com/v2/room/$ROOM_ID/notification
```

**Comment by ktsaou** [comment] 2017-01-13 00:04
ok, I added it with PR #1561
I see the command executed by netdata is like this:

```
/usr/bin/curl -X POST --write-out '%{http_code}' --silent --output /dev/null -H 'Content-type: application/json' -H 'Authorization: Bearer 1234567890' -d '{"color": "green", "from": "", "message_format": "text", "message": "
<b>test alarm (alarm was raised for 3 seconds)</b>  <small><br/>this is a test alarm to verify notifications work</small><br/>&nbsp;
<small><b>test.chart</b><br/>Chart<br/>&nbsp;</small>
<small><b>test.family</b><br/>Family<br/>&nbsp;</small>
<small><b>Recovered from WARNING</b><br/>Severity<br/>&nbsp;</small>
<small><b>Fri Jan 13 01:51:15 EET 2017<br/><small>(alarm was raised for 3 seconds)</small></b><br/>Time<br/>&nbsp;</small>
<a href="https://registry.my-netdata.io/goto-host-from-alarm.html?host=costa-pc&chart=test.chart&family=test.family&alarm=test_alarm&alarm_unique_id=1&alarm_id=1&alarm_event_id=3">View Netdata</a><br/>&nbsp;
<small><small>The source of this alarm is line ./plugins.d/alarm-notify.sh</small></small>
", "notify": "true"}' https://api.hipchat.com/v2/room/myroom/notification
```

I would like from you a things though:

1. Test it
2. I would appreciate if you format the HTML message to be pretty on hipchat. The HTML is here: https://github.com/ktsaou/netdata/blob/19ab7a86ed068fa22b2c08751cb1c3e7367b8b0b/plugins.d/alarm-notify.sh#L1190-L1198
3. I would like you to add a screenshot and a few instructions on how to obtain a hipchat auth token and enable it at the wiki page: https://github.com/firehol/netdata/wiki/health-monitoring (search on that page for `slack` or `twilio` and do add the coresponding information for hipchat).

Let me know when you are ready, to merge it.

To test it, `git clone https://github.com/ktsaou/netdata.git` and install it. Then, edit `/etc/netdata/health_alarm_notifiy.conf` to set your hipchat auth token and default room, then run `/usr/libexec/netdata/plugins.d/alarms_notify.sh test` to send a few test alarms.

**Comment by ktsaou** [comment] 2017-01-13 00:05
I forgot. I assumed the hipchat API returns http code 200 on success. If it returns something else, let me know.

**Comment by ktsaou** [comment] 2017-01-14 01:09
I merged it, but please check it and I would appreciate if you take care of the wiki...

Thanks!

**Closed** 2017-01-14 01:08 UTC
Labels: enhancement

**Comment by curantes** [comment] 2017-01-19 22:00
I will try to get some time during the weekend to test this and verify the hipchat integration. Also take a look at the wiki and write some documentation about it.

**Comment by ktsaou** [comment] 2017-01-20 00:12
thanks!

**Comment by stolzyboy** [comment] 2017-02-16 21:02
So, we are trying out netdata on our DEV server to see if we want to run it on all the servers but we're having problems with the hipchat notifications. I have the configuration setup correctly, the auth works because if I change it I'll get a 405 error, but when the auth is correct we are receiving a 400 error in the netdata log similar to the below message.

> 2017-02-16 13:52:50: alarm-notify.sh: ERROR: failed to send HipChat notification for: you-will-never-know.net disk.dm-0.disk_last_collected_secs is CLEAR to 'Notifications' with HTTP error code 400.

Any ideas on what could be wrong? The config isn't rocket science so I'm not sure what the issue is fully. 'Notifications' is the room name in HipChat.

**Comment by ktsaou** [comment] 2017-02-16 21:19
@stolzyboy I am afraid this is untested. @curantes never confirmed it works.

So, you are getting error 400. The command that sends the message is this: https://github.com/firehol/netdata/blob/491c122be64043d7dca4622b3ad42b71f80ae5f8/plugins.d/alarm-notify.sh#L883-L887

Experiment with this:

```sh
authtoken="YOUR AUTH TOKEN"
room="YOUR ROOM"
color="red"
netdata="hostname"
msg_format="text"
message="hello world"

curl -X POST --write-out %{http_code} --silent --output /dev/null \
                    -H "Content-type: application/json" \
                    -H "Authorization: Bearer ${authtoken}" \
                    -d "{\"color\": \"${color}\", \"from\": \"${netdata}\", \"message_format\": \"${msg_format}\", \"message\": \"${message}\", \"notify\": \"${notify}\"}" \
                    "https://api.hipchat.com/v2/room/${room}/notification")
```

Can you make it work? It probably needs some minor tweaking...

**Comment by ktsaou** [comment] 2017-02-16 21:20
I have edited my response above. So, get it from github.

You can remove `--output /dev/null` to see the full message it sends back.

**Comment by stolzyboy** [comment] 2017-02-16 21:27
Ok, I thought it was a working solution. 

We use hipchat notifications on our web apps all the time so I can probably figure it out. I probably would have  by now if I had realized this wasn't working "out of the box".

**Comment by stolzyboy** [comment] 2017-02-16 21:41
> 2017-02-16 15:38:00: alarm-notify.sh: ERROR: failed to send HipChat notification for: asdfasdf.net ipv4.udperrors.ipv4_udperrors_last_collected_secs is WARNING to 'Notifications' with HTTP error code {
  "error": {
    "code": 400,
    "message": "The request body cannot be parsed as valid JSON: Invalid control character u'\\n' at: line 1 column 71 (char 70)",
    "type": "Bad Request"
  }

**Comment by stolzyboy** [comment] 2017-02-16 22:40
Ok, so if I remove the ${message} and replace that with 'hello world' the notifications get sent just fine, so something must be wrong with the JSON message that's getting built or how it's encoded or something of that sort.

I'm a PHP dev so I'm not real sure what you can do in this shell script or what language it is so outside of getting this error to show up I'm not sure what else I can help with.

**Comment by ktsaou** [comment] 2017-02-16 23:30
hm... the problem then is here: https://github.com/firehol/netdata/blob/491c122be64043d7dca4622b3ad42b71f80ae5f8/plugins.d/alarm-notify.sh#L1287-L1295

If you make all these lines, one line, separated with `<br/>`, it should work. Can you test it?

**Comment by ktsaou** [comment] 2017-02-16 23:34
I just made a PR. You can download `alarm-notify.sh` from there to test it.

**Comment by stolzyboy** [comment] 2017-02-17 00:04
Doesn't send but has a different error. I looked through and couldn't find anything crazy but here it is.

> HTTP error code {
  "error": {
    "code": 400,
    "message": "The request body cannot be parsed as valid JSON: Expecting ',' delimiter or '}': line 1 column 383 (char 382)",
    "type": "Bad Request"
  }
}

**Comment by ktsaou** [comment] 2017-02-17 00:13
ok, give it another try. Again at the PR.
I think it was not escaping quotes in `<a href="">` properly.

**Comment by ktsaou** [comment] 2017-02-17 00:18
I verified it with json validator. It should be ok now.

**Comment by stolzyboy** [comment] 2017-02-17 00:19
Ok I'll try it. I did remove the anchor tag and then it sent fine. It does send some html in the hipchat message though. 'small' tags look to be doubled up and hipchat may not like that I guess. I'll let you know after I test this version though.

**Comment by ktsaou** [comment] 2017-02-17 00:23
yes, please do. Post a screenshot too.

**Comment by stolzyboy** [comment] 2017-02-17 00:32
I took out all the [small] tags. Also, with HipChat API v2, A successful response is 204 so you'll want to change that, since even though it's sending it still says error.

![image](https://cloud.githubusercontent.com/assets/25830193/23047534/0e30c954-f476-11e6-95be-e2bec3fa1e6f.png)

**Comment by ktsaou** [comment] 2017-02-17 00:41
ok. last one. Please check it and post another screenshot.

**Comment by stolzyboy** [comment] 2017-02-17 00:47
![image](https://cloud.githubusercontent.com/assets/25830193/23047927/66e38e54-f478-11e6-87bc-6344880ebf25.png)

**Comment by ktsaou** [comment] 2017-02-17 00:54
thanks!
I hope this will be the last one.
Post a screenshot again...

**Comment by ktsaou** [comment] 2017-02-17 00:56
keep in mind you can run `/usr/libexec/netdata/plugins.d/alarm-notify.sh test` to generate test alarms

**Comment by stolzyboy** [comment] 2017-02-17 01:08
I think you meant to have it look like the screenshot below. The file you had still had the ) on the next line. I changed the block to the following:

`send_hipchat "${HIPCHAT_AUTH_TOKEN}" "${to_hipchat}" "\
${host} ${status_message}<br/>\
<b>${alarm}</b> ${info_html}<br/>\
<b>${chart}</b> (family <b>${family}</b>) \
<b>${date}${raised_for_html}</b><br/>\
<a href=\\\"${goto_url}\\\">View netdata dashboard</a> \
(source of alarm ${src})\
"
`

![image](https://cloud.githubusercontent.com/assets/25830193/23048426/5309c08a-f47b-11e6-8d09-412a627ca2af.png)

**Comment by stolzyboy** [comment] 2017-02-17 01:09
And that code insert doesn't work so well... :)

**Comment by stolzyboy** [comment] 2017-02-17 01:10
I put a <space> after the closing 'family' ) and before the \ to get the ) on the same line and not fall through to the next.

**Comment by ktsaou** [comment] 2017-02-17 08:21
ok. fixed and merged it.
Could you please confirm it is ok now?

**Comment by stolzyboy** [comment] 2017-02-17 17:33
Looks good.

![image](https://cloud.githubusercontent.com/assets/25830193/23076170/ec2ac79e-f504-11e6-939f-2263dff0df86.png)

**Comment by ktsaou** [comment] 2017-02-17 17:36
nice! Thank you for let me know.

**Comment by stolzyboy** [comment] 2017-02-17 17:37
No problem. Glad I could help.
