### ISSUE TITLE
ElasticsSearch Plugin stalled

### ISSUE THREAD

**Issue by jurgenhaas** [firehol/netdata#1695] opened 2017-02-01 09:58 UTC
This morning, I've updated my ElasticSearch hosts to the latest 5.2 release and restarting the services worked fine on all host except one. NetData reported that there was no data collected by ElasticSearch which was tru for a short moment in time but that recovered, just that NetData didn't recognize that on one host. It was OK on the others.

The attached screenshot shows, that the charts were not collecting data, they stoipped at 10:32 for ElasticSearch were the charts for other plugins continued.

![2017-02-01 10 40 10 screen](https://cloud.githubusercontent.com/assets/1475675/22502473/49ea3490-e86d-11e6-8c30-894b453f5a4b.jpg)

**Comment by l2isbad** [comment] 2017-02-01 11:22
You are right @jurgenhaas  I didn't restart elasticsearch service on my test.
Plugin fail because of

```python
to_netdata['shards_total'] = data['indices']['shards']['total']
```

And the data after restart

```
indices" : {
    "count" : 0,
    "shards" : { },
```

@jurgenhaas if it is not critical for you can you test it?

You need to change
https://github.com/firehol/netdata/blob/master/python.d/elasticsearch.chart.py#L332

to

```python
to_netdata['shards_total'] = data['indices'].get('shards', {}).get('total')
```

Restart netdata service. Then after 30 second restart elasticsearch service. Plugin should not fail.

**Comment by jurgenhaas** [comment] 2017-02-01 11:25
Yes, I can try. However, the effect is not reproducable and probably only happens sometimes. So my question is if I could tailor the test such that I stop ElasticSearch, wait for the alarm and then start ElasticSearch again. Would that answer your question as well?

**Comment by l2isbad** [comment] 2017-02-01 11:30
I can reproduce it 100% of the time on my ES server. The reason i ask you is your ES version. Mine is 2.0.0 and perhaps I am missing something else...

You can  restart service or stop start  or whatever - more tests is better! Plugin must handle all this things correctly.

**Comment by jurgenhaas** [comment] 2017-02-01 11:39
Works like a charm!

**Comment by l2isbad** [comment] 2017-02-01 11:42
@jurgenhaas thx for reporting!

**Comment by jurgenhaas** [comment] 2017-02-01 11:43
My pleasure, that's the best I can contribute. The real work is from your end - much appreciated!

**Comment by ktsaou** [comment] 2017-02-01 12:56
merged the fix.

**Closed by ktsaou** 2017-02-01 12:56 UTC
Labels: bug, fixed
