### ISSUE TITLE
Gradients on gauges

### ISSUE THREAD

**Issue by AckRiteris** [firehol/netdata#1136] opened 2016-10-18 13:49 UTC
Hey, did you change anything to how gradients work? Had a dashboard that looked OK but after one of the updates suddenly all of them are orange-red. 
Relevant div on my page. Color codes are shades of green but I'm getting orangered:

```
<div class="mygauge-combo">
                                <div class="mygauge">
                                        <div
                                                data-netdata="system.swap"
                                                data-host="http://'.$serveriai_ip[$i].':19999/"
                                                data-title="'.$serveriai_vardai[$i].' Swap used space"
                                                data-chart-library="gauge"
                                                data-width="80%"
                                                data-after="-300"
                                                data-points="300"
                                                data-dimensions="used"
                                                data-append-options="absolute,percentage"
                                                data-units="%"
                                                data-gauge-max-value="100"
                                                data-gauge-generate-gradient="[0, 80,100]"
                                                data-gauge-gradient-percent-color-0="#33cc33"
                                                data-gauge-gradient-percent-color-80="#009933"
                                                data-gauge-gradient-percent-color-100="#003300"
                                        ></div>
                                </div>
                        </div>
```

**Comment by ktsaou** [comment] 2016-10-18 20:23
hm... interesting...

I have updated gauge.js to the latest git version with these commits: 63e72bcb0d06240c19ae718191985d1c12d0e218 and e4f65069652915b63f7886d8220465e0041c5e2c

Actually I haven't used the latest, but one a few commits before it, because of this bug: https://github.com/bernii/gauge.js/issues/100

Can you test that the previous version of gauge.js works right?

To do this:

1. if you updated netdata in-place, you should have `/usr/share/netdata/web/lib/gauge.min.js`. If you have it, just edit `/usr/share/netdata/web/dashboard.js` and at line 115, change this:

  ```
NETDATA.gauge_js            = NETDATA.serverDefault + 'lib/gauge-d5260c3.min.js';
```

  to this:

   ```
NETDATA.gauge_js            = NETDATA.serverDefault + 'lib/gauge.min.js';
```

  and press control-F5 on the dashboard.

2. if you don't have this file, download it from this url: `http://bernii.github.io/gauge.js/dist/gauge.min.js`

If it works with this file, I will have to restore it.

**Comment by ktsaou** [comment] 2016-10-20 20:30
did you check it?

**Comment by AckRiteris** [comment] 2016-10-21 10:22
Will check it today and come back to you, ETA 1-2 hrs :)

**Comment by AckRiteris** [comment] 2016-10-21 11:46
Checked, still red.

**Comment by ktsaou** [comment] 2016-10-21 22:12
ok, I will try to reproduce it and report back.

**Comment by ktsaou** [comment] 2017-02-05 16:00
I have updated gauge.is to the just released version 1.3.1
If you can test it, please give it a try...

**Comment by ideaweb** [comment] 2017-03-14 15:44
Any bug in reading data attributes? Because for its not working thats why i tried to debug dashboard.js.

HTML Attributes:
`data-gauge-gradient-percent-color-100="#003300"
data-gauge-gradient-percent-color="#33cc33"`

JS Debug (e.g. 5780):
`console.log(self.data('gauge-gradient-percent-color-100'));
console.log(self.data('gauge-gradient-percent-color'));`

Browser Console Output:
`dashboard.js:5780 undefined
dashboard.js:5781 #33cc33`

**Comment by ktsaou** [comment] 2017-03-14 21:01
this probably broke when I added a more recent jquery version.
I switched `$.data()` to `$.attr()` and it works. Somehow, jquery decided it the to return `undefined` for these keys....

fixed it.

**Comment by ktsaou** [comment] 2017-03-14 21:16
merged it.

**Closed** 2017-03-14 21:16 UTC
Labels: bug, fixed
