### ISSUE TITLE
 multi-server dashboards

### ISSUE THREAD

**Issue by Yangqingsheng** [firehol/netdata#1539] opened 2017-01-10 08:08 UTC
hi！
Netdata only a single monitor a host?

**Comment by ktsaou** [comment] 2017-01-10 08:19
Unfortunately yes, currently.

Could you please describe what a multi-server dashboard could show? You want just CPU, Disk I/O and RAM for each host, or you are interested for something specific?

**Comment by ktsaou** [comment] 2017-01-11 18:20
I am closing this as a duplicate of #115

**Closed** 2017-01-11 18:20 UTC
Labels: question
