### ISSUE TITLE
multiply_range fails if index doesn't exist

### ISSUE THREAD

**Issue by afletch** [firehol/netdata#799] opened 2016-08-18 11:33 UTC
If multiply_range is set and there interfaces within that range which do not exist (no OID), then it appears to block any interfaces which do exist beyond that index.

eg. if you multiply_range: [ 500, 510 ]
And interface 505 doesn't exist, it will not continue to 506 and onwards.

I believe one of two things (or both) would be preferred:
1. continue regardless
2. allow multiple ranges, such as [500,504],[506,510]

**Comment by ktsaou** [comment] 2016-08-20 22:03
Hi, I see in the code that there is nothing to fail at the multiply_range code.

I suspect the issue is related to something else. Can you post the error you get in `/var/log/netdata/error.log`?

Also, please check with `max_request_size: 1`. I suspect that because netdata is sending SNMP requests in batches of `max_request_size`, the whole batch that includes 505 is invalidated.

**Comment by ktsaou** [comment] 2016-09-20 21:33
Did you find the time to check `max_request_size: 1` ?

**Comment by afletch** [comment] 2016-09-21 08:44
I haven't yet. As this is currently working I would need to book in some maintenance for it and that isn't possible just at the moment. Will update this if/when possible. Sorry for not being more responsive.

**Comment by ktsaou** [comment] 2017-02-04 21:43
ok, I am closing this now.
If you manage to check `max_request_size: 1`, please post the result.

**Closed by ktsaou** 2017-02-04 21:43 UTC
Labels: question
