### ISSUE TITLE
apps.plugin complains about not finding its parent

### ISSUE THREAD

**Issue by luisgmuniz** [firehol/netdata#1605] opened 2017-01-22 10:06 UTC
I'm using netdata 1.4.1_master on CentOS 6.8.
When netdata is (re)started, the following message is shown on `/var/log/netdata/error.log`:

    apps.plugin: ERROR: pid 14472 netdata states parent 1, but the later does not exist.

Of course, there **is** a process 1, and it is `/sbin/init`; I've also checked that `/var/run/netdata` contains the correct PID (14472, in this case).

Could it be caused by netdata being run as `netdata` user?  Somewhat to my surprise, I have checked that running as a normal user I can't get details of others' processes (that is, I have to run `sudo ps -fp 1` instead of `sudo ps -p1`).

**Comment by ktsaou** [comment] 2017-01-22 11:25
On the applications charts, do you have any other processes displayed, or it is just netdata?

apps.plugin requires linux capabilities or setuid to root to see the whole process tree.

**Comment by luisgmuniz** [comment] 2017-01-23 12:49
Hmmm...it shows only netdata processes (netdata, apps.plugin, python.d.plugin and tc-qos-helper).
The capabilities [seem to be correct](https://github.com/firehol/netdata/wiki/Apps-Plugin#apps-plugin-is-missing-information):

    # getcap /usr/libexec/netdata/plugins.d/apps.plugin
    /usr/libexec/netdata/plugins.d/apps.plugin = cap_dac_read_search,cap_sys_ptrace+ep

Just in case (and because the machine is hosted in [OVH](http://www.ovh.com) ), I've changed it to setuid/setgid.  Still, no luck.

**Comment by ktsaou** [comment] 2017-01-24 10:15
Well, something is preventing `apps.plugin` from reading files from `/proc`. Are you using selinux, apparmor, grsecurity or something similar?

Other things to try:

1. become user `netdata` (`su -s /bin/sh netdata`) and run `cat /proc/1/stat`. Does it work?
2. post the output of `ls -l /proc`

**Comment by ktsaou** [comment] 2017-02-04 18:35
Did you solve it?

I am closing this since the issue you face does seem related to netdata code.
But, please post if you still believe the issue is related to netdata.

**Closed by ktsaou** 2017-02-04 18:35 UTC
Labels: question

**Comment by mynetfocus** [comment] 2020-05-09 14:54
I encountered similar problem:

> ls -lah  /var/log/netdata/error.log
2020-05-09 10:16:23: apps.plugin ERROR : MAIN : pid 3298645 netdata states parent 1, but the later does not exist.
2020-05-09 10:16:25: apps.plugin ERROR : MAIN : pid 3298645 netdata states parent 1, but the later does not exist.
2020-05-09 10:16:27: apps.plugin ERROR : MAIN : pid 3298645 netdata states parent 1, but the later does not exist.
2020-05-09 10:16:29: apps.plugin ERROR : MAIN : pid 3298645 netdata states parent 1, but the later does not exist.
2020-05-09 10:16:31: apps.plugin ERROR : MAIN : pid 3298645 netdata states parent 1, but the later does not exist.
2020-05-09 10:16:33: apps.plugin ERROR : MAIN : pid 3298645 netdata states parent 1, but the later does not exist.
2020-05-09 10:16:35: apps.plugin ERROR : MAIN : pid 3298645 netdata states parent 1, but the later does not exist.
2020-05-09 10:16:37: apps.plugin ERROR : MAIN : pid 3298645 netdata states parent 1, but the later does not exist.
2020-05-09 10:16:39: apps.plugin ERROR : MAIN : pid 3298645 netdata states parent 1, but the later does not exist.

> ps -ef | grep 3298645
netdata  3298645       1  1 03:13 ?        00:08:24 /usr/sbin/netdata -P /var/run/netdata/netdata.pid -D
netdata  3298841 3298645  0 03:13 ?        00:00:19 /usr/libexec/netdata/plugins.d/apps.plugin 2
netdata  3298847 3298645  0 03:13 ?        00:00:14 /usr/libexec/netdata/plugins.d/go.d.plugin 1
netdata  3298852 3298645  0 03:13 ?        00:03:24 /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
netdata  3657316 3298645  0 10:13 ?        00:00:00 bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1

netdata dashboard is displaying all others metrics such as
- netdata
- apps.plugin
- pythod.d.plugin
- tc-qos-helper
- go.d.plugin
- other

but not showing other apps.

**Comment by ilyam8** [comment] 2020-05-09 20:30
@vlvkobal please take a look

**Comment by vlvkobal** [comment] 2020-05-12 10:37
Please look at the previous [comment](https://github.com/netdata/netdata/issues/1605#issuecomment-274762694).

**Comment by mynetfocus** [comment] 2020-05-15 06:36
> 
> 
> Please look at the previous [comment](https://github.com/netdata/netdata/issues/1605#issuecomment-274762694).

It displayed cat: /proc/1/stat: No such file or directory

So, how to get it working?

**Comment by vlvkobal** [comment] 2020-05-15 08:04
Provide as much information about your environment (which operating system and distribution you're using, if Netdata is running in a container, etc.) as possible.
```
uname -a; grep -Hv "^#" /etc/*release
netdata -V
```

**Comment by mynetfocus** [comment] 2020-05-15 13:06
/etc/cloudlinux-release:CloudLinux release 7.8 (Alexei Leonov) 
/etc/os-release:NAME="CloudLinux"
/etc/os-release:VERSION="7.8 (Alexei Leonov)"
/etc/os-release:ID="cloudlinux"
/etc/os-release:ID_LIKE="rhel fedora centos"
/etc/os-release:VERSION_ID="7.8"
/etc/os-release:PRETTY_NAME="CloudLinux 7.8 (Alexei Leonov)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:cloudlinux:cloudlinux:7.8:GA:server"

netdata v1.22.1-33-nightly

**Comment by vlvkobal** [comment] 2020-05-15 13:33
Do you run Netdata in a container?

**Comment by mynetfocus** [comment] 2020-05-15 15:26
It runs in cpanel with cloudlinux and litespeed webserver.

**Comment by vlvkobal** [comment] 2020-05-15 15:30
@Ferroin do you have any idea on the matter?

**Comment by Ferroin** [comment] 2020-05-15 15:53
If it's affecting root, it's probably an LSM interfering with access to `/proc`.

@mynetfocus Can you run `ls -lZ /proc` and see if it lists anything after the user and group name in the output? If it's anything other than just a `?` for everything, then SELinux is probably the issue here.

**Comment by mynetfocus** [comment] 2020-05-16 10:54
ls -lZ /proc 
dr-xr-xr-x root     root     ?                                1
dr-xr-xr-x root     root     ?                                10
dr-xr-xr-x root     root     ?                                1046332
dr-xr-xr-x root     root     ?                                1046377
dr-xr-xr-x root     root     ?                                11
dr-xr-xr-x root     root     ?                                12
dr-xr-xr-x root     root     ?                                1282
dr-xr-xr-x root     root     ?                                13
dr-xr-xr-x root     root     ?                                131
dr-xr-xr-x root     root     ?                                1338453
dr-xr-xr-x mailman  mailman  ?                                1338484
dr-xr-xr-x mailnull mail     ?                                1338492
dr-xr-xr-x mailman  mailman  ?                                1338500
dr-xr-xr-x mailman  mailman  ?                                1338501
dr-xr-xr-x mailman  mailman  ?                                1338502
dr-xr-xr-x mailman  mailman  ?                                1338503
dr-xr-xr-x mailman  mailman  ?                                1338504
dr-xr-xr-x mailman  mailman  ?                                1338505
dr-xr-xr-x mailman  mailman  ?                                1338506
dr-xr-xr-x mailman  mailman  ?                                1338507
dr-xr-xr-x root     root     ?                                1338639
dr-xr-xr-x dovecot  dovecot  ?                                1338827
dr-xr-xr-x root     root     ?                                139305
dr-xr-xr-x root     root     ?                                1395
dr-xr-xr-x root     root     ?                                14
dr-xr-xr-x root     root     ?                                1409
dr-xr-xr-x root     root     ?                                1455
dr-xr-xr-x root     root     ?                                16
dr-xr-xr-x root     root     ?                                1656
dr-xr-xr-x root     root     ?                                1661
dr-xr-xr-x root     root     ?                                1695
dr-xr-xr-x root     root     ?                                1696
dr-xr-xr-x root     root     ?                                1697
dr-xr-xr-x root     root     ?                                17
dr-xr-xr-x root     root     ?                                1751
dr-xr-xr-x root     root     ?                                1770
dr-xr-xr-x root     root     ?                                18
dr-xr-xr-x root     root     ?                                19
dr-xr-xr-x mysql    mysql    ?                                1928163
dr-xr-xr-x mysql    mysql    ?                                1928566
dr-xr-xr-x root     root     ?                                2
dr-xr-xr-x root     root     ?                                2007694
dr-xr-xr-x root     root     ?                                21
dr-xr-xr-x root     root     ?                                22
dr-xr-xr-x root     root     ?                                23
dr-xr-xr-x root     root     ?                                24
dr-xr-xr-x root     nobody   ?                                2450709
dr-xr-xr-x root     nobody   ?                                2450710
dr-xr-xr-x root     nobody   ?                                2450711
dr-xr-xr-x nobody   nobody   ?                                2450717
dr-xr-xr-x root     nobody   ?                                2450721
dr-xr-xr-x root     nobody   ?                                2450722
dr-xr-xr-x root     root     ?                                26
dr-xr-xr-x root     root     ?                                2640
dr-xr-xr-x root     root     ?                                2689
dr-xr-xr-x root     root     ?                                27
dr-xr-xr-x mongod   mongod   ?                                2733
dr-xr-xr-x root     root     ?                                274
dr-xr-xr-x root     root     ?                                2755
dr-xr-xr-x root     root     ?                                28
dr-xr-xr-x root     root     ?                                2807
dr-xr-xr-x root     root     ?                                2818
dr-xr-xr-x root     root     ?                                29
dr-xr-xr-x root     root     ?                                290
dr-xr-xr-x root     root     ?                                296
dr-xr-xr-x root     root     ?                                297
dr-xr-xr-x root     root     ?                                298
dr-xr-xr-x root     root     ?                                299
dr-xr-xr-x root     root     ?                                3
dr-xr-xr-x root     root     ?                                304
dr-xr-xr-x root     root     ?                                305
dr-xr-xr-x root     root     ?                                306
dr-xr-xr-x root     root     ?                                307
dr-xr-xr-x root     root     ?                                31
dr-xr-xr-x root     root     ?                                313
dr-xr-xr-x root     root     ?                                3139
dr-xr-xr-x root     root     ?                                314
dr-xr-xr-x root     root     ?                                3140
dr-xr-xr-x root     root     ?                                3142
dr-xr-xr-x root     root     ?                                32
dr-xr-xr-x named    named    ?                                3204163
dr-xr-xr-x root     root     ?                                3209
dr-xr-xr-x root     root     ?                                321
dr-xr-xr-x root     root     ?                                322
dr-xr-xr-x root     root     ?                                3226
dr-xr-xr-x root     root     ?                                323
dr-xr-xr-x root     root     ?                                3237
dr-xr-xr-x root     root     ?                                3239
dr-xr-xr-x root     root     ?                                3240
dr-xr-xr-x root     root     ?                                3241
dr-xr-xr-x root     root     ?                                33
dr-xr-xr-x root     root     ?                                3360
dr-xr-xr-x root     root     ?                                3376
dr-xr-xr-x root     root     ?                                34
dr-xr-xr-x root     root     ?                                3401
dr-xr-xr-x root     root     ?                                3428
dr-xr-xr-x root     root     ?                                3465
dr-xr-xr-x root     root     ?                                36
dr-xr-xr-x root     root     ?                                3638467
dr-xr-xr-x root     root     ?                                366744
dr-xr-xr-x root     root     ?                                37
dr-xr-xr-x root     root     ?                                3700
dr-xr-xr-x root     root     ?                                3781664
dr-xr-xr-x fashion1 fashion1 ?                                3787544
dr-xr-xr-x root     root     ?                                38
dr-xr-xr-x root     root     ?                                3804435
dr-xr-xr-x centos   centos   ?                                3804488
dr-xr-xr-x centos   centos   ?                                3804493
dr-xr-xr-x root     root     ?                                3804713
dr-xr-xr-x centos   centos   ?                                3804735
dr-xr-xr-x centos   centos   ?                                3804743
dr-xr-xr-x netdata  netdata  ?                                3831976
dr-xr-xr-x netdata  netdata  ?                                3831986
dr-xr-xr-x netdata  netdata  ?                                3832165
dr-xr-xr-x netdata  netdata  ?                                3832178
dr-xr-xr-x netdata  netdata  ?                                3832188
dr-xr-xr-x root     root     ?                                3840785
dr-xr-xr-x root     root     ?                                3841985
dr-xr-xr-x root     root     ?                                388
dr-xr-xr-x root     root     ?                                39
dr-xr-xr-x hairdot1 hairdot1 ?                                3908956
dr-xr-xr-x root     root     ?                                391
dr-xr-xr-x root     root     ?                                3960482
dr-xr-xr-x root     root     ?                                3960630
dr-xr-xr-x root     root     ?                                3960642
dr-xr-xr-x root     root     ?                                3987463
dr-xr-xr-x root     root     ?                                3987557
dr-xr-xr-x root     root     ?                                3987584
dr-xr-xr-x root     root     ?                                3994439
dr-xr-xr-x foodlic1 foodlic1 ?                                3994846
dr-xr-xr-x rehabsu1 rehabsu1 ?                                4000076
dr-xr-xr-x root     root     ?                                4001642
dr-xr-xr-x assists1 assists1 ?                                4004689
dr-xr-xr-x root     root     ?                                4006046
dr-xr-xr-x root     root     ?                                4009824
dr-xr-xr-x root     root     ?                                4010317
dr-xr-xr-x netdata  netdata  ?                                4013080
dr-xr-xr-x root     root     ?                                4015001
dr-xr-xr-x cooking1 cooking1 ?                                4018353
dr-xr-xr-x root     root     ?                                4018630
dr-xr-xr-x root     root     ?                                4019758
dr-xr-xr-x root     root     ?                                4020872
dr-xr-xr-x netfocus netfocus ?                                4022063
dr-xr-xr-x root     root     ?                                4022943
dr-xr-xr-x root     root     ?                                4022965
dr-xr-xr-x root     root     ?                                4025092
dr-xr-xr-x root     root     ?                                4025098
dr-xr-xr-x root     root     ?                                4026665
dr-xr-xr-x root     root     ?                                4026857
dr-xr-xr-x root     mail     ?                                4027280
dr-xr-xr-x root     root     ?                                4027346
dr-xr-xr-x root     root     ?                                4027355
dr-xr-xr-x root     root     ?                                4027379
dr-xr-xr-x root     root     ?                                4027454
dr-xr-xr-x root     mail     ?                                4027546
dr-xr-xr-x mailnull mail     ?                                4027550
dr-xr-xr-x root     root     ?                                4027764
dr-xr-xr-x mygameb1 mygameb1 ?                                4029982
dr-xr-xr-x root     root     ?                                4030264
dr-xr-xr-x sportin1 sportin1 ?                                4030782
dr-xr-xr-x emfsafe1 emfsafe1 ?                                4030876
dr-xr-xr-x root     root     ?                                4031143
dr-xr-xr-x root     root     ?                                4031181
dr-xr-xr-x root     root     ?                                4031186
dr-xr-xr-x mgbf1    mgbf1    ?                                4031250
dr-xr-xr-x rehabsup rehabsup ?                                4031284
dr-xr-xr-x dovecot  dovecot  ?                                4031386
dr-xr-xr-x mgbf1    mgbf1    ?                                4031393
dr-xr-xr-x root     root     ?                                4031394
dr-xr-xr-x root     mail     ?                                4031548
dr-xr-xr-x root     mail     ?                                4031705
dr-xr-xr-x mailnull mail     ?                                4031708
dr-xr-xr-x root     root     ?                                4031717
dr-xr-xr-x root     root     ?                                4031730
dr-xr-xr-x stemcel3 stemcel3 ?                                4031886
dr-xr-xr-x newshub1 newshub1 ?                                4032137
dr-xr-xr-x stemcel1 stemcel1 ?                                4032143
dr-xr-xr-x autohow1 autohow1 ?                                4032211
dr-xr-xr-x netfocus netfocus ?                                4032401
dr-xr-xr-x nucerit1 nucerit1 ?                                4032464
dr-xr-xr-x reviewa1 reviewa1 ?                                4032573
dr-xr-xr-x faithar1 faithar1 ?                                4032586
dr-xr-xr-x gadgeth1 gadgeth1 ?                                4032594
dr-xr-xr-x assists1 assists1 ?                                4032757
dr-xr-xr-x whoaret1 whoaret1 ?                                4032834
dr-xr-xr-x whoaret1 whoaret1 ?                                4032836
dr-xr-xr-x doggiet1 doggiet1 ?                                4032839
dr-xr-xr-x root     centos   ?                                4032858
dr-xr-xr-x travelf1 travelf1 ?                                4032884
dr-xr-xr-x woodwor1 woodwor1 ?                                4032919
dr-xr-xr-x hpi1     hpi1     ?                                4032928
dr-xr-xr-x hpi1     hpi1     ?                                4032931
dr-xr-xr-x root     root     ?                                4032937
dr-xr-xr-x highseo1 highseo1 ?                                4032952
dr-xr-xr-x highseo1 highseo1 ?                                4032955
dr-xr-xr-x root     root     ?                                4032956
dr-xr-xr-x woodwor1 woodwor1 ?                                4032980
dr-xr-xr-x mailnull mail     ?                                4032985
dr-xr-xr-x hairdot1 hairdot1 ?                                4032989
dr-xr-xr-x foodlic1 foodlic1 ?                                4032992
dr-xr-xr-x fashion1 fashion1 ?                                4032995
dr-xr-xr-x root     root     ?                                4033010
dr-xr-xr-x wealthc1 wealthc1 ?                                4033014
dr-xr-xr-x whoaret1 whoaret1 ?                                4033018
dr-xr-xr-x cooking1 cooking1 ?                                4033019
dr-xr-xr-x faithar1 faithar1 ?                                4033020
dr-xr-xr-x wealthc1 wealthc1 ?                                4033021
dr-xr-xr-x autohow1 autohow1 ?                                4033022
dr-xr-xr-x wealthc1 wealthc1 ?                                4033023
dr-xr-xr-x cooking1 cooking1 ?                                4033025
dr-xr-xr-x root     root     ?                                4033027
dr-xr-xr-x root     root     ?                                408
dr-xr-xr-x root     root     ?                                41
dr-xr-xr-x root     root     ?                                416
dr-xr-xr-x root     root     ?                                42
dr-xr-xr-x root     root     ?                                420
dr-xr-xr-x root     root     ?                                43
dr-xr-xr-x root     root     ?                                44
dr-xr-xr-x root     root     ?                                46
dr-xr-xr-x root     root     ?                                475
dr-xr-xr-x root     root     ?                                48
dr-xr-xr-x root     root     ?                                49
dr-xr-xr-x root     root     ?                                5
dr-xr-xr-x root     root     ?                                50
dr-xr-xr-x root     root     ?                                51
dr-xr-xr-x root     root     ?                                52
dr-xr-xr-x root     root     ?                                53
dr-xr-xr-x root     root     ?                                534
dr-xr-xr-x dbus     dbus     ?                                537
dr-xr-xr-x root     root     ?                                54
dr-xr-xr-x root     root     ?                                55
dr-xr-xr-x root     root     ?                                56
dr-xr-xr-x root     root     ?                                57
dr-xr-xr-x root     root     ?                                589
dr-xr-xr-x polkitd  polkitd  ?                                608
dr-xr-xr-x root     root     ?                                63
dr-xr-xr-x root     root     ?                                635
dr-xr-xr-x root     root     ?                                636
dr-xr-xr-x nscd     nscd     ?                                638
dr-xr-xr-x root     root     ?                                639
dr-xr-xr-x root     root     ?                                64
dr-xr-xr-x root     root     ?                                645
dr-xr-xr-x root     root     ?                                65
dr-xr-xr-x root     root     ?                                67
dr-xr-xr-x root     root     ?                                684
dr-xr-xr-x root     root     ?                                685
dr-xr-xr-x root     root     ?                                7
dr-xr-xr-x root     root     ?                                75
dr-xr-xr-x root     root     ?                                77
dr-xr-xr-x root     root     ?                                78
dr-xr-xr-x root     root     ?                                79
dr-xr-xr-x dovenull dovenull ?                                799075
dr-xr-xr-x dovenull dovenull ?                                799076
dr-xr-xr-x root     root     ?                                799077
dr-xr-xr-x dovenull dovenull ?                                799078
dr-xr-xr-x dovenull dovenull ?                                799079
dr-xr-xr-x dovenull dovenull ?                                799080
dr-xr-xr-x dovenull dovenull ?                                799081
dr-xr-xr-x root     root     ?                                799082
dr-xr-xr-x dovecot  dovecot  ?                                799083
dr-xr-xr-x dovenull dovenull ?                                799084
dr-xr-xr-x dovenull dovenull ?                                799085
dr-xr-xr-x dovenull dovenull ?                                799086
dr-xr-xr-x dovenull dovenull ?                                799087
dr-xr-xr-x root     root     ?                                8
dr-xr-xr-x root     root     ?                                80
dr-xr-xr-x root     root     ?                                807875
dr-xr-xr-x root     root     ?                                81
dr-xr-xr-x root     root     ?                                9
dr-xr-xr-x root     root     ?                                94
dr-xr-xr-x root     root     ?                                acpi
dr-xr-xr-x root     root     ?                                bc
-r--r--r-- root     root     ?                                buddyinfo
dr-xr-xr-x root     root     ?                                bus
-r--r--r-- root     root     ?                                cgroups
-r--r--r-- root     root     ?                                cmdline
-r--r--r-- root     root     ?                                consoles
-r--r--r-- root     root     ?                                cpuinfo
-r--r--r-- root     root     ?                                crypto
-r--r--r-- root     root     ?                                devices
-r--r--r-- root     root     ?                                diskstats
-r--r--r-- root     root     ?                                dma
dr-xr-xr-x root     root     ?                                driver
-r--r--r-- root     root     ?                                execdomains
-r--r--r-- root     root     ?                                fairsched
-r--r--r-- root     root     ?                                fairsched2
-r--r--r-- root     root     ?                                fb
-r--r--r-- root     root     ?                                filesystems
dr-xr-xr-x root     root     ?                                fs
-r--r--r-- root     root     ?                                interrupts
-r--r--r-- root     root     ?                                iomem
-r--r--r-- root     root     ?                                ioports
dr-xr-xr-x root     root     ?                                irq
-r--r--r-- root     root     ?                                kallsyms
dr-xr-xr-x root     root     ?                                kcare
-r-------- root     root     ?                                kcore
-r--r--r-- root     root     ?                                keys
-r--r--r-- root     root     ?                                key-users
-r-------- root     root     ?                                kmsg
-r-------- root     root     ?                                kpagecgroup
-r-------- root     root     ?                                kpagecount
-r-------- root     root     ?                                kpageflags
-r--r--r-- root     root     ?                                loadavg
-r--r--r-- root     root     ?                                locks
dr-xr-xr-x root     root     ?                                lve
-r--r--r-- root     root     ?                                mdstat
-r--r--r-- root     root     ?                                meminfo
-r--r--r-- root     root     ?                                misc
-r--r--r-- root     root     ?                                modules
lrwxrwxrwx root     root     ?                                mounts -> self/mounts
-rw-r--r-- root     root     ?                                mtrr
lrwxrwxrwx root     root     ?                                net -> self/net
-r--r--r-- root     root     ?                                pagetypeinfo
-r--r--r-- root     root     ?                                partitions
-r--r--r-- root     root     ?                                sched_debug
-r--r--r-- root     root     ?                                schedstat
dr-xr-xr-x root     root     ?                                scsi
lrwxrwxrwt root     root     ?                                self -> 4033027
-r-------- root     root     ?                                slabinfo
-r--r--r-- root     root     ?                                softirqs
-r--r--r-- root     root     ?                                stat
-r--r--r-- root     root     ?                                swaps
dr-xr-xr-x root     root     ?                                sys
--w------- root     root     ?                                sysrq-trigger
dr-xr-xr-x root     root     ?                                sysvipc
-r--r--r-- root     root     ?                                timer_list
-rw-r--r-- root     root     ?                                timer_stats
dr-xr-xr-x root     root     ?                                tty
-r--r--r-- root     root     ?                                uptime
-r-------- root     root     ?                                user_beancounters
-r--r--r-- root     root     ?                                version
-r-------- root     root     ?                                vmallocinfo
-r--r--r-- root     root     ?                                vmstat
dr-xr-xr-x root     root     ?                                vz
-r--r--r-- root     root     ?                                zoneinfo

**Comment by mynetfocus** [comment] 2020-05-16 10:54
cat /etc/selinux/config

# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#     enforcing - SELinux security policy is enforced.
#     permissive - SELinux prints warnings instead of enforcing.
#     disabled - No SELinux policy is loaded.
SELINUX=disabled
# SELINUXTYPE= can take one of three two values:
#     targeted - Targeted processes are protected,
#     minimum - Modification of targeted policy. Only selected processes are protected. 
#     mls - Multi Level Security protection.
SELINUXTYPE=targeted
