### ISSUE TITLE
Keyboard prompts during netdata installation

### ISSUE THREAD

**Issue by elfgoh** [firehol/netdata#2320] opened 2017-06-13 09:13 UTC
I wish to run a bash script to install netdata. Example

```
!#/usr/bin/bash 

bash <(curl -Ss https://my-netdata.io/kickstart.sh) all

```

When the kickstart script is running, I believe there is an "Enter" prompt to start the install. Is there anyway to automate the install so I dont have to wait around to physically press enter?

Same question applies to the installation of dependencies

**Comment by ktsaou** [comment] 2017-06-13 19:47
Yes, this is duplicate of #2305 
It is already in PR #2312 
I am closing this. Let's discuss it there.

**Closed by ktsaou** 2017-06-13 19:47 UTC
