### ISSUE TITLE
Sending data to another machine

### ISSUE THREAD

**Issue by sLuvpreet33** [firehol/netdata#2153] opened 2017-05-04 12:14 UTC
Hi, I am using netdata on ubuntu 14.04.

I want to store the netdata data to the influxdb database.

I have configured that successfully when Influxdb is on my local machine,

    [backend]
             enabled = yes
            # data source = average
             type = graphite
             destination = 127.0.0.1:2003
             prefix = nd
             hostname = alpha
             update every = 10

Now, I want to send data to another machine. But there is a thing, I cannot open 2003 port on my remote machine due to some limitations. So, I did something like this on the machine where data is to be sent,

    server {
            listen 80;
            server_name a.b.c.d; # it is the IP(I don't want to disclose it)

        location /netdata-backend {
                proxy_pass http://localhost:2003/;

                access_log /var/log/nginx/netdata-backend_access.log;
                error_log /var/log/nginx/netdata-backend_error.log;

        }

and this on my local machine where netdata is working, 

    [backend]
         enabled = yes
        # data source = average
         type = graphite
         destination = 35.185.176.233:80/netdata-backend
         prefix = nd
         hostname = alpha
         update every = 10

But the error logs say I cannot do that, 

    2017-05-04 17:30:16: netdata: ERROR: Cannot resolve host '35.185.176.233', port '80/netdata-backend': Servname not supported for ai_socktype
    2017-05-04 17:30:16: netdata: ERROR: Failed to update database backend '35.185.176.233:80/netdata-backend'

Can I achieve this ? Is there any way I can send data without opening any other port ?

**Comment by sLuvpreet33** [comment] 2017-05-04 14:05
Also ,

Can we send data to 2 influxdb instances by declaring this `[backend]` block 2 times ?

    [backend]
       enabled = yes
      # data source = average
       type = graphite
       destination = 35.185.176.233:80/netdata-backend
       prefix = nd
       hostname = alpha
       update every = 10

    [backend]
       enabled = yes
      # data source = average
       type = graphite
       destination = 127.0.0.1:2003
       prefix = nd
       hostname = alpha
       update every = 10

like this ??

**Comment by ktsaou** [comment] 2017-05-04 23:33
Hi,

Unfortunately the graphite protocol is not HTTP, so you cannot proxy it through a web server. You can stream metrics from netdata to netdata, but neither this protocol is HTTP. You will need to open port 19999.

So, I think that without opening a port, it cannot be done.

Regarding 2 backends, netdata will accept them on the same line, but only the first available will get the metrics.

If you need to push the metrics to 2 backends concurrently, you can do it by having 2 netdata, even on the same machine. The idea is that on the second netdata:

1. you will bind it to 127.0.0.1:19998
2. you will disable all data collection (everything under the `[plugins]` section) and set all its directories to `/tmp`.
3. you will configure it to receive metrics from the other netdata - you can also set its `memory mode = ram` and `history = 10`, so it will maintain a very short memory database.
4. you will configure it to push its metrics to the second influxdb

So, netdata 1 will be sending metrics to netdata 2 and influxdb 1. Then, netdata 2 will be sending metrics to influxdb 2.

Of course, if you have multiple machines, you can send metrics from each machine to influxdb 1 and to a central netdata. Then at the central netdata push all metrics to influxdb 2.

**Comment by sLuvpreet33** [comment] 2017-05-05 06:39
Oh, that will get things messy.

Another question which I have is that sometimes my disk memory gets fully occupied, means there is no more space on the disk. This causes netdata to crash. So, I am wondering why does netdata crash as netdata only needs RAM ?

**Comment by ktsaou** [comment] 2017-05-05 07:00
I think your RAM is also fully used.

netdata does not crash. It sets its out-of-memory score to 1000, so that it will be the first to be killed in case the system runs out of memory.

This is by design. Running out of memory is a very bad condition and I decided to stop netdata in this case, to protect your other applications.

Generally, you should add swap memory. You can change the OOM score of netdata by editing `netdata.conf`.

**Comment by sLuvpreet33** [comment] 2017-05-05 07:03
Can you give some more info on this OOM score? any kind of article/blog ?

I also suggest you to start a community where people can ask general questions.

**Comment by ktsaou** [comment] 2017-05-05 08:02
> Can you give some more info on this OOM score? any kind of article/blog ?

There are plenty: https://www.google.gr/search?q=linux+oom+score&oq=linux+oom+score

> I also suggest you to start a community where people can ask general questions.

This is where we are discussing now.  You ask questions, I respond. I always respond and for 99% of the cases my response is after a few hours.

Unfortunately, I cannot handle chat or emails myself (I nicelly reject all personal emails I receive too).

Chatting and emailing is one-to-one. They are both a nightmare at this scale if you want to have consistent results. I cannot even imagine how would I handle chatting for a quarter of a million users, 1k new users per day, 500 new installations per day and about 8k users per day using the wiki and searching these issues. You know... I have to work for a living too. These can only happen if the community helps.

So, if you want to lead chatting for netdata, I would be glad to add links all over the place to slack, gitter, or whatever else you decide to use. I will even try to participate and help with all my strength. But, if it becomes loose and people get frustrated due to unresponsiveness, this feature will be harming netdata and I'll be forced to get a distance from it.

**Comment by sLuvpreet33** [comment] 2017-05-05 08:57
So, as Netdata is very light and does not take much RAM and CPU time, I think it should not be killed when physical memory is very less. I will change its oom score so that it keeps working.

I think gitter would be good. I am a beginnner in this field, so, I don't have much insights into this, but sure I will participate and try my best.

**Comment by sLuvpreet33** [comment] 2017-05-05 10:19
And how can I install 2 netdata in the same machine ?
What will be location of the conf file of the 2nd one ?

**Comment by ktsaou** [comment] 2017-05-05 11:02
> And how can I install 2 netdata in the same machine ?
> What will be location of the conf file of the 2nd one ?

anywhere you like, just run `netdata -c /path/to/netdata.conf`. In that netdata.conf you can set the directories it will use, the memory mode, history size, disable plugins to prevent it from collecting system metrics, etc.

**Comment by sLuvpreet33** [comment] 2017-05-05 13:02
So, it means I don't need another installation of Netdata.
Just copy the file to some different location, and run it, is it so ?

**Comment by ktsaou** [comment] 2017-05-05 17:38
> o, it means I don't need another installation of Netdata.
> Just copy the file to some different location, and run it, is it so ?

yes, that is right. Make sure you also set different ports on each.

**Comment by sLuvpreet33** [comment] 2017-05-08 19:00
> you will configure it to receive metrics from the other netdata

How do I do that ?

> you will disable all data collection (everything under the [plugins] section) and set all its directories to /tmp.

       [global]
           # config directory = /etc/netdata
           # log directory = /var/log/netdata
           # plugins directory = /usr/libexec/netdata/plugins.d
           # web files directory = /usr/share/netdata/web
           # cache directory = /var/cache/netdata
           # lib directory = /var/lib/netdata
           # home directory = /var/cache/netdata

Changing all these would be enough ?

**Comment by ktsaou** [comment] 2017-05-08 19:17
metrics replication overview: https://github.com/firehol/netdata/wiki/Replication-Overview
In short, you need to edit `stream.conf` on both the master and the slave (master = receiving netdata, slave = sending netdata).

To run 2 netdata, you need to set completely different directories to both, or a mess is about to happen (they will both save metrics to the same files, use the same files for alarms state, etc).

You have 2 solutions. Pick any:

1. Install netdata another time, at `/opt`. Just run the `./netdata-installer.sh --install /opt`. Now you will have one netdata at `/usr/sbin/netdata` and another one at `/opt/netdata/usr/sbin/netdata`. If you edit `/opt/netdata/etc/netdata/netdata.conf` and set the port to 19998 and start both, everything will work.

2. check [this comment](https://github.com/firehol/netdata/issues/1841#issuecomment-282609090) to see how to configure netdata to use other directories.

Once you have 2 netdata running, both will be collecting metrics. This is a waste. So, on one netdata edit `netdata.conf` and disable all the plugins.

**Comment by sLuvpreet33** [comment] 2017-05-08 20:01
>  disable all the plugins.
 simply comment them out?

**Comment by ktsaou** [comment] 2017-05-08 20:04
> simply comment them out?

by default they are commented:

```
[plugins]
	# tc = yes
	# idlejitter = yes
	# proc = yes
	# diskspace = yes
	# cgroups = yes
	# checks = no
	# enable running new plugins = yes
	# check for new plugins every = 60
	# charts.d = yes
	# fping = yes
	# node.d = yes
	# python.d = yes
	# apps = yes
```

You need to uncomment them and set them to `no`.

**Comment by sLuvpreet33** [comment] 2017-05-09 06:46
2017-05-09 12:14:11: **2437**: (sent/all = 711/1409 bytes -50%, prep/sent/total = 0.06/0.08/0.14 ms) data: 200 '/api/v1/alarms?active&_=1494263457946'

What is that 2347 in the netdata access logs here ?


> You need to uncomment them and set them to no.
What if I delete them ?

**Comment by ktsaou** [comment] 2017-05-09 07:33
When you compile netdata with `-DNETDATA_INTERNAL_CHECKS=1`, netdata logs a few more things, like the unused API parameters passed. This is ok. When you remove this flag, these logs will dissapear. They help us spot issues at the development phase of netdata.

**Comment by ktsaou** [comment] 2017-05-09 07:33
2347 is the id of the connection to netdata. debugging info. ignore it.

**Comment by sLuvpreet33** [comment] 2017-05-15 18:26
Hi @ktsaou , Can you please tell me that from where do you collect the info of Sockets opened by Users in the Users section ?

The root user on my system has opened around 80 sockets, Is this normal OR something is wrong with the system ?

**Comment by ktsaou** [comment] 2017-05-15 20:33
Charts under the Users, Groups and Applications sections collect metrics from the process tree. 
To see all the sockets on your system, per pid, do this:

```sh
sudo ls -l /proc/*/fd/ | grep socket
```

**Comment by sLuvpreet33** [comment] 2017-05-17 21:10
Yeah got it. There is a command for this also, 

    $ ss | wc -l
    96

**Comment by sLuvpreet33** [comment] 2017-05-17 21:19
When I see output of ss,

     monitoring-server@monitoring-server:~$ ss
     Netid State      Recv-Q Send-Q                      Local Address:Port                                       Peer Address:Port                
    u_str ESTAB      0      0                                       * 34006                                                 * 34007

Most of the connections are having Netid as u_str ,  and others having tcp. 

What is this u_str ?

**Comment by ktsaou** [comment] 2017-05-17 23:14
Interesting: https://askubuntu.com/questions/916241/understanding-output-of-ss-command/916252

**Comment by ktsaou** [comment] 2017-05-26 23:00
Cleaning up. I am closing this now. If you need help or something is not answered, just post.

**Closed by ktsaou** 2017-05-26 23:00 UTC
Labels: question

**Comment by sLuvpreet33** [comment] 2017-06-01 07:57
Hey @ktsaou  a problem has come up. I have not touched the netdata configuration file, but I don't know the reason behind this.

The data in users.cpu is not getting updated. It is stuck at 04:35:00 AM, and its 12 hours since then. The Users and Applications part is not getting updated, rest all are OK. Why so ? look at the current time in the screenshot (1:15 pm), and the netdata time in users data(4:35 am).

![screenshot from 2017-06-01 13-18-48](https://cloud.githubusercontent.com/assets/23127804/26669810/df36c384-46cc-11e7-9dd1-d778a3705502.png)

**Comment by ktsaou** [comment] 2017-06-01 08:42
Hi, is `apps.plugin` running?
Check also the `error.log`.

**Comment by sLuvpreet33** [comment] 2017-06-01 09:12
There is nothing related to this in error logs, just some alerting errors and influxdb backend errors.

apps.plugin should be running, I did not change any config. Where to check for it ?

**Comment by ktsaou** [comment] 2017-06-01 09:14
Well, just run `ps fax` on the data collection node. You will see the process tree of netdata, something like this:

```
20983 ?        Ssl    1:22 /usr/sbin/netdata -D
21018 ?        S      1:37  \_ /usr/libexec/netdata/plugins.d/apps.plugin 1
21034 ?        Sl     1:03  \_ /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
11777 ?        S      0:08  \_ bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
```

Is apps.plugin in your list?

**Comment by ktsaou** [comment] 2017-06-01 09:16
You have to do this on the data collection node. I am confused a bit about your setup, because this thread is about slave-master communication, but the URL on the screenshot you posted is from a standalone netdata.

**Comment by sLuvpreet33** [comment] 2017-06-01 09:26
alphauser@AlphaServer:/var/log/netdata$ ps fax | grep apps.plugin
     8264 pts/2    S+     0:00  |           \_ grep apps.plugin

I am using it on ubuntu 14.04, and also sending data to influxdb via the graphite protocol.

**Comment by ktsaou** [comment] 2017-06-01 09:29
So, it is not running.

Could you please run `grep apps.plugin /var/log/netdata/error.log` and post the output?

**Comment by sLuvpreet33** [comment] 2017-06-01 09:30
There is nothing in the output.

**Comment by ktsaou** [comment] 2017-06-01 09:37
It might be rotated. Could you please check the last rotated log?

**Comment by sLuvpreet33** [comment] 2017-06-01 09:51
alphauser@AlphaServer:/var/log/netdata$ grep apps.plugin /var/log/netdata/error.log.1
     2017-05-31 07:57:39: netdata: ERROR: PLUGINSD: /usr/libexec/netdata/plugins.d/apps.plugin : read failed.
    2017-05-31 07:57:39: netdata: ERROR: PLUGINSD: plugin '/usr/libexec/netdata/plugins.d/apps.plugin' disconnected.
    2017-05-31 07:57:39: netdata: INFO : PLUGINSD: '/usr/libexec/netdata/plugins.d/apps.plugin' on pid 13245 stopped after 748852 successful data collections (ENDs).
    2017-05-31 07:57:40: netdata: INFO : PLUGINSD: '/usr/libexec/netdata/plugins.d/apps.plugin' running on pid 25711
     2017-05-31 07:57:40: apps.plugin: INFO : started on pid 25711
    2017-05-31 08:28:01: apps.plugin: ERROR: Cannot stat file '/proc/27332/stat' (errno 2, No such file or directory)
    2017-05-31 11:57:41: netdata: ERROR: PLUGINSD: /usr/libexec/netdata/plugins.d/apps.plugin : read failed.
    2017-05-31 11:57:41: netdata: ERROR: PLUGINSD: plugin '/usr/libexec/netdata/plugins.d/apps.plugin' disconnected.
    2017-05-31 11:57:41: netdata: INFO : PLUGINSD: '/usr/libexec/netdata/plugins.d/apps.plugin' on pid 25711 stopped after 748852 successful data collections (ENDs).
    2017-05-31 11:57:42: netdata: INFO : PLUGINSD: '/usr/libexec/netdata/plugins.d/apps.plugin' running on pid 38669
    2017-05-31 11:57:42: apps.plugin: INFO : started on pid 38669
    2017-05-31 12:53:01: apps.plugin: ERROR: Cannot stat file '/proc/41840/stat' (errno 2, No such file or directory)
    2017-05-31 13:39:01: apps.plugin: ERROR: Cannot stat file '/proc/44510/stat' (errno 2, No such file or directory)
    2017-05-31 15:57:43: netdata: ERROR: PLUGINSD: /usr/libexec/netdata/plugins.d/apps.plugin : read failed.
    2017-05-31 15:57:43: netdata: ERROR: PLUGINSD: plugin '/usr/libexec/netdata/plugins.d/apps.plugin' disconnected.
    2017-05-31 15:57:43: netdata: INFO : PLUGINSD: '/usr/libexec/netdata/plugins.d/apps.plugin' on pid 38669 stopped after 748852 successful data collections (ENDs).
    2017-05-31 15:57:44: netdata: INFO : PLUGINSD: '/usr/libexec/netdata/plugins.d/apps.plugin' running on pid 52593
    2017-05-31 15:57:44: apps.plugin: INFO : started on pid 52593
    2017-05-31 19:57:45: netdata: ERROR: PLUGINSD: /usr/libexec/netdata/plugins.d/apps.plugin : read failed.
    2017-05-31 19:57:45: netdata: ERROR: PLUGINSD: plugin '/usr/libexec/netdata/plugins.d/apps.plugin' disconnected.
    2017-05-31 19:57:45: netdata: INFO : PLUGINSD: '/usr/libexec/netdata/plugins.d/apps.plugin' on pid 52593 stopped after 748852 successful data collections (ENDs).
    2017-05-31 19:57:46: netdata: INFO : PLUGINSD: '/usr/libexec/netdata/plugins.d/apps.plugin' running on pid 4831
    2017-05-31 19:57:46: apps.plugin: INFO : started on pid 4831
    2017-05-31 23:04:10: apps.plugin: ERROR: Cannot stat file '/proc/16478/stat' (errno 2, No such file or directory)
    2017-05-31 23:57:47: netdata: ERROR: PLUGINSD: /usr/libexec/netdata/plugins.d/apps.plugin : read failed.
    2017-05-31 23:57:47: netdata: ERROR: PLUGINSD: plugin '/usr/libexec/netdata/plugins.d/apps.plugin' disconnected.
    2017-05-31 23:57:47: netdata: INFO : PLUGINSD: '/usr/libexec/netdata/plugins.d/apps.plugin' on pid 4831 stopped after 748852 successful data collections (ENDs).
    2017-05-31 23:57:48: netdata: INFO : PLUGINSD: '/usr/libexec/netdata/plugins.d/apps.plugin' running on pid 19603
    2017-05-31 23:57:48: apps.plugin: INFO : started on pid 19603
    2017-06-01 03:08:01: apps.plugin: ERROR: Cannot process /proc/30479/io (command 'wc') (errno 3, No such process)
    2017-06-01 03:57:49: netdata: ERROR: PLUGINSD: /usr/libexec/netdata/plugins.d/apps.plugin : read failed.
    2017-06-01 03:57:49: netdata: ERROR: PLUGINSD: plugin '/usr/libexec/netdata/plugins.d/apps.plugin' disconnected.
    2017-06-01 03:57:49: netdata: INFO : PLUGINSD: '/usr/libexec/netdata/plugins.d/apps.plugin' on pid 19603 stopped after 748852 successful data collections (ENDs).
    2017-06-01 03:57:50: netdata: INFO : PLUGINSD: '/usr/libexec/netdata/plugins.d/apps.plugin' running on pid 33254
    2017-06-01 03:57:50: apps.plugin: INFO : started on pid 33254
    2017-06-01 04:28:03: apps.plugin: ERROR: heartbeat missed between 3337057020983 usec and 3337057020983 usec (errno 2, No such file or directory)
    2017-06-01 04:31:10: apps.plugin: ERROR: heartbeat missed between 3337244121379 usec and 3337244121379 usec
    2017-06-01 04:31:17: apps.plugin: ERROR: heartbeat missed between 3337251015509 usec and 3337251015509 usec
    2017-06-01 04:32:05: apps.plugin: ERROR: heartbeat missed between 3337299030551 usec and 3337299030551 usec (errno 2, No such file or directory)
    2017-06-01 04:32:13: 2017-06-01 04:32:13: apps.plugin: ERROR: netdata: ERROR: heartbeat missed between 3337307029351 usec and 3337307029351 usec
    2017-06-01 04:32:19: apps.plugin: ERROR: heartbeat missed between 3337313034236 usec and 3337313034236 usec
    2017-06-01 04:32:22: apps.plugin: ERROR: heartbeat missed between 3337316005646 usec and 3337316005646 usec
    2017-06-01 04:32:26: 2017-06-01 04:32:26: apps.plugin: ERROR: netdata: ERROR: heartbeat missed between 3337320016085 usec and 3337320016085 usec
    2017-06-01 04:32:28: apps.plugin: ERROR: heartbeat missed between 3337322044454 usec and 3337322044454 usec
    2017-06-01 04:32:31: apps.plugin: ERROR: heartbeat missed between 3337325118691 usec and 3337325118691 usec
    2017-06-01 04:32:36: apps.plugin: ERROR: heartbeat missed between 3337330004800 usec and 3337330004800 usec
    2017-06-01 04:32:39: apps.plugin: ERROR: heartbeat missed between 3337333085179 usec and 3337333085179 usec
    2017-06-01 04:32:42: apps.plugin: ERROR: heartbeat missed between 3337336222983 usec and 3337336222983 usec
    2017-06-01 04:32:54: apps.plugin: ERROR: heartbeat missed between 3337348090344 usec and 3337348090344 usec (errno 2, No such file or directory)
    2017-06-01 04:32:57: apps.plugin: ERROR: heartbeat missed between 3337351007204 usec and 3337351007204 usec
    2017-06-01 04:33:03: apps.plugin: ERROR: heartbeat missed between 3337357013490 usec and 3337357013490 usec
    2017-06-01 04:33:08: apps.plugin: ERROR: heartbeat missed between 3337362047402 usec and 3337362047402 usec (errno 2, No such file or directory)
    2017-06-01 04:33:14: apps.plugin: ERROR: heartbeat missed between 3337368033224 usec and 3337368033224 usec
    2017-06-01 04:33:21: apps.plugin: ERROR: heartbeat missed between 3337375081706 usec and 3337375081706 usec
    2017-06-01 04:33:24: apps.plugin: ERROR: heartbeat missed between 3337378011483 usec and 3337378011483 usec
    2017-06-01 04:33:30: apps.plugin: ERROR: heartbeat missed between 3337384020929 usec and 3337384020929 usec
    2017-06-01 04:33:48: 2017-06-01 04:33:48: netdata: ERROR: apps.plugin: ERROR: heartbeat missed between 3337402003026 usec and 3337402003026 usec
    2017-06-01 04:33:52: apps.plugin: ERROR: heartbeat missed between 3337406006271 usec and 3337406006271 usec (errno 2, No such file or directory)
    2017-06-01 04:33:54: apps.plugin: ERROR: heartbeat missed between 3337408041796 usec and 3337408041796 usec
     2017-06-01 04:33:57: apps.plugin: ERROR: heartbeat missed between 3337411004214 usec and 3337411004214 usec
     2017-06-01 04:33:59: 2017-06-01 04:33:59: apps.plugin: ERROR: netdata: ERROR: heartbeat missed between 3337413006844 usec and 3337413006844 usecheartbeat missed between 3337413005845 usec and 3337413005845 usec
    2017-06-01 04:34:03: apps.plugin: ERROR: heartbeat missed between 3337417233363 usec and 3337417233363 usec
    2017-06-01 04:34:07: apps.plugin: ERROR: heartbeat missed between 3337421019745 usec and 3337421019745 usec
    2017-06-01 04:34:11: apps.plugin: ERROR: heartbeat missed between 3337425122334 usec and 3337425122334 usec
    2017-06-01 04:34:22: apps.plugin: ERROR: heartbeat missed between 3337436030185 usec and 3337436030185 usec
    2017-06-01 04:35:19: apps.plugin: ERROR: heartbeat missed between 3337493030067 usec and 3337493030067 usec (errno 2, No such file or directory)
    2017-06-01 04:35:22: apps.plugin: ERROR: heartbeat missed between 3337496032280 usec and 3337496032280 usec
    2017-06-01 04:35:27: apps.plugin: ERROR: heartbeat missed between 3337501129384 usec and 3337501129384 usec
    2017-06-01 04:35:32: netdata: ERROR: PLUGINSD: /usr/libexec/netdata/plugins.d/apps.plugin : read failed.
    2017-06-01 04:35:32: netdata: ERROR: PLUGINSD: plugin '/usr/libexec/netdata/plugins.d/apps.plugin' disconnected.
    2017-06-01 04:35:32: netdata: INFO : PLUGINSD: '/usr/libexec/netdata/plugins.d/apps.plugin' on pid 33254 stopped after 113152 successful data collections (ENDs).
    2017-06-01 04:35:32: netdata: ERROR: PLUGINSD: '/usr/libexec/netdata/plugins.d/apps.plugin' exited with error code -1, but has given useful output in the past (73977696 times). Waiting a bit before starting it again.
    2017-06-01 04:35:42: netdata: ERROR: Cannot popen("exec /usr/libexec/netdata/plugins.d/apps.plugin 1 ", "r"). (errno 12, Cannot allocate memory)
    2017-06-01 04:35:43: netdata: INFO : PLUGINSD: '/usr/libexec/netdata/plugins.d/apps.plugin' thread exiting

**Comment by ktsaou** [comment] 2017-06-01 11:18
hm... your server runs out of memory:

```
2017-06-01 04:35:42: netdata: ERROR: Cannot popen("exec /usr/libexec/netdata/plugins.d/apps.plugin 1 ", "r"). (errno 12, Cannot allocate memory)
```

**Comment by ktsaou** [comment] 2017-06-01 11:24
I suggest to add some swap to this system.
I see, I have made apps.plugin to restart every a few hours. I think this is not needed. I'll test it a bit for memory leaks and make it stay open forever.

**Comment by sLuvpreet33** [comment] 2017-06-01 11:36
Okay, yea the server is just for testing, so, it runs out of memory sometimes due to influxdb. 
But it has been going out of memory for like 2 months but netdata never behaved like this. 

How should I add swap memory ?

**Comment by ktsaou** [comment] 2017-06-01 11:38
It seems that apps.plugin decided to restart exactly at the point the system is out of memory.
To add some swap there are many guides on the internet. Pick one that is proper for your distribution. In general you create a file with `dd` and define it as swap at your `/etc/fstab`. But, find a guide for your distro...

**Comment by sLuvpreet33** [comment] 2017-06-01 11:56
I restarted netdata twice and the problem is now gone.

But I will add some swap as a precaution for future.

> Interesting: https://askubuntu.com/questions/916241/understanding-output-of-ss-command/916252

This was my question 😄😄
