### ISSUE TITLE
Correct KSM Metrics

### ISSUE THREAD

**Issue by handle54** [firehol/netdata#3304] opened 2018-01-17 16:11 UTC
Looking through the source code for KSM, it appears that the netdata metrics are a bit inaccurate. It looks like `sharing` and `to_scan` are both being used incorrectly. The documentation states:

```
The KSM daemon is controlled by sysfs files in /sys/kernel/mm/ksm/,
readable by all but writable only by root:

pages_to_scan    - how many present pages to scan before ksmd goes to sleep
                   e.g. "echo 100 > /sys/kernel/mm/ksm/pages_to_scan"
                   Default: 100 (chosen for demonstration purposes)
```
```
The effectiveness of KSM and MADV_MERGEABLE is shown in /sys/kernel/mm/ksm/:

pages_shared     - how many shared pages are being used
pages_sharing    - how many more sites are sharing them i.e. how much saved
pages_unshared   - how many pages unique but repeatedly checked for merging
pages_volatile   - how many pages changing too fast to be placed in a tree
```

Currently, `pages_to_scan` seems to be used as in indicator of how many pages need to be evaluated for de-duplication. However, `page_to_scan` is actually a configurable to control ksmd resource utilization. Though it can change dynamically, for instance by ksmtuned, it does not provide any information about the effectiveness of KSM.

To calculate `savings`, netdata takes `sharing` and subtracts `shared` to come up with a difference, whereas the documentation claims that `sharing` is an indicator of how much is saved. Looking at the source, we can confirm that `sharing` is indeed how much redundant memory is saved and not how much memory would otherwise be consumed by all redundant pages. Therefore, `savings` should be based only on `sharing`.

To be more specific, 
* `pages_shared` is effectively the number of nodes in the stable tree. A page being considered "shared" indicates that it is stable enough to be write locked and has been de-duplicated.
```
/* The number of nodes in the stable tree */
static unsigned long ksm_pages_shared;
```
* `pages_sharing` is the number of second references to a page already in the stable tree. A page being considered "sharing" indicates that it references a page in the stable tree. This value is only incremented when additional references are added to the linked list for a page in the stable tree.
```
/* The number of page slots additionally sharing those nodes */
static unsigned long ksm_pages_sharing;
```
* `pages_unshared` is the number of pages in the unstable tree. A page being considered "unshared" indicates that it is stable enough to be write locked, but KSM has not detected any duplicates.
```
/* The number of nodes in the unstable tree */
static unsigned long ksm_pages_unshared;
```

We should also consider the meaning of `offered`. It appears to indicate that KSM has found duplicates and tried to merge that memory, regardless of its success. Instead, it indicates the total amount of memory that has been marked `MADV_MERGEABLE`. I suggest that `offered` shouldn't include `volatile`, should be renamed, or should be clearly defined.

With all of that said, effects on `ksm_ratios` will need to be considered. It is currently `savings` / `offered`, with `offered` being the total number of pages marked for KSM consideration. Given that `savings` is adjusted, I think that the metric is correct. However, if `offered` is changed, `ksm_ratios` may be impacted.

**Comment by Ferroin** [comment] 2018-01-17 16:55
First off, you get bonus points for thorough research (no, seriously, nobody likes dealing with a bug report that just says 'this is wrong, please fix it' without giving any details on why it's wrong).

Second, based on skimming the documentation myself and taking a closer look at the values on my systems, it appears that you are indeed correct, and our usage actually explains the cases I've seen on my systems where things looked completely wrong (and I unfortunately didn't have time to look into what was going on at the time).

**Comment by ktsaou** [comment] 2018-01-18 23:48
Hi,

thanks for taking the time to report this!

netdata now uses these:

```
    offered = pages_sharing + pages_shared + pages_unshared + pages_volatile;
    saved = pages_sharing - pages_shared;
    savings (ksm_ratios) = saved / offered;
```

Lets consider an example: 3 programs have 1 page each, with the same content, all offered to KSM.

I understand that in this case:

1. `pages_shared = 1` (just one copy of the page is in memory)
2. `pages_sharing = 3` (there are 3 links to the page)
3. `pages_unshared = 0`
4. `pages_volatile = 0`

So, the memory saved is `pages_sharing - pages_shared`. The system did not eliminate all the pages. It eliminated all the duplicate ones, except one.

I think the bug is at the calculation of the `offered`. It should not include `pages_shared`. With that change everything will work as expected.

Am I wrong?

**Comment by Ferroin** [comment] 2018-01-19 13:04
@ktsaou No, what you listed for the current calculation of `offered` is correct.  If a page is marked for KSM with `MADVISE_MERGEABLE`, it gets accounted under exactly one of the four `pages_*` metrics.

The issue is with the calculation of the memory savings, with the key being that `pages_sharing` tracks how many references _beyond the first_ match a page in `pages_shared`, in other words how many pages are duplicates of an existing page in memory.  So, in your example, `pages_shared` should be 1 (there is one page that is in memory), and `pages_sharing` should be 2, not 3, because there are two pages which are duplicates of the original, and your total savings is 2 pages (with a resultant `ksm_ratio` of 2/3).

To give a more concrete and slightly more complex example:

Consider a system with four processes, named A, B, C, and D.  Each of them has marked 8 pages, numbered 0-7, as mergeable.  Pages A0-A7 are identical to B0-B7 (so A and B share the entire range), pages C0-C3 are identical to A0-A3 (and by extension B0-B3), pages D4-D7 are identical to C4-C7, and pages D0-D3 are different from all of them.

So, in ASCII art, with vertical lines between processes indicating identical pages:
```
           +----+----+----+----+----+----+----+----+----+
Process A: | A0 | A1 | A2 | A3 | A3 | A4 | A5 | A6 | A7 |
           +----+----+----+----+----+----+----+----+----+
             ||   ||   ||   ||   ||   ||   ||   ||   ||
           +----+----+----+----+----+----+----+----+----+
Process B: | B0 | B1 | B2 | B3 | B3 | B4 | B5 | B6 | B7 |
           +----+----+----+----+----+----+----+----+----+
             ||   ||   ||   ||
           +----+----+----+----+----+----+----+----+----+
Process C: | C0 | C1 | C2 | C3 | C3 | C4 | C5 | C6 | C7 |
           +----+----+----+----+----+----+----+----+----+
                                 ||   ||   ||   ||   ||
           +----+----+----+----+----+----+----+----+----+
Process D: | D0 | D1 | D2 | D3 | D3 | D4 | D5 | D6 | D7 |
           +----+----+----+----+----+----+----+----+----+
```

In this case, once KSM merges things you should have:
* `pages_shared = 12` You have 4 pages shared by 3 of the processes (pages 0-3 in A, B, and C), and two sets of 4 pages shared by two processes (pages 4-7 in A and B and pages 4-7 in C and D).
* `pages_sharing = 16` There are 2 duplicates of the range A0-A3, and one each for A4-A& and C4-C7.
* `pages_unshared = 4` D0-D3 are not shared with anything, even though they're marked, simply because there are no matches.
* `pages_volatile = 0` Because we're ignoring it.
* `offered = 32` Simply equal to 8 * 4, or a simple sum of the `pages_*` values.
* `savings = 16 pages` You can easily count how many are duplicates above, but `pages_sharing` does that for you.
* `ksm_ratio = 0.5` Because half the pages are deduplicated.

With the logic you're discussing though, savings would be 4, and ratio would be 0.125, both of which are easy to prove wrong here.

**Comment by ktsaou** [comment] 2018-01-20 00:12
ok thanks!
Then the only change is to consider `pages_sharing` as the `savings`.

I am making a PR now.

**Comment by ktsaou** [comment] 2018-01-20 01:16
merged it

**Closed** 2018-01-20 01:16 UTC
Labels: bug, fixed

**Comment by ktsaou** [comment] 2018-01-20 01:27
I have an interesting system though:

```
# find . -type f | while read x; do echo "${x} = $(cat ${x})"; done
./run = 1
./pages_unshared = 471
./pages_sharing = 119422
./full_scans = 27049
./pages_to_scan = 100
./pages_shared = 26
./pages_volatile = 3646
./merge_across_nodes = 1
./sleep_millisecs = 1000
```

This system says that is sharing 119422 pages, but it has only 26 shared pages.
I am not sure how this system managed to save 119422 pages...

kernel is 3.16.0.4 debian.

**Comment by ktsaou** [comment] 2018-01-20 01:35
hm... restarted netdata and got these:

```sh
# find . -type f | while read x; do echo "${x} = $(cat ${x})"; done
./run = 1
./pages_unshared = 102043
./pages_sharing = 170537
./full_scans = 27054
./pages_to_scan = 100
./pages_shared = 14408
./pages_volatile = 3185
./merge_across_nodes = 1
./sleep_millisecs = 1000
```

hm...

**Comment by handle54** [comment] 2018-01-20 04:48
Thank you for resolving the `savings` case.

I also intended to point out that `to_scan` is not a relevant metric and means nothing useful when multiplied by the page size. I don't see harm in collecting the `pages_to_scan` value, but don't think it should be multiplied by the page size or represented as it is in the web interface. In most cases, `pages_to_scan` will be static (defaults to 100 pages) or configured by an administrator. It does not change on it's own and offers no indication of the effectiveness of KSM.

Admittedly, the `to_scan` metric being as it is, is nothing more than a minor annoyance in the interface. I'm only following up on it since the presentation and naming gives the impression that it is a performance indicator.

**Comment by ktsaou** [comment] 2018-01-20 09:22
ok, in PR #3320 
I guess I decided then that this should be added, hopping that there could be a useland program to dynamically adapt `to_scan` to control the speed of KSM under different conditions. But, since there is no such program yet, I have commented it.

**Comment by ktsaou** [comment] 2018-01-20 10:05
merged it.
thank you for reporting this!

**Comment by Ferroin** [comment] 2018-01-22 13:16
@ktsaou  Keep in mind that KSM also merges populated but empty pages, and depending on what all you have running, that could be a very large number of pages (especially if netdata just started up).
