### ISSUE TITLE
during installing   the install processing hang!

### ISSUE THREAD

**Issue by 402309718** [firehol/netdata#196] opened 2016-04-08 09:16 UTC
RHEL6.4

when I install netdata then it appears bleow:
:-----------------------------------------------------------------------------
Running command:

/usr/sbin/netdata 

OK. NetData Started!
Downloading default configuration from netdata...

installation is hangd  and i found this operation
wget -O /etc/netdata/netdata.conf.new http://localhost:19999/netdata.conf
 I think this operation stuck the installation

but I do not know how to finish it

**Comment by ktsaou** [comment] 2016-04-08 13:02
Just stop the installer. It is installed at that point.

Can you execute the same wget command by hand? Does it work?

**Comment by 402309718** [comment] 2016-04-11 01:55
no，it dose not work   ,
 :
[root@MySQL ~]# ps -ef|grep netdata
root      4249  4214  0 09:55 pts/0    00:00:00 grep netdata
netdata  18007     1  0 Apr08 ?        00:00:00 /usr/sbin/netdata
[root@MySQL ~]# lsof -i:19999
COMMAND   PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
netdata 18007 netdata    3u  IPv6  43878      0t0  TCP *:dnp-sec (LISTEN)
[root@MySQL ~]# wget -O /etc/netdata/netdata.conf.new http://localhost:19999/netdata.conf
--2016-04-11 09:55:33--  http://localhost:19999/netdata.conf
Resolving localhost... ::1, 127.0.0.1, 10.45.6.180
Connecting to localhost|::1|:19999... connected.
HTTP request sent, awaiting response... 

always waiting

**Comment by 402309718** [comment] 2016-04-11 03:11
I found  some errors  but ,I can't find which limits    .

[root@MySQL netdata]# tail -f error.log 
16-04-11 10:51:00: ERROR: netdata: failed to create new thread for tc. (errno 11, Resource temporarily unavailable)
16-04-11 10:51:00: INFO: netdata: Starting thread idlejitter.
16-04-11 10:51:00: ERROR: netdata: failed to create new thread for idlejitter. (errno 11, Resource temporarily unavailable)
16-04-11 10:51:00: INFO: netdata: Starting thread proc.
16-04-11 10:51:00: ERROR: netdata: failed to create new thread for proc. (errno 11, Resource temporarily unavailable)
16-04-11 10:51:00: INFO: netdata: Starting thread plugins.d.
16-04-11 10:51:00: ERROR: netdata: failed to create new thread for plugins.d. (errno 11, Resource temporarily unavailable)
16-04-11 10:51:00: INFO: netdata: Not starting thread check.
16-04-11 10:51:00: INFO: netdata: Starting thread web.
16-04-11 10:51:00: ERROR: netdata: failed to create new thread for web. (errno 11, Resource temporarily unavailable)

-----------------
My root  ulimits   root user start ./netdata  app
[root@MySQL sbin]# ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 514829
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 655350
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 100000000000
cpu time               (seconds, -t) unlimited
max user processes              (-u) 514829
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by ktsaou** [comment] 2016-04-11 06:48
I read this must be related to your  `/etc/security/limits.conf`.

Check this: https://groups.google.com/forum/#!msg/mongodb-user/je-GuiBh-60/4w2lTHi4IKwJ
this: http://stackoverflow.com/questions/28477997/mongodb-pthread-create-failed-errno11

Could you please post the output of these:

```
ulimit -Sa
ulimit -Ha
```

**Comment by 402309718** [comment] 2016-04-11 07:09
[root@MySQL ~]# ulimit -Sa
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 514829
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 655350
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 100000000000
cpu time               (seconds, -t) unlimited
max user processes              (-u) 514829
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
[root@MySQL ~]# ulimit -Ha
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 514829
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 655350
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 100000000000
cpu time               (seconds, -t) unlimited
max user processes              (-u) 514829
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by ktsaou** [comment] 2016-04-11 07:34
@alonbl @philwhineray any ideas?

**Comment by alonbl** [comment] 2016-04-11 07:54
This download of default from daemon was always something that is abnormal.

**Comment by ktsaou** [comment] 2016-04-11 08:01
ok, but the issue is that it does not start the threads.

**Comment by 402309718** [comment] 2016-04-11 13:37
any ideas ?

**Comment by ktsaou** [comment] 2016-04-11 15:27
As I said above, the problem seem to be something in your security limits.
If you check the links I posted above, the same issue appears also for the mongodb.

What I can understand is that your system does not allow netdata to spawn its threads. It needs some research to figure out which setting of your system is applying this restriction.

**Comment by 402309718** [comment] 2016-04-11 23:20
NO on the same system I also run the mongodb ,and it dose not appear this problem ,and I just want to use netdata to monitor  performance of mongodb host

**Comment by ktsaou** [comment] 2016-04-12 08:02
> NO on the same system I also run the mongodb ,and it dose not appear this problem ,and I just want to use netdata to monitor performance of mongodb host

I guess there must be something for mongodb in your `/etc/security` settings. Isn't it?

**Comment by paulfantom** [comment] 2016-07-31 06:57
@402309718 did you solve this?

**Comment by ktsaou** [comment] 2016-07-31 08:37
I think this is related to system policy. Cannot be solved by netdata. I am closing it. @402309718 if you need help, just post.

**Closed by ktsaou** 2016-07-31 08:37 UTC
Labels: installation help
