### ISSUE TITLE
Build packages for various distributions

### ISSUE THREAD

**Issue by hauleth** [firehol/netdata#94] opened 2016-03-31 09:16 UTC
It should not be hard using [fpm](https://github.com/jordansissel/fpm).

**Comment by fabfurnari** [comment] 2016-03-31 10:53
If needed I can help with debian packaging (source/binary package)

**Comment by daveloyall** [comment] 2016-03-31 15:43
@fabfurnari see #42

**Comment by ktsaou** [comment] 2016-03-31 19:43
> If needed I can help with debian packaging (source/binary package)

I need help! So, please do!

**Comment by tsumaru720** [comment] 2016-04-01 10:29
producing packages would be nice, this would make for easier deployment using orchestration (puppet, for example!)

**Comment by hauleth** [comment] 2016-04-01 10:45
There is also hosted solution which has special offer for [FLOSS](https://packagecloud.io/pricing).

**Comment by mcnewton** [comment] 2016-04-01 23:41
For Debian see #132 as a start.

**Comment by philwhineray** [comment] 2016-04-02 12:56
I am going to close this as a duplicate of #87 please continue discussion there,

**Comment by ktsaou** [comment] 2016-07-31 08:56
Closing it as @philwhineray suggested.

**Closed by ktsaou** 2016-07-31 08:56 UTC
Labels: duplicate, packaging
