### ISSUE TITLE
Should netdata identify the js binary as NodeJS by default?

### ISSUE THREAD

**Issue by orditeck** [firehol/netdata#4217] opened 2018-09-17 11:39 UTC
`/usr/libexec/netdata/plugins.d/node.d.plugin` uses 100% CPU a few times a day. I installed it three days ago and didn't change any default configuration. 

Version: `1.10.0-663-g57d0392f_rolling`

I searched in this repo's issues and on Google. Server is a Xeon D-1540 w/ 32GB. Any help regarding this would be appreciated. Sorry for the lack of information, I'm pretty sure I could give much more useful information but I'm new to this software so feel free to ask me any details you need. 

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
 netdata   7714  0.2  0.1 223244 45288 ?        Ssl  03:06   0:56 /usr/sbin/netdata -P /var/run/netdata/netdata.pid -D -W set global process scheduling policy keep -W set global OOM score keep
 netdata   7741 99.8  0.0  47232  2136 ?        Rl   03:06 346:10  \_ /usr/bin/js /usr/libexec/netdata/plugins.d/node.d.plugin 1
 netdata   7747  0.2  0.0 177720 23780 ?        Sl   03:06   0:54  \_ /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
 root      9760  0.0  0.0  10880  1480 ?        S    07:06   0:04  \_ /usr/libexec/netdata/plugins.d/apps.plugin 1
 netdata  28492  0.1  0.0   9812  1708 ?        S    08:06   0:02  \_ bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
```

**Comment by ktsaou** [comment] 2018-09-17 11:42
With default configuration `node.d` should be monitoring `named`.
I just pushed a few fixes for `named`. There were 2 wrong conditions in it, though,I don't know if these could lead to increased loops in it.

So, could you please update your netdata and check if it happens again?

**Comment by orditeck** [comment] 2018-09-17 11:58
I just updated netdata (now using `netdata 1.10.0-667-g49dea6ba_rolling`). I'll let you know if it happens again!

**Comment by alivxlive** [comment] 2018-09-17 13:17
Is there any update on this case.

**Comment by ktsaou** [comment] 2018-09-17 13:29
@orditeck is testing the latest netdata.

Do you have the same issue? Could you please update your netdata and check if it happens again?

**Comment by orditeck** [comment] 2018-09-17 13:36
So far so good, but it wasn't like it was once per hour or something like that. Somewhat random, look at the dates & times.

![](https://i.imgur.com/dXl7dDG.png)

**Comment by ktsaou** [comment] 2018-09-18 12:49
hm... your server had other issues too.
How did you conclude this was triggered by netdata? I mean, are you sure netdata is not right that your system has some other issue?

**Comment by ktsaou** [comment] 2018-09-18 12:51
I suggest to disable `node.d.plugin` and see how it goes.
To disable it, edit `netdata.conf` and set:

```
[plugins]
	node.d = no
```

Make sure you uncomment the line too.

**Comment by orditeck** [comment] 2018-09-18 20:27
ugh, I think that the datas are no longer there and I'm not sure I had the time to include them. I opened the page ~55min after it happened, I went back 55min before and was able to see the CPU at 100% in the graph. Then I exported. But when I tried to scroll down, every graphs were showing "! empty", probably because the history got deleted. Is there any way to keep the history longer than 1 hour? Would that use too much disk/resource? I'd like to keep a few days at least of history

And yes, I edited the original to remove my server URL and hostname. I'll send you the original one by email in a few seconds.

**Comment by ktsaou** [comment] 2018-09-18 20:30
You can edit `/etc/netdata.conf` and set `history = 7200` for 2 hours of data.
Generally, netdata needs about 25MB ram per hour, depending on the number of metrics collected.
You can get 50% reduction by activating KSM. The installer says what you need to run to activate it.

**Comment by orditeck** [comment] 2018-09-18 20:31
Just to make sure, you meant `/etc/netdata/netdata.conf` right?

**Comment by ktsaou** [comment] 2018-09-18 20:32
KSM = Kernel Same Page, a memory deduplication feature inside the kernel. It uses some CPU resources when active, but the settings suggested by the netdata installer are very for extremely light use (but sufficient for netdata to consume 50% less memory).

**Comment by ktsaou** [comment] 2018-09-18 20:34
> Just to make sure, you meant `/etc/netdata/netdata.conf` right?

yes, of course. Sorry.

**Comment by orditeck** [comment] 2018-09-18 20:43
@ktsaou I actually just noticed that `node.d.plugin` is always using 100% of one CPU. I'm sending you another snapshot by email right now.

**Comment by ktsaou** [comment] 2018-09-18 20:46
Wow! You are right!

**Comment by ktsaou** [comment] 2018-09-18 20:47
First, please edit netdata.conf and set `node.d = no` to stop it on your system.
Let me write a few instructions to debug this.

**Comment by ktsaou** [comment] 2018-09-18 20:55
Then please run this:

```sh
# become user netdata
sudo su -s /bin/sh netdata

# run the node plugin in debug mode
/usr/libexec/netdata/plugins.d/node.d.plugin debug 1
```

The plugin will run forever, so you will need to stop it with Control-C. Let it run for 10 seconds, and please post here the output.

On github you can add logs in sections like these:

<details>
<summary>click here for the log</summary>

```
THE LOG HERE
```
</details>

---

Using this block in edit mode:

```

<details>
<summary>click here for the log</summary>

` ` `     <<< these are 3x apostrophes without spaces between them
THE LOG HERE
` ` `     <<< these are 3x apostrophes without spaces between them
</details>

```

**Comment by ktsaou** [comment] 2018-09-18 20:58
btw, which distro and version is this? I may be able to reproduce this myself if it happens on a standard distro.

**Comment by orditeck** [comment] 2018-09-18 21:08
I've replaced `# node.d = yes` to `node.d = no` in `/etc/netdata/netdata.conf`.

Then:

```
[root@s01 netdata.git]# service netdata restart
Redirecting to /bin/systemctl restart netdata.service
[root@s01 netdata.git]# sudo su -s /bin/sh netdata
sh-4.2$ /usr/libexec/netdata/plugins.d/node.d.plugin debug 1
^C
sh-4.2$ 
```

I waited 30 seconds before doing `CTRL+C`. So, no output from `node.d.plugin`.

I'm using CENTOS 7.5 standard with cPanel/WHM v74.0.8

```
[root@s01 netdata.git]# uname -a
Linux s01.removed.com 3.14.32-xxxx-grs-ipv6-64 #9 SMP Thu Oct 20 14:53:52 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by alivxlive** [comment] 2018-09-19 11:51
> I suggest to disable `node.d.plugin` and see how it goes.
> To disable it, edit `netdata.conf` and set:
> 
> ```
> [plugins]
> 	node.d = no
> ```
> Make sure you uncomment the line too.

Question:
What I will lose if I diable "node.d.plugin"

**Comment by Ferroin** [comment] 2018-09-19 12:49
SNMP, Fronius, Steibeltron, named, and sma_webbox modules won't run.  If you don't have any of those enabled, you'll lose nothing.

**Comment by ktsaou** [comment] 2018-09-19 12:58
> hen:
> 
> ```
> [root@s01 netdata.git]# service netdata restart
> Redirecting to /bin/systemctl restart netdata.service
> [root@s01 netdata.git]# sudo su -s /bin/sh netdata
> sh-4.2$ /usr/libexec/netdata/plugins.d/node.d.plugin debug 1
> ^C
> sh-4.2$ 
> ```
> 
> I waited 30 seconds before doing `CTRL+C`. So, no output from `node.d.plugin`.

So I understand it does not even start. Like a broken `node.js`...

Can you help me install your distro? How did you install `cPanel/WHM v74.0.8` on centos 7.5 ?

**Comment by orditeck** [comment] 2018-09-19 13:09
```
cd /home && curl -o latest -L https://securedownloads.cpanel.net/latest && sh latest
```
(from the [installation guide](https://documentation.cpanel.net/display/74Docs/Installation+Guide))

**Comment by ktsaou** [comment] 2018-09-19 17:10
Installing cpanel now...
This thing installs way too many packages...

**Comment by ktsaou** [comment] 2018-09-19 20:40
Well, the installation of cpanel did not install `node`. Do you remember how you installed node.js on your system?

**Comment by ktsaou** [comment] 2018-09-19 20:59
I also installed node.js 8.12 following the instructions from here: https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora

netdata works as expected.

Could you please post the output of this:

```sh
# node --version
v8.12.0
```

**Comment by orditeck** [comment] 2018-09-19 21:00
```
[staging@s01 logs]$ node --version
-bash: node: command not found
```

**Comment by ktsaou** [comment] 2018-09-19 21:05
interesting. This one:

```sh
# nodejs --version
```

**Comment by ktsaou** [comment] 2018-09-19 21:07
or even this one:

```sh
# js --version
```

netdata searches for `node`, `nodejs` and `js` in this order.

**Comment by orditeck** [comment] 2018-09-19 21:09
```
[staging@s01 logs]$ nodejs --version
-bash: nodejs: command not found
[staging@s01 logs]$ js --version
^C
[staging@s01 logs]$
```

`js --version` seems to hang forever. Could be the issue!

**Comment by ktsaou** [comment] 2018-09-19 21:11
hm... So the `js` command on your system is problematic.

**Comment by ktsaou** [comment] 2018-09-19 21:13
What I could do is to remove `js` from the list. But I am not sure if this is the right thing to do for most of the people.

If would help if you could identify what is the `js` command you have installed. If it is a generic tool, not related with `node.js` we should remove it.

If you renamed something to `js` by accident, we should keep netdata as it is.

**Comment by orditeck** [comment] 2018-09-19 21:16
I don't know what `js` is on my system. I can't get it to show something. While searching, I found that `/usr/bin/js` may refer to Mozilla's Rhino on some systems. But I don't know how common that is. I'll keep trying to find what `js` is on my system and will get back to you when I find out!

**Comment by ktsaou** [comment] 2018-09-19 21:18
ok.

It is important to know, since based on this we will decide if we will keep searching for `js` to run node.js plugins.

Thank you!

**Comment by orditeck** [comment] 2018-09-20 11:28
Found out that `js` is `JavaScript-C 1.8.5 2011-03-31` [from Mozilla](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Introduction_to_the_JavaScript_shell) using cmd `strings /usr/bin/js`.

So no, netdata shouldn't search for `js`.

**Comment by Ferroin** [comment] 2018-09-20 11:29
Alternatively, it should check if the program outputs a version string that looks like Node.js and bail if it takes too long to do so.

**Comment by orditeck** [comment] 2018-09-20 11:31
> Alternatively, it should check if the program outputs a version string that looks like Node.js and bail if it takes too long to do so.

If it then remember it and doesn't try again that seems like a great solution. 

Or add a config setting. IDK what's best.

**Comment by Ferroin** [comment] 2018-09-20 11:41
> If it then remember it and doesn't try again that seems like a great solution.

Unless I'm mistaken, it should only be checking for node.js during startup.

> Or add a config setting

Technically already exists, disabling the node.js plugin should disable checking for this.  If it doesn't disable the check, then that's a bug that needs to be fixed.

**Comment by orditeck** [comment] 2018-09-20 11:44
> > If it then remember it and doesn't try again that seems like a great solution.
> 
> Unless I'm mistaken, it should only be checking for node.js during startup.

In that case it'd be a great solution.

> > Or add a config setting
> 
> Technically already exists, disabling the node.js plugin should disable checking for this. If it doesn't disable the check, then that's a bug that needs to be fixed.

I meant a setting to tell netdata where to search for nodejs. That way I could remove `js` from the list of binary it searches for.

**Comment by Ferroin** [comment] 2018-09-20 11:54
> In that case it'd be a great solution.

So, I had forgotten, the search is done by a shell-script one-liner at the top of `plugins.d/node.d.plugin`.  That's not exactly going to be easy to configure...

> I meant a setting to tell netdata where to search for nodejs. That way I could remove js from the list of binary it searches for.

Ah, OK, sorry I misunderstood.

**Comment by ktsaou** [comment] 2018-09-20 15:50
I think the best solution is to remove `js` from the list of commands to be searched.
However, keep in mind your `js` is not good. It should not run with 100% cpu for no reason.
Making a PR to remove it now...

**Comment by ktsaou** [comment] 2018-09-20 15:53
ok, in PR #4239

**Comment by ktsaou** [comment] 2018-09-20 16:21
merged it.

**Closed** 2018-09-20 16:21 UTC
Labels: bug, fixed
