### ISSUE TITLE
Graphite backend fails with errno 115, Operation in progress)

### ISSUE THREAD

**Issue by henry-spanka** [firehol/netdata#3168] opened 2017-12-22 15:40 UTC
Hello,
it seems that there is an issue with the netdata graphite backend implementation.
The socket to the backend is opened non-blocking but there is no check if the socket is ready yet, which leads to the following error in the error.log and data is not sent.

netdata ERROR: Failed to connect to '10.1.1.2', port '2003' (errno 115, Operation in progress)

**Comment by ktsaou** [comment] 2018-01-03 13:18
Hi,

well, the backends do not use non-blocking I/O.
Also, this error message appears before setting any such options on the socket.

Check it here https://github.com/ktsaou/netdata/blob/42a58e4c9d0f29fec025db69cc1c14fbe660f031/src/socket.c#L611-L626

Anyway, I added code to handle this case too.

**Comment by ktsaou** [comment] 2018-01-03 13:34
merged it.
I can't reproduce this, so could you please try it?

**Closed** 2018-01-03 13:34 UTC
Labels: bug, fixed

**Comment by henry-spanka** [comment] 2018-01-03 15:30
Hello,
I just built a new package as described here: https://github.com/firehol/netdata/blob/master/makeself/README.md

However netdata still shows this: 
![screenshot at jan 03 16-28-38](https://user-images.githubusercontent.com/10375269/34526596-3499b87e-f0a3-11e7-9e1d-9ca2731aa57f.png)

The binary that was built has the name: netdata-v1.9.0-96-g547d4e9c-x86_64-20180103-144321.gz.run

Why does the commit differ? I built it from the master branch that includes the latest async commit.

**Comment by ktsaou** [comment] 2018-01-03 16:10
I just tried that.

the file `netdata-v1.9.0-101-gc6caec3e-x86_64-20180103-160706-ktsaou.gz.run` was generated.
I installed it and got:

![screenshot from 2018-01-03 18-09-35](https://user-images.githubusercontent.com/2662304/34528328-4689c138-f0b1-11e7-864e-e7adcbfc9c74.png)

I think the installer installed the newer netdata but you are still running the older netdata. Could you please restart it? Which distro is this?

**Comment by henry-spanka** [comment] 2018-01-03 17:31
Hello,
well actually it was a bug in my Puppet manifest which returned success but did not correctly install the update. It's working now and I receive metrics from netdata.

Thank you very much for your help!

**Comment by ktsaou** [comment] 2018-01-03 17:37
I the original issue fixed? I can't test it so I rely on you to confirm it.

**Comment by henry-spanka** [comment] 2018-01-03 18:07
Yes it is. The connection to graphite is now established successfully.

**Comment by ktsaou** [comment] 2018-01-03 18:25
thanks!
