### ISSUE TITLE
netdata export chart to image 

### ISSUE THREAD

**Issue by phaothu** [firehol/netdata#2032] opened 2017-03-29 06:54 UTC
Does netdata have any API to export a chart to image .jpeg or .png ?

Example: when the CPU chart issue a warning , I want to send an email with the screen shot of CPU chart at that moment.

**Comment by l2isbad** [comment] 2017-03-29 09:55
https://github.com/firehol/netdata/issues/1921

**Comment by ktsaou** [comment] 2017-03-29 20:03
Well, as @l2isbad pointed, not yet. I would love to have this though. So #1921 is an enhancement.
I am closing this as duplicate of #1921.

**Closed by ktsaou** 2017-03-29 20:03 UTC
Labels: duplicate
