### ISSUE TITLE
Negative values for disk operations

### ISSUE THREAD

**Issue by GeorgeTG** [firehol/netdata#583] opened 2016-06-20 01:14 UTC
I am getting negatives values for several disk stats:

`
	"api": 1,
	"id": "disk_avgsz.mmcblk0",
	"name": "disk_avgsz.mmcblk0",
	"view_update_every": 1,
	"update_every": 1,
	"first_entry": 1466380663,
	"last_entry": 1466384263,
	"before": 1466384263,
	"after": 1466383784,
	"dimension_names": ["writes"],
	"dimension_ids": ["writes"],
	"latest_values": [0],
	"view_latest_values": [0],
	"dimensions": 1,
	"points": 480,
	"format": "json",
	"result": {
	"labels": ["time", "writes"],
	"data":
	[
        ....
		[ 1466383795000, -4],`

`	"api": 1,
	"id": "disk.mmcblk0",
	"name": "disk.mmcblk0",
	"view_update_every": 1,
	"update_every": 1,
	"first_entry": 1466381495,
	"last_entry": 1466385095,
	"before": 1466385095,
	"after": 1466384616,
	"dimension_names": ["writes"],
	"dimension_ids": ["writes"],
	"latest_values": [-11.54899],
	"view_latest_values": [-11.54899],
	"dimensions": 1,
	"points": 480,
	"format": "json",
	"result": {
	"labels": ["time", "writes"],
	"data":
	[ ....`

`"api": 1,
	"id": "disk_mops.mmcblk0",
	"name": "disk_mops.mmcblk0",
	"view_update_every": 1,
	"update_every": 1,
	"first_entry": 1466381542,
	"last_entry": 1466385142,
	"before": 1466385142,
	"after": 1466384663,
	"dimension_names": ["writes"],
	"dimension_ids": ["writes"],
	"latest_values": [-0.17687],
	"view_latest_values": [-0.17687],
	"dimensions": 1,
	"points": 480,
	"format": "json",
	"result": {
	"labels": ["time", "writes"],
	"data":
	[`

Is this normal?
Also netdata is running on a RaspberryPI, ArchLinux Armv7l, on a MicroSD card (mmcblk0).

**Comment by ktsaou** [comment] 2016-06-20 05:49
This is by design: inbound traffic is positive, outbound traffic is negative. It helps having the nice charts you see on the dashboard. To get positive values just pass `&options=absolute` to the URL.

**Comment by GeorgeTG** [comment] 2016-06-20 10:30
Hmm that makes sense.
I was confused since there were only writes shown on my dashboard.
![writes_only](https://cloud.githubusercontent.com/assets/6360940/16190934/637fefa6-36ea-11e6-9c66-1c888dd10375.png)

Turns out read stats where all zero the whole time and were omitted, hence my confusion.

**Comment by ktsaou** [comment] 2016-06-20 11:12
ok. I am closing this.

**Closed by ktsaou** 2016-06-20 11:12 UTC
Labels: question
