### ISSUE TITLE
Ignore health monitoring specific disks?

### ISSUE THREAD

**Issue by antons-** [firehol/netdata#1231] opened 2016-11-09 00:55 UTC
I've recently installed the Ubuntu Livepatch Service https://www.ubuntu.com/server/livepatch on my server.

The service creates 3 disks:

```
Filesystem      Size  Used Avail Use% Mounted on
/dev/loop0      4.4M  4.4M     0 100% /snap/canonical-livepatch/15
/dev/loop1       75M   75M     0 100% /snap/ubuntu-core/423
/dev/loop2      4.4M  4.4M     0 100% /snap/canonical-livepatch/17
```

These disks are 100% full and have no inodes left, so Netdata generates alarms for them. 

These alarms seem to be false positives to me as this is normal. Is there a way to specify disks to ignore for the health alarms?

**Comment by ktsaou** [comment] 2016-11-09 15:00
3 options:

1. disable the charts. This is the best. Edit `/etc/netdata/netdata.conf` (download a fresh from the server), find the mount points and disable them. This will also disable the alarms (and save some memory).

2. override the default alarms. Copy the templates and turn then to alarms for the specific mount points

3. comment out the disk alarm templates shipped by netdata and add alarm only for the disks you need alarms.

**Comment by robbat2** [comment] 2016-12-14 18:03
I have a dataset that is mostly read-only, and runs at ~98% full. I do care about IO performance on it (be able to see that the code running on it is utilizing the SSD fully), and want charts & other alerts on it, but I don't need the health checks for how full on JUST that volume. (I do care greatly about other volumes).

```
[plugin:proc:/proc/diskstats:/mnt/dataset]
   health template exclude = disk_space_usage disk_inode_usage
```

**Comment by ktsaou** [comment] 2016-12-14 19:45
override the alarm for the specific disk. Check this to find out how: https://github.com/firehol/netdata/issues/904#issuecomment-248288046

**Comment by robbat2** [comment] 2016-12-14 20:41
Thanks, I updated #904 with an example for overriding the alarm for other people to find. I do have a followup problem now that device-mapper numbers are not consistent between boots, so they aren't good for using in the `on` line.
I left more details on https://github.com/firehol/netdata/issues/435#issuecomment-267149995

**Comment by ktsaou** [comment] 2016-12-14 20:57
hm... you can place this alarm on its own file and have a boot script generate the file and send a SIGUSR2 to netdata (to reload the health configuration).
Will this do?

**Comment by robbat2** [comment] 2016-12-14 21:21
That works for this specific case, could even chain it to cron/incron for populating it as some devices are hot-plugged, but having a way to specify it by some attribute (mountpoint, fstype, matching sysfs attributes) would be better, which is why I put in the comments into #435.

**Comment by ktsaou** [comment] 2016-12-14 21:37
You are right.

However, the way netdata is now, this is not that easy to support it.

The problem is that alarms templates are linked to charts. Charts are agnostic, they are just a collection of metrics/dimensions. They don't know they are disk charts, or ethernet charts. There is no mount point or fstype at that level.

So, to support this feature:

1. charts should support custom per-case attributes/tags
2. alarm templates should support considering these chart attributes/tags

It can be done (and should be done, as I see it), but it is not a quick fix I can implement in an hour...

I added this feature to https://github.com/firehol/netdata/issues/809, where I collect all the health monitoring improvements required.

**Comment by ktsaou** [comment] 2016-12-21 20:52
Cleaning up. I am closing this. The task that remains is already added in #809. If I missed something, please post here and I'll re-open it.

**Closed by ktsaou** 2016-12-21 20:52 UTC
Labels: question
