### ISSUE TITLE
netdata fails to start via systemd

### ISSUE THREAD

**Issue by Trikolon** [firehol/netdata#769] opened 2016-08-10 13:14 UTC
I installed netdata-dependencies via the installation script (all features).
Custom installation directory /opt/netdata
Ubuntu Server 16.04

When I run netdata manually it seems to work, but starting it with systemd throws this error message:
https://gist.github.com/Trikolon/07bf3a6e074dc41deec33e366a5e95d5

**Comment by ktsaou** [comment] 2016-08-10 14:51
@candrews please check this. It seems the change we merged yesterday does not work in this case.

cc: @paulfantom

**Comment by paulfantom** [comment] 2016-08-10 18:50
When I tried to reproduce it on Ubuntu desktop 16.04 I found a different issue. Netdata couldn't create PID file and systemd was timeouting and killing service. After creating directory `/opt/netdata/var/run/netdata` with `rwx` permission for user `netdata` everything works.

I am currently installing stock version of Ubuntu Server 16.04 to try to reproduce this.

**Comment by paulfantom** [comment] 2016-08-10 19:37
Installed and upgraded ubuntu 16.04. Apart from issue with `netdata` PID file I couldn't reproduce this.

@Trikolon does commenting out lines:
```
AmbientCapabilities=CAP_DAC_READ_SEARCH CAP_SYS_PTRACE
CapabilityBoundingSet=CAP_DAC_READ_SEARCH CAP_SYS_PTRACE
```
in `/etc/systemd/system/netdata.service` and reloading systemd (`systemctl daemon-reload`) allows to start netdata with systemd?

**Comment by Trikolon** [comment] 2016-08-10 19:50
Commenting those two lines out fixed it for me. Also I had to create the directory (to fix the PID issue) as you mentioned previously.

**Comment by ktsaou** [comment] 2016-08-10 22:38
@paulfantom @candrews why don't we start netdata with `-D` and get rid of the pid file?

**Comment by ktsaou** [comment] 2016-08-20 21:53
merged the fix

**Closed** 2016-08-26 10:22 UTC
Labels: bug, fixed
