### ISSUE TITLE
web_log reports unmatched lines

### ISSUE THREAD

**Issue by ale-rinaldi** [firehol/netdata#2201] opened 2017-05-18 10:58 UTC
web_log plugin reports unmatched lines.

This is my log:

```txt

37.159.226.69 - - [18/May/2017:12:52:15 +0200] "-" 408 0 "-" "-"

```

**Comment by ktsaou** [comment] 2017-05-18 21:25
hm... this is line is missing information...
Could you please post another line that is matched?

**Comment by ktsaou** [comment] 2017-09-16 17:01
This is duplicate of #2675 (or the other way around).
Anyway, there is PR #2693 that attempts to fix this. So, if you can test it, please do so and comment on #2693

**Closed by ktsaou** 2017-09-16 17:01 UTC
Labels: bug, fixed
