### ISSUE TITLE
User agent problem - css

### ISSUE THREAD

**Issue by LITHERO** [firehol/netdata#1484] opened 2016-12-31 15:59 UTC
If I use firefox with the default user agent, the styles are not loaded. (First screenshot)
![n1](https://cloud.githubusercontent.com/assets/16992481/21578235/bdbd789a-cf91-11e6-9b7d-34c63a11ab01.PNG)
If I use the panel on android smartphone then everything is OK.
With custom user-agent from the android in firefox everything is loaded.
A config nginx I have attached below.
```
upstream netdata {
    server 10.0.3.1:19999;
    keepalive 64;
}

server {
    listen      10.0.3.60:80;
    server_name domain.com ;

    location / {
        proxy_pass      http://10.0.3.60:8080;
        location ~* ^.+\.(jpg|jpeg|gif|png|ico|svg|css|zip|tgz|gz|rar|bz2|doc|xls|exe|pdf|ppt|txt|odt|ods|odp|odf|tar|wav|bmp|rtf|js|mp3|avi|mpeg|flv|html|$
            root           /home/admin/web/domain.com/public_html;
            access_log     /var/log/apache2/domains/domain.com.log combined;
            access_log     /var/log/apache2/domains/domain.com.bytes bytes;
            expires        max;
            try_files      $uri @fallback;
        }
    }

   location /netdata {
        return 301 /netdata/;
   }

   location ~ /netdata/(?<ndpath>.*) {
        proxy_redirect off;
        proxy_set_header Host $host;

        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
        proxy_pass http://netdata/$ndpath$is_args$args;

        gzip on;
        gzip_proxied any;
        gzip_types *;
    }

```
Peculiarities of my server that netdata running on the host system, and nginx server running inside LXC container, which is open for only one TCP port of the host system. (19999)
What is the problem?

**Comment by LiveChief** [comment] 2017-01-15 11:43
hey bro, i had the same issue earlier this week i can conform this is caused by catch, for some reason older browser use some crappy catch system,

Secondary Fix (Recommended)
1. Use Something Like Google Chrome and you should not run into this problem.
Fix:
2. Go to :19999 instead of /netdata so that way its forced to update
or
try /netdata/??? i havent tried this tho

**Comment by ktsaou** [comment] 2017-02-04 21:14
@LITHERO did you solve it?

I am closing this now, but if you need help, just post.

**Closed by ktsaou** 2017-02-04 21:14 UTC
Labels: question
