### ISSUE TITLE
/api/v1/data?chart returns an Object instead of JSON

### ISSUE THREAD

**Issue by hiendv** [firehol/netdata#158] opened 2016-04-03 10:37 UTC
URI: `/api/v1/data?chart=system.cpu&format=json&points=68&group=average`
Response:
```js
{
	"labels": ["time", "guest_nice", "guest", "steal", "softirq", "irq", "user", "system", "nice", "iowait"],
	"data":
	[
		[ new Date(2016,3,3,10,30,24), 0, 0, 0, 0.02604, 0, 0.01573, 0.89138, 0.35095, 0.01573],
		[ new Date(2016,3,3,10,29,36), 0, 0, 0, 0.01573, 0, 0.01031, 0.85379, 0.31992, 0.00527],
		[ new Date(2016,3,3,10,28,48), 0, 0, 0, 0.02142, 0, 0.01564, 0.94042, 0.42052, 0.01575],
		[ new Date(2016,3,3,10,28,0), 0, 0, 0, 0.01056, 0, 0.01047, 0.76023, 0.37728, 0.02096],
		[ new Date(2016,3,3,10,27,12), 0, 0, 0, 0.0157, 0, 0.00523, 0.74063, 0.36764, 0.0157],
		[ new Date(2016,3,3,10,26,24), 0, 0, 0, 0.01576, 0, 0.00522, 0.6773, 0.41984, 0.01572],
		[ new Date(2016,3,3,10,25,36), 0, 0, 0, 0.00529, 0, 0.01052, 0.76668, 0.37827, 0.01572],
		//...
	]
}
```
The API is not really well-documented :(

**Comment by ktsaou** [comment] 2016-04-03 10:52
duplicate of #83 
Please let's discuss this there.

**Closed by ktsaou** 2016-04-03 10:52 UTC
Labels: duplicate
