### ISSUE TITLE
Totally wrong cgroups per lxd container memory info

### ISSUE THREAD

**Issue by cryptofuture** [firehol/netdata#1019] opened 2016-09-24 19:36 UTC
I have like this values, or even lower with some containers for `cgroup_lxc_containername.mem`. All values for processes in containers or for containers are totally wrong!
```
MB
cache 0.023
rss 0.203
mapped_file 0.023
```

But in real this container use 19-32MB of memory.
Most fun part per process mem values could be bigger then value for full container, for example
`cgroup_lxc_containername_system.slice_nginx.service.mem` values:
```
MB
cache 0.086
rss 0.848
mapped_file 0.082
```
When in real nginx use 1.6 MB of memory total.

**Comment by ktsaou** [comment] 2016-09-24 21:42
Netdata uses the `memory.stat` files found under `/sys/fs/cgroup/memory`: https://github.com/firehol/netdata/blob/fba8d0f91d0f2559c5c252e400c262217d68a9b8/src/sys_fs_cgroup.c#L987

It just reads the values of interest: https://github.com/firehol/netdata/blob/fba8d0f91d0f2559c5c252e400c262217d68a9b8/src/sys_fs_cgroup.c#L355-L560

And when it creates charts, it just divides them by 1 MB (i.e. 1024 * 1024): https://github.com/firehol/netdata/blob/fba8d0f91d0f2559c5c252e400c262217d68a9b8/src/sys_fs_cgroup.c#L1121-L1129

Could you please check the contents of the `memory.stat` files of your containers to verify netdata presents the right values?

**Comment by cryptofuture** [comment] 2016-09-24 23:12
In netdata:
```
Memory Usage for cgroup containername (cgroup_lxc_containername.mem)
MB
cache 0.668
rss 0.223
mapped_file 0.527
```
And `cat /sys/fs/cgroup/memory/memory.stat`output for container:
```
cache 876544
rss 323584
mapped_file 790528
```

**Comment by ktsaou** [comment] 2016-09-24 23:26
Not that file. We need the `memory.stat` file of the specific container.

It will be something line `/sys/fs/cgroup/memory/lxc/CONTAINERNAME/memory.stat`.

**Comment by ktsaou** [comment] 2016-09-24 23:28
You can to find the file of the same container with the chart. Try not to mix them, because we are not going to understand what is happening.

**Comment by cryptofuture** [comment] 2016-09-25 06:33
Looks like right values as for `/sys/fs/cgroup/memory/lxc/containername/memory.stat`output:
```
cache 4096
rss 0
rss_huge 0
mapped_file 4096
```
netdata:

```
Memory Usage for cgroup lxc_containername (cgroup_lxc_containername.mem)
MB
cache 0.004
mapped_file 0.004
```

In same time (that looks like real now):
```
 Memory Usage for cgroup lxc_containername_system.slice_nginx.service (cgroup_lxc_containername_system.slice_nginx.service.mem)
MB
cache 0.664
rss 0.734
mapped_file 0.66
```

**Comment by ktsaou** [comment] 2016-09-25 08:30
So, you say that the child of the container uses more memory than the parent?

**Comment by cryptofuture** [comment] 2016-09-25 10:03
It seems `/sys/fs/cgroup/memory/lxc/containername/memory.stat`gives wrong values for containers, but per process values are right. My system highly swapped sometimes, but I don't think this is the issue, since per container values are unrealistic low.
btw, what `cgroup lxc_containername_init.scope`used for?

**Comment by ktsaou** [comment] 2016-09-25 10:08
> btw, what cgroup lxc_containername_init.scopeused for?

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Resource_Management_Guide/sec-Default_Cgroup_Hierarchies.html

Can you post your cgroup hierarchy by runnig `systemd-cgls` and also pin-point the the ones with the memory discrepancy? It might be that netdata reads the wrong file...

**Comment by cryptofuture** [comment] 2016-09-25 12:11
```
Control group /:
-.slice
|-1976 /sbin/cgmanager -m name=systemd
|-lxc
| |-con1
| | |-init.scope
| | | `-2818 /sbin/init
| | `-system.slice
| |   |-dbus.service
| |   | `-3879 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
| |   |-cron.service
| |   | `-3808 /usr/sbin/cron -f
| |   |-networking.service
| |   | `-4291 /sbin/dhclient -1 -v -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases -I -df /var/lib/dhcp/dhclient6.eth0.leases eth0
| |   |-nginx.service
| |   | |-4707 nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.con
| |   | `-4708 nginx: worker process                   
| |   |-atd.service
| |   | `-3827 /usr/sbin/atd -f
| |   |-systemd-journald.service
| |   | `-3112 /lib/systemd/systemd-journald
| |   |-systemd-logind.service
| |   | `-3866 /lib/systemd/systemd-logind
| |   |-systemd-udevd.service
| |   | `-3104 /lib/systemd/systemd-udevd
| |   |-console-getty.service
| |   | `-4609 /sbin/agetty --noclear --keep-baud console 115200 38400 9600 linux
| |   |-php7.0-fpm.service
| |   | |-4861 php-fpm: master process (/etc/php/7.0/fpm/php-fpm.conf)                      
| |   | |-5281 php-fpm: pool www                                                            
| |   | `-5282 php-fpm: pool www                                                            
| |   `-rsyslog.service
| |     `-3831 /usr/sbin/rsyslogd -n
| |-con2
| | |-init.scope
| | | `-3091 /sbin/init
| | `-system.slice
| |   |-dbus.service
| |   | `-5388 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
| |   |-cron.service
| |   | `-5423 /usr/sbin/cron -f
| |   |-networking.service
| |   | `-5516 /sbin/dhclient -1 -v -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases -I -df /var/lib/dhcp/dhclient6.eth0.leases eth0
| |   |-nginx.service
| |   | |-5689 nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.con
| |   | `-5690 nginx: worker process                   
| |   |-atd.service
| |   | `-5376 /usr/sbin/atd -f
| |   |-systemd-journald.service
| |   | `-4125 /lib/systemd/systemd-journald
| |   |-ssh.service
| |   | `-5585 /usr/sbin/sshd -D
| |   |-systemd-logind.service
| |   | `-5414 /lib/systemd/systemd-logind
| |   |-ttrss.service
| |   | `-6236 php /var/www/ttrss/public_html/update_daemon2.php
| |   |-systemd-udevd.service
| |   | `-4182 /lib/systemd/systemd-udevd
| |   |-system-syncthing.slice
| |   | `-syncthing@postgres.service
| |   |   `-5580 /usr/bin/syncthing -no-browser -no-restart -logflags=0
| |   |-system-postgresql.slice
| |   | `-postgresql@9.5-main.service
| |   |   |-5583 /usr/lib/postgresql/9.5/bin/postgres -D /var/lib/postgresql/9.5/main -c config_file=/etc/postgresql/9.5/main/postgresql.conf
| |   |   |-6240 postgres: 9.5/main: checkpointer process                                                                                    
| |   |   |-6241 postgres: 9.5/main: writer process                                                                                          
| |   |   |-6242 postgres: 9.5/main: wal writer process                                                                                      
| |   |   |-6243 postgres: 9.5/main: autovacuum launcher process                                                                             
| |   |   |-6244 postgres: 9.5/main: archiver process   last was 000000010000001A0000006D                                                    
| |   |   `-6245 postgres: 9.5/main: stats collector process                                                                                 
| |   |-console-getty.service
| |   | `-5634 /sbin/agetty --noclear --keep-baud console 115200 38400 9600 linux
| |   |-php7.0-fpm.service
| |   | |-5762 php-fpm: master process (/etc/php/7.0/fpm/php-fpm.conf)                      
| |   | |-5846 php-fpm: pool www                                                            
| |   | `-5847 php-fpm: pool www                                                            
| |   `-rsyslog.service
| |     `-5417 /usr/sbin/rsyslogd -n
| |-con3
| | |-init.scope
| | | `-2572 /sbin/init
| | `-system.slice
| |   |-dbus.service
| |   | `-4091 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
| |   |-cron.service
| |   | `-3935 /usr/sbin/cron -f
| |   |-prosody.service
| |   | `-5353 /usr/bin/lua5.1 /usr/bin/prosody
| |   |-networking.service
| |   | `-4716 /sbin/dhclient -1 -v -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases -I -df /var/lib/dhcp/dhclient6.eth0.leases eth0
| |   |-atd.service
| |   | `-3975 /usr/sbin/atd -f
| |   |-systemd-journald.service
| |   | `-2865 /lib/systemd/systemd-journald
| |   |-systemd-logind.service
| |   | `-4011 /lib/systemd/systemd-logind
| |   |-systemd-udevd.service
| |   | `-2889 /lib/systemd/systemd-udevd
| |   |-console-getty.service
| |   | `-5212 /sbin/agetty --noclear --keep-baud console 115200 38400 9600 linux
| |   `-rsyslog.service
| |     `-4061 /usr/sbin/rsyslogd -n
| |-con4
| | |-init.scope
| | | `-3474 /sbin/init
| | `-system.slice
| |   |-dbus.service
| |   | `-4600 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
| |   |-cron.service
| |   | `-4526 /usr/sbin/cron -f
| |   |-networking.service
| |   | `-4855 /sbin/dhclient -1 -v -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases -I -df /var/lib/dhcp/dhclient6.eth0.leases eth0
| |   |-nginx.service
| |   | |-5310 nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.con
| |   | `-5311 nginx: worker process                   
| |   |-atd.service
| |   | `-4585 /usr/sbin/atd -f
| |   |-systemd-journald.service
| |   | `-3923 /lib/systemd/systemd-journald
| |   |-ssh.service
| |   | `-5179 /usr/sbin/sshd -D
| |   |-systemd-logind.service
| |   | `-4544 /lib/systemd/systemd-logind
| |   |-systemd-udevd.service
| |   | `-3945 /lib/systemd/systemd-udevd
| |   |-system-syncthing.slice
| |   | `-syncthing@postgres.service
| |   |   `-5153 /usr/bin/syncthing -no-browser -no-restart -logflags=0
| |   |-system-postgresql.slice
| |   | `-postgresql@9.5-main.service
| |   |   |-5328 /usr/lib/postgresql/9.5/bin/postgres -D /var/lib/postgresql/9.5/main -c config_file=/etc/postgresql/9.5/main/postgresql.conf
| |   |   |-5437 postgres: 9.5/main: checkpointer process                                                                                    
| |   |   |-5438 postgres: 9.5/main: writer process                                                                                          
| |   |   |-5439 postgres: 9.5/main: wal writer process                                                                                      
| |   |   |-5441 postgres: 9.5/main: autovacuum launcher process                                                                             
| |   |   |-5442 postgres: 9.5/main: archiver process                                                                                        
| |   |   `-5443 postgres: 9.5/main: stats collector process                                                                                 
| |   |-console-getty.service
| |   | `-5245 /sbin/agetty --noclear --keep-baud console 115200 38400 9600 linux
| |   `-rsyslog.service
| |     `-4559 /usr/sbin/rsyslogd -n
| |-con5
| | |-init.scope
| | | `-2465 /sbin/init
| | |-system.slice
| | | |-dbus.service
| | | | `-2940 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
| | | |-cron.service
| | | | `-3040 /usr/sbin/cron -f
| | | |-networking.service
| | | | `-3261 /sbin/dhclient -1 -v -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases -I -df /var/lib/dhcp/dhclient6.eth0.leases eth0
| | | |-nginx.service
| | | | |-3934 nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.con
| | | | `-3939 nginx: worker process                   
| | | |-atd.service
| | | | `-3035 /usr/sbin/atd -f
| | | |-systemd-journald.service
| | | | `-2594 /lib/systemd/systemd-journald
| | | |-ssh.service
| | | | `-3682 /usr/sbin/sshd -D
| | | |-systemd-logind.service
| | | | `-3053 /lib/systemd/systemd-logind
| | | |-systemd-udevd.service
| | | | `-2581 /lib/systemd/systemd-udevd
| | | |-system-syncthing.slice
| | | | `-syncthing@con5.service
| | | |   `-3651 /usr/bin/syncthing -no-browser -no-restart -logflags=0
| | | |-console-getty.service
| | | | `-3762 /sbin/agetty --noclear --keep-baud console 115200 38400 9600 linux
| | | `-rsyslog.service
| | |   `-3026 /usr/sbin/rsyslogd -n
| | `-user.slice
| |   `-user-1000.slice
| |     |-user@1000.service
| |     | `-init.scope
| |     |   |-6393 /lib/systemd/systemd --user
| |     |   `-6396 (sd-pam)  
| |     `-session-c1.scope
| |       |-6391 sshd: con5 [priv] 
| |       `-6435 sshd: con5        
| `-con6
|   |-init.scope
|   | `-3783 /sbin/init
|   `-system.slice
|     |-dbus.service
|     | `-4668 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
|     |-cron.service
|     | `-4656 /usr/sbin/cron -f
|     |-networking.service
|     | `-4965 /sbin/dhclient -1 -v -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases -I -df /var/lib/dhcp/dhclient6.eth0.leases eth0
|     |-nginx.service
|     | |-5306 nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.con
|     | `-5308 nginx: worker process                   
|     |-atd.service
|     | `-4654 /usr/sbin/atd -f
|     |-systemd-journald.service
|     | `-4101 /lib/systemd/systemd-journald
|     |-systemd-logind.service
|     | `-4640 /lib/systemd/systemd-logind
|     |-systemd-udevd.service
|     | `-4117 /lib/systemd/systemd-udevd
|     |-console-getty.service
|     | `-5253 /sbin/agetty --noclear --keep-baud console 115200 38400 9600 linux
|     |-rsyslog.service
|     | `-4651 /usr/sbin/rsyslogd -n
|     `-gatekeeper.service
|       `-5132 /usr/bin/node /var/www/gatekeeper/server.js
|-init.scope
| `-1 /sbin/init
|-system.slice
| |-dbus.service
| | `-1938 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
| |-sshguard.service
| | `-2031 /usr/sbin/sshguard -i /run/sshguard.pid -w /etc/sshguard/whitelist -l /var/log/auth.log -a 40 -p 420 -s 1200
| |-systemd-journald.service
| | `-1779 /lib/systemd/systemd-journald
| |-lxd.service
| | |-2337 /usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log
| | |-2434 [lxc monitor] /var/lib/lxd/containers con5
| | |-2529 [lxc monitor] /var/lib/lxd/containers con3
| | |-2733 [lxc monitor] /var/lib/lxd/containers con1
| | |-2996 [lxc monitor] /var/lib/lxd/containers con2
| | |-3379 [lxc monitor] /var/lib/lxd/containers con4
| | `-3697 [lxc monitor] /var/lib/lxd/containers con6
| |-systemd-timesyncd.service
| | `-1906 /lib/systemd/systemd-timesyncd
| |-ssh.service
| | `-2273 /usr/sbin/sshd -D
| |-systemd-logind.service
| | `-1970 /lib/systemd/systemd-logind
| |-system-getty.slice
| | `-getty@tty1.service
| |   `-2367 /sbin/agetty --noclear tty1 linux
| |-netdata.service
| | |-2330 /usr/sbin/netdata -D
| | `-8804 bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 3
| |-systemd-udevd.service
| | `-282 /lib/systemd/systemd-udevd
| |-haveged.service
| | `-1768 /usr/sbin/haveged --Foreground --verbose=1 -w 2048
| |-irqbalance.service
| | `-2095 /usr/sbin/irqbalance --pid=/var/run/irqbalance.pid
| |-lxd-bridge.service
| | `-2142 dnsmasq -s 10.135.225.1 -S /10.135.225.1/ -u lxd --strict-order --bind-interfaces --pid-file=/run/lxd-bridge//dnsmasq.pid --dhcp-no-override --except-interface=lo --interface=lxdbr0 --dhcp-leasefile=/var/lib/lxd-bridge//dnsmasq.
| |-rsyslog.service
| | `-1940 /usr/sbin/rsyslogd -n
| `-lxcfs.service
|   `-1991 /usr/bin/lxcfs /var/lib/lxcfs/
`-user.slice
  `-user-1000.slice
    |-session-28.scope
    | |-10396 sshd: user [priv]   
    | |-10437 sshd: user@pts/6    
    | |-10438 -bash
    | |-11091 systemd-cgls
    | `-11092 pager
    `-user@1000.service
      `-init.scope
        |-10400 /lib/systemd/systemd --user
        `-10408 (sd-pam)  
```
I'm interesting only in some things:
```bash
	enable cgroup lxc_con1_init.scope = no
	enable cgroup lxc_con1_system.slice_nginx.service = yes # right
	enable cgroup lxc_con1_system.slice_php7.0-fpm.service = yes # not sure its right, less then 1Mb
	enable cgroup lxc_con2_init.scope = no
	enable cgroup lxc_con2_system.slice_nginx.service = yes # not right, most highloaded
	enable cgroup lxc_con2_system.slice_ttrss.service = yes # right, feed update script only ?
	enable cgroup lxc_con2_system.slice_system-postgresql.slice = yes # right
	enable cgroup lxc_con2_system.slice_php7.0-fpm.service = yes # not sure its right, less then 1Mb
	enable cgroup lxc_con3_init.scope = no
	enable cgroup lxc_con3_system.slice_prosody.service = yes # not right lua
	enable cgroup lxc_con4_init.scope = no
	enable cgroup lxc_con4_system.slice_nginx.service = yes # right
	enable cgroup lxc_con4_system.slice_system-postgresql.slice = yes # right
	enable cgroup lxc_con5_init.scope = no
	enable cgroup lxc_con5_system.slice_nginx.service = yes # right
	enable cgroup lxc_con6_init.scope = no
	enable cgroup lxc_con6_system.slice_nginx.service = yes # right
	enable cgroup lxc_con6_system.slice_gatekeeper.service = yes # right, nodejs
```

**Comment by ktsaou** [comment] 2016-09-25 15:10
thanks. So you have edited the netdata config to select only what is interesting for you.

Summing up, you found that for `lxc` the top cgroup in the container hierarchy reports too low memory. However, the cgroups under it, report the memory as it should be.

So, you ended up enabling monitoring of specific cgroups that netdata has disabled by default.

I just installed lxc and fired up a few containers. I don't see this problem in kernel 4.4.6 on gentoo.
Which kernel and distro do you use?

**Comment by cryptofuture** [comment] 2016-09-25 16:29
4.4.0-38 on Ubuntu Xenial, containers under lxd, not pure lxc.
>Summing up, you found that for lxc the top cgroup in the container hierarchy reports too low memory. However, the cgroups under it, report the memory as it should be.
Yes.

**Comment by ktsaou** [comment] 2016-09-25 16:47
cgroups in hierarchical. The parent always includes the children.

However, netdata does not use `/sys/fs/cgroup/memory/memory.stat` at all.

netdata uses only `/sys/fs/cgroup/memory/lxc/containername/memory.stat`, which you found that shows less memory than `/sys/fs/cgroup/memory/lxc/containername/nginx.service/memory.stat`.

Right?

**Comment by cryptofuture** [comment] 2016-09-25 17:02
Yes.  
More above I tested right now, even more interesting thing.
`lxc exec containername -- cat /sys/fs/cgroup/memory/memory.stat` and `cat /sys/fs/cgroup/memory/memory.stat` in container gives different values too! Thats total nonsense.
Overall:
`cat /sys/fs/cgroup/memory/lxc/containername/memory.stat` on host shows incorrect values for sure
But values even totally different between  `lxc exec containername -- cat /sys/fs/cgroup/memory/memory.stat` and `cat /sys/fs/cgroup/memory/memory.stat` in container itself.
Data:
```
@host: cat /sys/fs/cgroup/memory/lxc/valya/memory.stat
cache 196608
rss 0
rss_huge 0
mapped_file 126976
dirty 0
writeback 0
pgpgin 13329
pgpgout 13281
pgfault 21176
pgmajfault 6640
inactive_anon 0
active_anon 0
inactive_file 45056
active_file 151552
unevictable 0
hierarchical_memory_limit 9223372036854771712
total_cache 4370432
total_rss 15507456
total_rss_huge 0
total_mapped_file 2215936
total_dirty 0
total_writeback 0
total_pgpgin 1482149
total_pgpgout 1478829
total_pgfault 1879399
total_pgmajfault 1119926
total_inactive_anon 8884224
total_active_anon 7729152
total_inactive_file 1617920
total_active_file 1646592
total_unevictable 0
```
```
@container
cache 925696
rss 581632
rss_huge 0
mapped_file 872448
dirty 0
writeback 0
pgpgin 14506
pgpgout 14138
pgfault 22978
pgmajfault 7313
inactive_anon 258048
active_anon 286720
inactive_file 561152
active_file 311296
unevictable 0
hierarchical_memory_limit 9223372036854771712
total_cache 4235264
total_rss 19251200
total_rss_huge 0
total_mapped_file 2940928
total_dirty 0
total_writeback 0
total_pgpgin 1489468
total_pgpgout 1485267
total_pgfault 1888559
total_pgmajfault 1125768
total_inactive_anon 10407936
total_active_anon 9830400
total_inactive_file 1613824
total_active_file 1544192
total_unevictable 0
```
```
@host:`lxc exec containername -- cat /sys/fs/cgroup/memory/memory.stat 
cache 528384
rss 90112
rss_huge 0
mapped_file 475136
dirty 0
writeback 0
pgpgin 14805
pgpgout 14654
pgfault 23373
pgmajfault 7572
inactive_anon 0
active_anon 61440
inactive_file 376832
active_file 73728
unevictable 0
hierarchical_memory_limit 9223372036854771712
total_cache 4698112
total_rss 19542016
total_rss_huge 0
total_mapped_file 3870720
total_dirty 0
total_writeback 0
total_pgpgin 1494030
total_pgpgout 1489645
total_pgfault 1893777
total_pgmajfault 1129612
total_inactive_anon 12091392
total_active_anon 10670080
total_inactive_file 835584
total_active_file 536576
total_unevictable 0
```
Now, I'm totally confused.

**Comment by cryptofuture** [comment] 2016-09-30 22:44
Do I need to make changes anywhere beside sys_fs_cgroup.c file to make alternative memory chart?

So far I tested `/sys/fs/cgroup/memory/lxc/containername/memory.stat`on 3 different machines with different containers, and it always shows wrong values. But I found out that `cat /sys/fs/cgroup/memory/lxc/containername/memory.usage_in_bytes` always gives right values. (it used for lxc info too!). It will be more simple chart, but its enough to see how much memory container use, and well `memory.usage_in_bytes` works for me. I took logic from cgroup.memory, but I didn't see new graph in web interface, however netdata discovered new module, and I enabled it in config.
I found only how to make new module on python information in wiki.
[sys_fs_cgroup.txt](https://github.com/firehol/netdata/files/503939/sys_fs_cgroup.txt)
Sadly, I can't send a pull request, since its not now working right now.

**Comment by ktsaou** [comment] 2016-09-30 23:18
I don't think this is right. Something else is happening on your machine:

https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt

It says:

```
5.5 usage_in_bytes

For efficiency, as other kernel components, memory cgroup uses some optimization
to avoid unnecessary cacheline false sharing. usage_in_bytes is affected by the
method and doesn't show 'exact' value of memory (and swap) usage, it's a fuzz
value for efficient access. (Of course, when necessary, it's synchronized.)
If you want to know more exact memory usage, you should use RSS+CACHE(+SWAP)
value in memory.stat(see 5.2).
```

**Comment by ktsaou** [comment] 2016-09-30 23:25
I can confirm `lxc` is using `usage_in_bytes` though.

**Comment by ktsaou** [comment] 2016-09-30 23:33
Check this:

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Resource_Management_Guide/sec-memory.html

```
memory.use_hierarchy

contains a flag (0 or 1) that specifies whether memory usage should be accounted for throughout a hierarchy of cgroups. If enabled (1), the memory subsystem reclaims memory from the children of and process that exceeds its memory limit. By default (0), the subsystem does not reclaim memory from a task's children.
```

**Comment by ktsaou** [comment] 2016-09-30 23:38
Seems like exactly your problem: https://issues.apache.org/jira/browse/MESOS-758

**Comment by ktsaou** [comment] 2016-09-30 23:44
It seems the kernel devs had a similar issue in 2011: https://groups.google.com/forum/#!topic/linux.kernel/EwiYK53Itk8

**Comment by ktsaou** [comment] 2016-10-01 00:17
I have added 2 new charts:

1. a chart that shows `ram` and `swap` calculated from `usage_in_bytes` and `memsw_usage_in_bytes`.
2. a chart that shows `failcnt` (it will appear only if there are any).

Please clone `https://github.com/ktsaou/netdata`, install it and test it.
Report back any issues to fix them before merging it.

**Comment by ktsaou** [comment] 2016-10-01 00:19
On my system:

![image](https://cloud.githubusercontent.com/assets/2662304/19010246/d2bc50bc-8785-11e6-884a-3c4ca6d85565.png)

**Comment by cryptofuture** [comment] 2016-10-01 09:18
Works great for me!
![stat](https://cloud.githubusercontent.com/assets/6484506/19012936/9f19ff7a-87b2-11e6-9e68-889659663249.png)

**Comment by ktsaou** [comment] 2016-10-01 09:41
merged. thanks!

**Closed** 2016-10-01 09:41 UTC
