### ISSUE TITLE
Failed to start netdata: Cannot cd to directory /usr/libexec/netdata/plugins.d

### ISSUE THREAD

**Issue by Feeliiix** [firehol/netdata#1293] opened 2016-11-28 16:31 UTC
Hello,

i have a problem. I installed netdata on a clean Ubuntu 16.10. It fails to start and this is the problem (log from `journalctl -rx`):

`netdata[9237]: Cannot cd to directory '/usr/libexec/netdata/plugins.d'`

But the directory is available and I can `cd` into the directory. With `ls -n` I get this output:

```total 248
-rwxr-xr-x 1 0 0    110 Nov 28 17:02 alarm-email.sh
-rwxr-xr-x 1 0 0  36471 Nov 28 17:02 alarm-notify.sh
-rwxr-xr-x 1 0 0    265 Nov 28 17:02 alarm-test.sh
-rwxr-xr-x 1 0 0 116808 Nov 28 17:02 apps.plugin
-rwxr-xr-x 1 0 0   3119 Nov 28 17:02 cgroup-name.sh
-rwxr-xr-x 1 0 0   1206 Nov 28 17:02 charts.d.dryrun-helper.sh
-rwxr-xr-x 1 0 0  19834 Nov 28 17:02 charts.d.plugin
-rwxr-xr-x 1 0 0   4338 Nov 28 17:02 fping.plugin
-rw-r--r-- 1 0 0   5611 Nov 28 17:02 loopsleepms.sh.inc
-rwxr-xr-x 1 0 0  11143 Nov 28 17:02 node.d.plugin
-rwxr-xr-x 1 0 0  19428 Nov 28 17:02 python.d.plugin
-rw-r--r-- 1 0 0   7374 Nov 28 17:02 README.md
-rwxr-xr-x 1 0 0   3561 Nov 28 17:02 tc-qos-helper.sh
```

Thanks for your help,
Feeliiix

**Comment by gmorain** [comment] 2016-11-28 16:47
Hello Feeliiix, 

I have the same problem. Since it looks like a duplicate of issue #1292, may I suggest you close this issue and add your input to the other one ?

Gilles

**Comment by ktsaou** [comment] 2016-11-28 20:20
Just fixed (sorry... my bad).
Just run `git pull` and then `./netdata-installer.sh` again. It should be ok now.

**Closed** 2016-11-30 14:37 UTC
Labels: bug, duplicate, fixed
