### ISSUE TITLE
Notifications mails 

### ISSUE THREAD

**Issue by Cdiez50** [firehol/netdata#285] opened 2016-04-20 13:36 UTC
Hy form France :)

Is there planned/possible to have mail notification system ?
For downtime and warning, a bit like ;
if $incoming_traf > $x { mail -s "warning on `hostname`" "$email" << EOF } fi 

I didn't see any information about that and it could be really cool !

Thanks for all the jobs !

**Comment by ktsaou** [comment] 2016-04-20 22:42
Yes, I agree.
This is duplicate of #88 #183

**Comment by ktsaou** [comment] 2016-04-20 22:43
I am flooded with requests, so I'll close this and we will discuss it on #88.
Please post your suggestion there.
Thanks!

**Closed by ktsaou** 2016-04-20 22:43 UTC
Labels: duplicate
