### ISSUE TITLE
CPU usage of Netdata way too much

### ISSUE THREAD

**Issue by samof76** [firehol/netdata#1630] opened 2017-01-24 11:52 UTC
![htop_output](https://cloud.githubusercontent.com/assets/98111/22246171/78ddb732-e259-11e6-8312-2237a8a1e4ed.png)

Using netdata 1.4.1_master
OS: Elementary OS Loki
4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ktsaou** [comment] 2017-01-24 11:57
At the netdata dashboard, there is a "Netdata monitoring" section with several "CPU Usage" charts. Could you please identify the plugin that causes this?

**Comment by l2isbad** [comment] 2017-01-24 12:02
Why there is so many netdata processes?

**Comment by ktsaou** [comment] 2017-01-24 12:09
they are not processes. They are threads (htop shows threads individually).

**Comment by ktsaou** [comment] 2017-01-24 12:11
They are:

1. one for /proc
2. one for cgroups
3. one for disks
4. one for health/alarms
5. one per external plugin
6. one per web client

**Comment by samof76** [comment] 2017-01-24 12:49
@ktsaou I do not see anything but the "user" and "system" on those graphs.

**Comment by ktsaou** [comment] 2017-01-24 12:53
Yes, but one of them should show values of 500 milliseconds/s. Normally they should be 1-10 ms/s. The one having 500 is the problem.

**Comment by samof76** [comment] 2017-01-24 13:07
Right now it dropped, but i see consistent there are spikes on the `user` upto 150ms or more.

**Comment by ktsaou** [comment] 2017-01-24 13:09
on which chart?

**Comment by samof76** [comment] 2017-01-24 13:10
Sorry! on the `netdata.server_cpu` charts!

**Comment by ktsaou** [comment] 2017-01-24 13:16
hm... this one counts the total, of all threads.

If no other CPU utilization chart shows increased CPU, this is due to web clients accessing the dashboard. This explains also why the CPU consumption is visible only for a limited time.

Are you the only one accessing the dashboard? If you have many users, this is normal, especially when users zoom out the charts (lots of calculations to respond).

Keep in mind though that netdata is running with the IDLE process scheduling priority (lower than nice 19) and adjusts its OOM score to 1000 (so that it will be the first process to be killed if the server runs out of memory). So, it is pretty safe to run...

**Comment by samof76** [comment] 2017-01-25 07:41
![netdata_cpu](https://cloud.githubusercontent.com/assets/98111/22281956/a6ddcfb8-e2ff-11e6-87af-18945879cd7a.png)

This is as i speak. But only one client is connected to netdata.

**Comment by ktsaou** [comment] 2017-01-25 08:33
hm... this is system. It is outside control of netdata. Your kernel spends that much time.

Could you please help me pinpoint the issue?

Can you post this chart:

![image](https://cloud.githubusercontent.com/assets/2662304/22283218/a7415d6e-e2e9-11e6-8b23-4dc3644eca5d.png)

**Comment by samof76** [comment] 2017-01-25 08:37
I have stopped the netdata on my local machine, and the resource usage has dropped. Next time when i hit on this issue i will post that graph. Thanks.

**Comment by ktsaou** [comment] 2017-01-25 08:39
ok, If you can post all the charts on the "Netdata Monitoring" section, it would be helpful.
If I can't pinpoint the issue from the charts, I would ask you to disable a few netdata modules, until we find the offending one.

**Comment by samof76** [comment] 2017-01-25 08:42
Sure, give me sometime.

**Comment by ktsaou** [comment] 2017-02-04 13:18
I have marked this as `bug` and `need reproduction`.
So, please help me identify the issue.

**Comment by samof76** [comment] 2017-02-06 06:46
Hi @ktsaou 

Sorry I was not around for a while, will check on this today and let you know how it goes.

**Comment by samof76** [comment] 2017-02-27 13:03
@ktsaou I still have not been able to replicate this situation. I had recently update netdata to 1.5 version. I guess you could close this, thanks for waiting on this.

**Comment by ktsaou** [comment] 2017-02-27 14:35
ok. thanks!

**Closed by ktsaou** 2017-02-27 14:35 UTC
Labels: question

**Comment by markosole** [comment] 2017-06-20 19:39
Hi,
How can I exclude Netdata from LFD reporting? I am getting email alerts like this: 
**Account:**      netdata
**Resource:**     Process Time
**Exceeded:**     18105 > 1800 (seconds)

I would like to exclude that account from LFD. If there is a way to find out what is causing this, that would be better. Thanks.

**Comment by ktsaou** [comment] 2017-06-20 19:45
@markosole what is LFD reporting? Googling around I found that is something related to cpanel. If this is the case, you should check cpanel docs. I am sorry, I don't know...

**Comment by markosole** [comment] 2017-06-20 19:58
It's a ConfigServer Security & Firewall for cPanel. I am getting this reporting every few minutes. Here are some details https://crybit.com/lfd-excessive-resource-usage-alert/  I found.
I have added this: **user:netdata**   to config pignore file  located here **/etc/csf/csf.pignore**
Test is in progress. WIl see.

**Comment by markosole** [comment] 2017-06-20 20:12
Here is a new one. Same thing but with more details I missed first time.
Account:      netdata
Resource:     Process Time
Exceeded:     1833 > 1800 (seconds)
Executable:   /bin/bash
Command Line: bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
PID:          16275 (Parent PID:3616)
Killed:       No

**Comment by elrond1999** [comment] 2017-11-17 13:12
Here is one: 
![image](https://user-images.githubusercontent.com/1906913/32948935-42fd85e8-cba1-11e7-8d42-310ee375e89e.png)

Large System. Big on Interrupts and softnet.

**Comment by ktsaou** [comment] 2017-11-18 21:52
Hi,

You can disable interrupts and softirqs in netdata.conf:

```
[plugin:proc]
	/proc/interrupts = no
	/proc/softirqs = no
```

However, 6 ms / sec is 0.6% of a single core.

What does this chart say on your netdata (select only `netdata` from the legend):

![2017-11-18 23-51-57](https://user-images.githubusercontent.com/2662304/32985107-846542da-ccbb-11e7-9446-6be7baf87a94.png)

**Comment by elrond1999** [comment] 2017-11-23 14:17
CPU usage has fallen now:
![image](https://user-images.githubusercontent.com/1906913/33177011-686c2e32-d061-11e7-9b01-d8e5790240ed.png)

Much better. Not sure what was changed.
