### ISSUE TITLE
go_expvar issues/improvements

### ISSUE THREAD

**Issue by kralewitz** [firehol/netdata#2718] opened 2017-09-11 14:05 UTC
Hello,

I have found two issues with my go_expvar python.d plugin that I would like to fix, but I need some pointers:

1) Charting very small values

I have recently started measuring response times in my app, which are in the microsecond range. The app is returning them as seconds, like this:

`"input.httplisten9448.request_duration.p50": 2.5883469939240174e-05`

It then gets rounded down to 0 during processing. If a metric is set to the `float` type in go_expvar plugin, the plugin multiplies the value by 1000 and then sets the line divisor to 1000, however, this is not enough for these values. I was thinking of multypling the values by let's say 10^12 in the plugin, and then setting the line divisor accordingly (if it's not overriden by the user). Would that be okay or is there a better way to go about this? Maybe let the user supply the internal multiplier value by config?

Let me know what do you think.

2) Duplicated chart ID's

I'm kind of stumped by this - for some reason, one of the dot-separated parts in the chart ID is getting duplicated for some charts, which then messes up other metrics backend (influx in my case).

This is the chart info from netdata dashboard for a chart that's having this issue:

`runtime: number of goroutines (go_expvar_stblogd.go_expvar_stblogd.num_goroutines)`

Another chart, (which is okay):

`pipeline: message rate (go_expvar_stblogd.message_rate)`

But, when I run the `python.d` plugin directly, the chart and dimension config looks okay:

```
CHART go_expvar_stblogd.runtime_goroutines num_goroutines 'runtime: number of goroutines' goroutines runtime expvar.runtime.goroutines line 60007 1
DIMENSION runtime_goroutines goroutines absolute 1 1

CHART go_expvar_stblogd.message_rate message_rate 'pipeline: message rate' req/s pipeline expvar.pipeline.reqrate line 60008 1
DIMENSION message_rate_input input incremental 1 1
DIMENSION message_rate_filter filter incremental 1 1
DIMENSION message_rate_output output incremental 1 1

...

BEGIN go_expvar_stblogd.runtime_goroutines 999975
SET runtime_goroutines = 752
END
BEGIN go_expvar_stblogd.message_rate 999975
SET message_rate_input = 129777748
SET message_rate_filter = 131840251
SET message_rate_output = 131840232
END
```

I have no idea where the duplicate part of ID is coming from.

@ktsaou or @l2isbad, I'd appreciate any help with either of these issues.

Thanks

**Comment by l2isbad** [comment] 2017-09-14 04:23
> Duplicated chart ID's

^
@kralewitz 
does it still unresolved?

> one of the dot-separated parts in the chart ID is getting duplicated for some charts

[Chart type.id](https://github.com/firehol/netdata/blob/master/python.d/python_modules/base.py#L414-L416) 
`type` =- `module.__name__` (or `module.__name__ + '_' + override_name`)
`id` =  `chart name` (from `self.order`)

**Comment by l2isbad** [comment] 2017-09-14 04:33
Since the module can have any number of jobs better to use `deepcopy` [here](https://github.com/firehol/netdata/blob/master/python.d/go_expvar.chart.py#L73-L75). Becasue of https://github.com/firehol/netdata/blob/master/python.d/go_expvar.chart.py#L159-L160

**Comment by kralewitz** [comment] 2017-09-14 08:28
Hey @l2isbad,

yes, the issue with duplicated part in chart ID is still not resolved.

I'm not sure if I follow you - if you take a look at the CHART line produced by the python.d plugin, the duplicated part is not there:

`CHART go_expvar_stblogd.runtime_goroutines num_goroutines 'runtime: number of goroutines' goroutines runtime expvar.runtime.goroutines line 60007 1`

So if the plugin itself is outputting the chart definition correctly, there is no reason for it to show up duplicated on the dashboard, no?

As for your second comment, I think it is not necessary to use `copy` there - it should be fine to just wrap it in a list() and dict(), as there are no variables inside MEMSTAT_CHARTS and MEMSTAT_ORDER, just plain strings and ints.

**Comment by l2isbad** [comment] 2017-09-14 09:06
> a list() and dict()

yes, that is why  prev comment was updated 😄 

> So if the plugin itself is outputting the chart definition correctly, there is no reason for it to show up duplicated on the dashboard, no?

yes

> This is the chart info **from netdata dashboard** for a chart that's having this issue

miss that part 😢

**Comment by kralewitz** [comment] 2017-09-14 09:15
One more thing I should have probably mentioned earlier - the netdata running the go_expvar plugin is configured only as a collector (no dashboard, no in-memory data), and is forwarding the data to a central netdata instance.

I have tried changing the collector settings to run a dashboard and keep values locally, and the duplicate part of ID disappeared.

So this looks like a problem between the central and collector netdata instances.

**Comment by l2isbad** [comment] 2017-09-14 09:31
> So this looks like a problem between the central and collector netdata instances

Good finding!

It's easy to reproduce @ktsaou 
If n`name `(CHART type.id **name**) is not '' we have duplicated part in chart id in master dashboard.

```python
CHARTS = {'uptime': {
            'options': ['hello_world', "System uptime", "uptime", 'uptime_my', 'uptime', 'stacked'],
            'lines': [
                ['minutes', None, 'absolute'], ['hours', None, 'absolute'], ['days', None, 'absolute']
                    ]}
        }
```

![screenshot_20170914_183105](https://user-images.githubusercontent.com/22274335/30422432-e7bcf7ac-997a-11e7-9e5c-fb19237ce498.png)

**Comment by ktsaou** [comment] 2017-09-16 14:23
I think I missed this thread.

So, there are 2 problems:

1. detail of floating point numbers.

   I think the solution to this is simple. The `go_expvar` configuration should probably have a setting to set the fractional detail of floating point values. I have done the same with statsd. By default it has 3 fractional digits precision, but the user can configure it to have up to 7 (this is the netdata max).

   I also think that the integer data collection policy is probably wrong. We should collect `long double` values, to avoid all this mess with multipliers and dividers to get a proper fractional number on the dashboard.

2. netdata masters duplicate components of the chart unique id at the title of the charts.

    I think there was such a problem some time ago, but it is not now. Can you confirm this happens with the current netdata as master? It has been fixed with https://github.com/firehol/netdata/pull/2294 (point 5).

**Comment by l2isbad** [comment] 2017-09-17 03:17
> Can you confirm this happens with the current netdata as master?

yes

**Comment by ktsaou** [comment] 2017-09-17 09:10
In PR #2749 
Could you please check it?

**Comment by ktsaou** [comment] 2017-09-17 11:10
merged.
Thanks!

**Closed** 2017-09-17 11:10 UTC
Labels: bug, fixed
