### ISSUE TITLE
Colors for BTRFS graphs are inconsistent

### ISSUE THREAD

**Issue by spinitron** [firehol/netdata#3719] opened 2018-05-12 14:52 UTC
I think it would be easier to read the BTRFS graphs if colors were used consistently.

The snapshot below shows what I have (default) overlaid with an example of my suggestion: use one color for one metric across all four graphs

- btrfs.disk uses green for unallocated space. so don't use green again in the data, metadata, and system graphs because they don't display unallocated space
- used data space is red in the disk and data graphs. that's good!
- free data space should be the same color in both disk and data graphs: blue
- used metadata space should be the same color in both disk and metadata graphs: orange
- and so on
- reserved metadata space should be some color not used anywhere else

![Snapshot](https://monosnap.com/image/SDjlgtA7EtqKoLQvPYW5DM3nAXHVn9.png)

**Comment by ktsaou** [comment] 2018-05-12 18:59
Hi,

well, they are not the same. If you had a raid-1 in your array, the values would not match. The first chart shows raw disk space (ie if you had 2x1TB in raid-1, the first chart would show 2TB total), the rest of the charts show usable disk space (1TB total).

Also, I am not sure which is better:

1. have the different sections with unified colors, so you can quickly match the first with the rest of the charts,
or
2. always have free as green and used as red

I preferred the second, since it allows us to instantly spot where disk space is missing, without reading the legends or the titles, like "if there is no green in it, you have a problem".

But I am open... if you want it the other way around, I can do it.
@Ferroin what do you think?

**Comment by spinitron** [comment] 2018-05-12 19:03
always have free as green and used as red and unallocated as something else would be fine too

**Comment by ktsaou** [comment] 2018-05-12 19:17
> always have free as green and used as red and unallocated as something else would be fine too

This is how it is now.

In the context of the first chart, "free" is only the "unallocated". All the others (of the first chart) are not "free" at all. The first chart tracks raw space allocations. So, for the first chart, "data free" is space that has been allocated to "data", but is not currently used to store any actual data.

I think the problem is that the first chart shows both "free" and "used" for each allocation type. This is a bit confusing. Probably it should show only:

- unallocated
- data (total)
- system (total)
- metadata (total)

or even:

- free (unallocated)
- used (allocated = sum of the all the other)

The key value to track on the first chart is "unallocated". If this gets zero, you have problems. The rest of the dimensions, are more like a nice informative addition, without too much purpose (because they actually show raw disk space, before any raid levels).

**Comment by spinitron** [comment] 2018-05-12 19:30
> The key value to track on the first chart is "unallocated". If this gets zero, you have problems. 

Agree.

> In the context of the first chart, "free" is only the "unallocated".

Disagree here. I think it's unhelpful to consider "unallocated" space as "free" in this context.

It always bugs me when I look at these graphs is that I need to carefully think through the difference between unallocated space and free space, which is a peculiarity of BTRFS, and a very important difference (which we agreed upon already).

That's why I argue for unallocated to be a color all its own. A medium-scary color like yellow or orange, maybe.

**Comment by Ferroin** [comment] 2018-05-14 13:05
The other thing though is that the first graph shows space usage _after_ any replication, striping, parity, etc, while the subsequent graphs show usage _before_ any of that.  IOW, the second graphs should match up with what `btrfs filesystem df shows, while the first graph should match up (roughly) with what regular `df` shows (with the sum of `unallocated` and all the `free` types being the free space).

So, while I agree that at least correlating them does make sense, I'm also of the opinion that it may confuse people (because matching both colors and naming seems to imply an equivalency that is not actually present).

**Comment by Ferroin** [comment] 2018-05-14 19:12
Kind of, the `allocated` and `free` parts correspond to the various chunk type sections in `btrfs filesystem usage`, albeit not split out by device, and the same goes for the `unallocated` metric.  However, aside from not splitting per-device, it also doesn't account for missing space (I'm actually not 100% certain _how_ it handles missing space TBH).

**Comment by Ferroin** [comment] 2018-05-29 12:50
I absolutely agree on the title change for the first chart.  It adds some rather important clarity.

As far as matching the colors like @spinitron is suggesting, the more I think about it, the more it actually does make some sense, provided of course tat it's made clear (in the chart titles in this case) that the first chart is physical allocations, while the other three are virtual allocations.

**Comment by ktsaou** [comment] 2018-06-10 22:17
ok, I am doing this now.

![image](https://user-images.githubusercontent.com/2662304/41206939-3e212c94-6d15-11e8-8656-1e8ab3f51b1b.png)

**Comment by ktsaou** [comment] 2018-06-10 22:52
merged it.

**Closed** 2018-06-10 22:51 UTC
Labels: discussion
