### ISSUE TITLE
Alert notification via email

### ISSUE THREAD

**Issue by Dasithz** [firehol/netdata#663] opened 2016-07-06 20:40 UTC
Is there any way to get notification when a threshold is exceeded for a particular performance level ?

**Comment by paulfantom** [comment] 2016-07-06 21:13
Currently it cannot be done but according to [poll](https://github.com/firehol/netdata/issues/436) it is the next feature to be implemented.

**Comment by ktsaou** [comment] 2016-07-08 10:17
Right. This is duplicate of #318 
I am closing it.

**Closed by ktsaou** 2016-07-08 10:17 UTC
Labels: duplicate, enhancement
