### ISSUE TITLE
logging verbosity control ?

### ISSUE THREAD

**Issue by centminmod** [firehol/netdata#240] opened 2016-04-15 16:14 UTC
Is there any log verbosity control for error.log and access.log ?
```
grep -c 'INFO:' /var/log/netdata/error.log 
2037
```
```
grep -c 'ERROR:' /var/log/netdata/error.log     
3267
```
```
ls -lah /var/log/netdata/
total 4.2M
drwxrwxr-x   2 netdata netdata   67 Apr 12 19:41 .
drwxr-xr-x. 14 root    root    4.0K Apr 12 19:41 ..
-rw-r--r--   1 root    root    3.5M Apr 15 14:45 access.log
-rw-r--r--   1 root    root       0 Apr 12 19:41 debug.log
-rw-r--r--   1 root    root    696K Apr 15 15:09 error.log
-rw-r--r--   1 netdata netdata    0 Apr 12 19:41 .keep
```

**Comment by ktsaou** [comment] 2016-04-15 21:30
No.
There is very fine control for debug.log only (which is disabled by default). The ERROR and INFO entries are hardcoded messages, I believe you should know. If you found something that should not be there by default, please let me know to turn it to a debug message.

**Comment by ktsaou** [comment] 2016-04-17 16:45
I have added a control that protects `netdata` and `apps.plugin` from log floods. Now you can control how much error loggings you want. Read more at #254 

Please close this, if the issue is solved.

**Comment by ktsaou** [comment] 2016-04-17 16:48
I have also openned #256 for adding the same logic to `charts.d.plugin` and `node.d.plugin`.

**Comment by ktsaou** [comment] 2016-04-19 17:36
ok, can we close this?

**Comment by ktsaou** [comment] 2016-05-21 22:53
I think we don't need this open anymore.
Thanks

**Closed by ktsaou** 2016-05-21 22:53 UTC
Labels: enhancement, fixed
