### ISSUE TITLE
Unresponsive on Linux Mint 17.3

### ISSUE THREAD

**Issue by voycey** [firehol/netdata#226] opened 2016-04-14 03:37 UTC
I thought I would check this out today (it looks fantastic by the way!), install was smooth but immediately after the install my system became really choppy (I am listening to music at the same time - this kept cutting in and out (Pulseaudio), the mouse and keyboard become really unresponsive, it feels as if there is a huge load on the system but top shows nothing out of the ordinary.

Here is some debug info:

```
dan@dan-linux ~/github/netdata $ uname -a
Linux dan-linux 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
dan@dan-linux ~/github/netdata $ cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.3
DISTRIB_CODENAME=rosa
DISTRIB_DESCRIPTION="Linux Mint 17.3 Rosa"
```
error.log:

```
16-04-14 13:31:33: INFO: netdata: Successfully became user 'netdata'.
16-04-14 13:31:33: INFO: netdata: NetData started on pid 31267
16-04-14 13:31:33: INFO: netdata: Starting thread tc.
16-04-14 13:31:33: INFO: netdata: Starting thread idlejitter.
16-04-14 13:31:33: INFO: netdata: 16-04-14 13:31:33: INFO: netdata: Starting thread proc.
TC thread created with task id 31268
16-04-14 13:31:33: INFO: netdata: CPU Idle Jitter thread created with task id 3126916-04-14 13:31:33: INFO: netdata: Starting thread plugins.d.

16-04-14 13:31:33: INFO: netdata: PROC Plugin thread created with task id 31270
16-04-14 13:31:33: INFO: netdata: executing command: 'exec /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1' on pid 31271.
16-04-14 13:31:33: INFO: netdata: Not starting thread check.
16-04-14 13:31:33: INFO: netdata: Starting thread web.
16-04-14 13:31:33: INFO: netdata: PLUGINS.D thread created with task id 31272
16-04-14 13:31:33: INFO: netdata: WEB SERVER thread created with task id 31273
16-04-14 13:31:33: INFO: netdata: executing command: 'exec /usr/libexec/netdata/plugins.d/charts.d.plugin 1 ' on pid 31276.
16-04-14 13:31:33: INFO: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/apps.plugin' running on pid 31277
16-04-14 13:31:33: INFO: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/charts.d.plugin' running on pid 31276
16-04-14 13:31:33: INFO: netdata: executing command: 'exec /usr/libexec/netdata/plugins.d/apps.plugin 1 ' on pid 31277.
16-04-14 13:31:33: INFO: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/node.d.plugin' running on pid 31279
16-04-14 13:31:33: INFO: netdata: executing command: 'exec /usr/libexec/netdata/plugins.d/node.d.plugin 1 ' on pid 31279.
16-04-14 13:31:33: INFO: apps.plugin: Found NETDATA_HOST_PREFIX=''
16-04-14 13:31:33: INFO: apps.plugin: Found NETDATA_CONFIG_DIR='/etc/netdata'
16-04-14 13:31:33: INFO: apps.plugin: starting...
charts.d: started from '/usr/libexec/netdata/plugins.d/charts.d.plugin' with options: 1
charts.d: airsearches: configuration file '/etc/netdata/airsearches.conf' not found. Using defaults.
charts.d: airsearches: not configured. Please set airsearches_url='url' in /etc/netdata/airsearches.conf
charts.d: chart 'airsearches' check() function reports failure.
charts.d: apache: configuration file '/etc/netdata/apache.conf' not found. Using defaults.
apache: Invalid response or missing keys from apache server: <html>
 <head><title>404 Not Found</title></head>
 <body bgcolor="white">
 <center><h1>404 Not Found</h1></center>
 <hr><center>nginx/1.9.14</center>
 </body>
 </html>
apache: cannot find stub_status on URL 'http://127.0.0.1:80/server-status?auto'. Please set apache_url='http://apache.server:80/server-status?auto' in /etc/netdata/apache.conf
charts.d: chart 'apache' check() function reports failure.
charts.d: ap: configuration file '/etc/netdata/ap.conf' not found. Using defaults.
charts.d: chart 'ap' check() function reports failure.
charts.d: cpu_apps: configuration file '/etc/netdata/cpu_apps.conf' not found. Using defaults.
charts.d: cpu_apps: Please set cpu_apps_apps='command1 command2 ...' in /etc/netdata/cpu_apps_apps.conf
charts.d: chart 'cpu_apps' check() function reports failure.
charts.d: cpufreq: configuration file '/etc/netdata/cpufreq.conf' not found. Using defaults.
Thu Apr 14 2016 13:31:33 GMT+1000 (AEST): node.d.plugin: ERROR: Cannot read configuration file /etc/netdata/node.d.conf: ENOENT, no such file or directory '/etc/netdata/node.d.conf', using internal defaults.
Thu Apr 14 2016 13:31:33 GMT+1000 (AEST): node.d.plugin: ERROR: Cannot load module's snmp config from /etc/netdata/snmp.conf exception: Error: ENOENT, no such file or directory '/etc/netdata/snmp.conf', using internal defaults.
Thu Apr 14 2016 13:31:33 GMT+1000 (AEST): node.d.plugin: ERROR: Cannot load module's sma_webbox config from /etc/netdata/sma_webbox.conf exception: Error: ENOENT, no such file or directory '/etc/netdata/sma_webbox.conf', using internal defaults.
Thu Apr 14 2016 13:31:33 GMT+1000 (AEST): node.d.plugin: ERROR: Cannot load module's named config from /etc/netdata/named.conf exception: Error: ENOENT, no such file or directory '/etc/netdata/named.conf', using internal defaults.
charts.d: crsproxy: configuration file '/etc/netdata/crsproxy.conf' not found. Using defaults.
charts.d: crsproxy: not configured. Please set crsproxy_url='url' in /etc/netdata/crsproxy.conf
charts.d: chart 'crsproxy' check() function reports failure.
charts.d: example: configuration file '/etc/netdata/example.conf' not found. Using defaults.
charts.d: load_average: configuration file '/etc/netdata/load_average.conf' not found. Using defaults.
charts.d: chart 'load_average' check() function reports failure.
charts.d: mem_apps: configuration file '/etc/netdata/mem_apps.conf' not found. Using defaults.
charts.d: mem_apps: not configured. Please set mem_apps_apps='command1 command2 ...' in /etc/netdata/mem_apps_apps.conf
charts.d: chart 'mem_apps' check() function reports failure.
charts.d: mysql: configuration file '/etc/netdata/mysql.conf' not found. Using defaults.
charts.d: nginx: configuration file '/etc/netdata/nginx.conf' not found. Using defaults.
Thu Apr 14 2016 13:31:33 GMT+1000 (AEST): node.d.plugin: ERROR: named: local: Failed to make request: { protocol: 'http:',
  hostname: 'localhost',
  port: '8888',
  path: '/json/v1/server',
  method: 'GET',
  headers: 
   { 'Content-Type': 'application/x-www-form-urlencoded',
     Connection: 'keep-alive' },
  agent: 
   { domain: null,
     _events: { free: [Function] },
     _maxListeners: undefined,
     defaultPort: 80,
     protocol: 'http:',
     options: 
      { maxFreeSockets: 1,
        maxSockets: 2,
        keepAliveMsecs: 1000,
        keepAlive: true,
        path: null },
     requests: {},
     sockets: 
      { 'localhost:8888::': 
         [ { _connecting: false,
             _hadError: false,
             _handle: null,
             _parent: null,
             _host: 'localhost',
             _readableState: 
              { objectMode: false,
                highWaterMark: 16384,
                buffer: [],
                length: 0,
                pipes: null,
                pipesCount: 0,
                flowing: true,
                ended: false,
                endEmitted: false,
                reading: true,
                sync: false,
                needReadable: true,
                emittedReadable: false,
                readableListening: false,
                defaultEncoding: 'utf8',
                ranOut: false,
                awaitDrain: 0,
                readingMore: false,
                decoder: null,
                encoding: null,
                resumeScheduled: false },
             readable: false,
             domain: null,
             _events: 
              { end: 
                 [ { [Function: g] listener: [Function: onend] },
                   [Function: socketOnEnd] ],
                finish: [Function: onSocketFinish],
                _socketEnd: [Function: onSocketEnd],
                free: [Function: onFree],
                close: [ [Function: onClose], [Function: socketCloseListener] ],
                agentRemove: [Function: onRemove],
                drain: [Function: ondrain],
                error: [Function: socketErrorListener],
                data: [Function: socketOnData],
                connect: 
                 [ { [Function: g] listener: [Function] },
                   { [Function: g] listener: [Function] } ] },
             _maxListeners: undefined,
             _writableState: 
              { objectMode: false,
                highWaterMark: 16384,
                needDrain: false,
                ending: false,
                ended: false,
                finished: false,
                decodeStrings: false,
                defaultEncoding: 'utf8',
                length: 127,
                writing: true,
                corked: 0,
                sync: false,
                bufferProcessing: false,
                onwrite: [Function],
                writecb: [Function: finish],
                writelen: 127,
                bufferedRequest: null,
                lastBufferedRequest: null,
                pendingcb: 1,
                prefinished: false,
                errorEmitted: true },
             writable: false,
             allowHalfOpen: false,
             destroyed: true,
             bytesRead: 0,
             _bytesDispatched: 0,
             _pendingData: 'GET /json/v1/server HTTP/1.1\r\nContent-Type: application/x-www-form-urlencoded\r\nConnection: keep-alive\r\nHost: localhost:8888\r\n\r\n',
             _pendingEncoding: 'binary',
             parser: 
              { '0': [Function: parserOnHeaders],
                '1': [Function: parserOnHeadersComplete],
                '2': [Function: parserOnBody],
                '3': [Function: parserOnMessageComplete],
                _headers: [],
                _url: '',
                socket: [Circular],
                incoming: null,
                maxHeaderPairs: 2000,
                onIncoming: [Function: parserOnIncomingClient] },
             _httpMessage: 
              { domain: null,
                _events: 
                 { response: { [Function: g] listener: [Function] },
                   error: [Function] },
                _maxListeners: undefined,
                output: [],
                outputEncodings: [],
                outputCallbacks: [],
                writable: true,
                _last: true,
                chunkedEncoding: false,
                shouldKeepAlive: true,
                useChunkedEncodingByDefault: false,
                sendDate: false,
                _removedHeader: { connection: false },
                _hasBody: true,
                _trailer: '',
                finished: true,
                _hangupClose: false,
                _headerSent: true,
                socket: [Circular],
                connection: [Circular],
                _header: 'GET /json/v1/server HTTP/1.1\r\nContent-Type: application/x-www-form-urlencoded\r\nConnection: keep-alive\r\nHost: localhost:8888\r\n\r\n',
                _headers: 
                 { 'content-type': 'application/x-www-form-urlencoded',
                   connection: 'keep-alive',
                   host: 'localhost:8888' },
                _headerNames: 
                 { 'content-type': 'Content-Type',
                   connection: 'Connection',
                   host: 'Host' },
                agent: [Circular],
                socketPath: undefined,
                method: 'GET',
                path: '/json/v1/server',
                parser: 
                 { '0': [Function: parserOnHeaders],
                   '1': [Function: parserOnHeadersComplete],
                   '2': [Function: parserOnBody],
                   '3': [Function: parserOnMessageComplete],
                   _headers: [],
                   _url: '',
                   socket: [Circular],
                   incoming: null,
                   maxHeaderPairs: 2000,
                   onIncoming: [Function: parserOnIncomingClient] } },
             read: [Function],
             _consuming: true,
             _idleNext: null,
             _idlePrev: null,
             _idleTimeout: -1 } ] },
     freeSockets: {},
     keepAliveMsecs: 1000,
     keepAlive: true,
     maxSockets: 2,
     maxFreeSockets: 1 } }, message: connect ECONNREFUSED
nginx: Invalid response from nginx server: <html>
 <head><title>404 Not Found</title></head>
 <body bgcolor="white">
 <center><h1>404 Not Found</h1></center>
 <hr><center>nginx/1.9.14</center>
 </body>
 </html>
nginx: cannot find stub_status on URL 'http://127.0.0.1:80/stub_status'. Please set nginx_url='http://nginx.server/stub_status' in /etc/netdata/nginx.conf
charts.d: chart 'nginx' check() function reports failure.
charts.d: nut: configuration file '/etc/netdata/nut.conf' not found. Using defaults.
charts.d: ERROR: Command 'upsc' is not found in the system path.
charts.d: chart 'nut' check() function reports failure.
charts.d: opensips: configuration file '/etc/netdata/opensips.conf' not found. Using defaults.
charts.d: ERROR: Command 'opensipsctl' is not found in the system path.
charts.d: chart 'opensips' check() function reports failure.
charts.d: postfix: configuration file '/etc/netdata/postfix.conf' not found. Using defaults.
charts.d: postfix: cannot find postqueue. Please set 'postfix_postqueue=/path/to/postqueue' in /etc/netdata/postfix.conf
charts.d: chart 'postfix' check() function reports failure.
charts.d: sensors: configuration file '/etc/netdata/sensors.conf' not found. Using defaults.
charts.d: squid: configuration file '/etc/netdata/squid.conf' not found. Using defaults.
charts.d: ERROR: Command 'squidclient' is not found in the system path.
charts.d: chart 'squid' check() function reports failure.
charts.d: cpufreq: on file='/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq', dir='/sys/devices/system/cpu/cpu0/cpufreq', cpu='0', id='cpu0'
charts.d: cpufreq: on file='/sys/devices/system/cpu/cpu1/cpufreq/scaling_cur_freq', dir='/sys/devices/system/cpu/cpu1/cpufreq', cpu='1', id='cpu1'
charts.d: cpufreq: on file='/sys/devices/system/cpu/cpu2/cpufreq/scaling_cur_freq', dir='/sys/devices/system/cpu/cpu2/cpufreq', cpu='2', id='cpu2'
charts.d: cpufreq: on file='/sys/devices/system/cpu/cpu3/cpufreq/scaling_cur_freq', dir='/sys/devices/system/cpu/cpu3/cpufreq', cpu='3', id='cpu3'
charts.d: cpufreq: on file='/sys/devices/system/cpu/cpu4/cpufreq/scaling_cur_freq', dir='/sys/devices/system/cpu/cpu4/cpufreq', cpu='4', id='cpu4'
charts.d: cpufreq: on file='/sys/devices/system/cpu/cpu5/cpufreq/scaling_cur_freq', dir='/sys/devices/system/cpu/cpu5/cpufreq', cpu='5', id='cpu5'
charts.d: cpufreq: on file='/sys/devices/system/cpu/cpu6/cpufreq/scaling_cur_freq', dir='/sys/devices/system/cpu/cpu6/cpufreq', cpu='6', id='cpu6'
charts.d: cpufreq: on file='/sys/devices/system/cpu/cpu7/cpufreq/scaling_cur_freq', dir='/sys/devices/system/cpu/cpu7/cpufreq', cpu='7', id='cpu7'
charts.d: sensors: on path='/sys/devices/platform/coretemp.0/hwmon/hwmon2', dir='hwmon2', device='coretemp.0', subsystem='hwmon', id='coretemp_0_hwmon_hwmon2', name='coretemp'
16-04-14 13:31:34: ERROR: apps.plugin: Cannot process /proc/31672/stat (errno 2, No such file or directory)
16-04-14 13:31:34: ERROR: netdata: PROCFILE: Cannot open file '/proc/net/stat/nf_conntrack' (errno 2, No such file or directory)
16-04-14 13:31:34: ERROR: netdata: PROCFILE: Cannot open file '/proc/net/ip_vs_stats' (errno 2, No such file or directory)
16-04-14 13:31:34: ERROR: netdata: PROCFILE: Cannot open file '/proc/net/stat/synproxy' (errno 2, No such file or directory)
16-04-14 13:31:34: INFO: netdata: Disabling /proc/net/rpc/nfsd threads histogram. It seems unused on this machine. It will be enabled automatically when found with data in it.
16-04-14 13:31:34: INFO: netdata: Disabling /proc/net/rpc/nfsd read ahead histogram. It seems unused on this machine. It will be enabled automatically when found with data in it.
16-04-14 13:31:34: INFO: netdata: Disabling /proc/net/rpc/nfsd v4 operations chart. It seems unused on this machine. It will be enabled automatically when found with data in it.
charts.d: sensors: on path='/sys/devices/virtual/hwmon/hwmon0', dir='hwmon0', device='hwmon0', subsystem='hwmon', id='hwmon0_hwmon_hwmon0', name='acpitz'
charts.d: sensors: on path='/sys/devices/virtual/hwmon/hwmon1', dir='hwmon1', device='hwmon1', subsystem='hwmon', id='hwmon1_hwmon_hwmon1', name='i8k'
16-04-14 13:31:34: ERROR: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/node.d.plugin' called DISABLE. Disabling it.
16-04-14 13:31:34: INFO: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/node.d.plugin' on pid 31279 stopped.
16-04-14 13:31:34: ERROR: netdata: pid 31279 killed by signal 15.
charts.d: sensors: on path='/sys/devices/virtual/thermal/thermal_zone0', dir='thermal_zone0', device='LNXTHERM:00', subsystem='thermal', id='lnxtherm_00_thermal_thermal_zone0', name='thermal_zone0'
charts.d: sensors: on path='/sys/devices/virtual/thermal/thermal_zone1', dir='thermal_zone1', device='LNXTHERM:01', subsystem='thermal', id='lnxtherm_01_thermal_thermal_zone1', name='thermal_zone1'
charts.d: sensors: on path='/sys/devices/virtual/thermal/thermal_zone2', dir='thermal_zone2', device='thermal_zone2', subsystem='thermal', id='thermal_zone2_thermal_thermal_zone2', name='thermal_zone2'
16-04-14 13:31:59: INFO: netdata: Signaled exit (signal 15). (errno 22, Invalid argument)
16-04-14 13:31:59: INFO: netdata: NetData exiting. Bye bye...
/usr/libexec/netdata/plugins.d/charts.d.plugin: line 457: cd: write error: Broken pipe
```

**Comment by ktsaou** [comment] 2016-04-14 07:20
Your netdata has been killed.
All the above errors are just auto-detection failures. They are normal logs stating that certain services that netdata is capable to monitor, were not found running on your system.

The only problem is:

```
16-04-14 13:31:34: ERROR: netdata: pid 31279 killed by signal 15.
```

Signal 15 is the TERM signal. Someone killed it.

If you start it, it will again do the same?

**Comment by ktsaou** [comment] 2016-04-14 07:28
> I thought I would check this out today (it looks fantastic by the way!), install was smooth but immediately after the install my system became really choppy (I am listening to music at the same time - this kept cutting in and out (Pulseaudio), the mouse and keyboard become really unresponsive, it feels as if there is a huge load on the system but top shows nothing out of the ordinary.

Did you see something that pointed netdata as the offending process for the load?

Does it happen again when you start netdata?

**Comment by voycey** [comment] 2016-04-14 10:26
I thought that part would have been obvious - that was me killing the process after the system instability - not any failure of the process - it continues to run until I kill it and the instability occurs until I kill it!

There is a direct relationship between the starting of netdata and the system instability, and once killed everything goes back to normal :)

**Comment by ktsaou** [comment] 2016-04-14 10:38
ok. There is something wrong though. What you describe is not normal.

The problem appears when you view the dashboard or always?
So, close the browser and start netdata. Does it still appear?

If not, the problem is your browser. Please open the `settings` of the dashboard with your browser and set in the `Synchronization` tab the setting `Which chart refresh policy to use?` to `Sequential`.
Does the problem still appear?

If the problem is gone, you computer might be too slow or you are facing an issue with your graphics card drivers.

**Comment by voycey** [comment] 2016-04-14 10:41
Just to give another example of how this affects it - a clean reboot and the following:

As this seems video related in this case (and I would say its a possibility this is the case considering top shows no high load on the system), I thought I would test with glxgears to produce a framerate value:

```
dan@dan-linux ~ $ sudo netdata
[sudo] password for dan: 
16-04-14 20:33:03: INFO: netdata: Listening on all IPs (IPv6 and IPv4)
dan@dan-linux ~ $ glxgears 
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
158 frames in 5.0 seconds = 31.512 FPS
155 frames in 5.0 seconds = 30.903 FPS
156 frames in 5.1 seconds = 30.873 FPS
^C
dan@dan-linux ~ $ sudo killall -9 netdata
dan@dan-linux ~ $ glxgears 
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
302 frames in 5.0 seconds = 60.281 FPS
300 frames in 5.0 seconds = 59.815 FPS
300 frames in 5.0 seconds = 59.816 FPS
^C
````

My system is running the intel i915 drivers for normal usage but has the optimus option using the nvidia discrete card:

```
dan@dan-linux ~ $ sudo lshw -c video
  *-display               
       description: VGA compatible controller
       product: GF108M [GeForce GT 540M]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:16 memory:f0000000-f0ffffff memory:c0000000-cfffffff memory:d0000000-d1ffffff ioport:3000(size=128) memory:f1000000-f107ffff
  *-display
       description: VGA compatible controller
       product: 2nd Generation Core Processor Family Integrated Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 09
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:35 memory:f1400000-f17fffff memory:e0000000-efffffff ioport:4000(size=64)
```

Hope someone else can replicate this and it gets fixed as I wouldnt be comfortable installing this on a production system until I can replicate clean usage on a local machine!

**Comment by voycey** [comment] 2016-04-14 10:42
@ktsaou - this issue happens as soon as I start netdata (see above) - I haven't opened the browser window at this point!

**Comment by ktsaou** [comment] 2016-04-14 10:51
ok, let's do a test.

open `/etc/netdata/netdata.conf` and set `update every = 30` in the `[global]` section.
Does it still happen?

**Comment by voycey** [comment] 2016-04-14 10:56
I can feel when it updates - everything freezes for about a second, you can see the delays below with glxgears at regular intervals that match up with the 30 seconds above:

```
dan@dan-linux ~ $ sudo netdata && glxgears
16-04-14 20:53:08: INFO: netdata: Listening on all IPs (IPv6 and IPv4)
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
273 frames in 5.0 seconds = 54.585 FPS
300 frames in 5.0 seconds = 59.812 FPS
300 frames in 5.0 seconds = 59.815 FPS
300 frames in 5.0 seconds = 59.811 FPS
271 frames in 5.0 seconds = 54.033 FPS
300 frames in 5.0 seconds = 59.815 FPS
300 frames in 5.0 seconds = 59.812 FPS
300 frames in 5.0 seconds = 59.818 FPS
300 frames in 5.0 seconds = 59.814 FPS
300 frames in 5.0 seconds = 59.815 FPS
271 frames in 5.0 seconds = 54.031 FPS
300 frames in 5.0 seconds = 59.814 FPS
300 frames in 5.0 seconds = 59.817 FPS
300 frames in 5.0 seconds = 59.812 FPS
300 frames in 5.0 seconds = 59.817 FPS
300 frames in 5.0 seconds = 59.814 FPS
271 frames in 5.0 seconds = 54.029 FPS
300 frames in 5.0 seconds = 59.815 FPS
```

**Comment by ktsaou** [comment] 2016-04-14 11:01
ok. Still in `/etc/netdata/netdata.conf`, let's find what causes this.

My plugins section is this:

```
[plugins]
	# tc = yes
	# idlejitter = yes
	# proc = yes
	# checks = no
	# plugins directory = /opt/netdata/usr/libexec/netdata/plugins.d
	# enable running new plugins = yes
	# check for new plugins every = 60
	# charts.d = yes
	# sma_webbox = yes
	# apps = yes
	# node.d = yes
```

Disable all except the `proc` one. Does it still happen?

The `proc` one is inside the daemon itself. You can enable/disable individual modules of it, using this section:

```
[plugin:proc]
	# /proc/net/dev = yes
	# /proc/diskstats = yes
	# /proc/net/snmp = yes
	# /proc/net/snmp6 = yes
	# /proc/net/netstat = yes
	# /proc/net/stat/conntrack = yes
	# /proc/net/ip_vs/stats = yes
	# /proc/net/stat/synproxy = yes
	# /proc/stat = yes
	# /proc/meminfo = yes
	# /proc/vmstat = yes
	# /proc/net/rpc/nfsd = yes
	# /proc/sys/kernel/random/entropy_avail = yes
	# /proc/interrupts = yes
	# /proc/softirqs = yes
	# /proc/loadavg = yes
	# /sys/kernel/mm/ksm = yes
	# netdata server resources = yes
```

Can you do a few try and fail tests to identify which one is causing the problem?

**Comment by voycey** [comment] 2016-04-14 11:04
Do I just need to uncomment them or set them to = no? Not sure what the defaults are here?

**Comment by ktsaou** [comment] 2016-04-14 11:04
both. uncomment and set to `no`.

**Comment by voycey** [comment] 2016-04-14 11:06
Ok cool - ill go through them all and see if I can figure out which is causing it! Thanks!

**Comment by ktsaou** [comment] 2016-04-14 11:08
If it is a `proc` one, stop netdata, open your fps test and do this:

```
cat FILE
```

where `FILE` is the `proc` file you found as the root cause.
It should happen too, without netdata running.

**Comment by voycey** [comment] 2016-04-14 11:10
Well I just started off with setting all of the items under `[plugin:proc]` to be uncommented and = no and the problem is still occurring - so I would say the issue isnt there unless you have a reason why them all being disabled might cause some other weirdness?

**Comment by ktsaou** [comment] 2016-04-14 11:12
and all `[plugins]` set to no?

**Comment by ktsaou** [comment] 2016-04-14 11:12
I am entering a meeting, I'll be able to help you more in 2 hours...

**Comment by voycey** [comment] 2016-04-14 11:14
With all plugins disabled everything works fine - no freezing - ill go through the plugins and see which one is causing it!

**Comment by voycey** [comment] 2016-04-14 11:17
```
[plugins]
     tc = yes
     idlejitter = yes
     proc = yes
     checks = yes
     plugins directory = /opt/netdata/usr/libexec/netdata/plugins.d
     enable running new plugins = yes
     check for new plugins every = 60
     charts.d = yes
     sma_webbox = yes
     apps = yes
     node.d = yes
```

The above config works (e.g. uncommenting everything and setting it to yes)

However:

```
[plugins]
     #tc = yes
     #idlejitter = yes
     #proc = yes
     #checks = yes
     #plugins directory = /opt/netdata/usr/libexec/netdata/plugins.d
     #enable running new plugins = yes
     #check for new plugins every = 60
     #charts.d = yes
     #sma_webbox = yes
     #apps = yes
     #node.d = yes
```

The problem recurs

**Comment by ktsaou** [comment] 2016-04-14 12:45
ok, can you please "try and fail" commenting/commenting until you find which one?

**Comment by voycey** [comment] 2016-04-14 12:58
I dont think you understand what happened above, everything enabled works fine, everything commented doesnt. that means there is something not affected by this config that is causing this problem!

**Comment by ktsaou** [comment] 2016-04-14 13:18
If you repeat commenting / uncommenting, like the last time, do you get exactly the same results? i.e. enabled = ok, commented = problematic? If yes, then this config affects it.

In general, when you disable all plugins, including the `proc`, netdata does not have anything to do. It will just sit there, completely idle. If you experience this problem when all plugins are disabled (= `no`), then the problem is something unrelated to netdata.

I just did this on mine:

```
[plugins]
        tc = no
        idlejitter = no
        proc = no
        checks = no
        plugins directory = /usr/libexec/netdata/plugins.d
        enable running new plugins = no
        check for new plugins every = 60
        charts.d = no
        node.d = no
        apps = no
```

and let's see the charts:
```
# curl http://127.0.0.1:19999/api/v1/charts
{
        "hostname": "box",
        "update_every": 1,
        "history": 28800,
        "charts": {
        }
}
```

So, no charts. netdata is started but is totally idle. This cannot do anything to your system. It is just a program waiting idle and doing nothing. Its web server is running, but if you don't send it commands, it will do nothing.

Then, enable the `proc` plugin and only the first collector `/proc/net/dev`, like this:

```
[plugins]
        tc = no
        idlejitter = no
        proc = yes
        checks = no
        plugins directory = /usr/libexec/netdata/plugins.d
        enable running new plugins = no
        check for new plugins every = 60
        charts.d = no
        node.d = no
        apps = no

[plugin:proc]
        /proc/net/dev = yes
        /proc/diskstats = no
        /proc/net/snmp = no
        /proc/net/snmp6 = no
        /proc/net/netstat = no
        /proc/net/stat/conntrack = no
        /proc/net/ip_vs/stats = no
        /proc/net/stat/synproxy = no
        /proc/stat = no
        /proc/meminfo = no
        /proc/vmstat = no
        /proc/net/rpc/nfsd = no
        /proc/sys/kernel/random/entropy_avail = no
        /proc/interrupts = no
        /proc/softirqs = no
        /proc/loadavg = no
        /sys/kernel/mm/ksm = no
        netdata server resources = no
```

Now, if you execute the same `curl` command, you will see only network interface charts.

Leave it running. Do you experience any issues? If no, add another collector and so on. If something related to netdata triggers your issue, you will be able at some point find it.

**Comment by voycey** [comment] 2016-04-14 14:20
charts.d seems to be the culprit about these freezes, at least by enabling them from the bottom up! 

I copied your configuration and then started from apps up until charts.d (restarting each time), as soon as charts.d is enabled it freezes the system! 

Any further ideas?

**Comment by ktsaou** [comment] 2016-04-14 15:39
This is even more interesting. charts.d is just a bash script.

If you enable it and the dashboard is usable, you can go to the "Netdata Monitoring" section, "charts.d" subsection. There you will be able to find timings per charts.d module. Which one is the bigger.

Alternatively you can do this:

```sh
/usr/libexec/netdata/plugins/charts.d.plugin debug 10
```

Ignore the first loop (too many auto-detection errors), focus on the second iteration.
If you can figure which one freezes it, you can run it like that too:

```sh
/usr/libexec/netdata/plugins/charts.d.plugin debug 10 postfix
```

where `postfix` is the plugin you want to test.

**Comment by voycey** [comment] 2016-04-15 05:42
I believe it is the `sensors` plugin that is causing the freezes

If I do:

```
/usr/libexec/netdata/plugins.d/charts.d.plugin debug 10 sensors
```

I get the expected freezes

If I do:

```
/usr/libexec/netdata/plugins.d/charts.d.plugin debug 10 cpufreq
```

No problem!

**Comment by ktsaou** [comment] 2016-04-15 08:32
ok. then something is happening with your sensors drivers. If you disable the sensors module (by editing `/etc/netdata/charts.d.conf` and setting `sensors = no`, is everything working as expected?

**Comment by voycey** [comment] 2016-04-15 08:42
Yep thanks! Why would sensor drivers be freezing I guess is the next step... It might be worth spinning up a VM of Mint 17.3 on a fresh install and seeing if it happens then, if so then its possibly an incompatibility but I dont see any problems through daily usage of it.

**Comment by ktsaou** [comment] 2016-04-15 08:44
> I dont see any problems through daily usage of it.

Probably netdata was the first you use that actually reads them regularly and frequently.

**Comment by voycey** [comment] 2016-04-15 08:45
Quite possibly! Ill investigate! thanks for the walk through :)

**Comment by ktsaou** [comment] 2016-04-15 08:53
Ok. I close this.

**Closed by ktsaou** 2016-04-15 08:53 UTC
