### ISSUE TITLE
sensors value from same sensor is group into same type

### ISSUE THREAD

**Issue by xuefer** [firehol/netdata#918] opened 2016-09-08 19:12 UTC
```
# sensors
it8712-isa-0a10
Adapter: ISA adapter
in0:          +0.98 V  (min =  +0.00 V, max =  +4.08 V)
in1:          +1.89 V  (min =  +0.00 V, max =  +4.08 V)
in2:          +3.25 V  (min =  +0.00 V, max =  +4.08 V)
+5V:          +2.91 V  (min =  +3.57 V, max =  +4.08 V)  ALARM
in4:          +3.02 V  (min =  +0.00 V, max =  +4.08 V)
in5:          +1.49 V  (min =  +0.00 V, max =  +4.08 V)
in6:          +1.06 V  (min =  +0.00 V, max =  +4.08 V)
5VSB:         +2.67 V  (min =  +0.00 V, max =  +4.08 V)
Vbat:         +3.23 V
fan1:        1650 RPM  (min =    0 RPM)
fan2:           0 RPM  (min =    0 RPM)
fan3:           0 RPM  (min =    0 RPM)
temp1:        +25.0 C  (low  =  -1.0 C, high = +127.0 C)  sensor = thermal diode
temp2:       -128.0 C  (low  =  -1.0 C, high = +127.0 C)  sensor = disabled
temp3:        +86.0 C  (low  =  -1.0 C, high = +127.0 C)  sensor = thermal diode
cpu0_vid:    +0.000 V
intrusion0:  ALARM
```
multiple types of value is populated from a single sensor, but netdata shows everything as temperature
simple fix: remove prev_chip check

**Comment by ktsaou** [comment] 2016-09-09 14:07
@paulfantom please check this too.

**Comment by paulfantom** [comment] 2016-09-09 17:27
@xuefer can you append a screenshot so I can have better understanding of this issue?

**Comment by xuefer** [comment] 2016-09-09 17:42
![qq 20160910013833](https://cloud.githubusercontent.com/assets/1741312/18396641/56fc84b8-76f7-11e6-93f5-5501ffc1d735.png)

bug reproduce only if there is only 1 sensor. with 2 sensors bug is not reproduced

**Comment by xuefer** [comment] 2016-09-09 17:46
simply remove "if chip_name != prev_chip" fix the problem
"name = chip_name + "_" + TYPE_MAP[feature.type]" should be always executed as it's a new name for new value

**Comment by ktsaou** [comment] 2016-09-20 20:50
Based on the image, the only fault I see is the y-scale. It says 600000 Celsius degrees, which of course is wrong!

So, what @xuefer is saying is that by removing this line: https://github.com/firehol/netdata/blob/3294c3db55012477a51e5fc2baf4f2c50c3b47e7/python.d/sensors.chart.py#L108

the problem is fixed, because the line after that, should always be executed.

@paulfantom can you help?

**Comment by xuefer** [comment] 2016-09-20 23:25
actually they are two problems. the 600000 Celsius degrees is another thing, it's the issue of motherboard
removing that line fix the other problem in the image

how could possibly a +5V being temperature? same applies in0 ~ in8 (some not shown in the mage). these are voltages while fan1 is the RPM speed. they're not temperature

**Comment by xuefer** [comment] 2016-09-21 01:06
i just created a pull request at https://github.com/firehol/netdata/pull/995

**Comment by ktsaou** [comment] 2016-10-11 10:47
is this fixed?

**Comment by ktsaou** [comment] 2016-10-11 10:48
I see it is merged. I am closing this.

**Closed by ktsaou** 2016-10-11 10:48 UTC
Labels: bug, fixed
