### ISSUE TITLE
allow screen updates at non-default zoom

### ISSUE THREAD

**Issue by thinrope** [firehol/netdata#1124] opened 2016-10-16 08:18 UTC
I was under the impression that this works, but after some testing it does not...

When I zoom out the dashboard (from the `+/-` control or Shift+Wheel), the screen stops updating. I guess that is for performance reasons, but it is useful to be able to look at graphs, say zoomed out 5 times, being updated once every 5 s. Of course that should only work when scroll is at right most.

Or is it supposed to be working like that and I am seeing a local bug?

To trigger: press `-` (a few times), then press `>>` (to go to present)

**Comment by ktsaou** [comment] 2016-10-16 10:10
When you pan or zoom the charts, automatic refreshing stops. This is by design.

When the dashboard starts, it calculates the maximum visible duration of the charts by giving 3 pixels width per point and per second refreshes.

If you start full screen and then resize the window horizontally, the dashboard will request from the netdata server to reduce the data (i.e. combine several points together), maintaining 3 pixes per point, the same visible duration, but lower update frequency (it will still have auto-refreshing on, but at a lower rate - since it would be meaningless to do shorter updates).

What would be nice, is a global menu to set the visible duration of the charts, e.g. `auto` (the one we have now), `5min`, `10min`, `15min`, `30min`, `1hour`, etc in auto-refreshing mode.

**Comment by thinrope** [comment] 2016-10-16 16:52
Hmm... I started a 8K px wide browser to experiment, but it made 2 columns instead :-|
Actually (wildly) resizing the window, things really get badly layout. May be a `more than X` resize should trigger a full reload.

I agree with the fixed duration, saw it on the old dashboard, but that is still not dynamic zoom.
But if that 3px/pt is being calculated anyway, it is just a matter of having it as a parameter. I looked at index.html, but failed to find the code that does it, sorry.

All in all, I think we are back to #1115 :-) to be able to control the update independently.

**Comment by thinrope** [comment] 2016-10-16 17:15
Taking screenshots outside the viewport didn't work, but this is the `after` status when I resized from 8K wide to 4K. It kept the two columns instead of switching to one (the way it looks if loaded in full screen @4K). The black square is to cover some other tabs, not artefact, ignore.

![8k_to_4k](https://cloud.githubusercontent.com/assets/754020/19419280/3c920ea6-940f-11e6-804b-9b6d4a22863e.png)

**Comment by ktsaou** [comment] 2016-10-16 17:33
wow! Can you check if the white theme does this too? I haven't set a limit on the width of the screen, so I suspect this is related to the theme.

**Comment by thinrope** [comment] 2016-10-16 18:07
Here you are, I guess it is the same. This time I resized it even tighter...
There is an issue with calculating whitespace (border/padding?), may be you use % of screen? So for a big (8Kx2K) screen this is really off. I see tiny graphs with lots of space to the right (like the previous picture), basically the screen feels really empty.

![test2](https://cloud.githubusercontent.com/assets/754020/19419529/8a4fd9a2-9414-11e6-886a-4344b05eead7.png)
![test3](https://cloud.githubusercontent.com/assets/754020/19419530/8a6783a4-9414-11e6-9f00-9b9679be12c7.png)

Also, to have 1 column in fullscreen at 4K, I need min 125% zoom. 100% zoom feels really bad with 2 columns and 4 apparent columns of graphs, but most of it empty to the right since there is only one or two graphs in the bunch.
E.g. I have one NIC, so it has badwith and packets and drops, so it shows like (X is white space):
lan0
B P |  X X
D X | X X

In the above cases reloading the page fixes it.

I know it is a daunting task, but may be some better algorithm for multi-column layout is needed. BTW, `tv.html` has no big issues, since it is hard-fixed to 2 columns.

**Comment by ktsaou** [comment] 2016-10-16 18:14
This is very strange... I am trying to figure out a way to get my hands on such a resolution to fix it...

This seems to be purely CSS related.

For resolutions above 1360px wide, this is used: https://github.com/firehol/netdata/blob/a8f637780fb4debe91931b8635ec519ffb18a057/web/index.html#L368-L390

As you can see here, all containers are 100% wide (minus a little): https://github.com/firehol/netdata/blob/a8f637780fb4debe91931b8635ec519ffb18a057/web/index.html#L277-L279

So, what I see on these pictures is not what it is configured. Either bootstrap has some kind of settings I am not aware of, or... I don't know...

**Comment by ktsaou** [comment] 2016-10-16 18:31
Can you get this screenshot for me?

To get there, select the text "cpu", right click and select "inspect". Then select this div:

```
<div class="charts-body" role="main">
```

What I need is the blue highlight and the bottom right inspection window.

![image](https://cloud.githubusercontent.com/assets/2662304/19419769/6cfd461e-93e7-11e6-9145-317f8cfaac33.png)

**Comment by thinrope** [comment] 2016-10-16 18:50
All the testing was in Chrome/53 BTW. I just tested in in FF/49 and found out it can resize the window even beyond 8K width; when reloaded in that huge window, the gauges are huge and the graphs are tiny. At at about 16Kx2K FF freezes even with a blank window :-|

Here is the screenshot you asked for
![test4](https://cloud.githubusercontent.com/assets/754020/19419879/7a633eec-941b-11e6-856e-c10d847303d5.png)

**Comment by ktsaou** [comment] 2016-10-16 19:18
oops! the browser believes this resolution is 992px wide!

**Comment by ktsaou** [comment] 2016-10-16 19:19
If you compare the resolutions of my screenshot and your screenshot you will see the difference...

**Comment by ktsaou** [comment] 2017-02-04 21:45
Have you managed to solve this?
I have a few such screens now and I tested netdata. I can't reproduce this issue.

I am closing this now, but if you still have the issue and you believe it is a netdata fault, please post here to help us identify the issue and fix it.

**Closed by ktsaou** 2017-02-04 21:45 UTC
Labels: question

**Comment by ktsaou** [comment] 2017-02-15 18:00
found the problem and solved it in #1795
