### ISSUE TITLE
SNMP: Corrupted 64bit counters

### ISSUE THREAD

**Issue by LapsusAntepedis** [firehol/netdata#2362] opened 2017-06-19 14:48 UTC
Hello!

I'm having some issues with getting netdata to get anything sane out of the snmp plugin.
My /opt/netdata/etc/netdata/node.d/snmp.conf is nearly the same as the example listed in the wiki, but changed to the appropriate OIDs for my router.

snmp.conf: https://gist.github.com/LapsusAntepedis/55cb09795a734e1e8c8dc061ef735342

Running `node.d.plugin 1 snmp debug` shows that it is getting the data as a buffer, which I think is correct, but then whatever is recieving that value isn't handling it properly.

```
2017-06-19 16:34:14: node.d.plugin: DEBUG: snmp: 172.16.0.1: got valid snmp response: [ { oid: '1.3.6.1.2.1.31.1.1.1.10.1',
    type: 70,
    value: <Buffer 33 18 72 ac 4e> },
  { oid: '1.3.6.1.2.1.31.1.1.1.6.1',
    type: 70,
    value: <Buffer 00 af ab e2 35 d7> } ]
2017-06-19 16:34:14: node.d.plugin: DEBUG: snmp: 172.16.0.1: found snmp value of OIDs 1.3.6.1.2.1.31.1.1.1.10.1 = 3r�N
2017-06-19 16:34:14: node.d.plugin: DEBUG: snmp: 172.16.0.1: found snmp value of OIDs 1.3.6.1.2.1.31.1.1.1.6.1 = ���5�
2017-06-19 16:34:14: node.d.plugin: DEBUG: snmp: 172.16.0.1: finished snmp with 2 successful and 0 failed values
2017-06-19 16:34:14: node.d.plugin: DEBUG: snmp: 172.16.0.1: processing snmp response (received in 72 ms)
2017-06-19 16:34:14: node.d.plugin: DEBUG: snmp: 172.16.0.1: service committed.
```

The full output from that command is here: https://gist.github.com/LapsusAntepedis/b063c9cdeb4c17edce17de1d06471232

And this is what it's looking like in netdata
![capture](https://user-images.githubusercontent.com/3533890/27290911-ed8500ea-550e-11e7-9f49-c84160a7dcda.PNG)

I've found a couple similar issues on the issue tracker via google, but none of them ever seemed to figure out what was going wrong. If you've got any ideas on how I can get this working, I'd love to hear them, and thank you for your time.

**Comment by ktsaou** [comment] 2017-06-19 23:25
Could you please the snmp plugin by hand and post here the output?

```sh
# become user netdata
sudo su -s /bin/bash netdata

# run the SNMP plugin by hand
/usr/libexec/netdata/plugins.d/node.d.plugin debug 1 snmp
```

**Comment by LapsusAntepedis** [comment] 2017-06-20 07:35
I don't think it's changed much from the last time I've run it, but maybe running it as the netdata user makes it behave differently. Here's the output from running the debug command as netdata.

https://gist.github.com/LapsusAntepedis/f404560ec4917b063da369476971fb02

**Comment by ktsaou** [comment] 2017-06-20 20:17
ok, can you fetch the same OIDs with `snmpget`?

I have to admit though that this is a bit strange. From the output you posted I see the SNMP response from the switch is an 64 bit value (5 or 6 bytes), and [at the netdata code](https://github.com/firehol/netdata/blob/640a02cd22cbd032cd4af6d7b30793f5f84c5f87/node.d/node_modules/netdata.js#L368-L371) I see that it handles this case properly.

From the code I only suspect this condition: https://github.com/firehol/netdata/blob/640a02cd22cbd032cd4af6d7b30793f5f84c5f87/node.d/snmp.node.js#L275

Could you please change this line from:

```js
if(varbinds[i].type === net_snmp.ObjectType.OctetString && service.snmp_oids_index[varbinds[i].oid].type !== 'title')
```

to

```js
if(varbinds[i].type === net_snmp.ObjectType.OctetString && service.snmp_oids_index[varbinds[i].oid].type !== 'title' && !(varbinds[i].value instanceof Buffer))
```

You can edit `/usr/libexec/netdata/node.d/snmp.node.js`, at line 275.

**Comment by ktsaou** [comment] 2017-06-20 20:39
The change above works for me (for 32 bit SNMP). So, please check it on 64 bit SNMP.

**Comment by LapsusAntepedis** [comment] 2017-06-21 15:14
Sorry about the delay, it's been a little busy.
I can indeed get the same OIDs with snmpget.
`
testing@MT-Netdata:~$ snmpget -v 1 -c testing 172.16.0.1 1.3.6.1.2.1.31.1.1.1.6.1
iso.3.6.1.2.1.31.1.1.1.6.1 = Counter64: 781020803050
testing@MT-Netdata:~$ snmpget -v 1 -c testing 172.16.0.1 1.3.6.1.2.1.31.1.1.1.10.1
iso.3.6.1.2.1.31.1.1.1.10.1 = Counter64: 224558063566
`

I have made the change that you listed above, but it unfortunately doesn't seem to have made any difference, aside from netdata thinking that there's a constant 4kpbs out instead of a constant 3kbps.

There's the debug output of node.d.plugin after making the change above: https://gist.github.com/LapsusAntepedis/0a643313dcd1ca81f764899ba76e5bee

**Comment by ktsaou** [comment] 2017-06-22 22:42
ok, this is interesting. I mark it as bug. I can't reproduce it but we have to find the cause.
Let me think a bit how to trace it.

**Comment by ktsaou** [comment] 2017-08-25 15:38
@antonsb I just found node-net-snmp has updated their code.
I don't know however if it fixes the issue or not.

I have made PR #2633 with the updated net-snmp package and its dependencies.
Could you please check if this fixes it? (`git clone https://github.com/ktsaou/netdata` and install it).

If it still does not work, I will add debugging info all over the place, to trace the issue. Unfortunately, I don't have access to a 64 bit snmp machine, so I need your help to find the root cause of the issue.

**Comment by antonsb** [comment] 2017-08-25 18:33
Unfortunately still an issue. I can provide direct SSH access to devices if needed.

**Comment by ktsaou** [comment] 2017-08-25 23:12
ok, let's try to find the issue.

In the same PR I have added more debugging info to understand the problem.

I need from you to do these:

1. install the PR, like you did
2. stop netdata
3. run `/usr/libexec/netdata/plugins.d/node.d.plugin debug 1 snmp`
4. leave it running for 30 seconds
5. stop it with control-C
6. post the output

**Comment by ktsaou** [comment] 2017-08-25 23:47
I also tried to re-write the code that handles 64 bit counters. The key change is that now I copy the data returned from net-snmp. This might have done a difference.
So, please check...

**Comment by antonsb** [comment] 2017-08-26 12:58
[debug.txt](https://github.com/firehol/netdata/files/1253660/debug.txt)

**Comment by antonsb** [comment] 2017-08-26 13:01
[debug.txt](https://github.com/firehol/netdata/files/1253667/debug.txt)

**Comment by ktsaou** [comment] 2017-08-26 15:16
Thanks!
I see this is good now, but you haven't included the `BEGIN`, `SET`, `END` lines to verify it really sends to netdata the proper values.

**Comment by ktsaou** [comment] 2017-08-26 15:16
Just let it run a little longer and catch both stdout and stderr.

**Comment by antonsb** [comment] 2017-08-26 18:58
i'm  sorry i didn't check the contents for this file before updating,
now it should have everything. Same thing is happening:

`BEGIN snmp_switch.bandwidth_port1 
SET in = a�c�0  SET out = Z>}G0 END
`
[debug.txt](https://github.com/firehol/netdata/files/1253911/debug.txt)

**Comment by ktsaou** [comment] 2017-08-26 23:38
I am almost certain there is something faulty on your node.js. I took your json objects and added them to the code and it works on my node version.

Anyway, I tried something different. I eliminated the `Buffer` objects used by `net-snmp` and I now just use hex strings to pass over 64 bit values.

Could you please retry and post again the output?

**Comment by antonsb** [comment] 2017-08-27 13:28
Thanks, now it works as intended.

**Comment by ktsaou** [comment] 2017-08-27 14:44
ok, thanks!
I am merging it.

**Comment by ktsaou** [comment] 2017-08-27 15:30
merged it.

**Closed** 2017-08-27 15:30 UTC
Labels: bug, fixed
