### ISSUE TITLE
Statsd metrics coming from a headless collector not written to backend by central netdata

### ISSUE THREAD

**Issue by jbfuzier** [firehol/netdata#2334] opened 2017-06-14 13:40 UTC
Hi,

I have a setup with a headless collector on host A (memory mode=none, web mode =none), host B is a central netdata receiving data from host A.

Host B has the following backend config : 
```
[backend]
        enabled = yes
        type = graphite
        destination = tcp:127.0.0.1:2003
        data source = average
        prefix = netdata
        update every = 10
        buffer on failures = 100
        timeout ms = 20000
        send charts matching = *
```

1. Send a metric to host A's statsd : 
`echo "metric3:1|c" |nc -u -w 1 localhost 8125`

2. On host B webui (http://hostb:19999/host/hostA/), we can see the collected metric :
![image](https://user-images.githubusercontent.com/4688432/27134733-c1098eec-5116-11e7-808c-a0a233709e93.png)

3. On graphite, we do not get metric3 for hostA (however built in data for hostA such as CPU, ram... are getting properly inside graphite)

4. On host B, if we run the same nc command to create a new statsd metric, it gets properly inside graphite; so the issue seems limited to streamed data.

I get the following log on HostB when a new metric is created on hostA : 
`2017-06-14 15:24:54: netdata INFO : (0139@rrddim.c  :rrddim_add_cust): Initializing file /opt/netdata/var/cache/netdata/f5f26bfc-503e-11e7-945b-3863bb3edce0/statsd_counter_metric3.counter/events.db.
`
And when a new metric is created on hostB :
`2017-06-14 15:21:12: netdata INFO : (0139@rrddim.c  :rrddim_add_cust): Initializing file /opt/netdata/var/cache/netdata/statsd_gauge_metric2.gauge/events.db.
`

All servers are running v1.6.0-510-gfcda480a_rolling (static build).

**Comment by ktsaou** [comment] 2017-06-14 19:09
Hi,

I can't reproduce this. It works for me.

This is what I did:

1. Setup hostA to send metrics to hostB

2. On hostB, run on a terminal this command: `nc -l --recv-only -p 1234` (based on the netcat version of your system, this command might be a little different - the idea is to have `nc` listen on port TCP port 1234).

3. On hostB, configure the backend, like this:

```
[backend]
	enabled = yes
        type = graphite
        destination = localhost:1234
        send charts matching = statsd*
```

3. restart netdata on hostB. Verify metrics are streamed from hostA to hostB.

4. On hostB run this command:

```
while true; do echo "metric1"; done | nc --send-only localhost 8125
```

5. Switch back to the terminal you have set at point 2. Metrics start showing up.

6. Repeat step 4, but this time on hostA.

7. The terminal set at point 2, starts showing statsd metrics from hostA.

Could you please help me find a way to reproduce this?

**Comment by jbfuzier** [comment] 2017-06-15 08:35
1. On hostA : `while true; do echo "metric1hosta"; done |nc -w 1 localhost 8125`

2.  In the webUI of hostB (central netdata), I am getting the metric from host A : 

![image](https://user-images.githubusercontent.com/4688432/27172377-54f6cdc4-51b5-11e7-982a-5b34c886522b.png)

3. I am getting nothing on hostsb's `nc -l -p 1234`

4.  I run on hostB : `while true; do echo "metric1hostb"; done |nc -w 1 localhost 8125`

5.  I got the following data on the nc :
`
netdata.elasticsearch1.statsd_meter_metrichostb1.meter.meter 0.0000000 1497515472
netdata.elasticsearch1.statsd_meter_metrichostb1.meter.events 0.0000000 1497515472
`

6. Here is the content of netdata.conf on hostB : 
```
[backend]
        enabled = yes
        type = graphite
        destination = tcp:127.0.0.1:1234
        data source = average
        prefix = netdata
        update every = 10
        buffer on failures = 100
        timeout ms = 20000
        send charts matching = statsd*

[global]
        history = 36000
        update every = 10
        debug flags = 0xffffff

```

**Comment by ktsaou** [comment] 2017-06-15 20:01
ok, let me try to reproduce this with the latest static build...

**Comment by ktsaou** [comment] 2017-06-15 20:45
Well, I still can't reproduce it. It works for me.

I setup 3 coreos VMs. `coreos1` is the master, while `coreos2` and `coreos3` are slaves sending their metrics to `coreos1`.

I setup metrics replication and verified metrics are mirrored between them.

Then this is the output of the `nc -l --recv-only -p 1234` command on `coreos1`:

```sh
# coreos1: nc -l --recv-only -p 1234

# coreos1: while true; do echo "metric1"; done | /tmp/ncat --send-only localhost 8125
netdata.coreos1.statsd_meter_metric1.meter.meter 62234.8842857 1497558855
netdata.coreos1.statsd_meter_metric1.meter.events 62234.8842857 1497558855
netdata.coreos1.statsd_meter_metric1.meter.meter 66436.1290000 1497558865
netdata.coreos1.statsd_meter_metric1.meter.events 66436.1290000 1497558865

# coreos2: while true; do echo "metric1"; done | /tmp/ncat --send-only localhost 8125
netdata.coreos1.statsd_meter_metric1.meter.meter 64397.8666667 1497558895
netdata.coreos1.statsd_meter_metric1.meter.events 64397.8666667 1497558895
netdata.coreos2.statsd_meter_metric1.meter.meter 60405.0700000 1497558895
netdata.coreos2.statsd_meter_metric1.meter.events 60405.0700000 1497558895
netdata.coreos1.statsd_meter_metric1.meter.meter 63375.0911111 1497558905
netdata.coreos1.statsd_meter_metric1.meter.events 63375.0911111 1497558905
netdata.coreos2.statsd_meter_metric1.meter.meter 64577.3850000 1497558905
netdata.coreos2.statsd_meter_metric1.meter.events 64577.3850000 1497558905
netdata.coreos1.statsd_meter_metric1.meter.meter 63092.2750000 1497558915
netdata.coreos1.statsd_meter_metric1.meter.events 63092.2750000 1497558915
netdata.coreos2.statsd_meter_metric1.meter.meter 64571.2240000 1497558915
netdata.coreos2.statsd_meter_metric1.meter.events 64571.2240000 1497558915

# coreos3: while true; do echo "metric1"; done | /tmp/ncat --send-only localhost 8125
netdata.coreos1.statsd_meter_metric1.meter.meter 61835.4250000 1497559025
netdata.coreos1.statsd_meter_metric1.meter.events 61835.4250000 1497559025
netdata.coreos3.statsd_meter_metric1.meter.meter 58627.6640000 1497559025
netdata.coreos3.statsd_meter_metric1.meter.events 58627.6640000 1497559025
netdata.coreos2.statsd_meter_metric1.meter.meter 64232.2210000 1497559025
netdata.coreos2.statsd_meter_metric1.meter.events 64232.2210000 1497559025
netdata.coreos1.statsd_meter_metric1.meter.meter 59229.6266667 1497559035
netdata.coreos1.statsd_meter_metric1.meter.events 59229.6266667 1497559035
netdata.coreos3.statsd_meter_metric1.meter.meter 59503.6100000 1497559035
netdata.coreos3.statsd_meter_metric1.meter.events 59503.6100000 1497559035
netdata.coreos2.statsd_meter_metric1.meter.meter 61148.8610000 1497559035
netdata.coreos2.statsd_meter_metric1.meter.events 61148.8610000 1497559035
```

I used today's binary package: `netdata-v1.6.0-541-g3b7b6654-x86_64-20170615-062837.gz.run`

Still can't reproduce it.

**Comment by ktsaou** [comment] 2017-06-15 20:59
Let me check the code for the conditions that could prevent a chart that is visible on the dashboard to be pushed to the backends...

**Comment by ktsaou** [comment] 2017-06-15 21:22
netdata does the following:

1. for each host for which we mirror metrics (no condition = all of them)

2. for each chart this host has (no condition = all of them)

3. **Do not send the chart** If it is flagged with `IGNORE` (see below)

4. If the chart is not flagged with `SEND`, then match it against the pattern `send charts matching = statsd*` and either give it the flag `SEND` or `IGNORE`. This is the only point we assign the flag `IGNORE` to it.

5. **Do not send the chart** if it is not viewable (hit F5 on the master dashboard for the slave - ie. at `http://master:19999/host/slave/` - if the chart is shown, it is viewable).

6. **Do not send the chart** if its `memory mode = none` and the the `data source` is not `as collected` (so, `as collected` sends metrics to the backends even if memory mode is `none`). If the chart is viewable on the master's dashboard for the slave, this is not the case for you (memory mode = none charts are not shown on the dashboard).

7. ok, this chart is to be sent.

8. For each of the chart dimensions, send them if they have been updated since the last time we sent data to the backend (every time a chart is updated we update its timestamp, every time we sent metrics to the backend we remember the timestamp) and the value to be send is not `NAN` (ie. the calculated value to be sent is not a chart gap).

I don't see why a chart from a slave should not be sent.
If you are sure this is not a misconfiguration from your side, I'll add some debugging info to help us trace the issue.

**Comment by jbfuzier** [comment] 2017-06-16 07:56
Thanks,
I am gonna try to make it work on a clean slate,then walk from there to identify the differences with my current install.

I hope I will have time to do that today, if not I will do it in 2 weeks as I will be out of office for a while.

**Comment by jbfuzier** [comment] 2017-06-16 12:00
Ok, tried exact same config on 2 new VMs and it is working as it should.
I will try to identify what is different between those 2 setups.

**Comment by jbfuzier** [comment] 2017-06-16 12:37
Ok I think I found how to reproduce the issue (on both of my test slaves). It is related to the `update every` setting on the slave collector:

On the slave collector : 
netdata.conf 
```
[global]
        memory mode = none
#        update every = 10 # Commenting this line fixes the issue
[web]
        mode = none
```
stream.conf : 

```
[stream]
    # Enable this on slaves, to have them send metrics.
    enabled = yes

    # Where is the receiving netdata?
    # A space separated list of:
    #
    #      [PROTOCOL:]HOST[%INTERFACE][:PORT]
    #
    # If many are given, the first available will get the metrics.
    #
    # PROTOCOL  = tcp or udp (only tcp is supported by masters)
    # HOST      = an IPv4, IPv6 IP, or a hostname.
    #             IPv6 IPs should be given with brackets [ip:address]
    # INTERFACE = the network interface to use
    # PORT      = the port number or service name (/etc/services)
    #
    # This communication is not HTTP (cannot be proxied by web proxies).
    destination = 127.0.0.1

    # The API_KEY to use (as the sender)
    api key = 51e23085-4a91-4e44-a66a-ee54c6133152

    # The timeout to connect and send metrics
    timeout seconds = 60

    # If the destination line above does not specify a port, use this
    default port = 19999

    # The buffer to use for sending metrics.
    # 1MB is good for 10-20 seconds of data, so increase this
    # if you expect latencies.
    buffer size bytes = 1048576

    # If the connection fails, or it disconnects,
    # retry after that many seconds.
    reconnect delay seconds = 5

    # Attempt to sync the clock the of the master with the clock of the
    # slave for that many iterations, when starting.
    initial clock resync iterations = 60

```

**Comment by jbfuzier** [comment] 2017-06-16 12:44
It is worth noting that if I remove the comment on `update every`, metrics that have been sent to the backend in the past (with this option commented) are still being sent to the backend. However new metrics name that were never sent to the backend are not sent.

**Comment by ktsaou** [comment] 2017-06-17 08:24
nice finding!
Let me reproduce it to trace the issue.

**Comment by ktsaou** [comment] 2017-06-17 12:56
Unfortunately, I still can't reproduce it.

Can you use a compiled netdata for the master?
If yes, I suggest to do these (on the master only - I assumed you have static binary installed):

```sh
# stop the current netdata master
systemctl stop netdata

# backup your old static installation
mv /opt/netdata /opt/netdata.old

# compile my fork of the repo
cd /usr/src
git clone https://github.com/ktsaou/netdata.git netdata-ktsaou.git
CFLAGS="-O1 -ggdb -DNETDATA_INTERNAL_CHECKS=1" ./netdata-installer.sh --install /opt --dont-start-it

# copy your config
cp /opt/netdata.old/etc/netdata/{netdata,stream}.conf /opt/netdata/etc/netdata/

# start netdata with backends debugging on the console
netdata -D -W set global 'debug flags' 0x0000000008000000 -W set global 'debug log' system
```

I have assumed you have statsd and backends configured properly.

We are looking for lines like this:

```
sending host 'slave', metrics of 2 dimensions, of 1 charts. Skipped 0 dimensions.
```

Mine logs skipped 0 dimensions always. The only reason for skipping them is if they somehow are not collected within the timeframe sending metrics to the backend (point 8 at https://github.com/firehol/netdata/issues/2334#issuecomment-308869375).

When skipping dimensions it will also log: `BACKEND: not sending dimension '%s' of chart '%s' from host '%s', its last data collection (%lu) is not within our timeframe (%lu to %lu)`

If it is skipping them because there are no usable points, it will log: `BACKEND: %s.%s.%s: no values stored in database for range %lu to %lu`

I hope these will help us identify the issue...

**Comment by jbfuzier** [comment] 2017-06-17 17:04
Thanks, I will do that when I am back in 2 weeks.

Le 17 juin 2017 2:56 PM, "Costa Tsaousis" <notifications@github.com> a
écrit :

Unfortunately, I still can't reproduce it.

Can you use a compiled netdata for the master?
If yes, I suggest to do these (on the master only - I assumed you have
static binary installed):

# stop the current netdata master
systemctl stop netdata
# backup your old static installation
mv /opt/netdata /opt/netdata.old
# compile my fork of the repocd /usr/src
git clone https://github.com/ktsaou/netdata.git netdata-ktsaou.git
CFLAGS="-O1 -ggdb -DNETDATA_INTERNAL_CHECKS=1" ./netdata-installer.sh
--install /opt --dont-start-it
# copy your config
cp /opt/netdata.old/etc/netdata/{netdata,stream}.conf /opt/netdata/etc/netdata/
# start netdata with backends debugging on the console
netdata -D -W set global 'debug flags' 0x0000000008000000 -W set
global 'debug log' system

I have assumed you have statsd and backends configured properly.

We are looking for lines like this:

sending host 'slave', metrics of 2 dimensions, of 1 charts. Skipped 0
dimensions.

Mine logs skipped 0 dimensions always. The only reason for skipping them is
if they somehow are not collected within the timeframe sending metrics to
the backend (point 8 at #2334 (comment)
<https://github.com/firehol/netdata/issues/2334#issuecomment-308869375>).

When skipping dimensions it will also log: BACKEND: not sending dimension
'%s' of chart '%s' from host '%s', its last data collection (%lu) is not
within our timeframe (%lu to %lu)

If it is skipping them because there are no usable points, it will
log: BACKEND:
%s.%s.%s: no values stored in database for range %lu to %lu

I hope these will help us identify the issue...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/firehol/netdata/issues/2334#issuecomment-309213660>,
or mute
the thread

**Comment by ktsaou** [comment] 2017-06-17 19:44
ok, I'll wait for you here...

**Comment by ktsaou** [comment] 2017-06-18 13:41
The changes have been merged.
So, you can use the offical repo too for this debugging. But, you need to compile netdata to enable it.

**Comment by jbfuzier** [comment] 2017-06-27 16:07
I compiled & run master branch on hostA (no change on hostC so far, still using the static version)

1. On host C : `while true; do echo "metrichostc6"; done |nc -w 1 127.0.0.1 8125`

2. On HostA (central) web UI in the hostC tab :

![image](https://user-images.githubusercontent.com/4688432/27596903-2f0c1d52-5b61-11e7-956f-a5a53b250fd2.png)

3. On host A : `while true; do echo "metrichostA1"; done |nc -w 1 127.0.0.1 8125`

4. On host A : `nc -l -p 1234` outputs : 

```
netdata.elasticsearch1.statsd_meter_metrichosta1.meter.meter 0.0000000 1498578932
netdata.elasticsearch1.statsd_meter_metrichosta1.meter.events 0.0000000 1498578932
``` 

5. In debug log : greping on hostc : 
```

2017-06-27 17:57:42: netdata DEBUG (0053@backends.c:backend_calcula): BACKEND: honeypot.statsd_meter_metrichostc5.meter.events: requested timeframe 1498579052 to 1498579062 is outside the chart's database range 1498578540 to 1498579050
2017-06-27 17:57:42: netdata DEBUG (0053@backends.c:backend_calcula): BACKEND: honeypot.statsd_meter_metrichostc6.meter.meter: requested timeframe 1498579052 to 1498579062 is outside the chart's database range 1498577770 to 1498579050
2017-06-27 17:57:42: netdata DEBUG (0053@backends.c:backend_calcula): BACKEND: honeypot.statsd_meter_metrichostc6.meter.events: requested timeframe 1498579052 to 1498579062 is outside the chart's database range 1498577770 to 1498579050
```

It gets repeated a log.

For hosta I have only a few lines : 

```
2017-06-27 17:55:42: netdata DEBUG (0053@backends.c:backend_calcula): BACKEND: elasticsearch1.statsd_meter_metrichosta1.meter.meter: requested timeframe 1498578932 to 1498578942 is outside the chart's database range 1498578530 to 1498578930
2017-06-27 17:55:42: netdata DEBUG (0053@backends.c:backend_calcula): BACKEND: elasticsearch1.statsd_meter_metrichosta1.meter.events: requested timeframe 1498578932 to 1498578942 is outside the chart's database range 1498578530 to 1498578930

```

**Comment by jbfuzier** [comment] 2017-06-27 16:13
`also : 2017-06-27 18:11:22: netdata DEBUG (0661@backends.c:backends_main  ): BACKEND: sending host 'hostc', metrics of 12 dimensions, of 6 charts. Skipped 0 dimensions.`

**Comment by ktsaou** [comment] 2017-06-27 18:10
ok, this is definitely a bug: when the update frequency is above 1, the backends logic does not align the timestamps to match the ones in the database.

**Comment by ktsaou** [comment] 2017-06-27 18:11
btw, thank you for tracing this!

**Comment by jbfuzier** [comment] 2017-06-28 19:04
Glad to help :)

**Comment by ktsaou** [comment] 2017-07-02 21:14
I think I fixed it.
It is in PR #2411

**Comment by ktsaou** [comment] 2017-07-02 21:58
merged it.

**Closed** 2017-07-02 21:58 UTC
Labels: bug, fixed

**Comment by jbfuzier** [comment] 2017-07-03 08:14
Tested it, it works. Thanks :)
