### ISSUE TITLE
synthetic statsd charts with pattern-based dimensions

### ISSUE THREAD

**Issue by pguyot** [firehol/netdata#2785] opened 2017-09-23 20:44 UTC
Synthetic statsd charts can only be based on a fixed list of dimensions defined at start time.
In some scenarios, the actual possible dimensions are not known or simply infinite. It would make sense to have:

```
# replace 'mychart' with the chart id
# the chart will be named: myapp.mychart
[mychart]
	name = mychart
	title = my chart title
	family = my family
	context = chart.context
	units = tests/s
	priority = 91000
	type = area
	dimension = myapp.collection.*.metric1
```

which would gather
```
myapp.collection.item1.metric1
myapp.collection.item2.metric1
myapp.collection.item3.metric1
myapp.collection.otheritem.metric1
...
```

including metrics that do not exist when the configuration file is loaded.
The context could then be further used to define an alarm on all these metrics.

**Comment by ktsaou** [comment] 2017-09-24 11:36
You are right.

However this approach will be somewhat problematic for netdata. The problem is that as dimensions are added to a chart, the specific chart becomes slower and slower to view (it does not slow down data collection, only viewing).

To be precise: a netdata chart with 1000 dimensions will still be faster than anything else. But, instead of 0.01ms per chart for generating the JSON representation, you will get 20ms on this chart. This will be fast for you, but will increase the CPU load on your server while you view this chart, increase the bandwidth between your server and your browser and put a tremendous amount of CPU pressure on your browser.

Then, we will have a memory issue. Each metric in netdata uses a fixed step round robin database (this is why netdata is so fast - most calculations are made at data collection time). This means that even if you push 1 value for a metric, the whole round robin database for it will be allocated.

I agree however that this feature will be handy if you have a finite number of charts and you want to avoid configuring all of them by hand.

**Comment by pguyot** [comment] 2017-09-24 12:28
This is exactly the scenario: an infinite number of possible metrics but only a few actual metrics on a given chart. The metric names are actually defined at runtime, there is no way netdata could be configured to cover them all. Typically, this could be metrics that are reported through statsd because they are beyond a given threshold.

I understand the performance issue, and in fact, being able to define charts with matching metrics would make it easier to disable private charts, thus reduce the number of statsd charts overall.

Maybe we could cap the number of dimensions per synthetic charts and, for matching metrics, only consider the last 10 (or 50) values in the chart?

**Comment by aigr** [comment] 2017-09-27 15:27
+1

**Comment by flysteur-dev** [comment] 2017-10-14 12:16
+1

**Comment by ktsaou** [comment] 2017-10-15 16:29
I ended up needing this too...
It will need some work though, due to the way it is now organized (for each dimension expected, netdata keeps a structure which is consumed once satisfied, so I'll need a way to add expectations that are not consumable).

**Comment by ktsaou** [comment] 2017-12-09 15:58
Made it in PR #3114

**Comment by ktsaou** [comment] 2017-12-10 00:23
merged it.
Check the PR and the wiki page for the additional functionality.

**Closed** 2017-12-10 00:23 UTC
Labels: enhancement, fixed
