### ISSUE TITLE
Alternative to dark theme?

### ISSUE THREAD

**Issue by bgulla** [firehol/netdata#184] opened 2016-04-05 12:49 UTC
Is there a way to invert the colors where the page loads with a white background?

**Comment by ktsaou** [comment] 2016-04-05 13:35
duplicate of #81
already done. 
Click "settings" -> "visual" on the dashboard.
If it is not there, update your netdata.

**Comment by bgulla** [comment] 2016-04-05 13:37
thanks. but is there a way to set it by default in the
/etc/netdata/netdata.conf file?

On Tue, Apr 5, 2016 at 9:35 AM, Costa Tsaousis <notifications@github.com>
wrote:

> duplicate of #81 <https://github.com/firehol/netdata/issues/81>
> already done.
> Click "settings" -> "visual" on the dashboard.
> If it is not there, update your netdata.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/firehol/netdata/issues/184#issuecomment-205807944>
>



-- 
Brandon

**Comment by ktsaou** [comment] 2016-04-05 14:11
It is saved on your browser - so, you just need to do this once.
If you follow the link at #81 you will see that it is a line you have to comment out in index.html.

**Closed** 2016-04-06 05:56 UTC
Labels: question
