### ISSUE TITLE
Disk critical notifications after wakeup from hibernation

### ISSUE THREAD

**Issue by tx7** [firehol/netdata#1296] opened 2016-11-28 21:22 UTC
Hi,

One thing that annoyed me is that every time my server boot up, I getting emails about my disks, RAID10, sda, sdb.... is critical.

In addition, I got the ipv4.tcphandshake has the same message.

For example:

disk last collected secs = 67213 seconds ago.

sde : family

Critical: severity

Is there a way I can fix this or disable the notification?

Thanks.

**Comment by ktsaou** [comment] 2016-11-28 21:32
You say this happens every time you boot up your server?

hm.... are you using the latest netdata? I thought I had added a protection against this.

Does it happen if you just stop netdata, wait 30 seconds and restart it?

**Comment by tx7** [comment] 2016-11-28 23:09
Yes, it happens when my server woke up from hibernation.
My server is a normal PC, running on Debian Jessie.

I stop Netdata, and restarted it without any issue.

**Comment by ktsaou** [comment] 2016-11-28 23:14
oh... I see... hibernation....
I have seen this before... hm... I think there is a solution... we have to somehow detect wake up from hibernation (clock skew) and delay all the alarms for a few seconds...

I leave this open, as an enhancement, to fix it.

**Comment by tx7** [comment] 2016-12-01 12:38
Hi,

Any ETA on this?
My emails is clogged up with these notifications.

Thanks.

**Comment by ktsaou** [comment] 2016-12-01 20:23
Well, I am not sure how to fix it yet. I'll try to R&D a bit during the weekend. If it is simple, it will be solved. Otherwise, we will have to check alternatives (i.e. disable this alarm in your case).

**Comment by tx7** [comment] 2016-12-01 20:54
Ok, how do I disable it?
Do you any additional info?

Thanks.

**Comment by ktsaou** [comment] 2016-12-01 21:02
> Ok, how do I disable it?

Well, all the notifications sent state the file and line they are defined. Just edit that file and disable that alarm definition.

> Do you any additional info?

If I find a solution, I would like you to test it.

**Comment by ktsaou** [comment] 2016-12-01 21:03
This is what I am going to try: #1225

**Comment by tx7** [comment] 2016-12-04 17:09
The new version fixed it.
Thanks guys.

One question, is the PID changed report matter?

i.e: 

PID changed Service nginx

        Date:        Sun, 04 Dec 2016 11:06:32
        Action:      alert
        Host:        server.test12345
        Description: process PID changed from 11836 to 12780

Your faithful employee,
Monit

**Comment by tx7** [comment] 2016-12-06 01:00
I had new warning notification:

disk_backlog.sdb
CHART
10min disk backlog = 2028 ms 
average of the kernel estimated disk backlog, for the last 10 minutes
ALARM
sdb
FAMILY
WARNING
SEVERITY
Mon Dec 5 18:05:21 EST 2016
TIME


disk_backlog.sdb
CHART
10min disk backlog = 2001 ms 
average of the kernel estimated disk backlog, for the last 10 minutes
ALARM
sdb
FAMILY
WARNING
SEVERITY
Mon Dec 5 17:39:22 EST 2016
TIME

**Comment by ktsaou** [comment] 2016-12-06 20:10
This will be solved when the first step of https://github.com/firehol/netdata/pull/1313#issuecomment-264629434 is implemented, so that we can compare the `monotonic` or `boottime` and the `realtime` clocks.

Waiting for the first commit from @rlefevre.

**Comment by tx7** [comment] 2016-12-20 23:05
Hello,
I still having issue after pc woke up from hibernation.

`disk_space._
CHART
disk space last collected secs = 67219 seconds ago 
number of seconds since the last successful data collection of the mount point
ALARM
/
FAMILY
CRITICAL
SEVERITY
Tue Dec 20 16:00:20 EST 2016
TIME`

`disk.sda
CHART
disk last collected secs = 67219 seconds ago 
number of seconds since the last successful data collection of the block device
ALARM
sda
FAMILY
CRITICAL
SEVERITY
Tue Dec 20 16:00:20 EST 2016
TIME`


`
disk.sdb
CHART
disk last collected secs = 67219 seconds ago 
number of seconds since the last successful data collection of the block device
ALARM
sdb
FAMILY
CRITICAL
SEVERITY
Tue Dec 20 16:00:20 EST 2016
TIME`


`disk.sdd
CHART
disk last collected secs = 67219 seconds ago 
number of seconds since the last successful data collection of the block device
ALARM
sdd
FAMILY
CRITICAL
SEVERITY
Tue Dec 20 16:00:20 EST 2016
TIME`

**Comment by rlefevre** [comment] 2016-12-21 07:31
Hibernation alarms issues are not fixed yet by the patches merged or those in review. We are (hopefully) fixing all issues with time progressively. I will submit soon another pull request with a proposal to fix this. 

I will add a comment here if you want to test it once it's ready. 

Unless @ktsaou has another plan?

**Comment by ktsaou** [comment] 2016-12-21 20:25
This plan is excellent I think...

**Comment by ktsaou** [comment] 2016-12-21 20:26
@tx7 I know we are delaying the fix, but the work @rlefevre is very important and since it affects netdata at its heart, I think we all want it to be done very accurately. The way @rlefevre proceeds, I think this will be fixed before the end of the month.

**Comment by tx7** [comment] 2016-12-22 13:16
The holiday is near. I think you guys need to take a break.
Thanks for the info.

**Comment by tx7** [comment] 2017-01-19 23:17
Hi,

Are these the new errors from hibernation?
``
disk_space._var_lib_openmediavault_rrd
CHART
disk space last collected secs (was critical for 10 seconds) 
number of seconds since the last successful data collection of the mount point
ALARM
/var/lib/openmediavault/rrd
FAMILY
Recovered from CRITICAL
SEVERITY
Thu Jan 19 16:11:17 EST 2017 
(was critical for 10 seconds)
TIME`
disk_space._run
CHART
disk space last collected secs (was critical for 10 seconds) 
number of seconds since the last successful data collection of the mount point
ALARM
/run
FAMILY
Recovered from CRITICAL
SEVERITY
Thu Jan 19 16:11:17 EST 2017 
(was critical for 10 seconds)
TIME`

`
disk_space._var_spool
CHART
disk space last collected secs = 66934 seconds ago 
number of seconds since the last successful data collection of the mount point
ALARM
/var/spool
FAMILY
CRITICAL
SEVERITY
Thu Jan 19 16:11:07 EST 2017
TIME`


`
disk.sda
CHART
disk last collected secs = 66934 seconds ago 
number of seconds since the last successful data collection of the block device
ALARM
sda
FAMILY
CRITICAL
SEVERITY
Thu Jan 19 16:11:07 EST 2017
TIME`



`net.eth2
CHART
interface last collected secs = 66934 seconds ago 
number of seconds since the last successful data collection
ALARM
eth2
FAMILY
CRITICAL
SEVERITY
Thu Jan 19 16:11:07 EST 2017
TIME`

**Comment by rlefevre** [comment] 2017-01-23 16:52
I can't reproduce the issue on current master for disk space, but this is not due to clock bug fixes.

I think this is due to the fact that disk space plugin has been moved in its own thread and is now running before the health check on heartbeat, so `$now - $last_collected_t` computation is most likely always consistent.

**Comment by ktsaou** [comment] 2017-01-23 18:26
hm... this would require another clock call per data collection iteration per chart and also add overheads on each iteration...

Since this only affects alarms, another way would be to delay all health checks for one iteration if we detect that `realtime` and `monotonic` report a significantly different delta (which could be a delta bigger than `min_run_every` - usually 10 seconds, or even better a new configuration setting for the min delta to trigger it).

This can be done at the health thread alone (at the point it sleeps). When it is triggered, we could update all alarms to set their `.next_update` member to point in future, so that a full `.update_every` (also their member) will be given to them.

**Comment by tx7** [comment] 2017-01-24 00:37
I don't know the number of users in real world use sleep/hibernation on their server like me.
It just bugging me with the daily errors  in my emails whenever it wakes up from hibernation.
If you guys can fix this, it'll be awesome and near perfection.
Overall, Netdata is an awesome tool for admins to view their server's specs/performance.

Thanks.

**Comment by rlefevre** [comment] 2017-01-24 10:44
You're right @ktsaou , the cpu and memory/storage overhead is not acceptable.

In summary, if we include  #1368, we have fixed:
- logs flood issues if system time is changed in the past too much
- hanged sleeps issues (I think this is the most severe issue) if system time is changed in the future

Known remaining issues:
- potential alarms flood after hibernation or if system time is changed in the future too much
- alarms iterations issues if system time is changed
- hanged RRD charts and RRD data loss if system time is changed to the past
- (python plugin heartbeat)

Also new or unknown problems can appear in the future if realtime clocks are used for any computation (I think they should only be used for realtime timestamps needs, like logs, alarm detection timestamps, cookies or expiration dates/times).

Your proposal would works perfectly, but it is IMHO more a specific work-around (a problem detection + runtime fix) than a way to properly and definitely fix all the remaining and potential future issues at their source. This would also be a fix only for alarms and would not prevent the same issue to appear again later in another module. 

Now that we have all the required APIs, I would like to find a "definitive" fix. Here what I think could be an acceptable solution:
- `rrddim_set_by_pointer` would use a boot time clock, as well as interpolations (so a single clock call)
- a realtime clock and monotonic clock offset would be stored in RRDSET and only updated on `rrdset_done`, keeping the overhead minimal (a clock call is usually a few tenths nanoseconds, cf.http://btorpey.github.io/blog/2014/02/18/clock-sources-in-linux/ for example ). As said previously, the monotonic offset must be fixed when the cache file is reloaded.
- alarms `$now` and `$last_collected_t` would use the monotonic clock (bootime clock + monotonic offset for `$last_collected_t`), eventually by adding all clock versions variables.
- web clients would have an option to display by realtime clock, bootime clock or monotonic clock
- for logs, cookies, expirations and backends timestamps, realtime clock would be used (using the offset when the time comes from dimensions)

I think this would fix all remaining issues, would prevent any RRD data loss or chart freeze, and offer a clear way to avoid new issues in the future (forbid any realtime clock computation in patches). Also I don't think that this would prevent to add chart annotations or new features, nor prevent cache files reload in other tools to be implemented (but they should be updated to compute the realtime clock with its offset if needed), and we could keep the current default behavior (in web clients charts for example) the same.

Did I miss something ?

**Comment by rlefevre** [comment] 2017-01-24 16:00
@tx7 hibernation may not be used much on servers, but netdata is also very useful on embedded systems, on which all kind of corner cases are possible (suspend, wrong clocks, time change after boot, ...). There are also most likely developers using it on their desktop/development computer.

I hope we can make netdata support all kind of systems, not only servers, hence my work on clocks.

**Comment by tx7** [comment] 2017-01-24 23:11
Most of the emails I got today are interface dropped packets and disk space.

Here are examples:

`disk_space._run
CHART
disk space last collected secs = 66944 seconds ago 
number of seconds since the last successful data collection of the mount point
ALARM
/run
FAMILY
CRITICAL
SEVERITY
Tue Jan 24 16:00:44 EST 2017
TIME`


`
disk_space._
CHART
disk space last collected secs = 66944 seconds ago 
number of seconds since the last successful data collection of the mount point
ALARM
/
FAMILY
CRITICAL
SEVERITY
Tue Jan 24 16:00:44 EST 2017
TIME`


`
disk_space._dev_shm
CHART
disk space last collected secs = 66944 seconds ago 
number of seconds since the last successful data collection of the mount point
ALARM
/dev/shm
FAMILY
CRITICAL
SEVERITY
Tue Jan 24 16:00:44 EST 2017
TIME`

`
redis_local.operations
CHART
redis last collected secs = 66944 seconds ago 
number of seconds since the last successful data collection
ALARM
operations
FAMILY
CRITICAL
SEVERITY
Tue Jan 24 16:00:44 EST 2017
TIME`

`
mdstat.md127
CHART
mdstat last collected (was critical for 10 seconds) 
number of seconds since the last successful data collection
ALARM
md127
FAMILY
Recovered from CRITICAL
SEVERITY
Tue Jan 24 16:00:54 EST 2017 
(was critical for 10 seconds)
TIME`


`
ipv4.udperrors
CHART
1m ipv4 udp send buffer errors = 8 errors 
number of UDP send buffer errors during the last minute
ALARM
udp
FAMILY
WARNING
SEVERITY
Tue Jan 24 16:01:44 EST 2017
TIME`

`
redis_local.operations
CHART
redis last collected secs (was critical for 10 seconds) 
number of seconds since the last successful data collection
ALARM
operations
FAMILY
Recovered from CRITICAL
SEVERITY
Tue Jan 24 16:00:54 EST 2017 
(was critical for 10 seconds)
TIME`

`
disk_space._run_lock
CHART
disk space last collected secs (was critical for 10 seconds) 
number of seconds since the last successful data collection of the mount point
ALARM
/run/lock
FAMILY
Recovered from CRITICAL
SEVERITY
Tue Jan 24 16:00:54 EST 2017 
(was critical for 10 seconds)
TIME`

`
net_packets.bond0
CHART
inbound packets dropped ratio = 9 % 
the ratio of inbound dropped packets vs the total number of received packets of the network interface, during the last 10 minutes
ALARM
bond0
FAMILY
CRITICAL
SEVERITY
Tue Jan 24 16:11:44 EST 2017
TIME`

`
ipv4.udperrors
CHART
1m ipv4 udp send buffer errors (was warning for 10 seconds) 
number of UDP send buffer errors during the last minute
ALARM
udp
FAMILY
Recovered from WARNING
SEVERITY
Tue Jan 24 16:01:54 EST 2017 
(was warning for 10 seconds)
TIME`

**Comment by ktsaou** [comment] 2017-02-23 16:23
I have added a fix in PR #1817

**Comment by tx7** [comment] 2017-02-23 23:22
Nice. When is it release?

Thanks.

**Comment by ktsaou** [comment] 2017-02-23 23:56
I need testers. Check the PR description. A lot of new functionality...

**Comment by tx7** [comment] 2017-02-24 00:30
You meant update the aggregated_hosts.conf?

`https://github.com/ktsaou/netdata/blob/5f9addf32418c6b4b2a764f09940ebd5ce9edbde/conf.d/aggregated_hosts.conf`

**Comment by ktsaou** [comment] 2017-02-24 00:37
No. That PR needs to be merged. I am pretty sure the old netdata functionality works well in this PR, but the new functionality is untested. I have added a few comments on what needs testing on the first comment of it.

Of course, you can install https://github.com/ktsaou/netdata and test alarms after hibernation. They should be fixed.

If you can also help me test the other functionality, it would be perfect! But at least test the functionality you need...

**Comment by tx7** [comment] 2017-02-25 03:07
Sorry, I'm running Netdata along with several web servers, and I don't want to risk corrupt the system.

**Comment by ktsaou** [comment] 2017-02-25 08:42
I thought you need hibernation... several web servers with hibernation?

**Comment by tx7** [comment] 2017-02-25 21:40
No, I meant they all running in one system.
The error occurs in the hibernation state.

**Closed** 2017-02-26 01:20 UTC
Labels: enhancement, fixed

**Comment by ktsaou** [comment] 2017-08-13 08:30
netdata was incorrectly using BOOTTIME to detect hibernation. With PR #2577 it uses MONOTONIC, so that wake up from hibernation is properly detected and no false alarms are sent.

**Comment by ktsaou** [comment] 2017-08-14 14:30
merged the fix
