### ISSUE TITLE
Run netdata on Windows

### ISSUE THREAD

**Issue by MTRNord** [firehol/netdata#342] opened 2016-04-30 18:54 UTC
Is there a way to port netdata to Windows or use cygwin?

**Comment by ktsaou** [comment] 2016-04-30 21:04
Hm... I don't know how to do it.

But even if someone does it, the data collectors netdata currently has are linux specific (they need `/proc` and `/sys`).

A friend has managed to compile netdata on Windows 10 prerelease with native BASH. A few data collectors do work, while others are reporting inaccurate values (although I guess this is a problem of the linux kernel emulation Microsoft has done).

Of course, if anyone knows how to write a WMI plugin for netdata, please do...

**Comment by MTRNord** [comment] 2016-04-30 21:34
I will test if i will get it to run with cygwin (or similar) and some changes. If it work (or not) I will tell it

**Comment by jhonnyvey** [comment] 2016-05-17 00:58
You can use perfmon to get these values, or via wmi.

**Comment by paulfantom** [comment] 2016-07-20 16:10
I think this is duplicate of #92.

**Comment by ktsaou** [comment] 2016-07-20 20:04
ok. let's discuss everything about windows support there. I am close this.

**Closed by ktsaou** 2016-07-20 20:04 UTC
Labels: distro support, duplicate
