### ISSUE TITLE
netdata-updater.sh throws grep: write error

### ISSUE THREAD

**Issue by malle-pietje** [firehol/netdata#1077] opened 2016-10-06 13:08 UTC
as the title says, when upgrading from `098028852337443bad09539ca24f18878b7a30d7` to `cd0a3e602e22b7b7d9e6d8d2b025b514e08e2bff` using the `git clone` method, running `netdata-updater.sh` throws this error.

Previous upgrades went fine.

**Comment by malle-pietje** [comment] 2016-10-06 13:23
BTW, a fresh install of the latest version (cd0a3e602e22b7b7d9e6d8d2b025b514e08e2bff) worked fine. Also `netdata-updater.sh` doesn't throw the error anymore.

**Comment by ktsaou** [comment] 2016-10-06 13:57
the error is thrown when you have edited a file in the source directory: git refuses to overwrite your changes.

**Comment by malle-pietje** [comment] 2016-10-06 14:01
Thanks, although I don't recall doing that. Also, the `git pull` command itself doesn't throw an error.

**Comment by ktsaou** [comment] 2016-10-11 09:38
hm... it could be a filesystem permission problem then.
Anyway, since you can't reproduce it now, I am closing this.

**Closed by ktsaou** 2016-10-11 09:38 UTC
Labels: question
