### ISSUE TITLE
time is UTС in log ???

### ISSUE THREAD

**Issue by zyxmon** [firehol/netdata#2096] opened 2017-04-18 05:45 UTC
Netdata 1.4 logs used time corrected to timezone in syslog.
Netdata 1.6 logs are always UTC.
I am compiling netdatda for embeded devices. Can the issue be because system lib has HAVE_CLOCK_GETTIME defined?

**Comment by zyxmon** [comment] 2017-04-18 06:21
Sorry - the information is not correct. Netdata 1.4 times in log are also UTC.
Here is an example

```
[I] Apr 18 09:11:55 wmond: WifiMaster0/AccessPoint0: (MT76x2) STA(6c:fa:a7:14:1f:fd) set key done in WPA2/WPA2PSK.
[I] Apr 18 09:12:20 dropbear[12605]: Child connection from 10.0.0.155:54332
[I] Apr 18 09:12:22 dropbear[12605]: Password auth succeeded for 'root' from 10.0.0.155:54332
[I] Apr 18 09:14:48 sshd[12747]: Server listening on 0.0.0.0 port 3322.
[I] Apr 18 09:14:48 sshd[12747]: Server listening on :: port 3322.
[E] Apr 18 09:15:14 sshd[12770]: error: Could not get shadow information for root
[I] Apr 18 09:15:14 sshd[12770]: Accepted password for root from 10.0.0.155 port 54544 ssh2
[I] Apr 18 09:15:46 sshd[12770]: syslogin_perform_logout: logout() returned an error
[I] Apr 18 09:15:54 sshd[12747]: Received signal 15; terminating.
[I] Apr 18 06:16:17 netdata: System has 1 processors.
[I] Apr 18 06:16:17 netdata: System supports 32768 pids.
[I] Apr 18 06:16:17 netdata[12909]: Adjusted my Out-Of-Memory score to 1000.
[I] Apr 18 06:16:17 netdata[12909]: Adjusted my scheduling priority to IDLE.
[I] Apr 18 06:16:17 netdata[12909]: Successfully became user 'nobody'.
[I] Apr 18 09:16:17 root: Started netdata from .
[I] Apr 18 06:16:17 netdata[12909]: NetData started on pid 12909
[I] Apr 18 06:16:17 netdata[12909]: Not starting thread tc.
[I] Apr 18 06:16:17 netdata[12909]: Starting thread idlejitter.
[I] Apr 18 06:16:17 netdata[12909]: Starting thread proc.
```

sshd and dropbear time in log is correct, netdata 1.4 is not.

**Comment by ktsaou** [comment] 2017-04-18 06:27
Hi,

netdata logs in whatever timezone the system believes is localtime: https://github.com/firehol/netdata/blob/0f37283905ebd01095e438165405ec590119887b/src/log.c#L216

I just checked my systems too. It is localtime. It reports the same date reported by the command `date`.

**Comment by ktsaou** [comment] 2017-04-18 06:29
hm... the logs you posted are not logs from netdata log files. Where did you get them?

**Comment by sviperz** [comment] 2017-04-18 06:46
> the logs you posted are not logs from netdata log files. Where did you get them?
Hi!

It's from router system log. As @zyxmon have mentioned in the initial comment we are talking about **netdatda** for embedded devices here. I can confirm that **netdatda** messages from the router system log have UTC timestamps. The messages from all other embedded services are correct, so this is something to do with **netdata** itself.

**Comment by ktsaou** [comment] 2017-04-18 06:53
So, you use syslog?

I just enabled syslog on a rpi and checked the remove system. The dates are localtime.
When netdata logs to syslog, netdata does not set any date/time. The current date/time is taken by the system/syslog server.

If it is syslog, I would check the syslog server configuration.

**Comment by ktsaou** [comment] 2017-04-18 07:08
Similar problem with yours:

http://www.linuxquestions.org/questions/linux-newbie-8/syslog-time-wrong-but-date-returns-the-correct-time-700986/

**Comment by ktsaou** [comment] 2017-04-18 07:13
And another one:

https://bugzilla.redhat.com/show_bug.cgi?id=435472

**Comment by ktsaou** [comment] 2017-04-18 07:18
hm... and I think I found what triggers it. You need the file `/etc/localtime` to be your local time zone.
Do you have this file? Also, it should not be a soft link.

**Comment by zyxmon** [comment] 2017-04-18 07:22
We use patched glibc and use `/opt/etc/localtime` that is correct. The firmware creates `/etc/localtime` that is different

```
 # cd /
/ # date
Tue Apr 18 10:22:01 MSK 2017
/ # cat /etc/localtime
MSK-3
/ # ls -al /opt/etc/localtime
lrwxrwxrwx    1 root     root            33 Mar  4 19:05 /opt/etc/localtime -> /opt/share/zoneinfo/Europe/Moscow
```

**Comment by ktsaou** [comment] 2017-04-18 07:26
hm... this is the problem then. I will add a netdata configuration option to set this the way you want it.

**Comment by ktsaou** [comment] 2017-04-18 07:32
I will merge it once travis completes.

This is the config I added in netdata conf:

```
[global]
	TZ environment variable = :/etc/localtime
```

**Comment by ktsaou** [comment] 2017-04-18 07:58
merged it.
Could you please check it is ok now?

**Closed** 2017-04-18 07:58 UTC
Labels: question

**Comment by zyxmon** [comment] 2017-04-18 10:26
I am sure it will work if systemlib is glibc and will not work in case of uclibc that is used in many embedede devivices. In uclibc
======================
TZ -This variable shall represent timezone information. The contents of the environment variable named TZ shall be used by the ctime(), localtime(), strftime(), mktime(), [TSF] [Option Start] ctime_r(), and localtime_r() [Option End] functions, and by various utilities, to override the default timezone. The value of TZ has one of the two forms (spaces inserted for clarity):
:characters
or:

std offset dst offset, rule
If TZ is of the first format (that is, if the first character is a colon), the characters following the colon are handled in an implementation-defined manner.

The expanded format (for all TZ s whose value does not have a colon as the first character) is as follows:

stdoffset[dst[offset][,start[/time],end[/time]]]
.....
=========================

I have quoted http://pubs.opengroup.org/onlinepubs/007904975/basedefs/xbd_chap08.html
I do not like this approach with changing TZ environment variable from netdata.

**Comment by zyxmon** [comment] 2017-04-18 10:57
After commenting out TZ environment change syslog is correct
https://github.com/Entware-for-kernel-3x/entware-packages-3x/commit/5f5e61d7c68e6a7602118292ea4e20681144b9e7

**Comment by ktsaou** [comment] 2017-04-18 14:43
You mean you have commented it in netdata source code?
Well... without it, if you strace netdata, you will see that libc is making excessive `stat()` calls to `/etc/localtime`, which may slow down netdata. This was the reason I added it in the first place.

I suggest to set it to something, for example: `:/opt/share/zoneinfo/Europe/Moscow`.

**Comment by zyxmon** [comment] 2017-04-18 14:50
The best place to setup environment variables is startup script. Your code will not run correctly in uclibc based distributions.

**Comment by ktsaou** [comment] 2017-04-18 14:52
ok. fair enough. I changed the code in netdata to set it only if it is not already set.
