### ISSUE TITLE
Feature request: JSON formatted 'allmetrics' endpoint

### ISSUE THREAD

**Issue by mahlonsmith** [firehol/netdata#1910] opened 2017-03-08 18:44 UTC
I haven't seen this suggested yet - I think it would be extremely helpful to receive a machine's status via structured data.  JSON seems the obvious choice, though that realistically doesn't matter as much as the structure.  The /v1/allmetrics?format={shell,prometheus} stuff is definitely useful, but being flat makes simple tasks for external probing less than ideal.

My end goal here is to replace Net-SNMP everywhere that is possible with netdata, and let it provide me the data that SNMP normally would.

**Comment by ktsaou** [comment] 2017-03-08 20:08
Well, netdata has an extensive API  to download data in a number of formats. Examples for `system.cpu`:

1. [last minute in json](http://london.my-netdata.io/api/v1/data?chart=system.cpu&after=-60&format=json)
2. [last minute in csv](http://london.my-netdata.io/api/v1/data?chart=system.cpu&after=-60&format=csv)
3. [last minute in tsv](http://london.my-netdata.io/api/v1/data?chart=system.cpu&after=-60&format=tsv)
4. [last minute in html](http://london.my-netdata.io/api/v1/data?chart=system.cpu&after=-60&format=html)

You can reduce the data by appending `&points=X&method=Y` where `X` is the number of points you want to get back for this duration and `Y` is `min`, `max`, `sum` or `average`.

You can flatten dimensions by giving dimensions as format `array`, `ssv`, `ssvcomma`, etc.

netdata is also a google [datatable](http://london.my-netdata.io/api/v1/data?chart=system.cpu&after=-60&format=datatable) and [datasource](http://london.my-netdata.io/api/v1/data?chart=system.cpu&after=-60&format=datasource). Check this [jsfiddle example](https://jsfiddle.net/ktsaou/ensu4uws/6/).

Check the [API documentation](https://github.com/firehol/netdata/wiki/REST-API-v1) for more details.

**Comment by mahlonsmith** [comment] 2017-03-08 21:26
Hey Costa, thanks! That's definitely along the lines of what I'm after, but let me elaborate a little more:

This works great for "static" chart names, such as "ipv4.errors".  For other stuff, here's what I was after.  Lets use disk availability as an example.  I want to get a structure of all disk data using as few round trips as possible.

For disk stats, since the keys are dynamically generated based on the mount name, what I'd currently need to do is hit /api/v1/charts, and get the names of the charts that start with "disk_avail".

Then for each one I'm interested in, enumerate on the /api/v1/chart?chart=[key] endpoint, for N calls.   This goes for network interface device names or any other metric, making an external probe requiring an initially unknown number of round trips.  Adding another metric doubles the round trips to netdata for charts you're interested in.  (avail + inode, etc)

The only endpoint (that I can see) that avoids this and gives me the data one nice big hit is allmetrics.

Optimally, something the pivots the keys, so you can drill into data without knowing the names in advance, like:

  * metrics['disk']['mounts']
  * metrics['disk_avail'][ mount ]
  * metrics['net']['packets'][ interface ]

Again, the structure itself is less important than getting it all in one hit, since figuring out chart names, interface devices, and cpu counts can take place after the data is available for easier processing.  That was an optimal example, after all.

Here's another idea... the /api/v1/charts endpoint returns a bunch of metadata about the chart itself, and among it is the last epoch time a value was written. Could it potentially also include the last value?

Just thinking out loud, I'd adore burying snmpwalk permanently.

Thanks for exploring with me.

**Comment by ktsaou** [comment] 2017-03-08 21:35
> get the names of the charts that start with "disk_avail"

you should examine the `context` of the chart. All the charts of the same template, have the same `context`.

> Here's another idea... the /api/v1/charts endpoint returns a bunch of metadata about the chart itself, and among it is the last epoch time a value was written. Could it potentially also include the last value?

So, you are just interested for the last value of them?

**Comment by mahlonsmith** [comment] 2017-03-08 21:40
> you should examine the context of the chart. All the charts of the same template, have the same context.

That does provide a nice categorization, but doesn't avoid the need for enumeration.

> So, you are just interested for the last value of them?

Yep.  Essentially the same information I'd receive from an snmpget/walk, or the allmetrics endpoint.  If I want longer term trend data, doing a separate call is absolutely fine (and that separation is honestly preferred.)

**Comment by ktsaou** [comment] 2017-03-08 21:49
ok, then I guess an `allmetrics` call for json is preferred.

**Comment by ktsaou** [comment] 2017-03-08 21:51
So, an object like:

```json

{
  chart1: {
    context: 'c1',
    dimensions: {
      dim1: value1,
      dim2: value2
    }
  },
  chart2: {
    context: 'c2',
    dimensions: {
      dim1: value1,
      dim2: value2
    }
  }
}
```

Do you need anything else?

**Comment by ktsaou** [comment] 2017-03-08 21:52
hm... and the last collected timestamp...

**Comment by mahlonsmith** [comment] 2017-03-08 22:16
Yes, I think that will do nicely.

I also noticed that the json generated for /data under disks (but not everything?) isn't generating epoch seconds, but JS data objects, making it not actually valid JSON:

```
http://[host]/api/v1/data?chart=disk_space._usr_local&after=-5&format=json
```

```
{
 "labels": ["time", "avail", "used", "reserved for root"],
    "data":
 [
      [ new Date(2017,2,8,14,2,43), 7.71719, 2.28281, 0],
      [ new Date(2017,2,8,14,2,42), 7.71719, 2.28281, 0],
      [ new Date(2017,2,8,14,2,41), 7.71719, 2.28281, 0],
      [ new Date(2017,2,8,14,2,40), 7.71719, 2.28281, 0],
      [ new Date(2017,2,8,14,2,39), 7.71719, 2.28281, 0]
  ]
}
```

If you like, I can submit a separate issue for that.

I'm really excited by netdata.  Thank you for your work on it!

**Comment by ktsaou** [comment] 2017-03-08 22:22
This is controlled by the `options` parameters. Just pass `options=seconds` (however I can't reproduce this on mine - are you using the current git version of netdata?)

**Comment by mahlonsmith** [comment] 2017-03-08 22:35
I was using the FreeBSD ports version, 1.5.0.  Didn't have the 'seconds' example in your links above ("last minute in json"), so ignore me -- false alarm!

**Comment by ktsaou** [comment] 2017-03-08 22:36
done. Test it at #1911

**Comment by mahlonsmith** [comment] 2017-03-08 23:16
Tested this out, it looks like it I can get at what I need.

Death to SNMP, long live netdata!!

**Comment by sarlalian** [comment] 2017-03-09 01:11
This is great!  Thank you.

**Comment by ktsaou** [comment] 2017-03-09 20:42
merged it!
thanks you for letting us know it works for you.

**Closed** 2017-03-09 20:41 UTC
Labels: enhancement, fixed
