### ISSUE TITLE
Error logs, what does it mean?

### ISSUE THREAD

**Issue by netchild** [firehol/netdata#1843] opened 2017-02-25 10:10 UTC
Hi,

this is based upon netdata 1.5.0 on FreeBSD.

This looks like programming/code errors:
 - ERROR: Number -4611686018427387838.0000000 is too big. (errno 2, No such file or directory)
 - ERROR: Health alarm 'system.swapio.30min_ram_swapped_out': expression '((($this / 1024) * 100) / (($system.ram.used + $system.ram.cached) + $system.ram.free))' failed: [ $this = 0 ] [ undefined variable 'system.ram.used' ] [ undefined variable 'system.ram.cached' ] [ undefined variable 'system.ram.free' ] ; failed to evaluate expression with error 105 (undefined variable) (errno 9, Bad file descriptor)

Bye,
Alexander.

**Comment by ktsaou** [comment] 2017-02-25 12:29
Thanks, both have been fixed in PR #1817

**Comment by ktsaou** [comment] 2017-02-25 12:30
not merged yet - testing it.

**Comment by ktsaou** [comment] 2017-02-26 12:25
merged it. Could you please confirm these are not appearing any more?

**Comment by netchild** [comment] 2017-02-28 18:50
Could you please point out a specific change? I would like to apply this to the installed 1.5.0 version (if possible) and test it there.

**Comment by ktsaou** [comment] 2017-02-28 19:11
> I would like to apply this to the installed 1.5.0 version (if possible) and test it there.

I suggest to wait a few days. I plan to release 1.6 this weekend.

**Comment by tomprogrammer** [comment] 2017-03-01 22:55
One of these error messages also appear in my logs:

2017-03-01 23:33:53: netdata: ERROR: Number 41214250109329744.0000000 is too big.

I've built netdata from git, version 1.5.0-485-g360b3624_rolling. That means the fix you mentioned is part of my binary. I guess you didn't expect that the error continue to appear.

**Comment by tomprogrammer** [comment] 2017-03-01 23:04
This may also the cause for an scrape error from prometheus:

The API endpoint `/api/v1/allmetrics?format=prometheus` returns:

```
# TYPE disk_qops_dm_0_operations gauge
disk_qops_dm_0_operations{instance="occulunculus_thomas_bahn_net"} 0 18446744071765061279
```

Prometheus complains that it `expected integer as timestamp, got "18446744071765192279"` which seems also to be an "value too big" error.

**Comment by ktsaou** [comment] 2017-03-01 23:36
hm... these 2 seem different.

1. `number too big` log: do you have many of them or just one? This is logged when netdata tries to store a normalized/interpolated number to its database that is above the [maximum supported value](https://github.com/firehol/netdata/blob/360b3624052e7a2a94a32b003fc61284d6083162/src/storage_number.h#L42) - As you can understand this is a really big value for a chart point (counters are converted to gauges when stored by netdata).

   What would be interesting to know, is if this happens all the time, or is it close to netdata loading an existing chart. I have seen unrealistic spikes when netdata starts, at the time it calculates the first point on the chart. So, it might be related to it.

2. This timestamp is fantastic. The calculation is [here](https://github.com/firehol/netdata/blob/360b3624052e7a2a94a32b003fc61284d6083162/src/rrd2json.c#L221).

   So, `rd->last_collected_time.tv_sec` is the number of seconds (unix timestamp) and `rd->last_collected_time.tv_usec` is the number of microseconds, of the last data collection. The second, takes values from 0 to 1000000 (i.e. up to 1 second). I just searched all the code. `rd->last_collected_time` is zeroed in 2 places and is updated to the current time here: https://github.com/firehol/netdata/blob/8246d10d2749734d15f8ad9c44c9a8f81850f33c/src/rrddim.c#L294-L294 - I am not sure how this could lead to this issue.


I see you are using `armv7`. Is you disk an sdcard? If these problems appear soon after you start netdata, it might be a faulty sdcard that reads back garbage from disk...

**Comment by tomprogrammer** [comment] 2017-03-01 23:59
The `number too big` messages occur all the time, interrupted by small pauses.

Example:
```
2017-03-02 00:30:31: netdata: ERROR: Number -1890043456797685760.0000000 is too big.
2017-03-02 00:30:31: netdata: ERROR: Number 886803503846106.5000000 is too big.
2017-03-02 00:30:31: netdata: ERROR: Number 425747077013728.6250000 is too big.
2017-03-02 00:31:56: netdata: ERROR: Number 44739167826432720.0000000 is too big.
2017-03-02 00:31:56: netdata: ERROR: Number -32249286110493080.0000000 is too big.
2017-03-02 00:31:56: netdata: ERROR: Number 3173589876921505792.0000000 is too big.
2017-03-02 00:31:57: netdata: ERROR: Number -24695674413516596.0000000 is too big.
2017-03-02 00:31:57: netdata: ERROR: Number 45079432536896880.0000000 is too big.
2017-03-02 00:31:57: netdata: ERROR: Number 26708768354512184.0000000 is too big.
2017-03-02 00:31:57: netdata: ERROR: Number -19252452697938928.0000000 is too big.
2017-03-02 00:31:57: netdata: ERROR: Number -3156660561556741120.0000000 is too big.
2017-03-02 00:31:57: netdata: ERROR: Number 1479166428794607.7500000 is too big.
2017-03-02 00:31:57: netdata: ERROR: Number 1898930043419191296.0000000 is too big.
2017-03-02 00:31:57: netdata: ERROR: Number 710162724274441.7500000 is too big.
2017-03-02 00:31:58: netdata: ERROR: Number -14729432663329276.0000000 is too big.
2017-03-02 00:31:58: netdata: ERROR: Number 26928990031071888.0000000 is too big.
2017-03-02 00:31:58: netdata: ERROR: Number -1889753147399529472.0000000 is too big.
2017-03-02 00:31:58: netdata: ERROR: Number 886638996794428.0000000 is too big.
2017-03-02 00:31:58: netdata: ERROR: Number 425684326762740.2500000 is too big.
2017-03-02 00:32:11: netdata: ERROR: Number 3255402927637374464.0000000 is too big.
2017-03-02 00:32:12: netdata: ERROR: Number 1934723991728710144.0000000 is too big.
2017-03-02 00:34:35: netdata: ERROR: Number 44732758808669312.0000000 is too big.
2017-03-02 00:34:35: netdata: ERROR: Number -32244666305128320.0000000 is too big.
2017-03-02 00:34:35: netdata: ERROR: Number 3170517405739287552.0000000 is too big.
2017-03-02 00:34:36: netdata: ERROR: Number -24694635844930720.0000000 is too big.
2017-03-02 00:34:36: netdata: ERROR: Number 45075980638987264.0000000 is too big.
2017-03-02 00:34:36: netdata: ERROR: Number 26715177372275592.0000000 is too big.
2017-03-02 00:34:36: netdata: ERROR: Number -19257072503303688.0000000 is too big.
2017-03-02 00:34:36: netdata: ERROR: Number -3156080127040402432.0000000 is too big.
2017-03-02 00:34:36: netdata: ERROR: Number 1478243223111227.7500000 is too big.
2017-03-02 00:34:36: netdata: ERROR: Number 1902002514601409536.0000000 is too big.
2017-03-02 00:34:36: netdata: ERROR: Number 709767159764280.1250000 is too big.
2017-03-02 00:34:37: netdata: ERROR: Number -14732395377264208.0000000 is too big.
2017-03-02 00:34:37: netdata: ERROR: Number 26932441928981504.0000000 is too big.
2017-03-02 00:34:37: netdata: ERROR: Number -1890579872520489984.0000000 is too big.
2017-03-02 00:34:37: netdata: ERROR: Number 887403288688819.0000000 is too big.
2017-03-02 00:34:37: netdata: ERROR: Number 426079891272900.8750000 is too big.
2017-03-02 00:35:11: netdata: ERROR: Number 44737859134023664.0000000 is too big.
2017-03-02 00:35:11: netdata: ERROR: Number -32248342767154784.0000000 is too big.
2017-03-02 00:35:11: netdata: ERROR: Number 3172419823479769600.0000000 is too big.
2017-03-02 00:35:12: netdata: ERROR: Number -24696384444903504.0000000 is too big.
2017-03-02 00:35:12: netdata: ERROR: Number 45079031645353976.0000000 is too big.
2017-03-02 00:35:12: netdata: ERROR: Number 26710077046921232.0000000 is too big.
2017-03-02 00:35:12: netdata: ERROR: Number -19253396041277224.0000000 is too big.
2017-03-02 00:35:12: netdata: ERROR: Number -3156211394511904768.0000000 is too big.
2017-03-02 00:35:12: netdata: ERROR: Number 1478645687509382.7500000 is too big.
2017-03-02 00:35:12: netdata: ERROR: Number 1900100096860927488.0000000 is too big.
```

The `/var` directory is on an USB hard disk, only `/` is on a sd card. Nevertheless I've moved the netdata database files (in `/var/cache/netdata/`) to a backup location and configured netdata to use another partition of the same disk (I don't have a spare disk to test). If that helps I'll revert to the previous setup and let you know my findings.

In the first ten minutes I didn't see any "number too big" errors, but the extremely big timestamps remain. Do you prefer opening a new issue for that, or should we continue here?

**Comment by ktsaou** [comment] 2017-03-02 07:30
Do these come from an PRi 2/3? I have 4x RPi2 running here, and I never had such a log.
Can you identify the chart that has these huge spikes?

**Comment by tomprogrammer** [comment] 2017-03-02 10:53
Im running two RPi 2 and could identify the graphs showing unrealistically high measurements on both machines. I use archlinuxarm with kernel 4.9.13 on them.
They all have to do with IPv6, which I use in my network. The graphs are:

 * system.ipv6
 * ipv6.ect
 * ipv6.fragsout
 * ipv6.bcast
 * ipv6.mcast
 * ipv6.mcastpkts

The chart ipv6.packets works as expected.

![system_ipv6](https://cloud.githubusercontent.com/assets/57975/23503805/68ee3300-ff3d-11e6-90ba-f118408f7881.png)
![ipv6_ect](https://cloud.githubusercontent.com/assets/57975/23503804/68c59a44-ff3d-11e6-929a-e0f0e5f538f2.png)

**Comment by ktsaou** [comment] 2017-03-02 21:25
> EDIT: I've checked /proc/net/snmp6 and saw the high values already there. So it seems not to be netdata's fault.

nice finding... I started thinking of what should I have missed for this to happen...

The timestamp is also problematic. It should never happen. There is a simple fix to hide it from netdata but I am not sure we should hide it... Could you please check if the prometheus output has more such timestamps? Does it only happen on `disk_qops_dm_0_operations` or it randomly appearing at more metrics?

@netchild I checked by freebsd installations and I see I have one `number too big` log line per day or two. I will try to trace it. It seems related to some value collected from freebsd. @vlvkobal note this.

The following output comes from https://freebsd.my-netdata.io . It is always a negative number. I will try to check which chart generates this.

```
2017-02-01 03:01:10: netdata: ERROR: Number -60680079189834048.0000000 is too big. (errno 2, No such file or directory)
2017-02-02 03:01:02: netdata: ERROR: Number -194176253407468956.0000000 is too big. (errno 2, No such file or directory)
2017-02-02 12:29:10: netdata: ERROR: Number -498560650640798665.0000000 is too big. (errno 2, No such file or directory)
2017-02-04 03:39:32: netdata: ERROR: Number -33785245556244598.0000000 is too big. (errno 2, No such file or directory)
2017-02-04 04:15:15: netdata: ERROR: Number -39165061727621126.0000000 is too big. (errno 2, No such file or directory)
2017-02-04 04:15:19: netdata: ERROR: Number -50817476787078652.0000000 is too big. (errno 2, No such file or directory)
2017-02-05 13:44:36: netdata: ERROR: Number -392483916461905332.0000000 is too big. (errno 2, No such file or directory)
2017-02-07 03:01:02: netdata: ERROR: Number -307445734561825847.0000000 is too big. (errno 2, No such file or directory)
2017-02-09 03:09:49: netdata: ERROR: Number -419244183493398877.0000000 is too big. (errno 2, No such file or directory)
2017-02-11 04:15:10: netdata: ERROR: Number -329406144173384835.0000000 is too big. (errno 2, No such file or directory)
2017-02-11 04:15:17: netdata: ERROR: Number -26465916891979269.0000000 is too big. (errno 2, No such file or directory)
2017-02-11 08:23:42: netdata: ERROR: Number -409927646082434459.0000000 is too big. (errno 2, No such file or directory)
2017-02-11 12:33:11: netdata: ERROR: Number -384307168202282304.0000000 is too big. (errno 2, No such file or directory)
2017-02-13 03:47:40: netdata: ERROR: Number -188232082384791333.0000000 is too big. (errno 2, No such file or directory)
2017-02-14 10:05:53: netdata: ERROR: Number -428994048225803502.0000000 is too big. (errno 2, No such file or directory)
2017-02-16 03:01:01: netdata: ERROR: Number -614891469123651694.0000000 is too big. (errno 2, No such file or directory)
2017-02-18 04:15:12: netdata: ERROR: Number -3689348814741910141.0000000 is too big. (errno 2, No such file or directory)
2017-02-18 04:54:07: netdata: ERROR: Number -376464164769582666.0000000 is too big. (errno 2, No such file or directory)
2017-02-18 09:54:26: netdata: ERROR: Number -472993437787424375.0000000 is too big. (errno 2, No such file or directory)
2017-02-19 03:01:02: netdata: ERROR: Number -401016175515425018.0000000 is too big. (errno 2, No such file or directory)
2017-02-23 03:01:01: netdata: ERROR: Number -498560650640798673.0000000 is too big. (errno 2, No such file or directory)
2017-02-24 03:01:01: netdata: ERROR: Number -368934881474191017.0000000 is too big. (errno 2, No such file or directory)
2017-02-25 03:01:01: netdata: ERROR: Number -614891469123651694.0000000 is too big. (errno 2, No such file or directory)
2017-02-25 04:15:24: netdata: ERROR: Number -3689348814741910146.0000000 is too big. (errno 2, No such file or directory)
2017-02-26 16:05:26: netdata: ERROR: Number -498560650640798665.0000000 is too big. (errno 2, No such file or directory)
2017-03-01 14:53:07: netdata: ERROR: Number -401016175515425013.0000000 is too big. (errno 2, No such file or directory)
```

**Comment by tomprogrammer** [comment] 2017-03-03 15:29
Every metric in the prometheus output has the huge timestamps (on both RPi2 and even my x86_64 PC). I've checked that irregularly over some hours. Then I built netdata including your clock fixes. Prometheus can scrape the output now, it looks like:
```
system_cpu_user{instance="occulunculus_thomas_bahn_net"} 817122 1488554134125
# TYPE system_cpu_system counter
system_cpu_system{instance="occulunculus_thomas_bahn_net"} 362041 1488554134125
# TYPE system_cpu_nice counter
system_cpu_nice{instance="occulunculus_thomas_bahn_net"} 0 1488554134125
# TYPE system_cpu_iowait counter
system_cpu_iowait{instance="occulunculus_thomas_bahn_net"} 9271 1488554134125
# TYPE system_cpu_idle counter
system_cpu_idle{instance="occulunculus_thomas_bahn_net"} 21751447 1488554134125
```
```
Before:           18446744071765192279
With clock fixes:        1488554134125
```

I also analyzed the problem "number is too big" and found that it's a regression from linux 4.4.49 to linux 4.9.13 (ArchlinuxARM). Which version of the kernel are you using on your RPi's? Maybe that explains why you don't observe the error messages. I guess I should file a bug on the linux kernel.

**Comment by ktsaou** [comment] 2017-03-03 18:40
ok. I will merge it with PR #1887

> Which version of the kernel are you using on your RPi's? Maybe that explains why you don't observe the error messages. I guess I should file a bug on the linux kernel.

I just checked. All of them are various 4.4.x prior to 4.4.49

**Comment by ktsaou** [comment] 2017-03-03 23:00
merged it.

**Comment by ktsaou** [comment] 2017-03-18 09:48
I think we have fixed this, so I am closing it.
If I am wrong, please post.

**Closed by ktsaou** 2017-03-18 09:48 UTC
Labels: bug, fixed

**Comment by andyforceno** [comment] 2017-10-08 22:02
I am seeing this error, it's filling my logs on one of the hosts that runs netdata. Netdata was installed using the kickstart script, the same as the other hosts. This particular machine is running Ubuntu Server 17.04. 

    2017-10-08 17:46:17: netdata ERROR: Number 2487531516957368921.7500000 is too big.
    2017-10-08 17:46:18: netdata ERROR: Number -1271711410612273.2468262 is too big. 
    2017-10-08 17:46:18: netdata ERROR: Number 752143386722461185.2500000 is too big.
    2017-10-08 17:46:35: netdata ERROR: Number 3254444559072053492.0000000 is too big.
    2017-10-08 17:46:36: netdata ERROR: Number 305383259272297215.8125000 is too big.
    2017-10-08 17:46:36: netdata ERROR: Number 975808914363687948.0000000 is too big.
    2017-10-08 17:46:37: netdata ERROR: Number 89910025819604224.1875000 is too big.
    2017-10-08 17:46:51: netdata Too many logs (201 logs in 610 seconds, threshold is set to 200 logs in 
    1200 seconds). Preventing more logs from process 'netdata' for 590 seconds.
    2017-10-08 17:57:21: netdata Resuming logging from process 'netdata' (prevented 339 logs in the last    
    1200 seconds).

**Comment by ktsaou** [comment] 2017-10-08 22:26
We should probably disable these errors.

The problem is that certain kernel versions report a few metrics (mainly ipv6 packet counters) that jump randomly across the whole 64bit number range. So, at ` t - 1 ` the counter says 10 packets, and at ` t ` it says 18446744073709551615 packets!

While netdata tries to manage these deltas, it detects that its internal structures cannot fit them and it logs these errors. The max delta netdata can handle is plus or minus 167772150000000, which is a truly big delta for a second of time.

So, until we disable them, you can just ignore them.
