### ISSUE TITLE
Netdata segfault (version: 1.9.0-541-g60078529_rolling)

### ISSUE THREAD

**Issue by nirmalthacker** [firehol/netdata#3507] opened 2018-03-05 22:50 UTC
Hi, 
I am new to netdata and currently evaluating it for a project I am working on. So far I am liking what I see, and netdata fits into my requirements perfectly.

However I noticed a segfault recently. The systemd service restarted it and there wasn't another segfault after. I am using a statically compiled binary for x86_64 Linux. My host OS is Ubuntu 16.04. 

Logs are below. I'd like to know:
- Any other information I can provide regarding this failure, assuming its not already a known and fixed issue
- Is there a version I should use that is considered 'stable'. I'd like to use netdata in a production environment

Thanks!

Version of netdata: 

> sudo /opt/netdata/bin/netdata -v
> netdata 1.9.0-541-g60078529_rolling
> 

Relevant logs from /var/log/syslog:

> Mar  5 14:39:58 localhost systemd[1]: Starting Real time performance monitoring...
> Mar  5 14:39:58 localhost systemd[1]: Started Real time performance monitoring.
> Mar  5 14:39:58 localhost kernel: [260152.134463] netdata[24678]: segfault at 18 ip 00007f10566355a8 sp 00007f1056873228 error 6 in netdata[7f105659e000+da000]
> Mar  5 14:40:00 localhost systemd[1]: netdata.service: Main process exited, code=killed, status=11/SEGV
> Mar  5 14:40:00 localhost systemd[1]: netdata.service: Unit entered failed state.
> Mar  5 14:40:00 localhost systemd[1]: netdata.service: Failed with result 'signal'.
> Mar  5 14:40:30 localhost systemd[1]: netdata.service: Service hold-off time over, scheduling restart.
> Mar  5 14:40:30 localhost systemd[1]: Stopped Real time performance monitoring.
> Mar  5 14:40:30 localhost systemd[1]: Starting Real time performance monitoring...
> Mar  5 14:40:30 localhost systemd[1]: Started Real time performance monitoring.
>

**Comment by ktsaou** [comment] 2018-03-05 23:49
Hi,

hm... the current repo is about to be released as v1.10, so it is pretty stable (actually it always is - we never commit untested code, although there are cases we didn't encounter an issue during testing and it gets merged).

You can of course use the v1.9 (although v1.10 is better in all aspects of it).

Regarding the crash, the only way to trace this, is if it is reproducible. I can provide you with a netdata binary with debugging enabled which you will have to run through `valgrind`. With this procedure, when the crash happens we will get the exact point in the code that triggered this. But we need it to crash in order to find it.

So, I suggest to check if this happens again. If it does, I'll provide you everything required to trace it.

**Comment by ktsaou** [comment] 2018-03-05 23:51
I see from the logs you posted, this crash happened immediately after netdata was started.
Can you restart it a few times to see if this is triggered again?

**Comment by ktsaou** [comment] 2018-03-05 23:52
Also, is this a cloud VM or a physical server?

**Comment by ktsaou** [comment] 2018-03-05 23:59
Just installed ubuntu 16.04 lts and updated it.
I 'll leave it running the following for some time:

```sh
while [ 1 ]; do systemctl restart netdata; sleep 2; done
```

So far it hasn't crashed.

**Comment by nirmalthacker** [comment] 2018-03-06 00:19
This is a physical machine : Intel NUC Kit NUC6i7KYK 

I was able to replicate the segfault, running: 

`while [ 1 ]; do service netdata restart ; sleep 10; done
`
> Mar  5 16:11:29 localhost systemd[1]: Stopping Real time performance monitoring...
> Mar  5 16:11:30 localhost systemd[1]: Stopped Real time performance monitoring.
> Mar  5 16:11:30 localhost systemd[1]: Starting Real time performance monitoring...
> Mar  5 16:11:30 localhost systemd[1]: Started Real time performance monitoring.
> Mar  5 16:11:32 localhost systemd[1]: Stopping Real time performance monitoring...
> Mar  5 16:11:32 localhost systemd[1]: Stopped Real time performance monitoring.
> Mar  5 16:11:32 localhost systemd[1]: Starting Real time performance monitoring...
> Mar  5 16:11:32 localhost systemd[1]: Started Real time performance monitoring.
> Mar  5 16:11:32 localhost kernel: [265645.587592] netdata[28052]: segfault at 10 ip 00007fc18885b5a0 sp 00007fc1889b3d38 error 6 in netdata[7fc1887c4000+da000]
> Mar  5 16:11:33 localhost systemd[1]: netdata.service: Main process exited, code=killed, status=11/SEGV
> Mar  5 16:11:33 localhost systemd[1]: netdata.service: Unit entered failed state.
> Mar  5 16:11:33 localhost systemd[1]: netdata.service: Failed with result 'signal'.

**Comment by ktsaou** [comment] 2018-03-06 00:48
ok, before proceeding, could you please run a memory check on that machine?
On my installation, I can't reproduce this.

If the machine passes the memory test, I'll prepare a package for you to run.

**Comment by nirmalthacker** [comment] 2018-03-06 01:11
That's fair. I'll do that and update this thread

**Comment by nirmalthacker** [comment] 2018-03-06 19:53
There is an issue with this hardware. We should close this bug

**Closed** 2018-03-06 19:54 UTC
Labels: bug, need reproduction
