### ISSUE TITLE
Netdata unable to send data over to Grafana Dashboard.

### ISSUE THREAD

**Issue by sohwaje** [firehol/netdata#2777] opened 2017-09-22 07:48 UTC
Hi.
I installed netdata to A_SERVER.
I installed influxdb, Grafana to B_SERVER.

1. target netdata machine is A_SERVER
/etc/netdata/netdata.conf
[backend]
        enabled = yes
        type = opentsdb
        host tags = 
        destination = tcp:B_SERVER:8086
        data source = average
        prefix = isweb09
        hostname = isweb09
        update every = 10
        buffer on failures = 10
        timeout ms = 20000
        send charts matching = *
        send names instead of ids = yes

2. I set it up influxdb and Grafana.
3. also set it up as below
![1](https://user-images.githubusercontent.com/19942049/30734295-8db98b62-9fb5-11e7-886f-6a5dec51b814.JPG)
![2](https://user-images.githubusercontent.com/19942049/30734300-9241467a-9fb5-11e7-9d78-776032f9db03.JPG)

4. But!!
netdata errorlog
2017-09-22 16:44:55: netdata ERROR: BACKEND: failed to write data to database backend 'tcp:B_SERVER:8086'. Willing to write 166929 bytes, wrote 49640 bytes. Will re-connect.

**Comment by critaL** [comment] 2017-09-22 09:48
In influxdb.conf you have to enable opentsdb for this to work.

**Comment by ktsaou** [comment] 2017-09-22 20:29
Closing this as duplicate of #2769 
Thank you @critaL !

**Closed by ktsaou** 2017-09-22 20:29 UTC
Labels: duplicate, question

**Comment by sohwaje** [comment] 2017-09-25 01:51
I had it. But it was the same.

![default](https://user-images.githubusercontent.com/19942049/30789297-74b6066e-a1df-11e7-996b-16f5a427d4fa.JPG)

**Comment by ktsaou** [comment] 2017-09-26 21:31
@sohwaje your netdata is configured to send the metrics to `tcp:B_SERVER:8086` but your influxdb is configured to listen to `:4242`.

In general, opentsdb protocol is very simple. If you get the ports and hosts right, it will just work.
