### ISSUE TITLE
web_log reports unmatched lines

### ISSUE THREAD

**Issue by Komic** [firehol/netdata#2780] opened 2017-09-22 16:36 UTC
```txt
example.org:443 xxx.xxx.xxx.xxx - - [22/Sep/2017:15:27:03 +0200] "-" 408 160 "-" "-"
```
seems to be the culprit

**Comment by ktsaou** [comment] 2017-09-22 20:06
The issue with parsing errors 408 is already fixed in PR #2693 
Could you please check if that PR fixes it for you?

I understand `example.org:443` has been edited by you. What was there? A hostname or an IP? Did it have the port too? The default parser expects an IP there (without a port).

duplicate of #2201 #2675
cc: @l2isbad

**Closed by ktsaou** 2017-09-22 20:06 UTC
Labels: duplicate

**Comment by Komic** [comment] 2017-09-22 22:54
> I understand `example.org:443` has been edited by you.

Yeah, the original had my server's main domain there.

**Comment by Komic** [comment] 2017-09-23 00:03
Got a new unmatched on `example.org:443 xxx.xxx.xxx.xxx - - [23/Sep/2017:01:23:49 +0200] "" 400 3582 "-" "-"`
Haven't seen an unmatched 408 yet though. 400s are slightly different so maybe the fix won't work for those?

**Comment by l2isbad** [comment] 2017-09-23 01:03
@Komic 
https://github.com/firehol/netdata/pull/2693/commits/02f5a1514c4d52ca91347015d1cf3bf67bdbf03a

**Comment by Komic** [comment] 2017-09-23 02:30
looking good 👍

**Comment by Komic** [comment] 2017-09-23 17:43
Nothing since https://github.com/firehol/netdata/commit/02f5a1514c4d52ca91347015d1cf3bf67bdbf03a, think this is good to merge.
