### ISSUE TITLE
Statsd counters/gauges stuck on -167,772,150,000,000

### ISSUE THREAD

**Issue by FedericoCeratto** [firehol/netdata#3978] opened 2018-07-18 14:58 UTC
Newly created counters and gauges on Netdata v1.9.1_rolling seem to be initialized on -167,772,150,000,000

The source is: https://github.com/atlassian/gostatsd - using TCP transport

Incoming metrics captured on tcpdump:
```
package_version_tracker.github.rate_limit_remaining:4.000000|g|#,s:172.16.92.5
package_version_tracker.github.commits_fetched:0|c|#,s:172.16.92.5
package_version_tracker.github.pages_scanned:0|c|#,s:172.16.92.5
```

**Comment by ktsaou** [comment] 2018-07-18 15:52
hm... can you help me reproduce this?

Check this:

```sh
# cat /tmp/statsd.txt 
package_version_tracker.github.rate_limit_remaining:4.000000|g|#,s:172.16.92.5
package_version_tracker.github.commits_fetched:0|c|#,s:172.16.92.5
package_version_tracker.github.pages_scanned:0|c|#,s:172.16.92.5

# cat /tmp/statsd.txt | netcat -N -w 1 localhost 8125
```

produces this:

![image](https://user-images.githubusercontent.com/2662304/42892863-91102130-8abb-11e8-9600-ea479bf7b185.png)

**Comment by ktsaou** [comment] 2018-07-18 18:49
hm... probably.
Here is the format they use: https://docs.datadoghq.com/developers/dogstatsd/datagram_shell/#metrics

let me check if I can make netdata parse the tags too, although it won't be able to anything with them yet.

**Comment by ktsaou** [comment] 2018-07-18 18:56
ok, here it is. Of course netdata does not use the tags, because it cannot do anything with them currently.

**Comment by ktsaou** [comment] 2018-07-18 19:09
merged it. Tags will not interfere any more...

**Closed** 2018-07-18 19:08 UTC
Labels: bug, fixed

**Comment by FedericoCeratto** [comment] 2018-07-18 21:16
@ktsaou thank you so much!
