### ISSUE TITLE
postgres: per database metrics are wrong

### ISSUE THREAD

**Issue by dblugeon** [firehol/netdata#1750] opened 2017-02-09 08:01 UTC
Hello Netdata commiters,

Yesterday, I had tried Netdata and I found a bug in Postgres plugin.

4 probes about indexes and tables (count and size) works only where statements are executed on current database. In our case, only on postgres database. These probes must be execute on each databases of the cluster to provide good information.

Regards.

**Comment by csamsel** [comment] 2017-02-09 08:10
You can configure the credentials netdata uses to connect to suit your needs.

**Comment by ktsaou** [comment] 2017-02-09 20:57
@dblugeon if I understand it right, you say that when postgres is running in cluster (I don't know what a postgres cluster is - excuse my ignorance) and netdata monitors the cluster as a whole (i.e. there is just one set of postgres charts at the netdata dashboard), then the values presented by netdata about indexes and tables come from one of the nodes of the postgres cluster.

Right?

Well, if this is the case, the problem is at the postgres server. netdata just asks for the metrics and the postgres server responds with incorrect information.

These are the postgres queries run by netdata: https://github.com/firehol/netdata/blob/40619866060663fecf814939b2dbb8615d761c76/python.d/postgres.chart.py#L20-L98

I don't know if we can alter these queries to get the metrics of both nodes of the cluster.

If there is no way to do it like that and you can configure both nodes of the cluster at [/etc/netdata/python.d/postgres.conf](https://github.com/firehol/netdata/blob/master/conf.d/python.d/postgres.conf), then this is your solution. Just configure 2 postgres instances and you will get 2 sets of postgres charts, one for each node.

Of course, if there is any other way, I'll be glad to make netdata get the metrics right.

**Comment by dblugeon** [comment] 2017-02-10 09:02
Hello everybody,

thanks for your replies.

@ktsaou : In postgres terminology, a postgres cluster is an instance of this SGBD. In a postgres instance, it can have many databases.

Each database has his own system catalog. Certain information has common for example the pg_stat_activity view return same rows on all databases of the cluster. However, the pg_class table content is unique per database.

The queries is good. To provide this information for each database in instance, a new connection on each database must be used. Indeed, a connection on one database can't query another database on the same postgres instance.

The workaround can be used, but we can have duplicate information. Update the plugin seems preferable to me.

I hope that I am clearer in my explications

Regards

**Comment by ktsaou** [comment] 2017-02-10 09:10
oh! ok. I see.

@l2isbad what do you think?

**Comment by ktsaou** [comment] 2017-02-10 09:12
cc: @moumoul @facetoe guys have a look at this. If anyone is willing to make a PR, please do so...

**Comment by l2isbad** [comment] 2017-02-10 09:19
@dblugeon 

> Update the plugin seems preferable to me.

Can you describe what the plugin logic should be in case of "cluster"?

databases to connect, queries to execute, what number of databases can be.

**Comment by facetoe** [comment] 2017-02-10 09:51
@l2isbad the core of this issue is that the postgres plugin uses a single connection to a single database in the cluster to report data on all databases in the cluster, however the index/table statistics are for only the "current" database, ie the one used to connect to the cluster.

**Comment by dblugeon** [comment] 2017-02-10 13:22
Hello @I2isbad

> Can you describe what the plugin logic should be in case of "cluster"?

As today, the plugin should provide health status about postgres instance and (eventually) about databases hosted by it.

> 
> And what is wrong with 'workaround' ? You can specify any number of databases in plugin configuration file you want to connect to and collect metrics.
> 
>     we can have duplicate information
> 
> Is that only reason 'workaround' don't suits you?

As say @facetoe, the index/table statistics is misleading. At the beginning, I believed that is the total size/number of the whole instance. After tests and reading the plugin code, I understand that statistics is only about postgres database.

Adding more connection for each database on the same instance duplicate db_stat_* graph. If the instance has ten databases or more, it's not very good to use.

If I can make some propositions : 
1. update the plugin to display the sum of index stats and table stats of all database (needs many connection) 
2. update the plugin to display the sum of index stats and table stats per database, display as like *db_stat_* probes (needs many connection)
3. update the plugin to display size of database (reuse the same connection that today used plus the pg_stat_database view and pg_database_size function). This information can be displayed per database or for the whole cluster.

**Comment by l2isbad** [comment] 2017-02-11 13:17
If no one will fix the bug, I'll see what I can do here later. After `mongodb` and `ceph` plugins.

**Comment by ktsaou** [comment] 2017-02-11 16:27
@l2isbad you rock!
(guys, If of course any one else is willing to help, please do so)

**Comment by l2isbad** [comment] 2017-03-01 08:52
> 3. update the plugin to display size of database (reuse the same connection that today used plus the pg_stat_database view and pg_database_size function). This information can be displayed per database or for the whole cluster.

I see [pg_stat_database](https://github.com/firehol/netdata/blob/master/python.d/postgres.chart.py#L52-L69) executes for all databases

pg_database_size
```python
cursor.execute("SELECT pg_database.datname, pg_database_size(pg_database.datname) AS size FROM pg_database WHERE NOT datname ~* '^template\d+';")

cursor.fetchall()
[['postgres', 7232024],
['test_database', 7272984],
['test_database2', 7119364],
['test_database3', 7119364]]
```

I can add stacked chart. Is that what you want? @dblugeon

**Comment by facetoe** [comment] 2017-03-01 09:22
Good find @l2isbad. You should be able to add this to the existing `pg_stat_database query` - https://github.com/firehol/netdata/blob/master/python.d/postgres.chart.py#L52. 

Unfortunately this statistic isn't a drop in replacement for the Index and Table metrics (although it is definitely a good one to have). There is also `pg_table_size` and `pg_index_size`, I guess it should be possible to calculate the total Index/Table sizes for the database with these functions however whether or not it is feasible depends on how expensive those queries are.

**Comment by l2isbad** [comment] 2017-03-02 06:12
https://github.com/firehol/netdata/pull/1877

**Comment by l2isbad** [comment] 2017-03-02 06:52
@facetoe What about [DATABASE_LOCKS](https://github.com/firehol/netdata/blob/master/python.d/postgres.chart.py#L72-L81) ? Looks like it's only true for database to which you are connected. Or not?

```
postgres-# ORDER BY datname, mode;
 database_name |      mode       | count 
---------------+-----------------+-------
 postgres      | AccessShareLock |     1


test_database-# ORDER BY datname, mode;
 database_name |      mode       | count 
---------------+-----------------+-------
 test_database | AccessShareLock |     1
```

**Comment by facetoe** [comment] 2017-03-03 00:07
No it is per database (https://www.postgresql.org/docs/9.3/static/view-pg-locks.html). It is joined on the `oid`.

**Comment by ktsaou** [comment] 2017-03-18 09:46
I think this is fixed (thank you @l2isbad ).
I am closing it, but if something remains, please post.

**Closed by ktsaou** 2017-03-18 09:46 UTC
Labels: bug, fixed
