### ISSUE TITLE
Cross-Origin Resource sharing policy

### ISSUE THREAD

**Issue by ashyjaggs** [firehol/netdata#1109] opened 2016-10-13 13:27 UTC
Hi,

I m running netdata server on my https://sub.domain.com and my website on http://ABCDEFG.cloudfront.net. I have used custom dashboard and want netdata graphs to be hosted on my website i added the code but when I run my website in browser I get the following error: 

http://ABCDEFG.cloudfront.net' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://sub.domain.com' is therefore not allowed

I m running my website using SimpleHTTPServer module of python please advice me.

Thanks,
Ashish J

**Comment by ktsaou** [comment] 2016-10-13 14:32
Can you post the http request and response headers? Use your web browser console to get them.

**Comment by ashyjaggs** [comment] 2016-10-13 15:13
Here is the error from browser console:

Font from origin 'http://netdata-server:19999' has been blocked from loading by Cross-Origin Resource Sharing policy: The 'Access-Control-Allow-Origin' header has a value 'http://mywebsite.com:8888' that is not equal to the supplied origin. Origin 'http://mywebsite.com:8888' is therefore not allowed access.
LoginController.js:14 Submit button clicked
angular.js:12011 XHR finished loading: GET "http://mywebsite.com:5005/".(anonymous function) @ angular.js:12011sendReq @ angular.js:11776serverRequest @ angular.js:11571processQueue @ angular.js:16383(anonymous function) @ angular.js:16399$eval @ angular.js:17682$digest @ angular.js:17495$apply @ angular.js:17790(anonymous function) @ angular.js:25890dispatch @ jquery-2.2.1.min.js:3r.handle @ jquery-2.2.1.min.js:3
DashboardController.js:11 [Object]

**Comment by ashyjaggs** [comment] 2016-10-13 15:17
Just a note I have embedded the graph code into my website html page. I haven't created explicit html file as suggested in Custom dashboard link. Since I need to display them in a panel on my website page.

**Comment by ktsaou** [comment] 2016-10-13 15:34
CORS works like this:

1. the client sends the HTTP header `Origin: URL`
2. the server responds with HTTP header `Access-Control-Allow-Origin: URL`

netdata already does this properly.
So, I guess that the URL your site sends as `Origin: URL` is not valid.

Could you please find the exact headers sent to and received from netdata?
Press Control-F12 on your browser, switch to the network tab, find the first request sent to netdata and post here the request and response headers.

**Comment by ktsaou** [comment] 2016-10-13 17:55
Example request:

```
GET http://10.11.12.1:19999/api/v1/chart?chart=tc.world_out&_=1476381162611 HTTP/1.1
Host: 10.11.12.1:19999
Proxy-Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: */*
Origin: http://box                <<<<<< the origin the browser sends
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
Referer: http://box/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-GB,en;q=0.8,el;q=0.6
```

Example response:

```
HTTP/1.1 200 OK
Server: NetData Embedded HTTP Server
Access-Control-Allow-Origin: http://box      <<<< netdata responded with this
Access-Control-Allow-Credentials: true
Content-Type: application/json; charset=utf-8
Date: Thu, 13 Oct 2016 17:52:43 GMT
Cache-Control: public
Expires: Fri, 14 Oct 2016 17:52:43 GMT
Content-Encoding: gzip
Transfer-Encoding: chunked
Connection: keep-alive
```

**Comment by broncha** [comment] 2016-10-19 10:17
Here are different responses from different servers:

response to OPTIONS request to server http://sanfrancisco.netdata.rocks/api/v1/data?chart=netdata.requests&format=array&points=300&group=average&options=absolute|jsonwrap|nonzero&after=-300&_=1476871588369
```
Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:accept, x-requested-with, origin, content-type, cookie, pragma, cache-control
Access-Control-Allow-Methods:GET, OPTIONS
Access-Control-Allow-Origin:http://192.168.1.9
```


response to OPTIONS request to our server
```
Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:accept, x-requested-with, origin, content-type, cookie
Access-Control-Allow-Methods:GET, OPTIONS
Access-Control-Allow-Origin:http://192.168.1.9
```

We installed netdata 2 days ago. You can see pragma and cache-control headers are not supported  by our server (default configuration)

**Comment by ktsaou** [comment] 2016-10-19 11:23
If you update your netdata you will have them. These headers were added in an attempt to force the browser not lookup its local cache for these requests. If you are using the same version of netdata everywhere, this should not be a problem.

Your browser complains that:

> Font from origin 'http://netdata-server:19999' has been blocked from loading by Cross-Origin Resource Sharing policy: The 'Access-Control-Allow-Origin' header has a value 'http://mywebsite.com:8888' that is not equal to the supplied origin. Origin 'http://mywebsite.com:8888' is therefore not allowed access.

What we need to verify is that the URL supplied by your browser at `Origin` header of the requests is equal to the URL supplied by netdata at the `Access-Control-Allow-Origin` of the response.

What you have posted above is 2 different responses. To verify netdata works properly we need a request and a response.

I think we will find out that netdata responds properly. So, the problem is somewhere else. A setting in angular maybe prevents CORS, or a browser plugin interferes with CORS.

**Comment by ktsaou** [comment] 2016-11-02 23:19
Did you solve it? Can we close this issue?

**Comment by ktsaou** [comment] 2016-12-21 20:46
Cleaning up. I am closing this, but if you need help, please post and I'll re-open it.

**Closed by ktsaou** 2016-12-21 20:46 UTC
Labels: question
