### ISSUE TITLE
netdata upgrade to 1.7 breaks Grafana charts

### ISSUE THREAD

**Issue by BrainDoctor** [firehol/netdata#2521] opened 2017-07-26 13:51 UTC
So I was updating netdata from 1.6 to 1.7 the other day. I had already a backend attached (graphite/influxdb) and grafana on top of it.

the backend section in netdata.conf was:
```
[backend]
        enabled = yes
        data source = average
        type = graphite
        destination = influxdb.intern:2006
        prefix = netdata
        hostname = vmm-1
        update every = 60
        buffer on failures = 10
        timeout ms = 20000
        send charts matching = *
```
After update it was the same, however the Grafana charts stopped displaying, since the dimensions changed the names:
![2017-07-26_154240](https://user-images.githubusercontent.com/12159026/28624317-15af8a46-7219-11e7-8981-104e26eb680d.png)
In the picture, the metrics named `...autonomy.Autonomy` (name) and `...autonomy.rel_autonomy` (id) refer to the same data, but are named differently.

I discovered that I had to add the line `send names instead of ids = no` in the backend config:
```
[backend]
        ...
        send names instead of ids = no
```

So by default, names are sent instead of IDs. Shouldn't the default be `no` to not break existing external charts? Luckily I discovered that soon enough and I only lost a couple of minutes, but others might detect this too late. What do you guys think? Is that by design? I intend to keep some data for 3 years, so compatibility/default settings should be considered carefully.

**Comment by ktsaou** [comment] 2017-07-26 19:24
Hi,

you are right. We had this problem:

1. Either all the old installations will get names instead of IDs, introducing this problem.

or 

2. All new users will also get IDs by default and when they realize they need names, they will suddenly understand they will have to loose all their data to make this change.

I chose to penalize old installations for just one reason: you really need to get names in the backend db. If you don't, then a lot of metrics will be just meaningless (QoS classes, dev-mapper disks, etc). So, the right setting for netdata should be `send names instead of ids = yes`. Unfortunately this functionality did not exist in netdata 1.6, so here we are...

I have added this note to [v1.7.0 releases notes](https://github.com/firehol/netdata/releases/tag/v1.7.0):

> IF YOU UPDATE FROM NETDATA 1.6 PLEASE CHECK YOUR DASHBOARDS, SINCE MANY METRICS HAVE CHANGED NAMES.

**Comment by BrainDoctor** [comment] 2017-07-26 23:31
Alright, I guess I should change it rather now than later.

Is there some kind of naming convention? I see some dimensions that are uppercase, others not. I think we should at least have a wiki page that clarifies things up for plugin developers (if there is, I missed it). I don't mind upper- or lowercase, but it should be consistent as possible.

what is the difference between IDs and names anyway? I thought of names to be just a user-friendly description of a dimension/chart to be displayed on the dashboard. I think of IDs that are "machine-friendly" meant for further processing, like primary keys or so. When should I use what?

**Comment by ktsaou** [comment] 2017-09-16 16:38
> Is there some kind of naming convention? I see some dimensions that are uppercase, others not. I think we should at least have a wiki page that clarifies things up for plugin developers (if there is, I missed it). I don't mind upper- or lowercase, but it should be consistent as possible.

I agree. I have opened issue #2746 to track all issues related to dimensions and added the request to have all dimension names to lower case.


> what is the difference between IDs and names anyway?

Well, IDs are used by the plugins to uniquely identify the metrics. The problem is that plugins need to be optimal for data collection. They should not lookup things in every iteration. So, the ID it the metric identifier as collected from the source.

Names on the other hand, are the human readable metric names. They are also unique. To understand the problem consider the interrupts charts: interrupt `11` is `eth0`. The data collection plugins collects it as `11` and communicates it with netdata as `11`. But we want to see it as `eth0`.

> When should I use what?

In netdata you can use either. All functions of the netdata API work with either. But plugins use IDs and backends use names (or whatever is configured at the `[backends]` section of netdata.conf).

Cleaning up. I am closing this. But if you believe I missed something, just post.

**Closed by ktsaou** 2017-09-16 16:38 UTC
Labels: discussion
