### ISSUE TITLE
Compression has already be initialized for this client.

### ISSUE THREAD

**Issue by irizzi** [firehol/netdata#1129] opened 2016-10-16 20:44 UTC
Sorry to bother you,
in error log I've a lot of

`ERROR: netdata: 2: Compression has already be initialized for this client.`

Thanks in advance

**Comment by ktsaou** [comment] 2016-10-16 22:41
hm... this should never happen.
It happened once or you have many of them?
which web browser do you used? which version?

**Comment by irizzi** [comment] 2016-10-16 22:54
I use Firefox 49.0.1 and it logs every time the browser is the active window and dygraph charts refresh.
Same error with Chrome 49.0.2623.112.
System is Win 8.1

**Comment by ktsaou** [comment] 2016-10-16 22:58
ok. I'll try to trace it down. Thanks for reporting it!

**Comment by ktsaou** [comment] 2016-11-02 23:10
I have been trying to find another server with this issue. I can't find one.

Even the public demo sites that get thousands of sessions per day have never reported this. I just searched all their logs for the last month...

The only solution I have is to comment the log out. netdata already handles this properly.

Before doing so though, could you please check that `/var/log/netdata/access.log` logs accesses when you access your netdata with firefox? The reason I need this is simple: compression is initialized when your browser connects and is cleared when the a log line is logged at `/var/log/netdata/access.log`. So, if it is logged, this error should not happen. If it is not logged, the problem is elsewhere.

**Comment by depraved22** [comment] 2016-12-07 18:10
I noticed this in my logs as well.

I get it each time a my browser connects.

I reverse proxy through apache and use MacOS and Chrome for the browser.
```

2016-12-07 13:08:29: netdata: ERROR: 4: Compression has already be initialized for this client.
2016-12-07 13:08:29: netdata: ERROR: 5: Compression has already be initialized for this client.
2016-12-07 13:08:30: netdata: ERROR: 3: Compression has already be initialized for this client.
2016-12-07 13:08:36: netdata: ERROR: 6: Compression has already be initialized for this client.
2016-12-07 13:08:36: netdata: ERROR: 3: Compression has already be initialized for this client.
2016-12-07 13:08:38: netdata: ERROR: 3: Compression has already be initialized for this client.
2016-12-07 13:08:40: netdata: ERROR: 3: Compression has already be initialized for this client.
2016-12-07 13:08:41: netdata: ERROR: 6: Compression has already be initialized for this client.
2016-12-07 13:08:43: netdata: ERROR: 5: Compression has already be initialized for this client.
2016-12-07 13:08:44: netdata: ERROR: 2: Compression has already be initialized for this client.
2016-12-07 13:08:45: netdata: ERROR: 3: Compression has already be initialized for this client.
2016-12-07 13:08:45: netdata: ERROR: 5: Compression has already be initialized for this client.
2016-12-07 13:08:45: netdata: ERROR: 2: Compression has already be initialized for this client.
2016-12-07 13:08:45: netdata: ERROR: 6: Compression has already be initialized for this client.
2016-12-07 13:08:52: netdata: ERROR: 7: Compression has already be initialized for this client.
2016-12-07 13:08:54: netdata: ERROR: 2: Compression has already be initialized for this client.
2016-12-07 13:08:54: netdata: ERROR: 5: Compression has already be initialized for this client.
2016-12-07 13:08:54: netdata: ERROR: 6: Compression has already be initialized for this client.
```

I can hit refresh to recreate the problem as well.

**Comment by ktsaou** [comment] 2016-12-07 18:34
Could you please check that /var/log/netdata/access.log logs accesses when you access your netdata? 

The reason I need this is simple: compression is initialized when your browser connects and is cleared when the a log line is logged at /var/log/netdata/access.log. So, if it is logged, this error should not happen. If it is not logged, the problem is elsewhere.

**Comment by depraved22** [comment] 2016-12-07 18:53
If I hit a refresh I get this in the access and error:

```
2016-12-07 13:52:04: 113: (sent/all = 3083/11910 bytes -74%, prep/sent/total = 0.11/0.16/0.27 ms) data: 200 '//api/v1/data?chart=redis_local.operations&format=json&points=263&group=average&options=ms|flip|jsonwrap|nonzero&after=-300&_=1481135472669'
2016-12-07 13:52:04: 111: (sent/all = 1081/8911 bytes -88%, prep/sent/total = 0.08/0.07/0.15 ms) data: 200 '//api/v1/data?chart=redis_local.hit_rate&format=json&points=263&group=average&options=ms|flip|jsonwrap|nonzero&after=-300&_=1481135472668'
2016-12-07 13:52:06: 113: (sent/all = 1081/8911 bytes -88%, prep/sent/total = 0.10/0.07/0.17 ms) data: 200 '//api/v1/data?chart=redis_local.hit_rate&format=json&points=263&group=average&options=ms|flip|jsonwrap|nonzero&after=-300&_=1481135472670'
2016-12-07 13:52:06: 111: (sent/all = 3092/11909 bytes -74%, prep/sent/total = 0.11/0.13/0.25 ms) data: 200 '//api/v1/data?chart=redis_local.operations&format=json&points=263&group=average&options=ms|flip|jsonwrap|nonzero&after=-300&_=1481135472671'
2016-12-07 13:52:06: 113: (sent/all = 34215/156645 bytes -78%, prep/sent/total = 0.02/1.83/1.85 ms) filecopy: 200 '//'
2016-12-07 13:52:06: 113: (sent/all = 20369/264369 bytes -92%, prep/sent/total = 1.59/1.24/2.83 ms) data: 200 '//api/v1/charts?_=1481136726505'
2016-12-07 13:52:07: 113: (sent/all = 1082/8911 bytes -88%, prep/sent/total = 0.08/0.07/0.15 ms) data: 200 '//api/v1/data?chart=redis_local.hit_rate&format=json&points=263&group=average&options=ms|flip|jsonwrap|nonzero&after=-300&_=1481136726506'
2016-12-07 13:52:07: 115: 127.0.0.1 port 37810 connected on thread task id 14371
2016-12-07 13:52:07: 115: (sent/all = 355/1313 bytes -73%, prep/sent/total = 0.02/0.05/0.07 ms) data: 200 '//api/v1/data?chart=postfix_local.qsize&format=json&points=263&group=average&options=ms|flip|jsonwrap|nonzero&after=-300&_=1481136726508'
2016-12-07 13:52:07: 116: 127.0.0.1 port 37812 connected on thread task id 14372
2016-12-07 13:52:07: 116: (sent/all = 358/1323 bytes -73%, prep/sent/total = 0.07/0.05/0.12 ms) data: 200 '//api/v1/data?chart=postfix_local.qemails&format=json&points=263&group=average&options=ms|flip|jsonwrap|nonzero&after=-300&_=1481136726509'
2016-12-07 13:52:07: 111: (sent/all = 3087/11901 bytes -74%, prep/sent/total = 0.12/0.17/0.29 ms) data: 200 '//api/v1/data?chart=redis_local.operations&format=json&points=263&group=average&options=ms|flip|jsonwrap|nonzero&after=-300&_=1481136726507'
2016-12-07 13:52:07: 111: (sent/all = 119/122 bytes -2%, prep/sent/total = 0.03/0.04/0.06 ms) data: 200 '//api/v1/alarms?active&_=1481136726510'
2016-12-07 13:52:08: 111: (sent/all = 148/165 bytes -10%, prep/sent/total = 0.01/0.04/0.05 ms) data: 200 '//api/v1/registry?action=hello&_=1481136726511'
```

```

2016-12-07 13:51:59: netdata: ERROR: 110: Compression has already be initialized for this client.
2016-12-07 13:51:59: netdata: ERROR: 111: Compression has already be initialized for this client.
2016-12-07 13:52:06: netdata: ERROR: 113: Compression has already be initialized for this client.
2016-12-07 13:52:06: netdata: ERROR: 111: Compression has already be initialized for this client.

```

Does that help?

**Comment by ktsaou** [comment] 2016-12-07 20:11
hm... it is logged, so this should never happen.
I have an indication. This is the only variable I have used with a bit-limit. Can you give me your gcc version?

I am preparing a fix already, but it would be nice if I knew your gcc version.

**Comment by ktsaou** [comment] 2016-12-07 20:37
merged the fix.

**Closed** 2016-12-07 20:37 UTC

**Comment by depraved22** [comment] 2016-12-08 12:28
I'm running:

```
netdata# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 6.2.0-5ubuntu12' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.2.0 20161005 (Ubuntu 6.2.0-5ubuntu12)
```

I just ran through an update and I'm seeing slightly similar things. The error log is the same but the access log looks like:

```
2016-12-08 07:27:30: 41: (sent/all = 1337/2964 bytes -55%, prep/sent/total = 0.20/0.30/0.50 ms) data: 200 '//api/v1/data?chart=system.cpu&format=array&points=300&group=average&options=absolute|jsonwrap|nonzero&after=-300&_=1481200040692'
2016-12-08 07:27:30: 36: (sent/all = 962/2019 bytes -52%, prep/sent/total = 0.10/0.19/0.29 ms) data: 200 '//api/v1/data?chart=system.io&format=array&points=300&group=average&options=absolute|jsonwrap|nonzero&after=-300&dimensions=in&_=1481200040694'
2016-12-08 07:27:30: 43: (sent/all = 1213/2369 bytes -49%, prep/sent/total = 0.09/0.61/0.70 ms) data: 200 '//api/v1/data?chart=system.io&format=array&points=300&group=average&options=absolute|jsonwrap|nonzero&after=-300&dimensions=out&_=1481200040693'
2016-12-08 07:27:30: 44: (sent/all = 572/2835 bytes -80%, prep/sent/total = 0.09/0.05/0.14 ms) data: 200 '//api/v1/data?chart=system.swap&format=array&points=300&group=average&options=absolute|jsonwrap|nonzero|percentage&after=-300&dimensions=used&_=1481200040695'
2016-12-08 07:27:31: 44: (sent/all = 655/1368 bytes -52%, prep/sent/total = 0.06/0.26/0.31 ms) data: 200 '//api/v1/alarms?active&_=1481200040696'
2016-12-08 07:27:31: 44: (sent/all = 513/911 bytes -44%, prep/sent/total = 0.11/0.24/0.35 ms) data: 200 '//api/v1/alarm_log?after=1480976185&_=1481200040697'
2016-12-08 07:27:38: 43: 127.0.0.1 port 60268 disconnected from thread task id 23895
2016-12-08 07:27:39: 36: 127.0.0.1 port 59600 disconnected from thread task id 23226
```


```
2016-12-08 07:27:18: netdata: ERROR: 38: Compression has already be initialized for this client.
2016-12-08 07:27:21: netdata: ERROR: 41: Compression has already be initialized for this client.
2016-12-08 07:27:21: netdata: ERROR: 36: Compression has already be initialized for this client.
2016-12-08 07:27:22: netdata: ERROR: 38: Compression has already be initialized for this client.
2016-12-08 07:27:22: netdata: ERROR: 42: Compression has already be initialized for this client.
2016-12-08 07:27:22: netdata: ERROR: 41: Compression has already be initialized for this client.
2016-12-08 07:27:22: netdata: ERROR: 38: Compression has already be initialized for this client.
2016-12-08 07:27:22: netdata: ERROR: 42: Compression has already be initialized for this client.
2016-12-08 07:27:30: netdata: ERROR: 41: Compression has already be initialized for this client.
2016-12-08 07:27:30: netdata: ERROR: 37: Compression has already be initialized for this client.
2016-12-08 07:27:30: netdata: ERROR: 36: Compression has already be initialized for this client.
```

**Comment by ktsaou** [comment] 2016-12-08 20:07
ok found it.
This happens when the request is too big and netdata receives it in chunks. Most probably you have many HTTP headers (cookies, etc).

I changed the error log to a debug statements.
Merged it.

Thanks for reporting (and insisting) on this...

**Comment by depraved22** [comment] 2016-12-08 20:25
I don't see the error anymore after updating it and restarting it. I tried a couple of refreshes and looks great. Thanks for the quick fix!
